### ISSUE TITLE
[BUG] GoFile appears to be down issue

### ISSUE THREAD

**Issue by Gwilwilethal** [Jules-WinnfieldX/CyberDropDownloader#102]
Hi there,

I get a GoFile appears to be down issue 
![image](https://user-images.githubusercontent.com/102547195/162285398-06e47ca2-1c5e-43f8-b56b-d5420fad29ac.png)

It's interesting as I haven't had these issues in previous versions of the program. I am wondering if there's something missing in my system?

I have python310..

Please advise~

**Comment by Jules-WinnfieldX** [comment]
There isn't anything wrong here. Gofile has been having issues and a lot of links aren't currently working on their end.

**Comment by Jules-WinnfieldX** [comment]
I'm wrong. Their API has turned into a premium service it appears. Leaving this open for now.

**Comment by Jules-WinnfieldX** [comment]
New update fixes gofile.
