### ISSUE TITLE
Thotsbay Login

### ISSUE THREAD

**Issue by Trollzy55** [Jules-WinnfieldX/CyberDropDownloader#104]
Hey, I have literally no clue where or how to type in my login information to thotsbay.

**Comment by Jules-WinnfieldX** [comment]
If you are using a start file you edit it and change the line `cyberdrop-dl` to `cyberdrop-dl --thotsbay-username TROLLYZY55 --thotsbay-password ALPINE`

changing the obvious to be your actual details.

**Comment by Trollzy55** [comment]
You're a lifesaver thanks bro

**Comment by Trollzy55** [comment]
You're a lifesaver, thanks bro
