### ISSUE TITLE
i can not download from cyberdrop [BUG]

### ISSUE THREAD

**Issue by FastAndreiiii** [Jules-WinnfieldX/CyberDropDownloader#107]
**Describe the bug**
file from cyberdrop is aprox 4 GB and 1093 file

1. when I open to download it notifies me to give "y" or "n" press y and it says that the download starts and then closes
 but it goes with smaller links in size
after saying that the download starts and closes the window after some time
**Screenshots**
![Screenshot_1](https://user-images.githubusercontent.com/92557305/163193441-5c63d029-8fc0-49ca-86a1-b9749efd090c.png)
![Screenshot_2](https://user-images.githubusercontent.com/92557305/163193445-986d0dde-41be-4d95-81aa-d7fe3d9bc1dd.png)

**Setup Information**
CPU amd 2600 16GB ram 3000,ssd 120gb and 1tb hdd OS Windows 11 Pro
honestly it would be great if you made a video with its installation and configuration, I'm sure I didn't do something right but all the links went to the previous version

**Comment by Jules-WinnfieldX** [comment]
For one, you shouldn't be using the start.py script, as it says it's only meant for development. You should use one of the actual installation methods described in the readme. The easiest is manual, just go to the releases page and grab the Cyberdrop-dl.V3.zip file. 

Cyberdrop on the other hand is having a lot of issues. I can't actually get through to their site right now and I'm assuming you probably can't either which would explain the issue.

**Comment by FastAndreiiii** [comment]
ok thx for answer, but can you tell me what should i open so i can download please, and where i need to link because there is no URL.txt

**Comment by FastAndreiiii** [comment]
ok sorry for this,thx for your time,Cyberdrop-dl.V3.zip is work but honestly I don't know where I downloaded it from,because I don't see it on your page

**Comment by Jules-WinnfieldX** [comment]
https://github.com/Jules-WinnfieldX/CyberDropDownloader/releases
