### ISSUE TITLE
ThotsBay download not working

### ISSUE THREAD

**Issue by notBradPitt** [Jules-WinnfieldX/CyberDropDownloader#108]
have tried with and without user and password. not working (no links found)

**Comment by Jules-WinnfieldX** [comment]
I'm assuming you are trying to download you are trying to download a thotsbay.com/album/ link which isn't supported yet. See the readme for supported link types.

**Comment by notBradPitt** [comment]
Let me check again, i think it was supposed to be from the forum which has /threads/ in the URL. Is the /album/ link going to be supported in the future, by the way?

**Comment by Jules-WinnfieldX** [comment]
Yea, it's on my to do list.

**Comment by notBradPitt** [comment]
Thanks! It'd be great if you added support for StateWinz user submissions too
