### ISSUE TITLE
[BUG] gofile account is created on each run

### ISSUE THREAD

**Issue by qarkai** [Jules-WinnfieldX/CyberDropDownloader#111]
**Describe the bug**
Abuse of gofile.io/api. Account is created even if there are no gofile links to download.

**To Help Reproduce**
Steps to help reproduce the behavior:
1. Run cyberdrop-dl for any url other than gofile.io
2. Inspect downloader.log. It has item with `DEBUG:connectionpool:connectionpool.py:456:https://api.gofile.io:443 "GET /createAccount HTTP/1.1"` string.

**Setup Information**
 - OS: Arch Linux
 - Cyberdrop Downloader Version 2.14.14

**Comment by Jules-WinnfieldX** [comment]
I'm in the middle of reworking how the scrapers are mapped. It'll fix this.

**Comment by Jules-WinnfieldX** [comment]
Should be fixed in 2.15.0
