### ISSUE TITLE
Linking Cyberdrop to Real Debrid/AllDebrid[FEATURE]

### ISSUE THREAD

**Issue by SmokyChinaTea** [Jules-WinnfieldX/CyberDropDownloader#112]
User Story: 

I want Cyberdrop to be able to link to my Alldebrid account so that I can download from mega.nz while scraping from the thotsbay forums with no restrictions.

**Comment by Jules-WinnfieldX** [comment]
This isn't something I'm prepared to do for multiple reasons, but the main ones are:
I don't want to pay for an account and provide upkeep for this service.
I don't think I can reliably automate something utilizing those services.
