### ISSUE TITLE
Unable to download from Thotsbay Forums [BUG]

### ISSUE THREAD

**Issue by SmokyChinaTea** [Jules-WinnfieldX/CyberDropDownloader#113]
**Describe the bug**
Encountered a bug while trying to download from Thotsbay. Attaching the error log.

**Screenshots**
![image](https://user-images.githubusercontent.com/103814926/163698857-0ca5df12-5fcb-455e-9970-37232e609ee6.png)

**Setup Information**
 - OS: Windows 11 Pro
 - Cyberdrop Downloader Version 2.15.3

**Additional context**
[downloader.log](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/8500927/downloader.log)

**Comment by Jules-WinnfieldX** [comment]
Pushing 2.15.4 now which should fix this.
