### ISSUE TITLE
Unable to download from bunkr [BUG]

### ISSUE THREAD

**Issue by mbul03** [Jules-WinnfieldX/CyberDropDownloader#114]
**Describe the bug**
Unable to download from bunkr, i tried with gofile, jpg.church, and cyberdrop the program works just fine but not with bunkr

**To Help Reproduce**
Steps to help reproduce the behavior:
1.Run cyberdrop-dl for bunkr url

**Screenshots**
![image](https://user-images.githubusercontent.com/72655925/163788042-4e4775c1-bfba-4363-be55-4ece20a035ca.png)

**Setup Information**
 - OS: Windows 10
 - Cyberdrop Downloader Version 2.15.4

**Additional context**
[downloader.log](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/8504853/downloader.log)

**Comment by Jules-WinnfieldX** [comment]
You are getting a 403 status code from Bunkr (forbidden). Either because you are in a blacklisted country or it doesn't like a vpn/proxy you are using.

**Comment by darkwind1q** [comment]
I have encounter a similar issue, but in my case it doesn't spit out any message. When I check the change log it said that bunker either is down or the file is deleted, however, I can still access the site.
Here is my change log.
[downloader.log](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/8508364/downloader.log)

Also when I tried to get a few files from pixeldrain it spit out "zip" file which I have to reassign the file extension to be able to open it properly.
![image](https://user-images.githubusercontent.com/103967333/163884037-86551c83-53d3-41bf-b978-abe67dc17966.png)

**Comment by fninog11** [comment]
My dowlonads only  show PART files, i dont know why? any one with the same issue? any help?

**Comment by Jules-WinnfieldX** [comment]
> My dowlonads only show PART files, i dont know why? any one with the same issue? any help?

The part files are partial downloads. Let the downloader run. Then read any messages it tells you after it's done.

**Comment by Jules-WinnfieldX** [comment]
> I have encounter a similar issue, but in my case it doesn't spit out any message. When I check the change log it said that bunker either is down or the file is deleted, however, I can still access the site. Here is my change log. [downloader.log](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/8508364/downloader.log)
> 
> Also when I tried to get a few files from pixeldrain it spit out "zip" file which I have to reassign the file extension to be able to open it properly. ![image](https://user-images.githubusercontent.com/103967333/163884037-86551c83-53d3-41bf-b978-abe67dc17966.png)

I've fixed the issue you were having with bunkr. I'll need URLS to test pixeldrain. Please open a new issue for that though.
