### ISSUE TITLE
Downloader overwrites URL domain to bunker

### ISSUE THREAD

**Issue by TheConMan3** [Jules-WinnfieldX/CyberDropDownloader#116]
The downloader is currently overwriting the URLs I put into the URLs.txt from "fs-05.cyberdrop.to" to "cdn.bunker.is" on every link which creates a 404 error. I'll attach screenshots of both files

This is on version 2.15.5 of the CyberDrop Downloader. I am on Windows 10 and Python is at version 3.10.4.

Let me know if you need other info.
![downloader log](https://user-images.githubusercontent.com/102829877/164117976-5894a0c8-29ab-4d7f-ac22-c5c05e3b4932.png)
![URLs txt](https://user-images.githubusercontent.com/102829877/164117978-e030e93d-8597-469f-a9b0-fd532708d7d9.png)

**Comment by Jules-WinnfieldX** [comment]
Fixed in 2.15.6, released now.

**Comment by TheConMan3** [comment]
That's fixed it. Thanks!
