### ISSUE TITLE
[FEATURE] Save a list of unsupported URLs from the thotsbay scraper.

### ISSUE THREAD

**Issue by ne0liberal** [Jules-WinnfieldX/CyberDropDownloader#118]
**Is your feature request related to a problem? Please describe.**
When scraping from thotsbay it will pass over links that the downloader doesn't support. (mega, zippyshare, etc)

**Describe the solution you'd like**
The terminal already prints the URL it can't download from, it would be nice if in the thread folder it creates it would also save a text file outputting all the links the scraper couldn't handle so the user can go through and download the missing stuff themself.

**Comment by Jules-WinnfieldX** [comment]
Can do. The only issue is most mega's will require a password that I'm not currently scraping. I should also implement a check for other password protected albums and actually warn the user about them.

**Comment by ne0liberal** [comment]
Didn't even think about the mega password. Good point. Generally, the post would have it hidden in a spoiler tag, but that's a whole thing.

**Comment by Jules-WinnfieldX** [comment]
2.16.9 added "Unsupported_Urls.txt" output. I haven't done anything about the passwords, yet (maybe later).
