### ISSUE TITLE
[FEATURE] A separate Folder for each Forum post. 

### ISSUE THREAD

**Issue by Phobobobo** [Jules-WinnfieldX/CyberDropDownloader#121]
**Is your feature request related to a problem? Please describe.**
Not a problem, but Downloading with your tool leafs unsupportable chaos in the folder.

**Describe the solution you'd like**
Like I wrote in the Forum, I would like to get A separate Folder for each Forum post (marked in red in the image). Idealy in the same numerical order as the are in the Forum. 

**Additional context**
[https://i.ibb.co/mFKH8Mt/Unbenannt.jpg](url)

**Comment by Jules-WinnfieldX** [comment]
implemented with `--separate-posts` flag.
