### ISSUE TITLE
thotsbay downloads question

### ISSUE THREAD

**Issue by neuri48** [Jules-WinnfieldX/CyberDropDownloader#123]
hey i noticed that if i scrape two different threads that happen to have some of the same links the first scrape will include the link and the second scrape wont. example: i scrape the thread 'women of wrestling'  and it has a paige vz link in there; i go to scrape the paige vz thread and the same link wont be scraped and added to the paige vz folder

is there an argument to change that?

**Comment by Jules-WinnfieldX** [comment]
`--ignore_history          ignores previous history and downloads everything`

I just added this.
