### ISSUE TITLE
Not shipping 'tkinter' dependency

### ISSUE THREAD

**Issue by MadMakz** [Jules-WinnfieldX/CyberDropDownloader#127]
It's seems there's a new? dependency _tkinter_.

_pip_ is not aware of this when doing _pip install -U cyberdrop-dl_ so we get a `ModuleNotFoundError: No module named 'tkinter'` error

I had to _apt install python3-tk_ because i don't know what pip packages is the correct one [https://pypi.org/search/?q=tkinter](https://pypi.org/search/?q=tkinter)

**Comment by Jules-WinnfieldX** [comment]
tkinter is a standard python package included since the release of python 3

**Comment by Jules-WinnfieldX** [comment]
as far as I can tell this is an unused import, I've removed it.
