### ISSUE TITLE
[BUG] Link not working

### ISSUE THREAD

**Issue by NicotherZ** [Jules-WinnfieldX/CyberDropDownloader#129]
Hi, try to download this gallery : https://jpg.church/a/sophie-mudd.pXy9
But don't work.
 
We are running version 2.17.8 of Cyberdrop Downloader
Starting Scrape
Starting scrape of https://jpg.church/a/sophie-mudd.pXy9/
Finished scrape of https://jpg.church/a/sophie-mudd.pXy9/
No links found, check the URL.txt
If the link works in your web browser, please open an issue ticket with me.
This program does not currently support password protected albums.

Thanks in advance for your help!

**Comment by Jules-WinnfieldX** [comment]
jpg.church has been having a lot of server issues lately. If you look at the downloader.log file, you are likely get 503 status codes.

**Comment by NicotherZ** [comment]
So, other option to rip a folder jpg.church ?

**Comment by Jules-WinnfieldX** [comment]
The downloader is fine, if what I said is correct you were just facing server issues.
