### ISSUE TITLE
Python int too large to convert to C long

### ISSUE THREAD

**Issue by jerrywoo96** [Jules-WinnfieldX/CyberDropDownloader#13]
Got this error while downloading on windows.
Here's the link: 
/a/gd9riZ62
Python int too large to convert to C long

**Comment by jerrywoo96** [comment]
Error appeared on downloading this.
vhJ5f48LoneyE3RTt19joKGO1U931NDt-Vf9fT3tl.mp4

**Comment by Jules-WinnfieldX** [comment]
I wasn't able to recreate this on my own, can you provide the full output from the script?

**Comment by jerrywoo96** [comment]
![image](https://user-images.githubusercontent.com/26324139/118358940-9e078b00-b5b3-11eb-9110-703c4dfab41b.png)

**Comment by jerrywoo96** [comment]
you could provide me a py file with console logs inserted to help you troubleshoot :)
I'm using Python 3.9.1 on Windows 10 Pro 64 bit.

**Comment by jerrywoo96** [comment]
Also here's the packages that are installed.
![image](https://user-images.githubusercontent.com/26324139/118359141-a3b1a080-b5b4-11eb-80c1-80ba7733a3da.png)

**Comment by Jules-WinnfieldX** [comment]
I've inserted the traceback command into this branch:
https://github.com/Jules-WinnfieldX/CyberDropDownloader/tree/debug

You basically just need a new copy of downloader.py

**Comment by jerrywoo96** [comment]
![image](https://user-images.githubusercontent.com/26324139/118387276-40754c00-b650-11eb-9662-e72840ad8399.png)

**Comment by jerrywoo96** [comment]
By the way, is there any possibility to allow simultaneous file downloads from an album? Or skip error files using try except?

**Comment by Jules-WinnfieldX** [comment]
> By the way, is there any possibility to allow simultaneous file downloads from an album? Or skip error files using try except?

I'll have to look into your issue above more. The program downloads multiple files at once using multiprocessing, but is currently set to retry indefinitely (I'll likely change this to 5 tries).

**Comment by jerrywoo96** [comment]
maybe if it encounters overflow error, it will skip after 5 tries, and if connection error, you can still leave it to retry indefinitely? 

Also, it is really helpful to have the number of files expected to download attached to the folder name, as i can check it easily to see if there is any missing files. Also the possibility to attach the album ID to the folder name as well to find the source of the album. 

Meanwhile, is there any thing i could help you in solving this bug?

**Comment by Jules-WinnfieldX** [comment]
> Meanwhile, is there any thing i could help you in solving this bug?

I've set it to 5 tries max. Try the current downloader.py in the [debug branch](https://github.com/Jules-WinnfieldX/CyberDropDownloader/tree/debug). It should fix the issue.

My goal has always been to keep folder names as simple as possible, so that things can be download, drag and drop with no extra work for myself.

**Comment by jerrywoo96** [comment]
Specifying the chunk_size fixed the issue. Thanks.
