### ISSUE TITLE
[BUG] coomer.party requests are blocked

### ISSUE THREAD

**Issue by d-miles** [Jules-WinnfieldX/CyberDropDownloader#131]
**Describe the bug**
I'm using the latest release that adds support for `coomer.party` links -- 2.18.6. 

The `*.party` servers have built-in DDOS protection that checks your browser once in a while performing a lot of downloads. Another downloader, [AlphaSlayer1964/kemono-dl](https://github.com/AlphaSlayer1964/kemono-dl), seems to get around this by allowing the user to provide a cookie file from the browser using an argument (similar to the existing `cyberfile-user`/`thotsbay-user` switches). Once blocked, the server will basically ban your IP address for the next 1 hour (although see _Additional context_ for more info about this).

**To Help Reproduce**
Steps to help reproduce the behavior:
1. Attempt to download a large profile (see my [URLs.txt](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/8647526/URLs.txt) below for examples of two such profiles)
2. After downloading several hundred files, note that downloads will abruptly stop
3. Attempting to visit `coomer.party` in the browser shows that the site is unreachable ([but it's not actually down 🙃](https://downforeveryoneorjustme.com/coomer.party))

**Screenshots**
N/A

**Setup Information**
 - OS: Windows 10 Pro 21H1 build 19043.1526
 - Cyberdrop Downloader Version 2.18.6

**Additional context**
Attachments:
* [URLs.txt](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/8647526/URLs.txt)
* [downloader.log](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/8647516/downloader.log) for line references

1. I started cyberdrop-dl at ~10:51, scraping finished at ~10:55
2. A few minutes later, began receiving a ton of 403 responses (starting at line 1185): 
```2022-05-08 10:58:48,957:DEBUG:downloaders:downloaders.py:209:We ran into a 400 level error: 403```
3. After the 403 responses stop, the DDOS protection seems to kick in because at this point I'm unable to connect to the server at all:
```powershell
PS C:\Users\***> Invoke-WebRequest -Uri https://coomer.party
Invoke-WebRequest : Unable to connect to the remote server
```
4. Then, cyberdrop-dl continues to retry for the next hour (which is nice I suppose, although from a sysadmin perspective I might still consider this similar to a DDOS and would be undesirable load on the servers)
5. After 1 hour, we can see `cyberdrop-dl` begins to download again (lines 3537 - 3544):
```2022-05-08 11:58:56,334:DEBUG:downloaders:downloaders.py:37:Retrying https://coomer.party/data/15/f6/15f68d0c8f66bae7ba1b90397137b20835c337ef9f28cf75e05bbef470a16913.m4v?f=b86bb299-62f5-4013-8036-1c622fed0908.m4v...
2022-05-08 11:59:00,364:DEBUG:downloaders:downloaders.py:131:348108987f210829926d807da4e6285964b8b13da2aa72f749922b7b292b099d.jpg Already Downloaded
2022-05-08 11:59:00,754:DEBUG:downloaders:downloaders.py:37:Retrying https://coomer.party/data/f7/be/f7be1297bf7c6cc244cd03a01ac3bb783d848c5eab7c4621bd2aa50321e61d79.jpg?f=2a9c9e78-d1b5-403c-9b66-9a3594ca85d1.jpg...
2022-05-08 11:59:00,816:DEBUG:downloaders:downloaders.py:131:7e6d30bcd74f920b16e2632a9e86ed2585d796c1a2bd04cbb7596991a8bfbe5f.jpg Already Downloaded
2022-05-08 11:59:00,948:DEBUG:downloaders:downloaders.py:131:ee43601091d0bd1987d0643dc73ec97ab44bcc891f82c2aa4bab444a8fe6bc5f.jpg Already Downloaded
2022-05-08 11:59:01,413:DEBUG:downloaders:downloaders.py:131:e8628eae263435036e67764488d72ca4d8b981ada350cc93ea9e08b879f29b73.jpg Already Downloaded
2022-05-08 11:59:02,728:DEBUG:downloaders:downloaders.py:229:Finished a4a1023451bd206b78d990c18b0892e7becef030c538e1406a72110861330c33.jpg
```
6. But within seconds (11:59:00 -> 11:59:09), 403 responses begin again (line 3565):
```2022-05-08 11:59:09,571:DEBUG:downloaders:downloaders.py:209:We ran into a 400 level error: 403```
7. My guess is that because either the requests hadn't stopped throughout the hour, OR because my IP address had already been blocked, I was re-blocked almost immediately after that hour "timeout" period had began.
8. While there was an error in the log file (see line 1503), this seems to have likely been caused by a file still being downloaded and having the server forcibly drop the connection. There is no error shown in the console itself during this period.

Since the servers are smart enough to re-block any potential DDOS right away, it isn't really feasible to download any large profiles with `cyberdrop-dl` (unless doing it in batches by re-running it some other day). As you can see from my log, there are lots of '_Already Downloaded_' messages; I had initially run this last night and ran into the issue for the first time.

**Comment by Jules-WinnfieldX** [comment]
Great write up. Ain't that a bees nest though. The cookies that the program generates and hands off to the downloader should be identical to those provided by the user. In theory anyways, I haven't validated that to be true for coomer. So I'm not sure what difference it would make grabbing the cookies from chrome vs what I'm already doing. 

Noted for myself moving forward though, I should specify why I'm retrying...

Having an http status code there would be nice, or it could just be timing out as my browser is currently doing. Something that would likely help is having a throttle on coomer, and a lengthier retry wait for that domain. 

I'll look into this more and try and come up with a solution.

**Comment by d-miles** [comment]
For what it's worth, I re-ran it later that day and ended up downloading nearly everything remaining in those two profiles in a single go -- so I don't think it's really cut and dry on how they're doing the blocking.

A separate issue (let me know if you'd prefer a new bug created):

I re-ran it earlier today for just what was left of a single profile (`e*********88`); this upgraded me to `v2.19.1` and ended up downloading almost everything as a duplicate (eg. `file.mp4` already existed, but it also created `file (1).mp4`; in some instances, it even created `file (1).mp4 and `file.mp4` did not exist). 

I just re-ran it with that same profile only (1,695 files scraped total -- 1,694 of which already existed) just to see if `v2.19.6` may have fixed that. No bueno, it seems to still be trying to download all of the same files again. 

**Attachments:**
* [downloader.log](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/8657470/downloader.log)
* [URLs.txt](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/8657474/URLs.txt)
* [List of files in directory after triggering download](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/8657485/dir.txt)

**Comment by Jules-WinnfieldX** [comment]
Yea. I'm aware of this unfortunately. 

I'm in the middle of reworking how the DB works. On the downside it's going to wipe past history from pre-next update, on the plus side it'll make checking if something was already downloaded a lot more accurate and a lot faster.

**Comment by Jules-WinnfieldX** [comment]
Trying to push that out tonight to avoid many people using the current bugged version.

**Comment by Jules-WinnfieldX** [comment]
As an update, that's out.

**Comment by Jules-WinnfieldX** [comment]
Still have to figure out what to do about coomer.

**Comment by Jules-WinnfieldX** [comment]
As far as I am aware this issue hasn't cropped back up. Going to close for now.
