### ISSUE TITLE
[FEATURE] follow links on .party site posts

### ISSUE THREAD

**Issue by hrm-princess-fluffybutt** [Jules-WinnfieldX/CyberDropDownloader#138]
looks like scraping the party sites isn't like scraping thotsbay threads?

in particular wondering about posts that don't have content as attachments, i think this is most prevalent on patreon stuff

instead the content is linked offsite.

example
https://kemono.party/patreon/user/5933740/post/55909893)kemono.party

so for thotsbay threads, those links end up in unsupported urls.txt (accessing and sifting through that is a pain btw, but i doubt there's any improvements to be made). or getting followed and downloaded. not the case for the party sites

could the change be made to follow those links where possible?

seeing all sorts of links. google drive, catbox,mega,nextcloud(seedbox),dropbox among others. nextcloud,catbox, look easy to scrape i guess. dropbox maybe?

**Comment by Jules-WinnfieldX** [comment]
This is done, it'll follow links, I didn't add any more native downloading, this is meant more to be used with jdownloader setup in conjunction with Cyberdrop-DL
