### ISSUE TITLE
[FEATURE] rate limiter argument

### ISSUE THREAD

**Issue by hrm-princess-fluffybutt** [Jules-WinnfieldX/CyberDropDownloader#139]
add in argument to set global rate limit in megabytes/s or megabits

**Comment by DGuzak** [comment]
Just a delay range between pulling new files in seconds would be epic.

Should be a default really otherwise they're going to block this too.

**Comment by Jules-WinnfieldX** [comment]
Delay range added. I'll look into doing one for speed. Just added a ratelimit argument for scraping which is in req/s, and a throttle argument for downloading which is a delay (in seconds) between request starts.

**Comment by Jules-WinnfieldX** [comment]
I don't think the mb/s rate limit is possible with aiohttp as of current, will revisit later.
