### ISSUE TITLE
[BUG] Stuck Download

### ISSUE THREAD

**Issue by ZeroRaven23** [Jules-WinnfieldX/CyberDropDownloader#140]
It's been giving me this error for a few days of just not downloading
I put the download log right below

**Comment by ZeroRaven23** [comment]
[download.txt](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/8703039/download.txt)

**Comment by ZeroRaven23** [comment]
[download.txt](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/8703044/download.txt)

**Comment by Jules-WinnfieldX** [comment]
Not much I can do about that. Cyberdrop has been having massive issues as of late, with both speed and stability. I put out 2.21.7 though that a better log read out. But it's likely "Response payload is not completed" issues, which is out of my control.

**Comment by ZeroRaven23** [comment]
How do I make this correction?

**Comment by Jules-WinnfieldX** [comment]
you just run the start file, or do a pip update.

**Comment by Jules-WinnfieldX** [comment]
As I said, the update wasn't a correction, but shows better error information in the downloader.log. It's like reponses from the server not being complete, which I can't do anything about. It's an issue with cyberdrop.

**Comment by ZeroRaven23** [comment]
okay thanks you

**Comment by ZeroRaven23** [comment]
so you still have the download error
[downloader.txt](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/8844567/downloader.txt)
