### ISSUE TITLE
[BUG] Discharge rate not constant

### ISSUE THREAD

**Issue by axel845845** [Jules-WinnfieldX/CyberDropDownloader#143]
**Describe the bug**
At the beginning it starts downloading with good speed 2MB- 3MB/s but after a few seconds the speed drops to 50KB/s. The strange thing is that if I close the script and open it again it starts downloading fast again for a few seconds but then the speed drops again.

**Setup Information**
 - OS: Windows 11
 - Cyberdrop Downloader Version #DL.V3

**Downloader.log file**
[downloader.log](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/8743803/downloader.log)

**Comment by Jules-WinnfieldX** [comment]
The download speed is near entirely dependent on file servers, and how much (if at all) they are throttling you. For pixeldrain (majority of the links in your downloader.log, I just tried and was getting around 4-8x speed vs chrome.
