### ISSUE TITLE
Not reading URL file

### ISSUE THREAD

**Issue by Autastical** [Jules-WinnfieldX/CyberDropDownloader#146]
I'm not a coder whatsoever and followed this instruction

-Downloaded and extracted the latest file from here https://github.com/Jules-WinnfieldX/CyberDropDownloader/releases
-Put the links in the URLs.txt file then run Start Windows.bat (Windows) 
-Tried running the Windows Bat again to get this message (https://i.imgur.com/m0Zq9V6.png)

I thought maybe I had to enter 'cyberdrop-dl' in either cmd/windows+r(run)/or even python itself 

running it in cmd gave me this message "No links found, check the URL.txt
If the link works in your web browser, please open an issue ticket with me.
This program does not currently support password protected albums." 
 
However I did enter this into cmd  
```cyberdrop -dl "https://exampleurl.com/a/12345/"```

 and it works. So I think it has something to do with not readying ther URLs file within the folder.

**Comment by Jules-WinnfieldX** [comment]
It doesn't appear like you start bat file finish. It was doing the installation of the requirements in that photo. Running cyberdrop-dl in cmd entirely depends upon what directory you are running the command in.

**Comment by Jules-WinnfieldX** [comment]
Closing as no response or follow-up
