### ISSUE TITLE
[FEATURE] Add a proxy option?

### ISSUE THREAD

**Issue by catshitz** [Jules-WinnfieldX/CyberDropDownloader#147]
**Is your feature request related to a problem? Please describe.**
cannot use cyberdrop-dl(python script) through a proxy

**Describe the solution you'd like**
add `--proxy http://127.0.0.1:7890` or `--proxy socks5://127.0.0.1:7890` (if pysocks pre-installed/built-in) for example to download through certain local proxy port

**Comment by Jules-WinnfieldX** [comment]
Proxy support added
