### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Frant241** [Jules-WinnfieldX/CyberDropDownloader#149]
It can't connect for some reason

![image](https://user-images.githubusercontent.com/106500895/170904258-35e1e39c-53e7-4264-887f-4d519afbab9a.png)

**Setup Information**
 - Windows 10
 - Latest

[downloader.log](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/8794892/downloader.log)

**Comment by Frant241** [comment]
Does this man it's the website fault?

**Comment by Jules-WinnfieldX** [comment]
If you are on the latest version it'll get past it eventually, but yes. If it's cyberdrop one of their file servers is down right now.

**Comment by sloyard** [comment]
fs-05.cyberdrop.to is unavailable, you can access those images by changing 05 to 04 and it will work

**Comment by Jules-WinnfieldX** [comment]
I have a temporary solution in that redirects fs-05 to fs-04 upon retrying. It's in 2.24.5
