### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Aira1133** [Jules-WinnfieldX/CyberDropDownloader#151]
**Describe the bug**
![bug](https://user-images.githubusercontent.com/106819060/171860007-651cc8bf-281e-4fa4-8e4b-09a2ddaee3af.png)

Here the link:
https://jpg.church/a/linny-hill.toNlI

It works in browser just fine.

Thank you in advance

**Comment by Jules-WinnfieldX** [comment]
The program doesn't support password protected albums currently.
