### ISSUE TITLE
Gofile scraper doesn

### ISSUE THREAD

**Issue by janibe** [Jules-WinnfieldX/CyberDropDownloader#152]
Hi there! Appreciate your work! Love it!
But the gofile scraper doesn't work..
"Couldn't start the GoFile crawler"
Any recommendations?

**Comment by janibe** [comment]
Hi there! Appreciate your work! Love it! 
But the gofile scraper doesn't work.. 
"Couldn't start the GoFile crawler"
Any recommendations?

**Comment by janibe** [comment]
[downloader.log](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/8860856/downloader.log)

**Comment by janibe** [comment]
Current version neither works.. 
[downloader.log](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/8866974/downloader.log)

**Comment by Jules-WinnfieldX** [comment]
That's not the current version, you are using 2.22.5, the program is currently on version 2.25.6 You are around 30 iterations behind.
