### ISSUE TITLE
[FEATURE] Would you consider adding support for ( undelete.news ) ?

### ISSUE THREAD

**Issue by axel845845** [Jules-WinnfieldX/CyberDropDownloader#153]
In the old days there was a website like, this one called isdb.pw, which was basically an archiver of Instagram stories of many celebrities and people, obviously this is illegal and the site closed down. 

Now there is only https://undelete.news/
Which is basically the same, the difference is that in undelete.news you must download the stories one by one, many accounts have thousands of stories, so downloading them one by one would take forever. I don't know if this can be done in a more automated way or at least faster.

Thanks for considering and your work and effort.

**Comment by Jules-WinnfieldX** [comment]
I don't think this is in my realm unfortunately.
