### ISSUE TITLE
Login for Website

### ISSUE THREAD

**Issue by thejos241** [Jules-WinnfieldX/CyberDropDownloader#154]
Where can I put my login data for supported websites that require one? I don't receive a prompt to log in.

**Comment by Jules-WinnfieldX** [comment]
If you're using a start file you edit it to change the line that reads only [ICODE]cyberdrop-dl[/ICODE] to be [ICODE]cyberdrop-dl --thotsbay-username "USERNAME" --thotsbay-password "PASSWORD"[/ICODE]
