### ISSUE TITLE
[BUG] Gofile connection issues

### ISSUE THREAD

**Issue by slitchampion** [Jules-WinnfieldX/CyberDropDownloader#155]
Program hangs on Gofile downloads. Connection to Gofile from browser, manually, works fine.

Any Gofile link has reproduced the issue for me. I just pip install upgraded cyberdrop-dl and the issue remains. Thotsbay thread downloads will hang on Gofile. Using --skip-gofile works fine. Trying to only download Gofile separate from a thread causes the issue as well.

[downloader.log](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/8865229/downloader.log)

Ubuntu 20.04.4 LTS
Cyberdrop-dl 2.25.6

**Comment by Jules-WinnfieldX** [comment]
antivirus, firewall rules, internet changes. The program was working properly then stopped being able to connect. You could try limiting download threads and see if it makes a difference reducing the total number of downloads at once.

**Comment by slitchampion** [comment]
I appreciate the quick responses. I certainly don't expect you to troubleshoot any network issues I may have on my own system. cyberdrop-dl has been working GREAT for me for weeks (thank you so much, by the way!!) and the Gofile issue just started happening. I've not made any changes to my system outside of updating cyberdrop-dl.

I just tried a single Gofile link that contained a single video and it worked fine. Other single Gofile links with either 7 or 15 video files seem unable to connect and error after the 10 retries, although I can access the links and download the files manually. If no one else is having issues with Gofile, and it's just a local system issue, I'll keep debugging. Thanks again!

**Comment by Jules-WinnfieldX** [comment]
It could be a concurrent download limiter, unless something has changed on their backend, try limiting threads as I said above and see if it makes a difference for you.
