### ISSUE TITLE
[BUG] Error purging empty

### ISSUE THREAD

**Issue by ZeroRaven23** [Jules-WinnfieldX/CyberDropDownloader#158]
Has given me this error recently, in addition to still not being able to download on cyberdrop.
regarding cyberdrop, is it still unstable?

[downloader.txt](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/8890730/downloader.txt)

**Comment by Jules-WinnfieldX** [comment]
What OS are you using?

**Comment by Jules-WinnfieldX** [comment]
Operating system, ie: windows, Mac OS, Linux

**Comment by ZeroRaven23** [comment]
Oh, windows

**Comment by Jules-WinnfieldX** [comment]
If you have a proxy enabled you need to disable it.

**Comment by ZeroRaven23** [comment]
I don't have any kind of proxy running, both on the network and on the pc

**Comment by Jules-WinnfieldX** [comment]
2.25.8 should fix this error. It's an issue with cyberdrop.
