### ISSUE TITLE
Added a couple features in my fork you might be interested in

### ISSUE THREAD

**Issue by c0d3m0nky** [Jules-WinnfieldX/CyberDropDownloader#161]
I was in need of improving my python skills so decided to [fork your repo](https://github.com/c0d3m0nky/CyberDropDownloader) and add some features that I wanted. Would you be interested in taking a PR from me to include them?

### Support for scanning multiple text files with urls and downloading them into folders named after their source file

I wanted to be able to pre-organize links so when they were downloaded they'd already be sorted into folders. 

For example if you have these files in the root where you're running the script:

```
root
│   URLS.txt
│   content1.txt
│   content2.txt
│   content3.txt
│
└───Downloads
```

Then ran `python3 start.py  --scan`, you end up with:

```
root
│   URLS.txt
│   content1.txt
│   content2.txt
│   content3.txt
│
└───Downloads
│   └───content1
│   │   │   [Files/folders from content1.txt]
│   └───content2
│   │   │   [Files/folders from content2.txt]
│   └───content3
│   │   │   [Files/folders from content3.txt]
│   [Files/folders from URLS.txt]
```

### Support for downloading from `https://thotsbay.com/albums/*`

The site won't load content without Javascript, but I noticed that in the basic server response is the url for getting a json payload of all the content. So I was able to scrape it without having to add any additional requirements to the project. The new crawler is located at `cyberdrop_dl/utils/crawlers/ThotsbayGallery_Spider.py`

**Comment by c0d3m0nky** [comment]
Also, although I've been a software dev for decades, I'm a Python noob. So I'd gladly accept any suggestions, criticism, or even nit picking, regardless.

**Comment by Jules-WinnfieldX** [comment]
If you make a pull request with the changes I'll merge them.
