### ISSUE TITLE
[FEATURE]Minimize the CMD console on Windows to Systray?

### ISSUE THREAD

**Issue by Ravn73** [Jules-WinnfieldX/CyberDropDownloader#164]
**Describe the solution you'd like**
I would like to have an option that can minimize the CMD console (on Windows, linux/mac i dont know) to the systray. Because it gets in the way when i have to do other things. And just minimizing it to the taskbar doesnt help. If there is way, it would be nice. If not, then i will have to live with it =)

![Screenshot 2022-06-24 093636](https://user-images.githubusercontent.com/21908456/175486926-1ec4238d-b4fb-48e4-beb0-b58d0214052c.png)

**Comment by Jules-WinnfieldX** [comment]
Unfortunately, nothing I can do here really. You can possibly alter the batch script to do so yourself.
