### ISSUE TITLE
[BUG] download from pixeldrain.com

### ISSUE THREAD

**Issue by eXoticD** [Jules-WinnfieldX/CyberDropDownloader#168]
Hey!
I have a problem with downloading via pixeldrain.com
I got only 1 file out of 250

**Comment by Jules-WinnfieldX** [comment]
I need to see the downloader.log file from that run.

**Comment by eXoticD** [comment]
[downloader.log](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/9037713/downloader.log)

**Comment by Jules-WinnfieldX** [comment]
You likely got locked out due to captcha, or the files were locked server side due to too many downloads.
