### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by lemonsqaure** [Jules-WinnfieldX/CyberDropDownloader#169]
First I don't know-how is the file suppose to be set up Because I have downloaded the 2 files (Source code.zip & Cyberdrop_DL.V3.zip)

The main problem for me is the Source code.zip because it doesn't have a Start Windows.bat and URLs.txt so I tried combining the (Source code.zip & Cyberdrop_DL.V3.zip) in the same file because the Cyberdrop_DL.V3.zip.

![file1](https://user-images.githubusercontent.com/108737047/177332728-08f24a26-2bc6-46b7-a202-fb4a386160ac.png)

And then when I combined it and started going through the steps of setting it up after the step of pasting the URL in the URLs.txt the download still won't work even when I saved the URL in the URLs.txt

https://user-images.githubusercontent.com/108737047/177338541-43e38af9-f141-4ece-b0d4-7587290f4268.mp4

https://user-images.githubusercontent.com/108737047/177341909-83e6546e-8a84-4a6c-beb4-8f3481a7c014.mp4

If you need more information to help identify on what is the problem just ask so I can provide more information on my end, Thank you

**Comment by Jules-WinnfieldX** [comment]
You don't download the source code zip, as it says on the release page. You just download the cyberdrop_DL zip. Everything you need is in there.
