### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by lenexyyy** [Jules-WinnfieldX/CyberDropDownloader#172]
**Stuck at ?Files/s**
When run the program it stuck on ?FILES/s and didn't downloading at all

**Screenshots**
![Uploading image_2022-07-13_214254082.png…]()

**Comment by Jules-WinnfieldX** [comment]
I need the downloader.log to help.

**Comment by lenexyyy** [comment]
[downloader.log](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/9103325/downloader.log)

**Comment by Jules-WinnfieldX** [comment]
The downloader is working, Cyberdrop isn't. It'll work it's way through the files. If you leave it, or you can take out the cyberdrop links.

**Comment by lenexyyy** [comment]
Yeah tried it, it works! So this is problem with cyberdrop servers?
