### ISSUE TITLE
[FEATURE] BayFiles

### ISSUE THREAD

**Issue by Jules-WinnfieldX** [Jules-WinnfieldX/CyberDropDownloader#174]
Add support for BayFiles

**Comment by github-userx** [comment]
Aren’t Bayfiles & Anonfiles all built the same?

**Comment by github-userx** [comment]
I think the following sites are the same as well:

myfile.is

megaupload.nz

letsupload.cc

openload.cc

filechan.org

**Comment by Jules-WinnfieldX** [comment]
They are the same (Bayfiles and anonfiles) I just haven't gotten around to explicitly adding support. Been super busy as of late with real life.

**Comment by github-userx** [comment]
Thanks. Let’s hope it wasn’t for nothing.. since both these filehosts seem to currently have financial/hardware issues according to their website
