### ISSUE TITLE
[FEATURE] Gofile password 

### ISSUE THREAD

**Issue by bnsave100** [Jules-WinnfieldX/CyberDropDownloader#175]
Will you please add function to accept gofile password ?

**Comment by Jules-WinnfieldX** [comment]
I'm planning on making a full application that should be compatible with mac and pc. It'll be supported on that. It won't be supported from command line.

**Comment by bnsave100** [comment]
> I'm planning on making a full application that should be compatible with mac and pc. It'll be supported on that. It won't be supported from command line.

tbh I'm using this on linux server thats why asked

**Comment by Jules-WinnfieldX** [comment]
gofile-dl supports passwords, I use it as a backbone. There just isn't a clean way that I can come up with to support it via the current methodology I'm using.

**Comment by Jules-WinnfieldX** [comment]
You can use it yourself, it works just like this via command line.
