### ISSUE TITLE
[BUG]Unsure where to put Thotsbay login

### ISSUE THREAD

**Issue by sdkasas** [Jules-WinnfieldX/CyberDropDownloader#178]
Didn't use help within program, stupid me sorry

**Comment by sdkasas** [comment]
Unsure why this happens, first time user!
![image](https://user-images.githubusercontent.com/90745922/181450924-ea71208d-a571-4b68-80ba-ed47db908db5.png)
![image](https://user-images.githubusercontent.com/90745922/181450996-b50a6c3f-46ab-46b9-996c-d5599f27dab2.png)

**Comment by Jules-WinnfieldX** [comment]
all of those --'s (--thotsbay-username for ex) don't go in the urls.txt file, they go at the end of the cyberdrop-dl line in the start file. 

So it'd change from `cyberdrop-dl` to `cyberdrop-dl --thotsbay-username "sdkasas" --thotsbay-password....`
