### ISSUE TITLE
thotshub

### ISSUE THREAD

**Issue by neuri48** [Jules-WinnfieldX/CyberDropDownloader#180]
hey, not exactly sure what the problem is but the scraper won't work in some links on this forum thread https://forum.thotsbay .to/threads/ggotbbang.30804/
 I belive that the issue is the format being used on the forum. is there any fix for this?
![Screenshot_20220808-120958_Chrome](https://user-images.githubusercontent.com/101938704/183495452-36304902-ded3-406d-86dd-6eff6d697d5d.jpg)

**Comment by Jules-WinnfieldX** [comment]
Closing for obvious reasons
