### ISSUE TITLE
[FEATURE] Where to now

### ISSUE THREAD

**Issue by Rit76Horizon** [Jules-WinnfieldX/CyberDropDownloader#185]
So, not really a feature request but as this doesn't have a discussion like some other projects do, I'm taking it upon myself to put this here. As posted on Twitter, the bay is gone permanently and I would prefer to go where a sizeable chunk of the community goes, I maybe wrongfully assume you'll migrate somewhere as well with this tool. Not sure, the current options I know about are bad if nothing else.

This could effectively be a feature request for "add support to X new website the community goes to" no idea where that will be.

**Comment by hrm-princess-fluffybutt** [comment]
https://forums.socialmediagirls.com/

is what the twitter is giving a shout out to

https://www.twitlonger.com/show/n_1ss40v9

idk how to feel.

it's funny, most of my saved links are now either party sites or tb threads themselves. it used to be tons of links to the file hosts. thanks, jules. this is your america. look what you've done. i say that with so much love

i have a feeling that this "feature request" is going to see a lot of use as time goes on lol

**Comment by Rit76Horizon** [comment]
Far as I can tell https://forums.leakednudes.co/ is an overall better site at least visually. At least Hiero that one HaneAme guy already has a post on there 

Certainly a useful "Feature Request" lol.

**Comment by daantee0** [comment]
> Far as I can tell https://forums.leakednudes.co/ is an overall better site at least visually. At least Hiero that one HaneAme guy already has a post on there Might as well try both at this point though.
> 
> Certainly a useful "Feature Request" lol.

the socialmediagirls have alot of content and members

**Comment by Rit76Horizon** [comment]
> 

Your right, but I constantly get redirects to different websites while using the site that Ublock has to stop. Feels real sketchy.

**Comment by Jules-WinnfieldX** [comment]
I'm going to close this, you can continue to discuss here however.

**Comment by minicoz** [comment]
I got it working with leakednudes.co. 
Ill see if I can post a PR

**Comment by hrm-princess-fluffybutt** [comment]
@Rit76Horizon 

change name to a more generic "best forum discussion" or something?


also, thotsbay.ac is apparently rather shady.

there's also a subreddit reddit.com/r/thotsbay_forum

**Comment by Rit76Horizon** [comment]
> @Rit76Horizon
> 
> change name to a more generic "best forum discussion" or something?
> 
> also, thotsbay.ac is apparently rather shady.
> 
> there's also a subreddit reddit.com/r/thotsbay_forum

Changed,
.ac has been called out by the Thotsbay twitter as illegitimate. 
The subreddit is unrelated to either the actual Thotsbay or .ac, and was created for similiar reasons as this thread.
So far the two best options are
socialmediagirls.com (SMG)
LeakedNudes.co
And I think lewdweb ?

I will say, I'm using both the first two options, though SMG I get constant redirects when trying to access my notifications or a page, they also seem to be completely restricting the OF part of the forum for new users, as people with hundreds of reaction score are unable to access it when you *supposedly* only need 20-40 score.

**Comment by hrm-princess-fluffybutt** [comment]
yeah i was suggesting the subreddit for alternatives, not actual content

idk, my smg account is about a year old and has 45 score. still treated like a new member. maybe it's first post date or number of posts. also some clowns keep throwing out dislikes. especially painful when you see somebody posting worse content one file at a time hidden behind "you need to react to see this content" blocks.

**Comment by Rit76Horizon** [comment]
> yeah i was suggesting the subreddit for alternatives, not actual content
> 
> idk, my smg account is about a year old and has 45 score. still treated like a new member. maybe it's first post date or number of posts. also some clowns keep throwing out dislikes. especially painful when you see somebody posting worse content one file at a time hidden behind "you need to react to see this content" blocks.

Ah, yeah. The sub basically suggest the same two
I see. No idea then, It just sucks because I have a txt doc that keeps track of all the people I was Watching on Tbay, I can't find most of them on SMG. I suspect some of them are in restricted places for new members? Example would be HaneAme. I can't find her at all, and the thread that directed to her is gone now. Though the directing lead to "you can't view this page"

Or they are under completely different names. The site lacks the level of organization Tbay had and it's frustrating honestly. I have a txt document with 855 lines going through getting names of the ones I used to Watch on Tbay and grabbing their socials (if available) just to help me locate threads and find when needed but it feels like a waste with how poor the management is.

**Comment by hrm-princess-fluffybutt** [comment]
i guess this is tangential, here are big names i'm noticing since that might matter. i'm seeing captain america choosing leaked over smg, said he doesn't like smg.  i see b0b, or someone posing as b0b on smg. i think i see our comrade doofus is lurking on the subreddit.

i'm still waiting to see how the dust settles. finally got the option to hide stuff behind reactions on smg, and that really boosts reaction scores. feel kinda bad, but at least there's good stuff in my posts. i think the hidden stuff is going to based on post count from here on out for me.

i think smg toned down the shady redirects. or someone updated adblockplus to deal with them better. who knows, it just works.

reaction score is still slow to gain on leaked

**Comment by Jules-WinnfieldX** [comment]
To be frank, the hiding behind reaction score is something that is stopping me from attempting to support it.

**Comment by hrm-princess-fluffybutt** [comment]
> To be frank, the hiding behind reaction score is something that is stopping me from attempting to support it (SMG).

yeah, i totally get it. wait, ethically or coding wise? wonder how it looks in scrapy or beautifulsoup. maybe if you can get the login to work, it looks just like a regular spoiler block

**Comment by Jules-WinnfieldX** [comment]
> yeah, i totally get it. wait, ethically or coding wise? wonder how it looks in scrapy or beautifulsoup. maybe if you can get the login to work, it looks just like a regular spoiler block

Both, regular spoiler blocks just have the content hidden, it's still on the page and scrapable. The "like-required-unspoil" reloads that section of the page. I take issue with "botting" likes, I'm not going add auto-liking functionality. There's also the fact that those  "like-required-unspoil" blocks don't stay loaded for extended periods of time. They will inevitably unload and require you to unlike then relike the post.

This is something I could do. Could do easily. I just don't jive with it.

**Comment by hrm-princess-fluffybutt** [comment]
> > yeah i was suggesting the subreddit for alternatives, not actual content
> > idk, my smg account is about a year old and has 45 score. still treated like a new member. maybe it's first post date or number of posts. also some clowns keep throwing out dislikes. especially painful when you see somebody posting worse content one file at a time hidden behind "you need to react to see this content" blocks.
> 
> Ah, yeah. The sub basically suggest the same two I see. No idea then, I have a txt document with 855 lines going through getting names of the ones I used to Watch on Tbay and grabbing their socials (if available) just to help me locate threads and find when needed but it feels like a waste with how poor the management is.
> 
> I can't find most of them on SMG. I suspect some of them are in restricted places for new members? Example would be HaneAme. I can't find her at all, and the thread that directed to her is gone now. Though the directing lead to "you can't view this page" Or they are under completely different names. The site lacks the level of organization Tbay had and it's frustrating honestly.

10 garbage padding posts for a total of 31, and 900 reaction score later, i found your dumb ha threads. there's a whole cosplay section and there's like 6 different threads on her. i'm blind or of still isn't there, i bet it's a dumpster fire. not sure i prefer it to crickets on leaked lol.



> > yeah, i totally get it. wait, ethically or coding wise? wonder how it looks in scrapy or beautifulsoup. maybe if you can get the login to work, it looks just like a regular spoiler block
> 
> Both, regular spoiler blocks just have the content hidden, it's still on the page and scrapable. The "like-required-unspoil" reloads that section of the page. I take issue with "botting" likes, I'm not going add auto-liking functionality. There's also the fact that those "like-required-unspoil" blocks don't stay loaded for extended periods of time. They will inevitably unload and require you to unlike then relike the post.
> 
> This is something I could do. Could do easily. I just don't jive with it.

yeah, if i think the content is bad or low effort enough i take back my like lol. the principle of it trumps my desire for less effort. maybe that's the solution. dislike after download complete. also, there are neutral reactions that don't give score but still unlock the content.  i bet the forum admins will be thrilled with the like botting.

sure is effective in farming the likes for the ones that can do it tho. i'm on track to speedrunning 1k likes in 24hrs

**Comment by github-userx** [comment]
I wish I had used cyberdrop-dl with its scraping capabilities more instead of often just bookmarking threads and posts :P

I think for main site I’ll stick to SMG and occasionally see what the other two boards are doing. SMG is terribly designed, terribly moderated and run, with lots of technical bugs but it has the biggest community and content (while content is terribly sorted/marked/named).

**Comment by Jules-WinnfieldX** [comment]
So if you haven't heard, peep the interesting change in the readme sites supported.

**Comment by hrm-princess-fluffybutt** [comment]
so quick

doesn't look like you put in the ability to auto replace "forums.thotsbay.to" with "simpcity.st",  should i open a request?

**Comment by Jules-WinnfieldX** [comment]
> so quick
> 
> doesn't look like you put in the ability to auto replace "forums.thotsbay.to" with "simpcity.st", should i open a request?

You could, I'd recommend just replacing all instances of it in the urls.txt file using cntl+f of notepad++
