### ISSUE TITLE
[BUG] login wasn't provided, consider using --thotsbay-username and --thotsbay-password

### ISSUE THREAD

**Issue by ghost** [Jules-WinnfieldX/CyberDropDownloader#189]
I think it's still scraping successfully, but it's still printing this error:
login wasn't provided, consider using --thotsbay-username and --thotsbay-password

Tried the new flags, tried the previous, and tried both, but still throws that.

**Comment by Jules-WinnfieldX** [comment]
Yea, I dun goofed it. It's fixed 3.2.7

**Comment by Jules-WinnfieldX** [comment]
reopening because the thotsbay-username / password should have worked. It's simpcity-username / password properly now let me know if it still doesn't work for you.

**Comment by dannyvoid** [comment]
it works now, changed nothing. super weird, idk why it was breaking earlier
