### ISSUE TITLE
simpcity credentials argument not being recognized

### ISSUE THREAD

**Issue by hrm-princess-fluffybutt** [Jules-WinnfieldX/CyberDropDownloader#190]
ya done goofed changing the thotsbay login argument to simpcity

pip: version 3.2.3

output:
usage: cyberdrop-dl [-h] [-V] [-i INPUT_FILE] [-o OUTPUT_FOLDER] [--log-file LOG_FILE] [--db-file DB_FILE]
                    [--threads THREADS] [--attempts ATTEMPTS] [--disable-attempt-limit] [--include-id]
                    [--exclude-videos] [--exclude-images] [--exclude-audio] [--exclude-other] [--ignore-history]
                    [--separate-posts] [--leakednudes-username LEAKEDNUDES_USERNAME]
                    [--leakednudes-password LEAKEDNUDES_PASSWORD]
                    [--socialmediagirls-username SOCIALMEDIAGIRLS_USERNAME]
                    [--socialmediagirls-password SOCIALMEDIAGIRLS_PASSWORD] [--thotsbay-username THOTSBAY_USERNAME]
                    [--thotsbay-password THOTSBAY_PASSWORD]
                    [--skip {anonfiles,bayfiles,bunkr,coomer.party,cyberdrop,cyberfile,erome,gfycat,gofile,jpg.church,jpg.homes,kemono.party,leakednudes,pixeldrain,pixl.is,postimg.cc,putme.ga,putmega.com,redgifs,saint,socialmediagirls,simpcity}]
                    [--ratelimit RATELIMIT] [--throttle THROTTLE]
                    [link ...]
cyberdrop-dl: error: unrecognized arguments: --simpcity-username

**Comment by Jules-WinnfieldX** [comment]
Yea, I dun goofed it. It's fixed 3.2.7

**Comment by Wolfeman0101** [comment]
I'm seeing the same bug.

**Comment by Jules-WinnfieldX** [comment]
> I'm seeing the same bug.

make sure you are on the latest version.
