### ISSUE TITLE
[FEATURE] option to set time out limit

### ISSUE THREAD

**Issue by despecial** [Jules-WinnfieldX/CyberDropDownloader#193]
Hi, since I got a lot of 522 errors on cyberdrop.to files, it would be great to have an option to set the time waiting for a response.
Like 1-2s is fine but currently it waits way longer for a single file response.

Or is there any other workaround?

**Comment by Jules-WinnfieldX** [comment]
Currently the limit is 5 minutes. I'm adding a connection specific timeout and making the default for it 15 seconds, it will have it's own argument for adjustability.

**Comment by Jules-WinnfieldX** [comment]
Just pushed 3.3.9 with this functionality.
