### ISSUE TITLE
[BUG] Can't download files from Bunkr

### ISSUE THREAD

**Issue by shaeems** [Jules-WinnfieldX/CyberDropDownloader#194]
After not using your package in a couple of weeks, I tried using it today, but I received some errors when trying to download from Bunkr. 

The error, "Unknown key: files" is thrown at line 40 in Bunkr_Spider.py. 

I've got a feeling the python JSON package was updated, so your current implementation needs a bit of rework. I've tried a couple of things out, and have managed to get the functionality back by changing the line to "for file in json_obj['album']['files']:"

I hope this is enough for you to get a good understanding of the bug that I encountered. You've really done some amazing work with everything here!

**Comment by Jules-WinnfieldX** [comment]
Merged fix, 3.3.4
