### ISSUE TITLE
[BUG]Bunkr.is download

### ISSUE THREAD

**Issue by mbul03** [Jules-WinnfieldX/CyberDropDownloader#195]
**Bunkr.is Bug**
when I tried to download something off bunkr, the program always said "No links found during scraping, check passwords or that the urls are accessible." even though the url is not protected by any password, I even tried to re-scrape the url I downloaded yesterday and the program said the same thing. the program is doing just fine on gofile & cyberdrop

**To Help Reproduce**
Steps to help reproduce the behavior:
1. Insert any bunkr.is link
2. Run the program
3. https://bunkr.is/a/AnqdzCZI Link that i used 

**Screenshots**
![image](https://user-images.githubusercontent.com/72655925/187027583-09d70eb8-00c6-4fbf-b994-8e00fc95a8f2.png)

**Setup Information**
 - OS: Windows 10
 - Cyberdrop Downloader Version 3.3.3

**Downloader.log file**
 
[downloader.log](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/9437828/downloader.log)

**Comment by hrm-princess-fluffybutt** [comment]
it's just albums that don't seem to work. clicking through and downloading a single file works on bunkr though. 

another example:
https://bunkr.is/a/FQr23UWj

2022-08-27 14:09:07,488:DEBUG:base_functions:base_functions.py:41:Starting scrape of https://bunkr.is/a/FQr23UWj
2022-08-27 14:09:08,021:DEBUG:Bunkr_Spider:Bunkr_Spider.py:51:Error encountered while handling https://bunkr.is/a/FQr23UWj

**Comment by Jules-WinnfieldX** [comment]
Merged fix, 3.3.4 fixes this
