### ISSUE TITLE
[BUG] Not loading all the albums from a user from jpg.church

### ISSUE THREAD

**Issue by RazredgeBR** [Jules-WinnfieldX/CyberDropDownloader#197]
**Describe the bug**
I have an account with many albums in jpg.church, in excess of 60 albums. When I used the url *USER/albums* it will only fetch about 40 albums (always the same), but not all of them.

**To Help Reproduce**
Steps to help reproduce the behavior:
1. Add on the URLs.txt the jpg.church of the user albums, containing more than 40 albums (https://jpg.church/*USERNAME*/albums);
2. Execute the application and wait for it to fetch the albums and download;
3. Only about 40 albums will be downloaded, not all of them, and repeating the second step will always only download the same albums, never the remaining ones.

**Setup Information**
 - Windows 10
 - Cyberdrop Downloader Version 3.3.3 (cyberdrop-dl 3.3.3)

**Downloader.log file**
[downloader.log](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/9438646/downloader.log)

**Comment by Jules-WinnfieldX** [comment]
Infinite scrolling is a wonderful terrible thing. I'll deal with this, just not sure how yet.

**Comment by Jules-WinnfieldX** [comment]
Sorry for the wait, this is fixed in 3.5.7.
