### ISSUE TITLE
Bunkr.is not working

### ISSUE THREAD

**Issue by TheDoctor40** [Jules-WinnfieldX/CyberDropDownloader#198]
Lately, when I try to download albums from Bunkr, the downloader is unable to scrape the pages, even though they load fine in my browser. It used to work before. Programs tells me "Error scraping" and then the URL.

**Comment by Jules-WinnfieldX** [comment]
I'd need to see the downloader.log. Make sure you are on the latest version.

**Comment by TheDoctor40** [comment]
I see in the release history on PyPi that a couple of new versions have been released since I had the issue. I was running 3.3.3 at the time. Judging by the release history, 3.3.4 came out the same day, although I do not know if it was already out then. Updating today to 3.3.9 fixed the issue. Next time I have problems I will include the downloader.log.
