### ISSUE TITLE
Downloader has trouble with folder/file names that contain unallowed characters.

### ISSUE THREAD

**Issue by AnonFapper** [Jules-WinnfieldX/CyberDropDownloader#2]
Link: https://cyberdrop.me/a/Rv3DUQx4

The set title "Balloon Birthday (?)" has a question mark which Windows does not allow when naming folders/files. For instance, the characters that aren't allowed are: \ / : * ? " < > |

![Problem](https://user-images.githubusercontent.com/61375779/75109791-90e83000-55ec-11ea-8881-9d70bdca1f41.png)

**Comment by Jules-WinnfieldX** [comment]
Added folder name sanitation. Replaces all unacceptable characters with underscores.
