### ISSUE TITLE
Download to a particular folder

### ISSUE THREAD

**Issue by heyitsritesh** [Jules-WinnfieldX/CyberDropDownloader#20]
Currently, it downloads all the galleries to the root folder of the program. I created a folder inside it with the name "Downloads" and want all the albums to be downloaded to it. How can I do that?

Thanks

**Comment by Jules-WinnfieldX** [comment]
As I get more free time soon I have a planned update that will come out. I plan to address that with it. I just haven't figured out how I want to do that quite yet.

**Comment by heyitsritesh** [comment]
Thank you. Will be waiting for the update :)

**Comment by Jules-WinnfieldX** [comment]
https://github.com/Jules-WinnfieldX/CyberDropDownloader/releases/tag/1.2.7
This will give you what you want!
