### ISSUE TITLE
[BUG] Cyberdrop Continue Downloading

### ISSUE THREAD

**Issue by bratworst** [Jules-WinnfieldX/CyberDropDownloader#201]
This was tested on Cyberdrop addresses only. 

The script no longer informs you when there are partially downloaded files. And If you run it again the download resume feature doesn't function correctly, the file size ends up being larger than it should be. 

![File Size Comparrison](https://user-images.githubusercontent.com/112353906/187385079-de5e1263-9729-4645-8693-e96f57f57e50.jpg)

**Comment by Jules-WinnfieldX** [comment]
It seems like this is a result of the recent change for handling cyberdrop, it doesn't appear like cyberdrop.me respects the bytes range header.

**Comment by Jules-WinnfieldX** [comment]
3.3.8 addresses this, had to change domains back to cc, and force to fs-01
