### ISSUE TITLE
anonfiles

### ISSUE THREAD

**Issue by neuri48** [Jules-WinnfieldX/CyberDropDownloader#204]
partial anonfiles downloads being read as fully downloaded so I end up getting an incomplete download without even knowing

**Comment by neuri48** [comment]
happened in gofile too

**Comment by Jules-WinnfieldX** [comment]
I'm not sure what you mean by this. But it's not possible for a link to be marked as complete in the DB when there is still a partial file. 

https://github.com/Jules-WinnfieldX/CyberDropDownloader/blob/master/cyberdrop_dl/client/downloaders.py#L236

The update to being marked as complete happens after the rename from .partial to .<actual extension>

**Comment by Jules-WinnfieldX** [comment]
I'd need more info to address this.

**Comment by neuri48** [comment]
that's what I mean. it's being renamed from filename.mp4.part to filename.mp4 even though the file isn't completely downloaded. the files that I'm trying o download are 2gb+ and the "finished" end up being a couple 100mb up to 1gb but not the actual complete file size. if I rerun the program the program won't even attempt to finish downloading the files and I'm assuming that it's because they are being marked as completed

**Comment by neuri48** [comment]
the post I'm trying to download is here https://simpcity.su 
 /threads/ibi-smiles-ibismiles.17078/post-917577

**Comment by nocoel** [comment]
the partial file is named .mp4 without ".part"
and when you play the video it cuts off at like 20% or wherever the download stopped at

**Comment by Jules-WinnfieldX** [comment]
AV is always an issue with programs/sites like this. But the issues you're both facing I don't believe are coming from the code. If anything they are coming from bad headers on the server side and that isn't something I can fix.

**Comment by Jules-WinnfieldX** [comment]
Closing, can re-open is more info is available.
