### ISSUE TITLE
Missing Files?

### ISSUE THREAD

**Issue by squiglybob13** [Jules-WinnfieldX/CyberDropDownloader#206]
I downloaded the current release but immediately noticed that there aren't any program files in the zip. I tried to run the Windows.bat anyways and as expected it threw and error that the cyberdrop-dl file\folder can't be found. is there another step to install that I'm missing?

**Comment by Jules-WinnfieldX** [comment]
There are no missing files, as long as python (and pip along with it [it’s a default]) running the start file will download what is needed. Python needs to be added to path during installation as is shown in the readme
