### ISSUE TITLE
[FEATURE] "Scrape-only" mode

### ISSUE THREAD

**Issue by RevENGE-code** [Jules-WinnfieldX/CyberDropDownloader#207]
**Describe the solution you'd like**
**Scrape only mode**, a --scrape-only flag or something similar, which only scrapes the URLs and saves them into a .txt-file. Would be especially useful for mega links in combination with https://github.com/basisvectors/mega-checker to only write online/active mega links into the .txt file. Another thing would be password-protected mega's, for which the body of the post is needed. I'm sure you will come up with something.

**Possible Output:**
Link										                           Password
https://mega.nz/folder/ZkZhhTga#TNM3E6B2GArchlc-igJ04g	   02nd91
https://mega.nz/folder/UHtkBBCA#CbVBBveFtX7X7yHJjx1CqA	    ---
https://mega.nz/folder/J1UCjDTQ#17Wk5AsguSWJowrqtYQCsg	   testpassword4
https://mega.nz/folder/mssHSbST#lw04QL4FtEKDwIc2qNyRHQ	     ---

**Comment by Jules-WinnfieldX** [comment]
I would include something like this, but it'd basically be impossible to scrape out the password for the mega with no standardization to posts. For just the link outputs of links that are skipped there is unsupported_urls.txt, mega links will be included in it.
