### ISSUE TITLE
[BUG] Event Loop Is Closed

### ISSUE THREAD

**Issue by marlekal** [Jules-WinnfieldX/CyberDropDownloader#208]
this text showed up when download finished [link](https://imgur.com/a/0l0aEfW) and another [case](https://imgur.com/a/ZAjd7MM)
i can't confirm if it completely finished downloading the whole thread, just reporting this since it looks like something is wrong
i also noticed it only happens when i try a thread for the first time, when i rerun it that error doesn't show up

[downloader.log](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/9491748/downloader.log)

**Comment by Jules-WinnfieldX** [comment]
I've experienced this as well, I've just been ignoring it. It doesn't impact anything but I should figure out why it happens.

**Comment by Jules-WinnfieldX** [comment]
Should be fixed in 3.3.18, out soon.
