### ISSUE TITLE
An ability to choose which file server to download from / exclude a particular file server

### ISSUE THREAD

**Issue by haro1721** [Jules-WinnfieldX/CyberDropDownloader#21]
In my experience, Cyberdrop has at least three file servers that provide content: 01, 02, 03.

During normal usage I've noticed that file server 02 gets called first by a handful of direct links, which would be fine if fs-02 wasn't the slowest server available to me. I am able to remedy this on my preferred web browser by editing the address on the address bar (and skip the "broken" images in the Downloader), but it would be nice to see a functionality like this built into the Downloader.

**Comment by Jules-WinnfieldX** [comment]
This would be a good improvement, I'll add this to the options I'm adding.

**Comment by Jules-WinnfieldX** [comment]
I've attempted to do this, but it is causing quite a few issues. I'll continue to tinker, but I'm going to close this for now.
