### ISSUE TITLE
[FEATURE] GoFile Individual Files

### ISSUE THREAD

**Issue by cam-au** [Jules-WinnfieldX/CyberDropDownloader#210]
Unsure if this is a Bug or more a 'Feature' request. I thought it worked before and something changed on GoFile's side, but, I may be wrong!

(Note the below is just being used as an example, I know there is only 1 file in the folder)

Downloading folder link works fine:
https://gofile.io/d/2wHjrb

However, if this folder had 100s of files in it, and I only wanted some, I go through, right click and Copy link address:
https://store6.gofile.io/download/a14b732c-950c-4078-a732-9f1d52dbb278/MikeShinoda-ReadingFestival(2018.08.25).mp4
And then add to the URL list. But that doesn't work and I get the bellow errors:

```
We are running version 3.3.14 of Cyberdrop Downloader
Starting Scrape
Error scraping https://store6.gofile.io/download/a14b732c-950c-4078-a732-9f1d52dbb278/MikeShinoda-ReadingFestival(2018.08.25).mp4
Starting scrape of https://store6.gofile.io/download/a14b732c-950c-4078-a732-9f1d52dbb278/MikeShinoda-ReadingFestival(2018.08.25).mp4
Finished scrape of https://store6.gofile.io/download/a14b732c-950c-4078-a732-9f1d52dbb278/MikeShinoda-ReadingFestival(2018.08.25).mp4
No links found duing scraping, check passwords or that the urls are accessible
This program does not currently support password protected albums.
```
Log File also attached
[downloader.log](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/9501790/downloader.log)

There are different subdomains that seem to come up; store4, store6, file143, file144, file171 etc. and it looks like assignment is random as multiple difference subdomains are used in the same folder for different files from what I've seen.
Likewise the hex key (download/a14b732c-950c-4078-a732-9f1d52dbb278/) is random for each file. It doesn't match a GoFile folder.
(eg, /984ae6a0-c9f1-4ba8-a8e8-6c17d7b314d9/, /ce29ca54-0081-42aa-a958-0ae0dfd994b7/, /2507b3a8-6c19-47a8-8039-578f0150eb20/ were all from the same folder)

Pasting the MP4 link right into Chrome, video downloads like a normal video.
Tried using DownThemAll (because the whole point was I wanted to do a batch/use a Downloader), but that failed and only downloaded html files.

I'm not a python/coding expert, but I assume it has something to do with the subdomain , and the CyberDrop Downloader's ability to detect the video file in what seems like a new location.

**Comment by Jules-WinnfieldX** [comment]
The issue here, is clicking those links without any of the pre-ample of going to the actual album etc, causes nothing to load or download. This is why they can't be supported like that.
