### ISSUE TITLE
[FEATURE] Output Last post's URL from a thread

### ISSUE THREAD

**Issue by lihengzz** [Jules-WinnfieldX/CyberDropDownloader#211]
**Is your feature request related to a problem? Please describe.**
Not a problem, but an optional feature that can be useful. Since the tool are scraping threads, it would be nice to have tool to output the last post's URL of a scarped thread. From there users can use those Last Post's URLs for the tool next time, so they can download the new posts in those threads without having to scrape the older posts.

**Describe the solution you'd like**
An optional argument would work, and it can take a string for the name of the output text file.
or, write an extra line for each thread in the downloader.log with the URL and user can manually find them.

**Additional context**
I am basing this idea on threads from simpcity and similar style forums since I do know how other websites that the tool also scrape work or if this idea can apply to those sites. Thanks!

**Comment by Jules-WinnfieldX** [comment]
Including this in 3.3.18. Out soon
