### ISSUE TITLE
[HELP] is not recognized as an internal or external command...

### ISSUE THREAD

**Issue by 1Luckboy** [Jules-WinnfieldX/CyberDropDownloader#212]
Hello friends how are you?  I'm trying to run Cyberdrop downloader, but the bat file after running I get the message:

"cyberdrop-dl" is not recognized as an internal or external command an operable program or batch file

I'm using windows 10, I already reinstalled python, checked the box "add python to Path", but even so this error persists, if anyone can help me, I'll be grateful.

**Comment by Jules-WinnfieldX** [comment]
First things first would be to uninstall all copies of python, reinstall python 3.10, make sure to check the box add to path. Make sure you don't run anything as administrator. Restart the computer, then try installing cyberdrop-dl again.
