### ISSUE TITLE
[BUG] pixeldrain broke

### ISSUE THREAD

**Issue by marlekal** [Jules-WinnfieldX/CyberDropDownloader#213]
[downloader.log](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/9531760/downloader.log)

**Comment by Jules-WinnfieldX** [comment]
It isn't broken:

`{"success":false,"value":"file_rate_limited_captcha_required","message":"This file is using too much bandwidth. For anonymous downloads a captcha is required now. The captcha entry is available on the download page"}`

Those files just aren't available to download through the API.
