### ISSUE TITLE
[FEATURE] Download files chronologically

### ISSUE THREAD

**Issue by Karmac** [Jules-WinnfieldX/CyberDropDownloader#214]
Hello,

**Is your feature request related to a problem? Please describe.**

Well, I find it annoying that pixl.is and jpg.church (this are the server I tried the program with) images get downloaded in no particular order, even tough the web page shows them in chronological order. This, mixed with the random filenames given by the servers, makes a mess of the folders.

**Describe the solution you'd like**

I think it would be nice to scrape the links in order if it's possible, even if filenames keep the same. This would al least make it possible to bulk rename them manually later using the information of the database.

Thank you very much for the program and your help.

Edit: typo (non native speaker here).

**Comment by Jules-WinnfieldX** [comment]
Files are scraped using the "Most Recent" tab on these sites. However, items are processed at random. What I mean by this is, there is no way for me to give priority to individual URLs or links during scraping. Further than that, as the downloads are multi-processed (up to potentially 16-24 at a time depending on your computer), there is no way to dictate what finishes when, what starts when, or necessarily what order to follow in that regard. 

This has been asked for a lot, and just isn't feasible. The program would need to be designed for it from the start. 

It's these things that make the program operate as quickly as it does, there isn't anything I can do per say to force it to download "chronologically", I'd also point out the uploads of said files likely aren't chronological either. The better solution would be to try and encourage uploaders to use better filenames in their uploads/naming schemes in their own downloaders. The filenames aren't given by the servers, at least with the two sites you listed.
