### ISSUE TITLE
[BUG] Last Post URL Formatting issue for SimpCity

### ISSUE THREAD

**Issue by lihengzz** [Jules-WinnfieldX/CyberDropDownloader#215]
**Describe the bug**
The URLs_last_post.txt generated incorrect URL formatting for SimpCity's page+post. I will attach my URL.txt and URLs_last_post.txt for sample. 

A valid page#+post# Simpcity URL: https://simpcity.su/threads/rizuna-rizuna.16719/### page-3#post-956462
Current URLs_last_post.txt generated URL: https://simpcity.su/threads/rizuna-rizuna.16719/### page-4/post-967976
the difference is the "#" and "/" that connects the page# and post#

**To Help Reproduce**
Steps to help reproduce the behavior:
1. Any SimpCity thread url will work.
2. Run downloader with "--output-last-forum-post" parameter
3. check the URLs_last_post.txt for the last post url

**Setup Information**
 - OS: Window 10
 - Cyberdrop Downloader Version 3.3.19

**Downloader.log file**
Attached 

**Additional context**
Also attached my URLs.txt and the URLs_last_post.txt

[downloader.log](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/9590593/downloader.log)
[URLs.txt](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/9590595/URLs.txt)
[URLs_last_post.txt](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/9590596/URLs_last_post.txt)

**Comment by Jules-WinnfieldX** [comment]
Fixed in 3.3.20, though not how you expect. Page number isn't needed, so we're getting rid of it entirely. As I was trying to do originally.
