### ISSUE TITLE
simpcity: certain links are not detected

### ISSUE THREAD

**Issue by marlekal** [Jules-WinnfieldX/CyberDropDownloader#216]
links that are posted like this (i don't know the term of that box) are not detected
![899](https://user-images.githubusercontent.com/29715144/190940149-6f2089f9-6613-44f3-b7e2-cbcade61a80e.PNG)
when i check downloader.log the links are not even scraped, and obviously when searching the files none is downloaded

**Comment by Jules-WinnfieldX** [comment]
I'll need an example of it (that I can open myself)

**Comment by marlekal** [comment]
https://simpcity.su/threads/haneame.10123/page-21#post-946448

**Comment by Jules-WinnfieldX** [comment]
These style of links, can't be supported as they rely on javascript to be rendered out and fetched. Nothing realistic I can do about it on my end unfortunately
