### ISSUE TITLE
[BUG]Downloader treats bunkr.is albums as password-protected

### ISSUE THREAD

**Issue by kevinwork98** [Jules-WinnfieldX/CyberDropDownloader#218]
**Describe the bug**
bunkr.is album links (the ones formatted like this: bunkr.is/a/blank) cause an unspecified error and cannot be bulk-downloaded. The individual files within those albums can be downloaded normally, and can even be placed in the URL.txt and bulk downloaded, but the albums as a whole cannot be bulk downloaded. It seems to treat the albums as password protected, when they are not.

**To Help Reproduce**
Steps to help reproduce the behavior:
1. Add any bunkr.is album to the URL.txt file. Alternatively, directly specifying the album link in the command line produces the same result. As far as I can tell, this applies to [any album from this link.](https://bunkr.is/albums) I cannot link any specific album because of their content.
2. Execute the CyberDropDownloader with any output directory. The scraping should fail.
3. Go to any individual file within the album, and put the link into the URL.txt file or directly into the command.
4. Execute the CyberDropDownloader. Downloading the individual file should work.

**Screenshots**
![PowerShell output](https://user-images.githubusercontent.com/19692253/191135790-4f734466-649a-40c9-92e9-f06b84296142.PNG)

**Setup Information**
 - OS: Windows 10
 - Cyberdrop Downloader Version #2.27.4

**Downloader.log file**
[download.log](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/9602865/download.log)

**Comment by Jules-WinnfieldX** [comment]
Appreciate the well written report, easy thing though is you aren't up to date. You are running 2.27.4, newest version is 3.3.22. If you're using the start script most likely the pip upgrade is failing. Try running `pip install --upgrade cyberdrop-dl`

**Comment by kevinwork98** [comment]
Ah, my mistake. I was just using pip install to try to update it, forgot I needed to include "--upgrade". Thank you for the help. It would be nice if the latest version was stated in the README.md.

**Comment by Jules-WinnfieldX** [comment]
Added :)
