### ISSUE TITLE
[BUG]not downloading, not recognizing links

### ISSUE THREAD

**Issue by ironalt123** [Jules-WinnfieldX/CyberDropDownloader#219]
[downloader.log](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/9609786/downloader.log)
![Screenshot_10](https://user-images.githubusercontent.com/114014600/191318488-8d612b17-ec15-4351-a742-389c300589cc.png)

Hey I just downloaded this for the first time and hadn't gotten it to work. I have the URLs populated and ran it and thats what the logs returned. I saw some previous bugs having the same problem but i believe i'm up to date on everything is there something that i'm missing

**Comment by Jules-WinnfieldX** [comment]
you need the `https://` before the links.

**Comment by ironalt123** [comment]
thank you my bad
