### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by kkma24** [Jules-WinnfieldX/CyberDropDownloader#220]
![C__Windows_System32_cmd exe 2022-09-25 오전 3_18_48](https://user-images.githubusercontent.com/114337364/192139506-0cb1ebb8-7a39-4b23-a54c-2b3715e896d2.png)

I tried to download all the cyberdrop albums
I encountered this error
As you know, cyberdrop does not have a password system
Of course, there is no problem with environment variables (I registered all paths related to cyberdop-dl and python LOL)

**Comment by Jules-WinnfieldX** [comment]
Hey, I need to see the downloader.log file.

**Comment by kkma24** [comment]
> Hey, I need to see the downloader.log file.

[downloader.log](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/9641763/downloader.log)

Sorry i forgot

**Comment by Jules-WinnfieldX** [comment]
You are running into a timeout error for cyberdrop, I'd say just try again, or else see if you can connect to them normally. You might need a VPN depending on your location for things to actually load.

But this isn't a bug coding wise.
