### ISSUE TITLE
simcity link-inserted text not detected

### ISSUE THREAD

**Issue by shiro789** [Jules-WinnfieldX/CyberDropDownloader#222]
when download from simpcity, the link that added to the text is not detected

**Comment by Jules-WinnfieldX** [comment]
Hey, I'd need to see the downloader.log to be able to give any help as the issue template describes.

**Comment by shiro789** [comment]
here's the logs and also the example
[downloader.log](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/9668541/downloader.log)
![image](https://user-images.githubusercontent.com/75563637/192876648-53f7b3e7-6de3-4752-9548-b5fb3366e9fd.png)

**Comment by Jules-WinnfieldX** [comment]
I'm unsure of what you are meaning. The link was scraped, and items were downloaded or had already been downloaded.

**Comment by shiro789** [comment]
thats a bunkr link inside the text [like this](https://www.google.com/) but it not detected you can check the forum inside the logs

**Comment by Jules-WinnfieldX** [comment]
Oh. I see what you are saying. 

I've had this brought up before. The program can't pick up those links as they are loaded after the fact with javascript.

**Comment by shiro789** [comment]
ah i see, i guess need to input it manually
thank you.
