### ISSUE TITLE
[FEATURE] f95zone.to thread support

### ISSUE THREAD

**Issue by hrm-princess-fluffybutt** [Jules-WinnfieldX/CyberDropDownloader#225]
f95zone.to is a forum with a lot of animation and comic content

usually, i find myself wanting to archive things in this forum https://f95zone.to/forums/animations-loops.94/

an example of a single collection thread https://f95zone.to/threads/general-butch-collection-2022-04-24-generalbutch-g_v.46281/

**Comment by RyuuSlayer** [comment]
> f95zone.to is a forum with a lot of animation and comic content
> 
> usually, i find myself wanting to archive things in this forum https://f95zone.to/forums/animations-loops.94/
> 
> an example of a single collection thread https://f95zone.to/threads/general-butch-collection-2022-04-24-generalbutch-g_v.46281/

+1 on this one, would love to see it added

**Comment by Jules-WinnfieldX** [comment]
In V5
