### ISSUE TITLE
[FEATURE] Partial Downloads Remaining Clarity

### ISSUE THREAD

**Issue by slitchampion** [Jules-WinnfieldX/CyberDropDownloader#227]
The logic at the end of the script that handles when the partial downloads messages is displayed appears to check the entire download directly for any "*.part" files when displaying "'There are still partial downloads in your folders, please re-run the program.'"

This leads to some clarity issues sometimes. Say I run the script and download hundreds of files, leading to some partial downloads ending in "*.part." The partial downloads message is displayed and that is clear. Say I clear the URLs.txt file, loading it with entirely new content to download. I run the script again, and the partial downloads message displays again. At this point, it is unclear if these partial downloads are from a previous run, or that the current (new content) downloads did not complete. This lack of clarity can lead one to keep repeating the script on content that actually has fully downloaded, not realizing that the partial downloads were from a previous set of content.

Request: Would it be possible to have the partial downloads message logic only check for files downloaded (or partially) during that run?

**Comment by Jules-WinnfieldX** [comment]
Added, kinda. It'll do it's best to check on files from the current run. Re-worked the messages on script finish.
