### ISSUE TITLE
[BUG] redgif user page doesn't work

### ISSUE THREAD

**Issue by hrm-princess-fluffybutt** [Jules-WinnfieldX/CyberDropDownloader#228]
fail: https://www.redgifs.com/users/secretbridgexxx

single items within profile work: https://www.redgifs.com/watch/unknownshorteastsiberianlaika

intended behaviour is that both work

**Comment by Jules-WinnfieldX** [comment]
No can do on the users. Those pages are entirely Javascript, which I can't scrape using the tools that I am.
