### ISSUE TITLE
[FEATURE] Adding media-files8.bunkr.is

### ISSUE THREAD

**Issue by Frant241** [Jules-WinnfieldX/CyberDropDownloader#229]
Seems like media-filesin bunkr is not added to the program

[downloader.log](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/9750174/downloader.log)

**Comment by Jules-WinnfieldX** [comment]
Will be fixed in the version released in probably an hour.

**Comment by Frant241** [comment]
Thank you
