### ISSUE TITLE
Failed Attempt

### ISSUE THREAD

**Issue by Melquiii** [Jules-WinnfieldX/CyberDropDownloader#23]
Can someone point out the problem with the error that I keep on getting?
![image](https://user-images.githubusercontent.com/86995371/124691074-ce153f80-df0d-11eb-8319-44a61a380e88.png)

Also, is there a way to skip the current file that's being downloaded or configure a setup where it skips the file after x attempts?

The tool is super useful and I really appreciate the devs for working on this one.

**Comment by HussainRafi232** [comment]
I'm getting the same problem. 
I would love to see the downloader downloading one image/video at a time to stop this from happening

**Comment by Jules-WinnfieldX** [comment]
> Can someone point out the problem with the error that I keep on getting?
> ![image](https://user-images.githubusercontent.com/86995371/124691074-ce153f80-df0d-11eb-8319-44a61a380e88.png)
> 
> Also, is there a way to skip the current file that's being downloaded or configure a setup where it skips the file after x attempts?
> 
> The tool is super useful and I really appreciate the devs for working on this one.

I'm going to be working on that soon.

**Comment by Jules-WinnfieldX** [comment]
> I'm getting the same problem.
> I would love to see the downloader downloading one image/video at a time to stop this from happening

You can with the latest version, just set the number of threads in the option file to 1.

**Comment by Jules-WinnfieldX** [comment]
https://github.com/Jules-WinnfieldX/CyberDropDownloader/releases/tag/1.2.9
This latest release has the ability to restrict the number of retries in the setting file,
