### ISSUE TITLE
[FEATURE] Read in credentials from config file?

### ISSUE THREAD

**Issue by minicoz** [Jules-WinnfieldX/CyberDropDownloader#230]
**Is your feature request related to a problem? Please describe.**
Its frustrating to always have to use the command line to enter in the credentials for simpcity or jdownloader. Could you include a read from config file that sets up maybe a yaml wile with the username and passwords for the cyberdrop program to run?

**Describe the solution you'd like**
Cyberdrop-dl cli looks for a config.yaml or something to read in the credentials listed in that file and populate the fields to use.

**Comment by Jules-WinnfieldX** [comment]
I like this. I just need to do it properly. I'm working on it now.

**Comment by Jules-WinnfieldX** [comment]
I'm going to close this now. It'll be out soon. The program will automatically create the config file using whatever arguments are first run (not including passwords). It also needs to be enabled, that'll be self explanatory once it's opened though.

**Comment by Jules-WinnfieldX** [comment]
It's bugged. I need to fix it.

**Comment by Jules-WinnfieldX** [comment]
Fixed with 3.4.4
