### ISSUE TITLE
[BUG]bunkr media.file4 

### ISSUE THREAD

**Issue by Frant241** [Jules-WinnfieldX/CyberDropDownloader#232]
The program goes to media file4 instead of stream 

![image](https://user-images.githubusercontent.com/106500895/195045547-353ed710-22d5-4134-b46a-40f0b45cf15c.png)
![image](https://user-images.githubusercontent.com/106500895/195045603-8dbfb331-6899-4736-b03c-80264d3c592d.png)

Windows 10
Latest 
![image](https://user-images.githubusercontent.com/106500895/195046176-91f52092-02b8-4ccc-bc72-fe88bb79de6b.png)

[downloader.log](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/9753324/downloader.log)

**Comment by Jules-WinnfieldX** [comment]
It isn't supposed to go to the stream link for downloading, it is supposed to go to the media-files link. That is the download link. Bunkr has been cracking down on accessibility, you may need to use a VPN.
