### ISSUE TITLE
[FEATURE] Changelog!!!! (or Release notes)

### ISSUE THREAD

**Issue by patelharsh9797** [Jules-WinnfieldX/CyberDropDownloader#233]
Can you provide the changelogs as well with the update Release?
Or if there is already can you address me where to find it.
Thnx

**Comment by Jules-WinnfieldX** [comment]
https://github.com/Jules-WinnfieldX/CyberDropDownloader/commits/master
Commits should act as an essential change log. (I know I'm not good with my messaging). I'll create a changelog file going forward.
