### ISSUE TITLE
[FEATURE] save unsupported and failed downloaded links

### ISSUE THREAD

**Issue by simonrule** [Jules-WinnfieldX/CyberDropDownloader#235]
it will be amazing if the program can make text file contains unsuported and failed downloaded links.

**Comment by Jules-WinnfieldX** [comment]
Failed won't be feasible to realistically do. Unsupported links are already output to unsupported_urls.txt though. If I redo the error handling I'll add it's output to there.

**Comment by Jules-WinnfieldX** [comment]
Yea, and that's what I mean by I'd have to redo the error handling in the program to be able to support this.
