### ISSUE TITLE
[BUG] ImportError: cannot import name 'Gofile' from 'gofile' (/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/gofile/__init__.py)

### ISSUE THREAD

**Issue by solartrans** [Jules-WinnfieldX/CyberDropDownloader#238]
Cyberdrop won't run on windows or macos for the following reason. gives the following error. ImportError: cannot import name 'Gofile' from 'gofile' (/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/gofile/__init__.py)

To reproduce, try running the app. Works on fresh installations. Maybe a python update issue?

Screenshot
<img width="1091" alt="Screenshot 2022-10-13 at 18 32 13" src="https://user-images.githubusercontent.com/26495931/195741594-8d208516-3740-4781-b3b6-5538b0fa479e.png">

**Setup Information**
Windows 11 and macos 13.0

 - Cyberdrop Downloader Version #3

Not seeing a download log file anywhere.

**Comment by Jules-WinnfieldX** [comment]
I haven't been able to recreate. Does this still 3.4.12 which was just pushed now?

**Comment by astuden** [comment]
Looks like you may need to require the gofile2 package instead of gofile? The gofile package does not contain a Gofile class, nor a "token" member variable, but gofile2 does.

**Comment by jtm666** [comment]
File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\cyberdrop_dl\crawlers\GoFile_Spider.py", line 4, in <module>
    from gofile import Gofile
ImportError: cannot import name 'Gofile' from 'gofile' (C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\gofile\__init__.py)

Same issue appears for me, was working fine yesterday

**Comment by Jules-WinnfieldX** [comment]
Is this still happening on 3.4.12? Can anyone confirm that?

**Comment by astuden** [comment]
Did you push 3.4.12 to PIP, or do I need to download the git source?

**Comment by Jules-WinnfieldX** [comment]
> Looks like you may need to require the gofile2 package instead of gofile? The gofile package does not contain a Gofile class, nor a "token" member variable, but gofile2 does.

No, it's gofile_client it should be looking at for gofile. The import is correct.

**Comment by Jules-WinnfieldX** [comment]
> Did you push 3.4.12 to PIP, or do I need to download the git source?

Pushed

**Comment by astuden** [comment]
I see the same problem with 3.4.12 on windows:
```
C:\Users\atuden\Documents\tools\CyberDropDownloader-V2>pip install --upgrade cyberdrop-dl
Requirement already satisfied: cyberdrop-dl in c:\users\atuden\appdata\local\programs\python\python310\lib\site-packages (3.4.12)
Requirement already satisfied: aiofiles>=22.1.0 in c:\users\atuden\appdata\local\programs\python\python310\lib\site-packages (from cyberdrop-dl) (22.1.0)
Requirement already satisfied: beautifulsoup4>=4.11.1 in c:\users\atuden\appdata\local\programs\python\python310\lib\site-packages (from cyberdrop-dl) (4.11.1)
Requirement already satisfied: gofile-client>=1.0.1 in c:\users\atuden\appdata\local\programs\python\python310\lib\site-packages (from cyberdrop-dl) (1.0.1)
Requirement already satisfied: certifi>=2022.9.24 in c:\users\atuden\appdata\local\programs\python\python310\lib\site-packages (from cyberdrop-dl) (2022.9.24)
Requirement already satisfied: yarl>=1.8.1 in c:\users\atuden\appdata\local\programs\python\python310\lib\site-packages (from cyberdrop-dl) (1.8.1)
Requirement already satisfied: colorama>=0.4.5 in c:\users\atuden\appdata\local\programs\python\python310\lib\site-packages (from cyberdrop-dl) (0.4.5)
Requirement already satisfied: myjdapi>=1.1.6 in c:\users\atuden\appdata\local\programs\python\python310\lib\site-packages (from cyberdrop-dl) (1.1.6)
Requirement already satisfied: setuptools>=65.4.1 in c:\users\atuden\appdata\local\programs\python\python310\lib\site-packages (from cyberdrop-dl) (65.4.1)
Requirement already satisfied: tqdm>=4.64.1 in c:\users\atuden\appdata\local\programs\python\python310\lib\site-packages (from cyberdrop-dl) (4.64.1)
Requirement already satisfied: PyYAML>=6.0 in c:\users\atuden\appdata\local\programs\python\python310\lib\site-packages (from cyberdrop-dl) (6.0)
Requirement already satisfied: aiohttp>=3.8.3 in c:\users\atuden\appdata\local\programs\python\python310\lib\site-packages (from cyberdrop-dl) (3.8.3)
Requirement already satisfied: charset-normalizer<3.0,>=2.0 in c:\users\atuden\appdata\roaming\python\python310\site-packages (from aiohttp>=3.8.3->cyberdrop-dl) (2.0.12)
Requirement already satisfied: frozenlist>=1.1.1 in c:\users\atuden\appdata\roaming\python\python310\site-packages (from aiohttp>=3.8.3->cyberdrop-dl) (1.3.0)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\users\atuden\appdata\roaming\python\python310\site-packages (from aiohttp>=3.8.3->cyberdrop-dl) (6.0.2)
Requirement already satisfied: attrs>=17.3.0 in c:\users\atuden\appdata\roaming\python\python310\site-packages (from aiohttp>=3.8.3->cyberdrop-dl) (21.4.0)
Requirement already satisfied: aiosignal>=1.1.2 in c:\users\atuden\appdata\roaming\python\python310\site-packages (from aiohttp>=3.8.3->cyberdrop-dl) (1.2.0)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in c:\users\atuden\appdata\roaming\python\python310\site-packages (from aiohttp>=3.8.3->cyberdrop-dl) (4.0.2)
Requirement already satisfied: soupsieve>1.2 in c:\users\atuden\appdata\local\programs\python\python310\lib\site-packages (from beautifulsoup4>=4.11.1->cyberdrop-dl) (2.3.1)
Requirement already satisfied: requests in c:\users\atuden\appdata\local\programs\python\python310\lib\site-packages (from gofile-client>=1.0.1->cyberdrop-dl) (2.25.1)
Requirement already satisfied: pycryptodome in c:\users\atuden\appdata\local\programs\python\python310\lib\site-packages (from myjdapi>=1.1.6->cyberdrop-dl) (3.15.0)
Requirement already satisfied: idna>=2.0 in c:\users\atuden\appdata\local\programs\python\python310\lib\site-packages (from yarl>=1.8.1->cyberdrop-dl) (2.10)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\atuden\appdata\roaming\python\python310\site-packages (from requests->gofile-client>=1.0.1->cyberdrop-dl) (1.26.9)
Requirement already satisfied: chardet<5,>=3.0.2 in c:\users\atuden\appdata\local\programs\python\python310\lib\site-packages (from requests->gofile-client>=1.0.1->cyberdrop-dl) (4.0.0)

C:\Users\atuden\Documents\tools\CyberDropDownloader-V2>cyberdrop-dl
Traceback (most recent call last):
  File "C:\Users\atuden\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\atuden\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\atuden\AppData\Local\Programs\Python\Python310\Scripts\cyberdrop-dl.exe\__main__.py", line 4, in <module>
  File "C:\Users\atuden\AppData\Local\Programs\Python\Python310\lib\site-packages\cyberdrop_dl\main.py", line 19, in <module>
    from cyberdrop_dl.scraper.scraper import scrape
  File "C:\Users\atuden\AppData\Local\Programs\Python\Python310\lib\site-packages\cyberdrop_dl\scraper\scraper.py", line 3, in <module>
    from .scraper_helper import ScrapeMapper
  File "C:\Users\atuden\AppData\Local\Programs\Python\Python310\lib\site-packages\cyberdrop_dl\scraper\scraper_helper.py", line 17, in <module>
    from ..crawlers.GoFile_Spider import GofileCrawler
  File "C:\Users\atuden\AppData\Local\Programs\Python\Python310\lib\site-packages\cyberdrop_dl\crawlers\GoFile_Spider.py", line 4, in <module>
    from gofile import Gofile
ImportError: cannot import name 'Gofile' from 'gofile' (C:\Users\atuden\AppData\Local\Programs\Python\Python310\lib\site-packages\gofile\__init__.py)
```

**Comment by Jules-WinnfieldX** [comment]
> I see the same problem with 3.4.12 on windows:
> 
> ```
> C:\Users\atuden\Documents\tools\CyberDropDownloader-V2>pip install --upgrade cyberdrop-dl
> Requirement already satisfied: cyberdrop-dl in c:\users\atuden\appdata\local\programs\python\python310\lib\site-packages (3.4.12)
> Requirement already satisfied: aiofiles>=22.1.0 in c:\users\atuden\appdata\local\programs\python\python310\lib\site-packages (from cyberdrop-dl) (22.1.0)
> Requirement already satisfied: beautifulsoup4>=4.11.1 in c:\users\atuden\appdata\local\programs\python\python310\lib\site-packages (from cyberdrop-dl) (4.11.1)
> Requirement already satisfied: gofile-client>=1.0.1 in c:\users\atuden\appdata\local\programs\python\python310\lib\site-packages (from cyberdrop-dl) (1.0.1)
> Requirement already satisfied: certifi>=2022.9.24 in c:\users\atuden\appdata\local\programs\python\python310\lib\site-packages (from cyberdrop-dl) (2022.9.24)
> Requirement already satisfied: yarl>=1.8.1 in c:\users\atuden\appdata\local\programs\python\python310\lib\site-packages (from cyberdrop-dl) (1.8.1)
> Requirement already satisfied: colorama>=0.4.5 in c:\users\atuden\appdata\local\programs\python\python310\lib\site-packages (from cyberdrop-dl) (0.4.5)
> Requirement already satisfied: myjdapi>=1.1.6 in c:\users\atuden\appdata\local\programs\python\python310\lib\site-packages (from cyberdrop-dl) (1.1.6)
> Requirement already satisfied: setuptools>=65.4.1 in c:\users\atuden\appdata\local\programs\python\python310\lib\site-packages (from cyberdrop-dl) (65.4.1)
> Requirement already satisfied: tqdm>=4.64.1 in c:\users\atuden\appdata\local\programs\python\python310\lib\site-packages (from cyberdrop-dl) (4.64.1)
> Requirement already satisfied: PyYAML>=6.0 in c:\users\atuden\appdata\local\programs\python\python310\lib\site-packages (from cyberdrop-dl) (6.0)
> Requirement already satisfied: aiohttp>=3.8.3 in c:\users\atuden\appdata\local\programs\python\python310\lib\site-packages (from cyberdrop-dl) (3.8.3)
> Requirement already satisfied: charset-normalizer<3.0,>=2.0 in c:\users\atuden\appdata\roaming\python\python310\site-packages (from aiohttp>=3.8.3->cyberdrop-dl) (2.0.12)
> Requirement already satisfied: frozenlist>=1.1.1 in c:\users\atuden\appdata\roaming\python\python310\site-packages (from aiohttp>=3.8.3->cyberdrop-dl) (1.3.0)
> Requirement already satisfied: multidict<7.0,>=4.5 in c:\users\atuden\appdata\roaming\python\python310\site-packages (from aiohttp>=3.8.3->cyberdrop-dl) (6.0.2)
> Requirement already satisfied: attrs>=17.3.0 in c:\users\atuden\appdata\roaming\python\python310\site-packages (from aiohttp>=3.8.3->cyberdrop-dl) (21.4.0)
> Requirement already satisfied: aiosignal>=1.1.2 in c:\users\atuden\appdata\roaming\python\python310\site-packages (from aiohttp>=3.8.3->cyberdrop-dl) (1.2.0)
> Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in c:\users\atuden\appdata\roaming\python\python310\site-packages (from aiohttp>=3.8.3->cyberdrop-dl) (4.0.2)
> Requirement already satisfied: soupsieve>1.2 in c:\users\atuden\appdata\local\programs\python\python310\lib\site-packages (from beautifulsoup4>=4.11.1->cyberdrop-dl) (2.3.1)
> Requirement already satisfied: requests in c:\users\atuden\appdata\local\programs\python\python310\lib\site-packages (from gofile-client>=1.0.1->cyberdrop-dl) (2.25.1)
> Requirement already satisfied: pycryptodome in c:\users\atuden\appdata\local\programs\python\python310\lib\site-packages (from myjdapi>=1.1.6->cyberdrop-dl) (3.15.0)
> Requirement already satisfied: idna>=2.0 in c:\users\atuden\appdata\local\programs\python\python310\lib\site-packages (from yarl>=1.8.1->cyberdrop-dl) (2.10)
> Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\atuden\appdata\roaming\python\python310\site-packages (from requests->gofile-client>=1.0.1->cyberdrop-dl) (1.26.9)
> Requirement already satisfied: chardet<5,>=3.0.2 in c:\users\atuden\appdata\local\programs\python\python310\lib\site-packages (from requests->gofile-client>=1.0.1->cyberdrop-dl) (4.0.0)
> 
> C:\Users\atuden\Documents\tools\CyberDropDownloader-V2>cyberdrop-dl
> Traceback (most recent call last):
>   File "C:\Users\atuden\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "C:\Users\atuden\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
>     exec(code, run_globals)
>   File "C:\Users\atuden\AppData\Local\Programs\Python\Python310\Scripts\cyberdrop-dl.exe\__main__.py", line 4, in <module>
>   File "C:\Users\atuden\AppData\Local\Programs\Python\Python310\lib\site-packages\cyberdrop_dl\main.py", line 19, in <module>
>     from cyberdrop_dl.scraper.scraper import scrape
>   File "C:\Users\atuden\AppData\Local\Programs\Python\Python310\lib\site-packages\cyberdrop_dl\scraper\scraper.py", line 3, in <module>
>     from .scraper_helper import ScrapeMapper
>   File "C:\Users\atuden\AppData\Local\Programs\Python\Python310\lib\site-packages\cyberdrop_dl\scraper\scraper_helper.py", line 17, in <module>
>     from ..crawlers.GoFile_Spider import GofileCrawler
>   File "C:\Users\atuden\AppData\Local\Programs\Python\Python310\lib\site-packages\cyberdrop_dl\crawlers\GoFile_Spider.py", line 4, in <module>
>     from gofile import Gofile
> ImportError: cannot import name 'Gofile' from 'gofile' (C:\Users\atuden\AppData\Local\Programs\Python\Python310\lib\site-packages\gofile\__init__.py)
> ```

Can you try and do a `pip uninstall gofile` and try again?

**Comment by jtm666** [comment]
Had been using v3.4.12, was working fine yesterday

E:\Cyberdrop_DL.V3>pip install --upgrade cyberdrop-dl
Requirement already satisfied: cyberdrop-dl in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (3.4.12)
.
.
.
   from ..crawlers.GoFile_Spider import GofileCrawler
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\cyberdrop_dl\crawlers\GoFile_Spider.py", line 4, in <module>
    from gofile import Gofile
ImportError: cannot import name 'Gofile' from 'gofile' (C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\gofile\__init__.py)

**Comment by astuden** [comment]
Different error now after removing the "gofile" package:
```
C:\Users\atuden\Documents\tools\CyberDropDownloader-V2>pip install --upgrade cyberdrop-dl
Requirement already satisfied: cyberdrop-dl in c:\users\atuden\appdata\local\programs\python\python310\lib\site-packages (3.4.12)
Requirement already satisfied: gofile-client>=1.0.1 in c:\users\atuden\appdata\local\programs\python\python310\lib\site-packages (from cyberdrop-dl) (1.0.1)
Requirement already satisfied: certifi>=2022.9.24 in c:\users\atuden\appdata\local\programs\python\python310\lib\site-packages (from cyberdrop-dl) (2022.9.24)
Requirement already satisfied: tqdm>=4.64.1 in c:\users\atuden\appdata\local\programs\python\python310\lib\site-packages (from cyberdrop-dl) (4.64.1)
Requirement already satisfied: PyYAML>=6.0 in c:\users\atuden\appdata\local\programs\python\python310\lib\site-packages (from cyberdrop-dl) (6.0)
Requirement already satisfied: colorama>=0.4.5 in c:\users\atuden\appdata\local\programs\python\python310\lib\site-packages (from cyberdrop-dl) (0.4.5)
Requirement already satisfied: aiofiles>=22.1.0 in c:\users\atuden\appdata\local\programs\python\python310\lib\site-packages (from cyberdrop-dl) (22.1.0)
Requirement already satisfied: beautifulsoup4>=4.11.1 in c:\users\atuden\appdata\local\programs\python\python310\lib\site-packages (from cyberdrop-dl) (4.11.1)
Requirement already satisfied: yarl>=1.8.1 in c:\users\atuden\appdata\local\programs\python\python310\lib\site-packages (from cyberdrop-dl) (1.8.1)
Requirement already satisfied: myjdapi>=1.1.6 in c:\users\atuden\appdata\local\programs\python\python310\lib\site-packages (from cyberdrop-dl) (1.1.6)
Requirement already satisfied: aiohttp>=3.8.3 in c:\users\atuden\appdata\local\programs\python\python310\lib\site-packages (from cyberdrop-dl) (3.8.3)
Requirement already satisfied: setuptools>=65.4.1 in c:\users\atuden\appdata\local\programs\python\python310\lib\site-packages (from cyberdrop-dl) (65.4.1)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\users\atuden\appdata\roaming\python\python310\site-packages (from aiohttp>=3.8.3->cyberdrop-dl) (6.0.2)
Requirement already satisfied: frozenlist>=1.1.1 in c:\users\atuden\appdata\roaming\python\python310\site-packages (from aiohttp>=3.8.3->cyberdrop-dl) (1.3.0)
Requirement already satisfied: aiosignal>=1.1.2 in c:\users\atuden\appdata\roaming\python\python310\site-packages (from aiohttp>=3.8.3->cyberdrop-dl) (1.2.0)
Requirement already satisfied: attrs>=17.3.0 in c:\users\atuden\appdata\roaming\python\python310\site-packages (from aiohttp>=3.8.3->cyberdrop-dl) (21.4.0)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in c:\users\atuden\appdata\roaming\python\python310\site-packages (from aiohttp>=3.8.3->cyberdrop-dl) (4.0.2)
Requirement already satisfied: charset-normalizer<3.0,>=2.0 in c:\users\atuden\appdata\roaming\python\python310\site-packages (from aiohttp>=3.8.3->cyberdrop-dl) (2.0.12)
Requirement already satisfied: soupsieve>1.2 in c:\users\atuden\appdata\local\programs\python\python310\lib\site-packages (from beautifulsoup4>=4.11.1->cyberdrop-dl) (2.3.1)
Requirement already satisfied: requests in c:\users\atuden\appdata\local\programs\python\python310\lib\site-packages (from gofile-client>=1.0.1->cyberdrop-dl) (2.25.1)
Requirement already satisfied: pycryptodome in c:\users\atuden\appdata\local\programs\python\python310\lib\site-packages (from myjdapi>=1.1.6->cyberdrop-dl) (3.15.0)
Requirement already satisfied: idna>=2.0 in c:\users\atuden\appdata\local\programs\python\python310\lib\site-packages (from yarl>=1.8.1->cyberdrop-dl) (2.10)
Requirement already satisfied: chardet<5,>=3.0.2 in c:\users\atuden\appdata\local\programs\python\python310\lib\site-packages (from requests->gofile-client>=1.0.1->cyberdrop-dl) (4.0.0)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\atuden\appdata\roaming\python\python310\site-packages (from requests->gofile-client>=1.0.1->cyberdrop-dl) (1.26.9)

C:\Users\atuden\Documents\tools\CyberDropDownloader-V2>cyberdrop-dl
Traceback (most recent call last):
  File "C:\Users\atuden\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\atuden\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\atuden\AppData\Local\Programs\Python\Python310\Scripts\cyberdrop-dl.exe\__main__.py", line 4, in <module>
  File "C:\Users\atuden\AppData\Local\Programs\Python\Python310\lib\site-packages\cyberdrop_dl\main.py", line 19, in <module>
    from cyberdrop_dl.scraper.scraper import scrape
  File "C:\Users\atuden\AppData\Local\Programs\Python\Python310\lib\site-packages\cyberdrop_dl\scraper\scraper.py", line 3, in <module>
    from .scraper_helper import ScrapeMapper
  File "C:\Users\atuden\AppData\Local\Programs\Python\Python310\lib\site-packages\cyberdrop_dl\scraper\scraper_helper.py", line 17, in <module>
    from ..crawlers.GoFile_Spider import GofileCrawler
  File "C:\Users\atuden\AppData\Local\Programs\Python\Python310\lib\site-packages\cyberdrop_dl\crawlers\GoFile_Spider.py", line 4, in <module>
    from gofile import Gofile
ImportError: cannot import name 'Gofile' from 'gofile' (unknown location)
```

**Comment by Jules-WinnfieldX** [comment]
Can someone try 3.4.14?

**Comment by jtm666** [comment]
E:\Cyberdrop_DL.V3>pip install --upgrade cyberdrop-dl
Requirement already satisfied: cyberdrop-dl in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (3.4.14)
.
.
.
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\cyberdrop_dl\crawlers\GoFile_Spider.py", line 4, in <module>
    from gofile import Gofile
ImportError: cannot import name 'Gofile' from 'gofile' (C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\gofile\__init__.py)

Still no luck

**Comment by SaalazarBR** [comment]
Fixed after uninstalled the gofile-client

**Comment by Jules-WinnfieldX** [comment]
> E:\Cyberdrop_DL.V3>pip install --upgrade cyberdrop-dl Requirement already satisfied: cyberdrop-dl in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (3.4.14) . . . File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\cyberdrop_dl\crawlers\GoFile_Spider.py", line 4, in from gofile import Gofile ImportError: cannot import name 'Gofile' from 'gofile' (C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\gofile__init__.py)
> 
> Still no luck

What's annoying is the fact that I reverted it back to exactly what it was before :(

**Comment by astuden** [comment]
Same, no luck with 3.4.14:
```
C:\Users\atuden\Documents\tools\CyberDropDownloader-V2>pip install --upgrade cyberdrop-dl
Requirement already satisfied: cyberdrop-dl in c:\users\atuden\appdata\local\programs\python\python310\lib\site-packages (3.4.14)
Requirement already satisfied: tqdm>=4.64.1 in c:\users\atuden\appdata\local\programs\python\python310\lib\site-packages (from cyberdrop-dl) (4.64.1)
Requirement already satisfied: PyYAML>=6.0 in c:\users\atuden\appdata\local\programs\python\python310\lib\site-packages (from cyberdrop-dl) (6.0)
Requirement already satisfied: colorama>=0.4.5 in c:\users\atuden\appdata\local\programs\python\python310\lib\site-packages (from cyberdrop-dl) (0.4.5)
Requirement already satisfied: gofile-client>=1.0.1 in c:\users\atuden\appdata\local\programs\python\python310\lib\site-packages (from cyberdrop-dl) (1.0.1)
Requirement already satisfied: certifi>=2022.9.24 in c:\users\atuden\appdata\local\programs\python\python310\lib\site-packages (from cyberdrop-dl) (2022.9.24)
Requirement already satisfied: myjdapi>=1.1.6 in c:\users\atuden\appdata\local\programs\python\python310\lib\site-packages (from cyberdrop-dl) (1.1.6)
Requirement already satisfied: aiofiles>=22.1.0 in c:\users\atuden\appdata\local\programs\python\python310\lib\site-packages (from cyberdrop-dl) (22.1.0)
Requirement already satisfied: aiohttp>=3.8.3 in c:\users\atuden\appdata\local\programs\python\python310\lib\site-packages (from cyberdrop-dl) (3.8.3)
Requirement already satisfied: yarl>=1.8.1 in c:\users\atuden\appdata\local\programs\python\python310\lib\site-packages (from cyberdrop-dl) (1.8.1)
Requirement already satisfied: beautifulsoup4>=4.11.1 in c:\users\atuden\appdata\local\programs\python\python310\lib\site-packages (from cyberdrop-dl) (4.11.1)
Requirement already satisfied: aiosignal>=1.1.2 in c:\users\atuden\appdata\roaming\python\python310\site-packages (from aiohttp>=3.8.3->cyberdrop-dl) (1.2.0)
Requirement already satisfied: attrs>=17.3.0 in c:\users\atuden\appdata\roaming\python\python310\site-packages (from aiohttp>=3.8.3->cyberdrop-dl) (21.4.0)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\users\atuden\appdata\roaming\python\python310\site-packages (from aiohttp>=3.8.3->cyberdrop-dl) (6.0.2)
Requirement already satisfied: charset-normalizer<3.0,>=2.0 in c:\users\atuden\appdata\roaming\python\python310\site-packages (from aiohttp>=3.8.3->cyberdrop-dl) (2.0.12)
Requirement already satisfied: frozenlist>=1.1.1 in c:\users\atuden\appdata\roaming\python\python310\site-packages (from aiohttp>=3.8.3->cyberdrop-dl) (1.3.0)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in c:\users\atuden\appdata\roaming\python\python310\site-packages (from aiohttp>=3.8.3->cyberdrop-dl) (4.0.2)
Requirement already satisfied: soupsieve>1.2 in c:\users\atuden\appdata\local\programs\python\python310\lib\site-packages (from beautifulsoup4>=4.11.1->cyberdrop-dl) (2.3.1)
Requirement already satisfied: requests in c:\users\atuden\appdata\local\programs\python\python310\lib\site-packages (from gofile-client>=1.0.1->cyberdrop-dl) (2.25.1)
Requirement already satisfied: pycryptodome in c:\users\atuden\appdata\local\programs\python\python310\lib\site-packages (from myjdapi>=1.1.6->cyberdrop-dl) (3.15.0)
Requirement already satisfied: idna>=2.0 in c:\users\atuden\appdata\local\programs\python\python310\lib\site-packages (from yarl>=1.8.1->cyberdrop-dl) (2.10)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\atuden\appdata\roaming\python\python310\site-packages (from requests->gofile-client>=1.0.1->cyberdrop-dl) (1.26.9)
Requirement already satisfied: chardet<5,>=3.0.2 in c:\users\atuden\appdata\local\programs\python\python310\lib\site-packages (from requests->gofile-client>=1.0.1->cyberdrop-dl) (4.0.0)

C:\Users\atuden\Documents\tools\CyberDropDownloader-V2>cyberdrop-dl
Traceback (most recent call last):
  File "C:\Users\atuden\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\atuden\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\atuden\AppData\Local\Programs\Python\Python310\Scripts\cyberdrop-dl.exe\__main__.py", line 4, in <module>
  File "C:\Users\atuden\AppData\Local\Programs\Python\Python310\lib\site-packages\cyberdrop_dl\main.py", line 19, in <module>
    from cyberdrop_dl.scraper.scraper import scrape
  File "C:\Users\atuden\AppData\Local\Programs\Python\Python310\lib\site-packages\cyberdrop_dl\scraper\scraper.py", line 3, in <module>
    from .scraper_helper import ScrapeMapper
  File "C:\Users\atuden\AppData\Local\Programs\Python\Python310\lib\site-packages\cyberdrop_dl\scraper\scraper_helper.py", line 17, in <module>
    from ..crawlers.GoFile_Spider import GofileCrawler
  File "C:\Users\atuden\AppData\Local\Programs\Python\Python310\lib\site-packages\cyberdrop_dl\crawlers\GoFile_Spider.py", line 4, in <module>
    from gofile import Gofile
ModuleNotFoundError: No module named 'gofile'
```

I noticed that I only have a "gofile_client-1.0.1.dist-info" folder in my "Python310\Lib\site-packages" directory, no "gofile-client" source code directory. Problem with PIP?

**Comment by Jules-WinnfieldX** [comment]
It should only be that one gofile_client, it imports as gofile, which when I accidentally included the regular gofile library things broke.

**Comment by Jules-WinnfieldX** [comment]
you could try uninstalling it as well, then re-running the install

**Comment by astuden** [comment]
After `pip uninstall -y gofile-client`, CyberDrop works again. I now have a "gofile" directory in my "site-packages" dir.

**Comment by jtm666** [comment]
> pip uninstall -y gofile-client

This works for me as well :)

**Comment by Jules-WinnfieldX** [comment]
I'll wait a little while to close this issue, and I'll wait to try re-simplify.

**Comment by astuden** [comment]
It seems like PIP was getting confused with the naming of the "gofile" and "gofile-client" packages. My old "site-packages\gofile" directory contained the "__init__.py" file from the "gofile" package, but the "client.py" file from the "gofile-client" package.

**Comment by Jules-WinnfieldX** [comment]
pipreqs fucked me over.

**Comment by solartrans** [comment]
> pip uninstall -y gofile-client
this worked for me too! problem solved, thanks guys.
