### ISSUE TITLE
[BUG] SSL: CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by bhaskoro-muthohar** [Jules-WinnfieldX/CyberDropDownloader#239]
**Describe the bug**
I tried to download an album from cyberdrop but some file got SSL Error.

**To Help Reproduce**
Steps to help reproduce the behavior:
1. Put the link on URLs file
2. Run cyberdrop-dl
3. Got SSL error for some files

**Screenshots**
![image](https://user-images.githubusercontent.com/35159954/195906390-912a8f06-051e-4224-a801-bc8065f72ac0.png)
![image](https://user-images.githubusercontent.com/35159954/195906541-507832a5-02a6-4856-8460-7110d99feeb1.png)

**Setup Information**
 - OS: Windows 10
 - Cyberdrop Downloader Version 3.4.14

**Downloader.log file**
[downloader.txt](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/9788767/downloader.txt)

**Comment by Jules-WinnfieldX** [comment]
This isn't an issue with the downloader, as it says in the error, cyberdrop's certificates have expired. It's on them to fix, I can't do anything about it without getting rid of all the security the program has.

**Comment by bhaskoro-muthohar** [comment]
I have a workaround for this, it involves using JDownloader2:

1. Open the downloader_history.sqlite by using your favorite SQLite browser
2. Query `SELECT "https://fs-01.cyberdrop.cc" | path FROM downloads`
3. Export the query results as a CSV
4. Paste all the links from that CSV to JDownloader2
5. Profit
