### ISSUE TITLE
[BUG] Can't download MP4 files from Cyberdrop

### ISSUE THREAD

**Issue by kkma24** [Jules-WinnfieldX/CyberDropDownloader#241]
**Setup Information**
 - OS:  Windows 10 HOME
 - Cyberdrop Downloader Version # 3.4.16

**Additional context**

The photo file downloads without any problem.
Can't download only .mp4 files

After copying the URL address of the failed .mp4 from the log
I can download it by pasting it into the Internet
ex // 2022-10-17 03:52:45,796:DEBUG:downloaders:downloaders.py:34:Skipping https://fs-01.cyberdrop.cc/0goau6v0e2ym3oc2y2806_source-pEIsYpcs.mp4...

So the URL is not problem

Maybe the script or function that reads .mp4 has been changed?

**Comment by Jules-WinnfieldX** [comment]
Cyberdrop's certificates have all expired, and it's a security risk allowing automated downloading from an insecure website. They need to fix it, it isn't an issue with the downloader.
