### ISSUE TITLE
[FEATURE] mark scrape as done mode

### ISSUE THREAD

**Issue by hrm-princess-fluffybutt** [Jules-WinnfieldX/CyberDropDownloader#243]
an argument that makes the program do the scrape as normal, but then only marks files as completed in the local db without downloading

**Comment by Jules-WinnfieldX** [comment]
This is coming in 3.4.26

**Comment by Jules-WinnfieldX** [comment]
Implemented

**Comment by Jules-WinnfieldX** [comment]
--mark-downloaded
