### ISSUE TITLE
[FEATURE] remove URL when completed 

### ISSUE THREAD

**Issue by despecial** [Jules-WinnfieldX/CyberDropDownloader#247]
First up, I love the latest version - it's so smooth!

Since CDD already handles unsupported urls and puts them in its own file, it would be great if the URLs.txt gets a cleanup feature. So, after the download is complete, the url will be removed or put in a Completed.txt file.

In the config.yaml file is a setting called "mark_downloaded". I set it to true but cannot figure out what should happen. The link is still in the URLs.txt after finishing the downloads.

**Comment by Jules-WinnfieldX** [comment]
The only reason why I'm hesitant to implement something like this is because not all downloads from links might work / complete fully.

**Comment by despecial** [comment]
Ah okay. But when it says 100% in the terminal, all the links should have been downloaded, right?

**Comment by Jules-WinnfieldX** [comment]
Hypothetically, yes. As long as it was actually able to scrape 100% of the links.

**Comment by despecial** [comment]
Hmm, the terminal closes as soon as its finished. I cannot see if there are partial downloads left over.
Or do I have to check the download.log each time? 

Sounds like its more complicated then I thought. Thanks for the insight

**Comment by despecial** [comment]
https://user-images.githubusercontent.com/4135109/197620017-b4e9b0fc-8b9b-4f94-b3df-1c44c5b54d16.mov

It shows it for a few seconds, then terminal closes the window

**Comment by despecial** [comment]
Exactly

**Comment by Jules-WinnfieldX** [comment]
If you are using a start script, can you open it in an editor, and show me what's in it?

**Comment by despecial** [comment]
It's the one that will be downloaded from the script itself

```
#!/bin/sh
cd "$(dirname "$0")"
pip install --upgrade cyberdrop-dl
cyberdrop-dl
```

**Comment by Jules-WinnfieldX** [comment]
Add
`read -p "Press any key to resume ..."`
to the end of it, below cyberdrop-dl

**Comment by despecial** [comment]
That worked. Terminal stays open.

**Comment by despecial** [comment]
> But also, pay attention to final lines that say "partial downloads still exist". The % is just how many files it's gone through. Even if one fails out and is left as a partial it will hit 100%

btw this didn't show up even though I can see messages above like "Error attempting http..."

**Comment by Jules-WinnfieldX** [comment]
The partial downloads message only shows up at the end, and only if there are any remaining .part files in the download folder.

**Comment by despecial** [comment]
I see. Maybe a message like "There were problems downloading all files" would be helpful.

Thanks!

**Comment by Jules-WinnfieldX** [comment]
The logistics behind that are a bit complicated, for example if a file no longer exists, and it returns a 404 value, that would trigger, a "problem". But that file is never going to download, as it doesn't exist anymore. That's what majority of the errors you will see when scraping are.

**Comment by despecial** [comment]
Okay, so at the moment, there is no way to tell if the downloads are really completed. A pity.

But the feature request should stay open imho even if you cannot implement it right now. Other people can see that it's already posted ;)

**Comment by Jules-WinnfieldX** [comment]
There's never going to be a way to 100% know. Whether the scraper misses something, links straight up don't work anymore, or downloading restrictions change.

The best method will likely remain simply checking for partial downloads, which the program does. I'll take it under consideration though and put some thought to it.

**Comment by despecial** [comment]
Cool, thanks!
