### ISSUE TITLE
[FEATURE] Setting a download path when downloading from forums

### ISSUE THREAD

**Issue by maslos** [Jules-WinnfieldX/CyberDropDownloader#248]
**Is your feature request related to a problem? Please describe.**
Right now when downloading from forum, all attatchments / galleries goes into single directory

**Describe the solution you'd like**
Option to enable or to set a download path for example thread_name/post1, thread_name/post2 etc.

**Additional context**
Easier to sort and keep track of whats been downloaded so far

**Comment by Jules-WinnfieldX** [comment]
This somewhat exists (I need to fix the readme)

But `--separate-posts` "Separates forum scraping into folders by post number"
