### ISSUE TITLE
[BUG] Table t already exists

### ISSUE THREAD

**Issue by RazFox** [Jules-WinnfieldX/CyberDropDownloader#249]
`We are running version 3.5.4 of Cyberdrop Downloader
Creating Config
Validating Config
Getting Run Args
Gathering Args
Traceback (most recent call last):
  File "C:\Python\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Python\Scripts\cyberdrop-dl.exe\__main__.py", line 7, in <module>
  File "C:\Python\lib\site-packages\cyberdrop_dl\main.py", line 197, in main
    loop.run_until_complete(director(args))
  File "C:\Python\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "C:\Python\lib\site-packages\cyberdrop_dl\main.py", line 146, in director
    await SQL_helper.sql_initialize()
  File "C:\Python\lib\site-packages\cyberdrop_dl\base_functions\sql_helper.py", line 45, in sql_initialize
    self.curs.execute(pre_alloc)
sqlite3.OperationalError: table t already exists`

The script on win is not used through a bat file, not through the console with a call to cyberdrop-dl. Calling cyberdrop-dl produces the following message:
We are using version 3.5.4 of Cyberdrop Downloader.
Create a configuration
Configuration check
Getting startup arguments
Collection of arguments
Links not found, check URL.txt
If the link works in your web browser, please send me a release request.
Start cleaning
Links not found during scraping, checking passwords, or checking URL availability.
This program does not currently support password-protected albums.

There are links in txt. Each link on a separate line.

**Comment by RazFox** [comment]
https://jpg.church/a/marcy-halloween.KBWVE
https://jpg.church/a/old-melamori.Xtvjp
https://bunkr.is/a/qOmZSjpZ

**Comment by Jules-WinnfieldX** [comment]
Sometime before this run you managed to stop the script at the exact right time for the table t to not be deleted (happens right after creation essentially), and I didn't have a check for it already existed because of it.

Update to 3.5.5 and try again

**Comment by RazFox** [comment]
Thank you so much for such a quick fix! Everything works perfectly!

**Comment by Jules-WinnfieldX** [comment]
No worries
