### ISSUE TITLE
[BUG] Error scraping links with apostrophes

### ISSUE THREAD

**Issue by cumblast** [Jules-WinnfieldX/CyberDropDownloader#250]
**Describe the bug**
An error occurs when scraping links with apostrophes.

**To Help Reproduce**
Steps to help reproduce the behavior:
1. Put a link with an apostrophe into `URLs.txt` (for example https://stream.bunkr.is/v/kimtylor_-2020.07.16-I'm-The-Best-Naughty-School-Girl-Ever-onlyfans-pWsNftD1.mp4).
2. Run `cyberdrop-dl`.

**Setup Information**
 - OS: Windows 11
 - Cyberdrop Downloader Version 3.5.5

**Downloader.log file**
[downloader.log](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/9868106/downloader.log)

**Comment by Jules-WinnfieldX** [comment]
This probably broke something else, but fixed this in 3.5.6
