### ISSUE TITLE
[BUG] Python_v3.11 Incompatible

### ISSUE THREAD

**Issue by bluefire369** [Jules-WinnfieldX/CyberDropDownloader#251]
**After Upgrading from Python v3.10.8 to 3.11, the program doesn't work anymore. The upgrading was down after uninstalling the old python completely.**

**Screenshots**

**Setup Information**
 - OS: [Windows 11 Build22621.755]
 - Cyberdrop Downloader Version #[3.5.1](https://github.com/Jules-WinnfieldX/CyberDropDownloader/releases/download/Release/Cyberdrop_DL.V3.zip)

**Downloader.log file**
`C:\Users\Nithish Thulaseedas\AppData\Local\Windows Utilities (Portable)\Cyberdrop DL_v3.5>pip install --upgrade cyberdrop-dl
Collecting cyberdrop-dl
  Using cached cyberdrop_dl-3.5.11-py3-none-any.whl (61 kB)
Collecting aiofiles>=22.1.0
  Using cached aiofiles-22.1.0-py3-none-any.whl (14 kB)
Collecting aiohttp>=3.8.3
  Using cached aiohttp-3.8.3-cp311-cp311-win_amd64.whl (317 kB)
Collecting beautifulsoup4>=4.11.1
  Using cached beautifulsoup4-4.11.1-py3-none-any.whl (128 kB)
Collecting certifi>=2022.9.24
  Using cached certifi-2022.9.24-py3-none-any.whl (161 kB)
Collecting colorama>=0.4.5
  Using cached colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Collecting gofile-client>=1.0.1
  Using cached gofile_client-1.0.1-py3-none-any.whl (7.3 kB)
Collecting myjdapi>=1.1.6
  Using cached myjdapi-1.1.6-py3-none-any.whl (13 kB)
Collecting PyYAML>=6.0
  Using cached PyYAML-6.0-cp311-cp311-win_amd64.whl (143 kB)
Requirement already satisfied: setuptools>=65.5.0 in c:\users\nithish thulaseedas\appdata\local\programs\python\python311\lib\site-packages (from cyberdrop-dl) (65.5.0)
Collecting tqdm>=4.64.1
  Using cached tqdm-4.64.1-py2.py3-none-any.whl (78 kB)
Collecting yarl>=1.8.1
  Using cached yarl-1.8.1.tar.gz (172 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting attrs>=17.3.0
  Using cached attrs-22.1.0-py2.py3-none-any.whl (58 kB)
Collecting charset-normalizer<3.0,>=2.0
  Using cached charset_normalizer-2.1.1-py3-none-any.whl (39 kB)
Collecting multidict<7.0,>=4.5
  Using cached multidict-6.0.2.tar.gz (50 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting async-timeout<5.0,>=4.0.0a3
  Using cached async_timeout-4.0.2-py3-none-any.whl (5.8 kB)
Collecting frozenlist>=1.1.1
  Using cached frozenlist-1.3.1.tar.gz (66 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting aiosignal>=1.1.2
  Using cached aiosignal-1.2.0-py3-none-any.whl (8.2 kB)
Collecting soupsieve>1.2
  Using cached soupsieve-2.3.2.post1-py3-none-any.whl (37 kB)
Collecting requests
  Using cached requests-2.28.1-py3-none-any.whl (62 kB)
Collecting pycryptodome
  Using cached pycryptodome-3.15.0-cp35-abi3-win_amd64.whl (1.9 MB)
Collecting idna>=2.0
  Using cached idna-3.4-py3-none-any.whl (61 kB)
Collecting urllib3<1.27,>=1.21.1
  Using cached urllib3-1.26.12-py2.py3-none-any.whl (140 kB)
Building wheels for collected packages: yarl, frozenlist, multidict
  Building wheel for yarl (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for yarl (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [37 lines of output]
      C:\Users\Nithish Thulaseedas\AppData\Local\Temp\pip-build-env-98r6birq\overlay\Lib\site-packages\setuptools\config\setupcfg.py:508: SetuptoolsDeprecationWarning: The license_file parameter is deprecated, use license_files instead.
        warnings.warn(msg, warning_class)
      **********************
      * Accelerated build *
      **********************
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-311
      creating build\lib.win-amd64-cpython-311\yarl
      copying yarl\_quoting.py -> build\lib.win-amd64-cpython-311\yarl
      copying yarl\_quoting_py.py -> build\lib.win-amd64-cpython-311\yarl
      copying yarl\_url.py -> build\lib.win-amd64-cpython-311\yarl
      copying yarl\__init__.py -> build\lib.win-amd64-cpython-311\yarl
      running egg_info
      writing yarl.egg-info\PKG-INFO
      writing dependency_links to yarl.egg-info\dependency_links.txt
      writing requirements to yarl.egg-info\requires.txt
      writing top-level names to yarl.egg-info\top_level.txt
      reading manifest file 'yarl.egg-info\SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      warning: no previously-included files matching '*.pyc' found anywhere in distribution
      warning: no previously-included files matching '*.cache' found anywhere in distribution
      warning: no previously-included files found matching 'yarl\*.html'
      warning: no previously-included files found matching 'yarl\*.so'
      warning: no previously-included files found matching 'yarl\*.pyd'
      no previously-included directories found matching 'docs\_build'
      adding license file 'LICENSE'
      writing manifest file 'yarl.egg-info\SOURCES.txt'
      copying yarl\__init__.pyi -> build\lib.win-amd64-cpython-311\yarl
      copying yarl\_quoting_c.pyi -> build\lib.win-amd64-cpython-311\yarl
      copying yarl\_quoting_c.pyx -> build\lib.win-amd64-cpython-311\yarl
      copying yarl\py.typed -> build\lib.win-amd64-cpython-311\yarl
      running build_ext
      building 'yarl._quoting_c' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for yarl
  Building wheel for frozenlist (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for frozenlist (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [33 lines of output]
      *********************
      * Accelerated build *
      *********************
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-311
      creating build\lib.win-amd64-cpython-311\frozenlist
      copying frozenlist\__init__.py -> build\lib.win-amd64-cpython-311\frozenlist
      running egg_info
      writing frozenlist.egg-info\PKG-INFO
      writing dependency_links to frozenlist.egg-info\dependency_links.txt
      writing top-level names to frozenlist.egg-info\top_level.txt
      reading manifest file 'frozenlist.egg-info\SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      warning: no previously-included files matching '*.pyc' found anywhere in distribution
      warning: no previously-included files matching '*.pyd' found anywhere in distribution
      warning: no previously-included files matching '*.so' found anywhere in distribution
      warning: no previously-included files matching '*.lib' found anywhere in distribution
      warning: no previously-included files matching '*.dll' found anywhere in distribution
      warning: no previously-included files matching '*.a' found anywhere in distribution
      warning: no previously-included files matching '*.obj' found anywhere in distribution
      warning: no previously-included files found matching 'frozenlist\*.html'
      no previously-included directories found matching 'docs\_build'
      adding license file 'LICENSE'
      writing manifest file 'frozenlist.egg-info\SOURCES.txt'
      copying frozenlist\__init__.pyi -> build\lib.win-amd64-cpython-311\frozenlist
      copying frozenlist\_frozenlist.pyx -> build\lib.win-amd64-cpython-311\frozenlist
      copying frozenlist\py.typed -> build\lib.win-amd64-cpython-311\frozenlist
      running build_ext
      building 'frozenlist._frozenlist' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for frozenlist
  Building wheel for multidict (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for multidict (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [59 lines of output]
      *********************
      * Accelerated build *
      *********************
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-311
      creating build\lib.win-amd64-cpython-311\multidict
      copying multidict\_abc.py -> build\lib.win-amd64-cpython-311\multidict
      copying multidict\_compat.py -> build\lib.win-amd64-cpython-311\multidict
      copying multidict\_multidict_base.py -> build\lib.win-amd64-cpython-311\multidict
      copying multidict\_multidict_py.py -> build\lib.win-amd64-cpython-311\multidict
      copying multidict\__init__.py -> build\lib.win-amd64-cpython-311\multidict
      running egg_info
      writing multidict.egg-info\PKG-INFO
      writing dependency_links to multidict.egg-info\dependency_links.txt
      writing top-level names to multidict.egg-info\top_level.txt
      reading manifest file 'multidict.egg-info\SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      warning: no previously-included files matching '*.pyc' found anywhere in distribution
      warning: no previously-included files found matching 'multidict\_multidict.html'
      warning: no previously-included files found matching 'multidict\*.so'
      warning: no previously-included files found matching 'multidict\*.pyd'
      warning: no previously-included files found matching 'multidict\*.pyd'
      no previously-included directories found matching 'docs\_build'
      adding license file 'LICENSE'
      writing manifest file 'multidict.egg-info\SOURCES.txt'
      C:\Users\Nithish Thulaseedas\AppData\Local\Temp\pip-build-env-ofojjccp\overlay\Lib\site-packages\setuptools\command\build_py.py:202: SetuptoolsDeprecationWarning:     Installing 'multidict._multilib' as data is deprecated, please list it in `packages`.
          !!

          ############################
          # Package would be ignored #
          ############################
          Python recognizes 'multidict._multilib' as an importable package,
          but it is not listed in the `packages` configuration of setuptools.

          'multidict._multilib' has been automatically added to the distribution only
          because it may contain data files, but this behavior is likely to change
          in future versions of setuptools (and therefore is considered deprecated).

          Please make sure that 'multidict._multilib' is included as a package by using
          the `packages` configuration field or the proper discovery methods
          (for example by using `find_namespace_packages(...)`/`find_namespace:`
          instead of `find_packages(...)`/`find:`).

          You can read more about "package discovery" and "data files" on setuptools
          documentation page.

      !!

        check.warn(importable)
      copying multidict\__init__.pyi -> build\lib.win-amd64-cpython-311\multidict
      copying multidict\py.typed -> build\lib.win-amd64-cpython-311\multidict
      running build_ext
      building 'multidict._multidict' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for multidict
Failed to build yarl frozenlist multidict
ERROR: Could not build wheels for yarl, frozenlist, multidict, which is required to install pyproject.toml-based projects

C:\Users\Nithish Thulaseedas\AppData\Local\Windows Utilities (Portable)\Cyberdrop DL_v3.5>cyberdrop-dl
'cyberdrop-dl' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\Nithish Thulaseedas\AppData\Local\Windows Utilities (Portable)\Cyberdrop DL_v3.5>pause
Press any key to continue . . .`

**Additional context**

**Comment by Jules-WinnfieldX** [comment]
It's not currently compatible with 3.11, it's on my to do list. Probably later today.

**Comment by Jules-WinnfieldX** [comment]
This is because of a dependency not having wheels available and them trying to be built from source, but failing because you don't have the build tools to do so.

I'm going to say Cyberdrop-DL is not 3.11 compatible for now. Will need to wait for the offending dependencies to be updated.

**Comment by Jules-WinnfieldX** [comment]
You can either install the said microsoft c++ build tools, or you can downgrade back to python 3.10.

**Comment by bluefire369** [comment]
Thank you, sir, for the quick reply. I just wanted to ensure I didn't mess up the new python Installation. 
Sorry for placing the issue as a bug, rather, it's because I update things most often soon as their release. 

#### May I ask which options I should choose from these to get installed?
![Visual_Studio_Installer_21](https://user-images.githubusercontent.com/4039987/198697354-fb4cb354-f022-4ed3-a7db-a34b3ab7edcb.png)

**Comment by Jules-WinnfieldX** [comment]
Pretty much the ones that are auto selected should work. You might have to restart your computer after installing to try again.

**Comment by bluefire369** [comment]
Thank you sir. The issue is resolved.😊
Installed Windows 11 SDK and VSC C++ 14 x86/64 alone, individually, to save space. But that seems to be working.
