### ISSUE TITLE
[BUG] No bunkr download

### ISSUE THREAD

**Issue by axel845845** [Jules-WinnfieldX/CyberDropDownloader#252]
I don't know why but it's giving me a lot of errors.
[downloader.log](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/9888375/downloader.log)

**Comment by Jules-WinnfieldX** [comment]
Is your disk full?

**Comment by axel845845** [comment]
> Is your disk full?

No, obviously

**Comment by Jules-WinnfieldX** [comment]
Just gotta cover bases. The only reason this should happen is if the disk is full, or for some reason the program isn't able to write output. 

I think I rectified that message a while ago, you are on 3.3.3, the latest version is 3.5.14. Try updating.

**Comment by axel845845** [comment]
Indeed, I am on 3.3.3, but how do I update it?

**Comment by Jules-WinnfieldX** [comment]
Open command prompt and type `pip install --upgrade cyberdrop-dl`

**Comment by axel845845** [comment]
Error
Command "python setup.py egg_info" failed with error code 1 in C:\Users\brawl\AppData\Local\Temp\pip-install-bd0azn_0\pycryptodome\

**Comment by Jules-WinnfieldX** [comment]
I need more information than that

**Comment by axel845845** [comment]
C:\Users\brawl>cd D:\Cyberdrop_DL.V3

C:\Users\brawl>pip install --upgrade cyberdrop-dl
Collecting cyberdrop-dl
  Using cached https://files.pythonhosted.org/packages/85/17/341ace3908f5c6d9e5fa0f3da407696dfbdf47240bb76758d86a1151c367/cyberdrop_dl-3.5.14-py3-none-any.whl
Requirement already satisfied, skipping upgrade: beautifulsoup4>=4.11.1 in c:\robodk\python37\lib\site-packages (from cyberdrop-dl) (4.11.1)
Collecting PyYAML>=6.0 (from cyberdrop-dl)
  Using cached https://files.pythonhosted.org/packages/d1/c0/4fe04181b0210ee2647cfbb89ecd10a36eef89f10d8aca6a192c201bbe58/PyYAML-6.0-cp37-cp37m-win_amd64.whl
Collecting myjdapi>=1.1.6 (from cyberdrop-dl)
  Using cached https://files.pythonhosted.org/packages/34/a7/52cb048c571f7d1fd673a7b003b4c94af73cf1ab45a28366ad863bfc3ae8/myjdapi-1.1.6-py3-none-any.whl
Collecting yarl>=1.8.1 (from cyberdrop-dl)
  Using cached https://files.pythonhosted.org/packages/d1/4a/294168151f8bb9eb2c9ae0192b01a274f1a98056bfe08b80ce96f39bfb04/yarl-1.8.1-cp37-cp37m-win_amd64.whl
Requirement already satisfied, skipping upgrade: gofile-client>=1.0.1 in c:\robodk\python37\lib\site-packages (from cyberdrop-dl) (1.0.1)
Collecting aiofiles>=22.1.0 (from cyberdrop-dl)
  Using cached https://files.pythonhosted.org/packages/a0/48/d5d1ab7cfe46e573c3694fa1365442a7d7cadc3abb03d8507e58a3755bb2/aiofiles-22.1.0-py3-none-any.whl
Collecting setuptools>=65.5.0 (from cyberdrop-dl)
  Using cached https://files.pythonhosted.org/packages/41/82/7f54bbfe5c247a8c9f78d8d1d7c051847bcb78843c397b866dba335c1e88/setuptools-65.5.0-py3-none-any.whl
Collecting certifi>=2022.9.24 (from cyberdrop-dl)
  Using cached https://files.pythonhosted.org/packages/1d/38/fa96a426e0c0e68aabc68e896584b83ad1eec779265a028e156ce509630e/certifi-2022.9.24-py3-none-any.whl
Collecting tqdm>=4.64.1 (from cyberdrop-dl)
  Using cached https://files.pythonhosted.org/packages/47/bb/849011636c4da2e44f1253cd927cfb20ada4374d8b3a4e425416e84900cc/tqdm-4.64.1-py2.py3-none-any.whl
Collecting aiohttp>=3.8.3 (from cyberdrop-dl)
  Using cached https://files.pythonhosted.org/packages/6a/db/7dd37ac95945fd259b3b6c9ff1a3944129f181a6a1912dcf473df3f505e2/aiohttp-3.8.3-cp37-cp37m-win_amd64.whl
Collecting colorama>=0.4.6 (from cyberdrop-dl)
  Using cached https://files.pythonhosted.org/packages/d1/d6/3965ed04c63042e047cb6a3e6ed1a63a35087b6a609aa3a15ed8ac56c221/colorama-0.4.6-py2.py3-none-any.whl
Requirement already satisfied, skipping upgrade: soupsieve>1.2 in c:\robodk\python37\lib\site-packages (from beautifulsoup4>=4.11.1->cyberdrop-dl) (2.3.2.post1)
Requirement already satisfied, skipping upgrade: requests in c:\robodk\python37\lib\site-packages (from myjdapi>=1.1.6->cyberdrop-dl) (2.27.1)
Collecting pycryptodome (from myjdapi>=1.1.6->cyberdrop-dl)
  Using cached https://files.pythonhosted.org/packages/11/e4/a8e8056a59c39f8c9ddd11d3bc3e1a67493abe746df727e531f66ecede9e/pycryptodome-3.15.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "c:\robodk\python37\lib\site-packages\setuptools\msvc.py", line 489, in _find_latest_available_vc_ver
        return self.find_available_vc_vers()[-1]
    IndexError: list index out of range

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\brawl\AppData\Local\Temp\pip-install-bd0azn_0\pycryptodome\setup.py", line 488, in <module>
        set_compiler_options(package_root, ext_modules)
      File "C:\Users\brawl\AppData\Local\Temp\pip-install-bd0azn_0\pycryptodome\compiler_opt.py", line 341, in set_compiler_options
        clang = compiler_is_clang()
      File "C:\Users\brawl\AppData\Local\Temp\pip-install-bd0azn_0\pycryptodome\compiler_opt.py", line 251, in compiler_is_clang
        return test_compilation(source, msg="clang")
      File "C:\Users\brawl\AppData\Local\Temp\pip-install-bd0azn_0\pycryptodome\compiler_opt.py", line 82, in test_compilation
        objects = compiler.compile([fname], extra_postargs=extra_cc_options)
      File "c:\robodk\python37\lib\distutils\_msvccompiler.py", line 346, in compile
        self.initialize()
      File "c:\robodk\python37\lib\distutils\_msvccompiler.py", line 239, in initialize
        vc_env = _get_vc_env(plat_spec)
      File "c:\robodk\python37\lib\site-packages\setuptools\msvc.py", line 185, in msvc14_get_vc_env
        return EnvironmentInfo(plat_spec, vc_min_ver=14.0).return_env()
      File "c:\robodk\python37\lib\site-packages\setuptools\msvc.py", line 843, in __init__
        self.si = SystemInfo(self.ri, vc_ver)
      File "c:\robodk\python37\lib\site-packages\setuptools\msvc.py", line 485, in __init__
        self.vc_ver = vc_ver or self._find_latest_available_vc_ver()
      File "c:\robodk\python37\lib\site-packages\setuptools\msvc.py", line 492, in _find_latest_available_vc_ver
        raise distutils.errors.DistutilsPlatformError(err)
    distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/
    Testing support for clang

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\brawl\AppData\Local\Temp\pip-install-bd0azn_0\pycryptodome\
You are using pip version 19.0.3, however version 22.3 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

**Comment by axel845845** [comment]
I'm trying to do it from the directory where I have installed cyberdropdownloader but I can't change the directory

**Comment by axel845845** [comment]
Maybe it is a bug in windows 11, I have an update, I will install it and try again.

**Comment by axel845845** [comment]
If it was a cmd or windows error, I did it with Windows PowerShell and it worked.

**Comment by axel845845** [comment]
> I need more information than that

It worked correctly, thanks for your help.

**Comment by Jules-WinnfieldX** [comment]
No worries
