### ISSUE TITLE
PermissionError: [Errno 13]

### ISSUE THREAD

**Issue by Jonnya125** [Jules-WinnfieldX/CyberDropDownloader#254]
Don't really understand what's happening, it just says 
PermissionError: [Errno 13] Permission denied: 'C:\\Windows\\System32\\downloader.log'
and I'm assuming it needs some kind of permission to start downloading stuff but idk how to give it said permission

![image](https://user-images.githubusercontent.com/117235009/199397495-63549b31-9ffc-4dce-95bc-8531b271200f.png)

**Setup Information**
 Windows 10
 Cyberdrop Downloader Version 3

**Comment by Jules-WinnfieldX** [comment]
You are running command prompt or the start script as admin, don't run it as admin. You are trying to write to a windows protected folder (system32) because of it
