### ISSUE TITLE
[FEATURE] Adding Package name for Jdownloader

### ISSUE THREAD

**Issue by minicoz** [Jules-WinnfieldX/CyberDropDownloader#256]
Hey Jules, I cant push a branch for some reason but I figured out how to send packagenames to jdownloader

```
        if self.jdownloader_enable:
            if not self.jdownloader_agent:
                await self.jdownloader_setup()
            try:
                if "facebook" in url_to_map.host.lower() or "instagram" in url_to_map.host.lower():
                    raise Exception("Blacklisted META")
                await log("Sending " + str(url_to_map) + " to JDownloader")
                self.jdownloader_agent.linkgrabber.add_links([{
                    "autostart": False,
                    "links": str(url_to_map),
                    "packageName": title,
                    "overwritePackagizerRules": True
                    }])
            except Exception as e:
                logging.debug(e)
                await log("Failed to send " + str(url_to_map) + " to JDownloader")
```

Now you can just add all the links to URL.txt and it will automatically send and package the similar model names to jdownloader so that they aren't split by link. Just a life improvement to use it since simpcity usually groups links together by model.

Now I can add how ever many model links to `URLS.txt` and it will group them correctly to jdownloder

**Comment by iDevLA** [comment]
how do you even use cyber to use  jdownloader? can you show an example of your config and the command you use in terminal to send external links to it?

**Comment by Jules-WinnfieldX** [comment]
The commands/config toggles are explained in the readme. You need all of the jdownloader commands.

**Comment by Jules-WinnfieldX** [comment]
Added
