### ISSUE TITLE
cmd turns off after few seconds after start 

### ISSUE THREAD

**Issue by Tashotakoe** [Jules-WinnfieldX/CyberDropDownloader#26]
So I start downloading, cmd appears and it seems like it will start downloading now, but it just closes and nothing happens after that. Win 10, idk what's wrong

**Comment by Jules-WinnfieldX** [comment]
https://github.com/Jules-WinnfieldX/CyberDropDownloader/archive/refs/heads/Cyberdrop-Pause.zip
Can you run this and give me a screenshot of the output?

**Comment by Tashotakoe** [comment]
![da](https://user-images.githubusercontent.com/88203533/127703834-e8b70ddf-32fb-412d-a9e9-5b6b254ec831.png)
Yep, here

**Comment by Jules-WinnfieldX** [comment]
can you open a command prompt and try running the command

pip install wheel

then try running the program again.

**Comment by Tashotakoe** [comment]
![ha](https://user-images.githubusercontent.com/88203533/127725790-719c33cc-1512-42c6-ac40-c41aabc51dd7.png)
Done, here's the new result, seems like i've got less errors but it still don't downloading anything

**Comment by Jules-WinnfieldX** [comment]
https://github.com/Jules-WinnfieldX/CyberDropDownloader/archive/refs/heads/Cyberdrop-Pause.zip
Try this, just changed one of the requirements.

**Comment by Tashotakoe** [comment]
Oh, now everything works for sure without errors. Thank you very much for your quick and efficient help, keep it up and good luck mate <З
![15176987](https://user-images.githubusercontent.com/88203533/127740466-ca520cc5-c8e7-41a7-9a56-f0e26211df66.jpg)

**Comment by Jules-WinnfieldX** [comment]
Glad everything works, enjoy.
