### ISSUE TITLE
[BUG] Stuck on "Starting scrape..."

### ISSUE THREAD

**Issue by Kekerin0** [Jules-WinnfieldX/CyberDropDownloader#261]
I start Windows.bat with a URL loaded in URLs.txt and it stops at "Starting scrape". I haven't used cyberdrop-dl on this computer before, but I think I did the same thing as on my computer where it worked.

 - OS: Windows 10 x64

[downloader.log](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/9999575/downloader.log)

Update: I tried another URL and it did the same thing.

**Comment by Jules-WinnfieldX** [comment]
Coomer and Kemono both take a long time to scrape, you need to give them some time.

**Comment by Kekerin0** [comment]
"a long time"

Like, more than an hour? It at least started the download before and created the relevant folder within that time (on my other computer).

**Comment by Jules-WinnfieldX** [comment]
I'll look into this more. It'll take me a minute though.

**Comment by evildemonx** [comment]
@Jules-WinnfieldX 
I personally experience this when scraping from coomer, no issue when scraping from simpcity

**Comment by Jules-WinnfieldX** [comment]
I'm adding which post the scrape is working out as an output to give a better idea for users if it's stuck or not.

**Comment by Jules-WinnfieldX** [comment]
Through my testing, it seems to work, it's just slow as I said. Additional logging information as specified in my last message should help identify if it's stuck or not.
