### ISSUE TITLE
[BUG]ERROR: Could not build wheels for yarl, multidict, which is required to install pyproject.toml-based projects

### ISSUE THREAD

**Issue by naruto3217** [Jules-WinnfieldX/CyberDropDownloader#262]
i have installed the latest Python and this happens
'cyberdrop-dl' is not recognized as an internal or external command,
operable program or batch file.
I don;t know what im doing wrong

**Comment by Jules-WinnfieldX** [comment]
multidict and hence yarl, need to be updated to support 3.11, I have to wait for them. As Umbra said, you need to downgrade to 3.10 or install the C++ build tools.

**Comment by Jules-WinnfieldX** [comment]
I didn't overly answer the question posed. 

Cyberdrop-dl is not a recognized internal command
This is most often caused by python not being included on path. Make sure you ticked the box for 'add python to path' during installation. (see readme)
If that didn't work, follow what another user did:

    I don't know if this will help anyone having my issue, but after 2 reinstalls of python with path selected I was still receiving cyberdrop-dl not recognized error. So I ran python -m pip list -v , in cmd to see where cyperdrop was like was mentioned a few pages back. Then I went to AppData\Roaming\Python\Python310\site-packages and I removed the 2 cyperdrop folders that were in there. I then opened cmd and ran pip3 install cyberdrop-dl. Now the scraper works for me.
