### ISSUE TITLE
[BUG] pixl.is is now pixl.li

### ISSUE THREAD

**Issue by lllllll-llll-llllll** [Jules-WinnfieldX/CyberDropDownloader#263]
maybe not a bug but **Pixl.is** urls changed to **Pixl.li** and so you cannot download from the new website yet

>2022-11-17 12:46:48,421:DEBUG:base_functions:base_functions.py:59:We are running version 3.5.26 of Cyberdrop Downloader
>...
>2022-11-17 12:46:48,601:DEBUG:base_functions:base_functions.py:59:Starting Scrape
>2022-11-17 12:46:48,602:DEBUG:base_functions:base_functions.py:59:https://pixl.li/album/XXXXXXX is not supported currently.
>2022-11-17 12:46:48,604:ERROR:main:main.py:119:ValueError No links
>2022-11-17 12:46:48,604:DEBUG:base_functions:base_functions.py:59:No links found duing scraping, check passwords or that the urls are accessible
>2022-11-17 12:46:48,604:DEBUG:base_functions:base_functions.py:59:This program does not currently support password protected albums.
>2022-11-17 12:46:48,605:DEBUG:sql_helper:sql_helper.py:120:Successfully closed sqlite database connection

**Comment by Jules-WinnfieldX** [comment]
Should be fixed in 3.5.27
