### ISSUE TITLE
[FEATURE] Any way to include Pixeldrain credentials?

### ISSUE THREAD

**Issue by aaam13** [Jules-WinnfieldX/CyberDropDownloader#266]
**Is your feature request related to a problem? Please describe.**
Base Pixeldrain caps your transfer speeds after downloading a certain amount of data, so I chose to upgrade my account to Pro to remove that limit. It doesn't look like there's any way for me to input my credentials into this downloader though. As it is right now, whenever a thread I'm downloading hits a pixeldrain link everything comes to a halt as it tries to download at ~256kb/s.

**Describe the solution you'd like**
I'd like to be able to use my pixeldrain account through this downloader.

**Comment by Jules-WinnfieldX** [comment]
It's unclear if providing authentication through the API would actually provide any benefit in this case, or if the download links themselves would accept an API key. I don't have a premium account to test anything with myself, and I can't interact with the website itself as it's primarily written in JS.

**Comment by Fornax96** [comment]
Yes, you can provide an API key to the download endpoint with either HTTP Basic auth or a session cookie. When you do this your account's bandwidth limit will be used instead of the IP address based limit. API keys can be generated on this page: https://pixeldrain.com/user/api_keys

**Comment by Jules-WinnfieldX** [comment]
I added this roday

**Comment by aaam13** [comment]
Sorry, not sure what argument I can use to input the API key

**Comment by Jules-WinnfieldX** [comment]
I forgot to actually make it an argument, I just added it to the config. I'll do that today.

**Comment by Jules-WinnfieldX** [comment]
--pixeldrain-api-key
