### ISSUE TITLE
[FEATURE] An API that allows for extension.

### ISSUE THREAD

**Issue by btw-arch** [Jules-WinnfieldX/CyberDropDownloader#267]
Hi, thanks for the work you put into this awesome script.

My use case is that I'd like to run cyberdrop-dl directly on my NAS running UNRAID.

I've put together a docker image serving up a basic web ui through an aiohttp server that lets me start downloads using cyberdrop-dl through the browser. So, I have this working in its basic form already.

Because cyberdrop-dl is designed around CLI my options for extending and improving the web ui at this point would be:
1. Fork and maintain a modified version
2. Hack something together through log output and probably building some kind of additional SQL table to track more information useful for QOL type stuff.

I'd probably go with number 2, even if it is more limited. But I'm curious if you'd be open to adding an alternative run mode which outputs progress information in a way that's easily queried.

Thanks

**Comment by Jules-WinnfieldX** [comment]
I would be open to that, are you asking me to build it, or accept a pull req? For the first I'd need time and to know exactly what you are looking for.

**Comment by Jules-WinnfieldX** [comment]
Also, love what ya got going on.

**Comment by btw-arch** [comment]
I'm open to putting a pull request through (and it'll take me a while to make too!) but I wanted to get your input on the overall design and strategy.

For a v1 of the dashboard, I'd like to have

- A record of scraped `DomainItem`s and their progress. Running, Complete, Complete with Failures, Failed.
- If an `DomainItem` is running, see the overall progress by number of files completed and current download speed.

I'm not very accustomed to reading other people's code, but looking through the source, I think my approach would involve...
- Adding a new table the the sqlite database that records the top level page for downloads and relates it to each download.
- Creating a custom `director` that integrates the `Client`, `Session`, `Downloader` and and `Item` classes into an existing python loop and pulls parameters from the environment instead of argparse. (I would build and maintain this as part of the dashboard implementation).
- Adding a parameter to the `Client` and `DownloadSession` functions that would return progress using a different method than tqdm.

Any thoughts or pointers?

**Comment by Jules-WinnfieldX** [comment]
As long as it doesn't change current functionality, I don't have an issue with it.
