### ISSUE TITLE
[BUG] Anonfiles - error 200 even though download page exists

### ISSUE THREAD

**Issue by gw2alt** [Jules-WinnfieldX/CyberDropDownloader#269]
**Describe the bug**
Anonfiles downloads will eventually reach a point where the server returns an error 200 on retry attempt. 
Manual browsing to download link shows file still exists & can be downloaded manually.

**To Help Reproduce**
Steps to help reproduce the behavior:
1. Populate >1 anonfiles link in URLs.txt
2. Run script

**Screenshots**
None, log is attached 

**Setup Information**
 - OS: Mac OS X High Sierra
 - Cyberdrop Downloader Version # 3.5.28

**Downloader.log file**
[downloader.log](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/10064711/downloader.log)

**Additional context**
1. Initially noticed this issue when URLs.txt was populated with many more links and had way more scrape results. 
In those instances anonfiles links wouldn't even begin a transfer, it went straight to error: `Server for https://cdn-110.anonfiles.com/....filename...mp4 is either down or the file no longer exists`. 
Suspected this 'insta-error' might have something to do with the time lapsed between scrape & actual download initiation but unsure.

1.5. In the downloader.log attached there is 1 link that actually is down, the other 10 are live at time of testing.

2. Same issue (error 200 after a certain number of retries) noticed with gofile links as well, will try to capture this in another log

**Comment by gw2alt** [comment]
Same issue but for gofile - once initial connection gets reset, retries of that file & initial connections for subsequent scraped links all result in error 200 even though file exists

[downloader.log](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/10068965/downloader.log)

**Comment by Jules-WinnfieldX** [comment]
Can you try with 3.5.31 and get me an updated log file?

**Comment by gw2alt** [comment]
[downloader.log](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/10070670/downloader.log)

**Comment by Jules-WinnfieldX** [comment]
Well that's majorly annoying. The download links are kicking back to the main file page after something happens (cookie expires or after it is already used to download one file). Not sure how to deal with this. I'll have to play around with it.

**Comment by Jules-WinnfieldX** [comment]
Are you using a VPN or a proxy?

**Comment by gw2alt** [comment]
no, only args are smg/simp + throttle 2

**Comment by Jules-WinnfieldX** [comment]
I think I have a plan to fix this, but it's an ugly solution. It's all I got though. It'll take me a while to write it when I get a chance.

Essentially, what I think is happening is the temp user we are using to get the downloads/links for these sites is being terminated after too many links or retries, etc, and it's spitting us back to the main link page. 

I already have detection for HTML/Text return (which is what it is doing), and instead of erroring out completely I need to essentially rescrape the offending links, issue is it'll happen one at a time, on a new user (new cookie) that I'll have to swap into the download client.

**Comment by Jules-WinnfieldX** [comment]
This will be fixed in the next release out soon (next hour or two)
