### ISSUE TITLE
[FEATURE] Name Kemono attachments by original file name

### ISSUE THREAD

**Issue by Schnugget** [Jules-WinnfieldX/CyberDropDownloader#270]
Currently Kemono attachments are being saved with the randomly generated file names they are stored as on the Kemono server, rather than the original file names that are provided in the links. Would be awesome if they were saved with the original file names. Thanks!

**Comment by Jules-WinnfieldX** [comment]
Without a large re-write this unfortunately isn't possible. All filenames are parsed out of the URL that they are located at, unfortunately for Kemono these are just gibberish identifiers.

**Comment by Schnugget** [comment]
Ahh, no worries then!

Hmm, though it looks like the original file name is passed as a "?f=" query string in the download URL on the Kemono page (not just in the link text.) Not sure if that helps though if that's stripped as part of creating the download list.

For example: https://kemono.party/data/6e/8e/6e8e2d5bc6aca1ccd922dd30e12141286a857900f001e4f69d3a8a630d3f9ad2.mp3?f=i%20swear%20to%20god%20don%27t%20you%20lewd%20this.mp3

**Comment by Jules-WinnfieldX** [comment]
This should be fixed in the release coming in a few versions.
