### ISSUE TITLE
[BUG] kemono.party user URLs not being properly scraped

### ISSUE THREAD

**Issue by Schnugget** [Jules-WinnfieldX/CyberDropDownloader#271]
kemono.party user URLs seem to not be being scraped properly anymore. As best as I can ascertain it seems that unless there is a preview thumbnail shown for the post it doesn't check for downloads? It seems to work ok if you pass it the individual post link, but of course that's not ideal.

Example 1:

User URL Doesn't Work (nothing returned): https://kemono.party/patreon/user/16388489
Post URL Works: https://kemono.party/patreon/user/16388489/post/74678953

Example 2:

User URL Partially Works (it only downloads the ones with thumbnails): https://kemono.party/gumroad/user/8174974221167
Post URL Works (no thumbnail): https://kemono.party/gumroad/user/8174974221167/post/rKcZh
Post URL Works (thumbnail): https://kemono.party/gumroad/user/8174974221167/post/KYRSmR

Thanks!

**Comment by Jules-WinnfieldX** [comment]
I'll have to work on this.

**Comment by Jules-WinnfieldX** [comment]
This will be fixed in the next release out soon (next hour or two)
