### ISSUE TITLE
help it doesnt work

### ISSUE THREAD

**Issue by LiamD2021** [Jules-WinnfieldX/CyberDropDownloader#272]
okay so i donwloaded [Cyberdrop_DL.V3.zip](https://github.com/Jules-WinnfieldX/CyberDropDownloader/releases/download/Release/Cyberdrop_DL.V3.zip) and when i run start windows it says all this :

C:\Users\Owner\Downloads\Cyberdrop_DL.V3>pip install --upgrade cyberdrop-dl
Requirement already satisfied: cyberdrop-dl in c:\users\owner\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (3.6.5)
Requirement already satisfied: PyYAML>=6.0 in c:\users\owner\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from cyberdrop-dl) (6.0)
Requirement already satisfied: gofile-client>=1.0.1 in c:\users\owner\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from cyberdrop-dl) (1.0.1)
Requirement already satisfied: beautifulsoup4>=4.11.1 in c:\users\owner\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from cyberdrop-dl) (4.11.1)
Requirement already satisfied: aiohttp>=3.8.3 in c:\users\owner\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from cyberdrop-dl) (3.8.3)
Requirement already satisfied: myjdapi>=1.1.6 in c:\users\owner\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from cyberdrop-dl) (1.1.6)
Requirement already satisfied: yarl>=1.8.1 in c:\users\owner\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from cyberdrop-dl) (1.8.1)
Requirement already satisfied: setuptools>=65.5.0 in c:\users\owner\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from cyberdrop-dl) (65.6.3)
Requirement already satisfied: aiofiles>=22.1.0 in c:\users\owner\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from cyberdrop-dl) (22.1.0)
Requirement already satisfied: tqdm>=4.64.1 in c:\users\owner\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from cyberdrop-dl) (4.64.1)
Requirement already satisfied: certifi>=2022.9.24 in c:\users\owner\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from cyberdrop-dl) (2022.9.24)
Requirement already satisfied: colorama>=0.4.6 in c:\users\owner\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from cyberdrop-dl) (0.4.6)
Requirement already satisfied: charset-normalizer<3.0,>=2.0 in c:\users\owner\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from aiohttp>=3.8.3->cyberdrop-dl) (2.1.1)
Requirement already satisfied: attrs>=17.3.0 in c:\users\owner\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from aiohttp>=3.8.3->cyberdrop-dl) (22.1.0)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\users\owner\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from aiohttp>=3.8.3->cyberdrop-dl) (6.0.2)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in c:\users\owner\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from aiohttp>=3.8.3->cyberdrop-dl) (4.0.2)
Requirement already satisfied: aiosignal>=1.1.2 in c:\users\owner\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from aiohttp>=3.8.3->cyberdrop-dl) (1.3.1)
Requirement already satisfied: frozenlist>=1.1.1 in c:\users\owner\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from aiohttp>=3.8.3->cyberdrop-dl) (1.3.3)
Requirement already satisfied: soupsieve>1.2 in c:\users\owner\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from beautifulsoup4>=4.11.1->cyberdrop-dl) (2.3.2.post1)
Requirement already satisfied: requests in c:\users\owner\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from gofile-client>=1.0.1->cyberdrop-dl) (2.28.1)
Requirement already satisfied: pycryptodome in c:\users\owner\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from myjdapi>=1.1.6->cyberdrop-dl) (3.15.0)
Requirement already satisfied: idna>=2.0 in c:\users\owner\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from yarl>=1.8.1->cyberdrop-dl) (3.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\owner\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from requests->gofile-client>=1.0.1->cyberdrop-dl) (1.26.13)

C:\Users\Owner\Downloads\Cyberdrop_DL.V3>cyberdrop_dl
'cyberdrop_dl' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\Owner\Downloads\Cyberdrop_DL.V3>pause
Press any key to continue . . .

Then when i press any key it closes

**Comment by Jules-WinnfieldX** [comment]
This is most often caused by python not being included on path. Make sure you ticked the box for 'add python to path' during installation. (see readme)
If that didn't work, follow what another user did:

    I don't know if this will help anyone having my issue, but after 2 reinstalls of python with path selected I was still receiving cyberdrop-dl not recognized error. So I ran python -m pip list -v , in cmd to see where cyperdrop was like was mentioned a few pages back. Then I went to AppData\Roaming\Python\Python310\site-packages and I removed the 2 cyperdrop folders that were in there. I then opened cmd and ran pip3 install cyberdrop-dl. Now the scraper works for me.
