### ISSUE TITLE
[BUG] Error at scraping but link found

### ISSUE THREAD

**Issue by forsainer** [Jules-WinnfieldX/CyberDropDownloader#273]
**Describe the bug**
Yesterday was fine until today every link I input to URLs isn't scraped

**Screenshots**
![image](https://user-images.githubusercontent.com/119073058/204038134-6856e7cf-dc42-457a-bd30-eb4b2cbca4d1.png)

**Setup Information**
 - OS: Windows 11 22H2
 - Cyberdrop Downloader Version: 3.6.7

**Downloader.log file**
 [downloader.log](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/10094590/downloader.log)

**Comment by Jules-WinnfieldX** [comment]
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'www.erome.com'. (_ssl.c:997)

You are experiencing issues with the website itself, or rather the certificate they used to sign it. It's not a bug with the downloader.
