### ISSUE TITLE
[FEATURE] Could each individual file have its own date?

### ISSUE THREAD

**Issue by Kekerin0** [Jules-WinnfieldX/CyberDropDownloader#275]
**Is your feature request related to a problem? Please describe.**
I'd just like to see from when a picture came without relying on the online archive still existing (coomer.party in this case) The --include-id option seems to not work for coomer.party either, or I would have used that to get an indication of chronology. Right now, I am kind of blind, I have a bunch of folders for posts with no ID or date on them. (I'm assuming the post ID would tell me if a certain post was made before or after another post.)

**Describe the solution you'd like**
An argument that could be added to the windows batch file would be ideal. A simple --includes-dates option would be great.

**Comment by Jules-WinnfieldX** [comment]
Each individual file won't. In 3.6.17 (out later today) --include-id will work for coomer and kemono, as long as --separate-posts is true (or specified).

**Comment by Kekerin0** [comment]
That works. If I run 3.6.17 while already having a bunch of folders downloaded with no IDs on them, will it know to rename the folders to have IDs based on this option or will it try to re-download everything?

**Comment by Jules-WinnfieldX** [comment]
Neither. It’ll only redownload things if you delete the download history, and it won’t rename anything from previous downloads

**Comment by Kekerin0** [comment]
If I want to tell the program to redownload only posts from certain creators (instead of deleting the entire download_history.sqlite file) how would I do that?

**Comment by Jules-WinnfieldX** [comment]
Put those links in the urls.txt file, then use the --ignore-history flag or option in the config.

**Comment by Kekerin0** [comment]
I thought --ignore-history would ignore all the history. Can I do "--ignore-history [URL]"?

**Comment by Jules-WinnfieldX** [comment]
No, it doesn't accept urls as an argument. As I said, just have the urls you want to ignore history for in the urls.txt file.

**Comment by Kekerin0** [comment]
Oh I think I see what you mean, thanks.
