### ISSUE TITLE
[FEATURE] Pause/don't run if drive is low on space

### ISSUE THREAD

**Issue by n30liberal** [Jules-WinnfieldX/CyberDropDownloader#279]
Would be amazing if I could tell the script how much drive space I need at minimum to run.
i.e. don't run if the drive only has 100gb left etc

**Comment by Jules-WinnfieldX** [comment]
I like this, and will add it soon.

**Comment by github-userx** [comment]
Yeah I regularly run into the script stopping cause database also can’t be written anymore cause 0Byte left on hard Drive :D

**Comment by Jules-WinnfieldX** [comment]
This is included in 3.6.43. I added a new argument (required-free-space), it defaults to 5gb.
