### ISSUE TITLE
502 Bad Gateway and 'content-length' Exception

### ISSUE THREAD

**Issue by Ixaruz** [Jules-WinnfieldX/CyberDropDownloader#28]
## 502 Bad Gateway
I often get files with the data as shown below
I guess this is CyberDrop's issue? but still, I'd wish it could be handled better by the Downloader when issues like this occure :)

```html
<!-- randomvideofromalbum.mp4 -->
<html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

I assume you can check the request.get response header 'Content-Type'; it always is 'text/html' when there is a html error and then inform the user that the file is "temporarily unavailable".

## 'content-length'
```
'content-length' 
[WinError 2] The system cannot find the file specified. './Downloads/album/pathtofile' 
Failed to Download
```
I just assume the WinError happens bc the file can't be created due to the exception(s).

OS: Windows 10
Python: 3.7.4

**Comment by Jules-WinnfieldX** [comment]
I'll look into this, I appreciate the well formed issue. I'm not sure if the recently approved pull request will help with this or not, but I should check more diligently for status from the links.

**Comment by Ixaruz** [comment]
I checked the pull and think it could help with the content-length exception I got.

Since the 502 Bad Gateway Error is not reproduceable, unless cyberdrop decides to have that issue again, we should be good.

**Comment by Jules-WinnfieldX** [comment]
Sounds good, if you want me to take another look at this, please reopen the issue in the future.
