### ISSUE TITLE
[FEATURE] Per URL directory definition

### ISSUE THREAD

**Issue by humaintenance** [Jules-WinnfieldX/CyberDropDownloader#281]
This program has been an amazing help, so firstly thank you!

I would like to be able to define the output directory of each and/or some of the URLs in the URLs.txt. 

For example in the URLs.txt do something like the following examples:
`https://bunkr.ru/a/IDofTheAlbum -o "/path/to/desired/directory"`
`https://bunkr.ru/a/IDofTheAlbum,"/path/to/desired/directory"`
`https://bunkr.ru/a/IDofTheAlbum "/path/to/desired/directory"`

Reason for this is I tend to build up a long list of URLs I want and then download them all at once. This can lead to a bunch of folders being created with names that aren't that indicative of what the contents is, as some albums sometimes aren't given titles that relate to the contents. This makes copying the files to where I actually want them a bit of a pain.

Ideally I'd like to download the files directly to where I want them, or at least be able to define the output folder name per URL in the txt file.

**Comment by Jules-WinnfieldX** [comment]
This unfortunately conflicts with how URLs are grabbed from the URLs.txt file (using regrex with the ability to grab links out of html code, etc). I'd suggest you alter a copy of the start script, you can specify any number of options for each run, with different output locations for said runs. Not a perfect solution, but it's the only one viable in this instance really.
