### ISSUE TITLE
FAILS (total freeze of script) on VPN connection

### ISSUE THREAD

**Issue by Ace-Cook** [Jules-WinnfieldX/CyberDropDownloader#282]
Been using CDD for a couple of years, through MANY updates, without incident. It is AWESOME!

Recently, it has absolutely unequivocally STOPPED WORKING OVER ANY OF MY VPN CONNECTIONS -- literally hundreds of possible VPN servers.  As soon as I turn the VPN (and kill switch) OFF, the script works normally.  It's driving me crazy, because this is exactly the kind of app I want riding over a VPN, not being logged by my ISP.

Screenshots would be redundant -- the ONLY thing visible in the Command shell is the command line (x:\CyberDropDownloader-master>cyberdrop-dl), whereupon the script freezes with no status/error messages or further activity -- just an empty black/blue window below the stalled command line.  Again, upon opening an unsecured connection, the script IMMEDIATELY runs normally. The issue is infinitely repeatable with no other variables in play.

Any ideas?  Thanks in advance for any help you can offer.

----------------------------------------------------------------
**Setup Information**
 - OS:  Windows 10 Home 21H2
 - Cyberdrop Downloader Version # 3.6.38

**Downloader.log file** [entire contents in quotes below]
"2022-12-12 13:15:11,142:DEBUG:proactor_events:proactor_events.py:629:Using proactor: IocpProactor"
[downloader - Copy.log](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/10210914/downloader.-.Copy.log)

**Comment by Jules-WinnfieldX** [comment]
Uhhhh. Interesting. What VPN are you using? It is working perfectly fine with my VPN. The only thing I can really think of is the VPN software you are using is blocking code execution locally somehow, or it's highjacked the running loop that CDD runs on.

**Comment by Ace-Cook** [comment]
WOW, thanks for the quick reply!

I'm currently using [VPN Unlimited ](https://www.vpnunlimited.com/) (KeepSolid Inc). Works with every major news, financial, e-commerce, streaming site in my toolbox -- and with every connected (non-browser) app except those that depend on local IP traffic (ex: cloud monitoring of UPS connected to PC, local WiFi connected printers, etc) because their tunneling feature isn't available on the Windows VPN app yet.  Thoughts?

**Comment by Jules-WinnfieldX** [comment]
So. A few thoughts, CDD doesn't rely on any local traffic, so that's not it. But also, out of curiosity for the issue I bought a month of it, and I can't recreate the issue. Are you using the monodefense?

**Comment by Ace-Cook** [comment]
Thanks again for the fast follow-thru (btw, your app is supernatural -- I can't fathom how much time it's saved me until this recent bump in the road).  

And, nope ... none of their other services, just VPN with the built-in Kill Switch (turning off the Kill Switch doesn't free up the CDD script).

**Comment by Jules-WinnfieldX** [comment]
I'm honestly a bit at a loss here. The log shows that it pauses essentially before anything happens, no requests are even being made. It should get further than that regardless of even having an internet connection. I'd suggest doing default troubleshooting steps like restarting the PC, etc. Make sure you don't run either as admin. Beyond that not sure I can be much more help.

**Comment by Ace-Cook** [comment]
Hmmm -- so you WERE able to duplicate the script freezing before anything happens over VPN Unlimited? 

"It should get further than that regardless of even having an internet connection."
That's the thing -- the minute I unload the VPN (not "turn off" -- actually kill the process) and re-run the script, it works normally. The minute I open the app again (even without connecting to a VPN server, CDD is dead in the water. Have you ever seen this behavior with OTHER apps or services?

FYI, I've done all the "normal" troubleshooting. Uninstalled/reinstalled all the suspects. Shut down all browsers. Virus scans. The works.

**Comment by Jules-WinnfieldX** [comment]
Sorry, I should have clarified better. I haven’t been able to replicate it. But no, I also haven’t seen this happen with other programs really. This is a first for me

**Comment by Jules-WinnfieldX** [comment]
Ohhhh. If you are running the program off the NAS itself that could be the issue itself. Network shares on windows for me break occasionally when connected to some VPNs. What happens if you try to run it entirely locally, not downloading to the NAS/not running off the NAS if you are

**Comment by Ace-Cook** [comment]
LOL .. thanks for hanging in there, but no -- I don't run any apps on the NAS -- it's really a pooled array of 20 mirrored NTFS drives spread over 5 external enclosures (no separate NAS OS, just a PC app that manages the array from within Windows) with all of my download content going to a single Windows drive letter / folder. So, from CDD's perspective (and, in fact), it IS all local storage, it's just not internal.  This exact same configuration has worked from Day 1 when I first found CDD -- and still works when I remove the VPN from memory.  Love ya for being so committed to solving this puzzle though.

**Comment by Jules-WinnfieldX** [comment]
Did ya get it working?

**Comment by github-userx** [comment]
Definitely seems like a local computer/vpn app/firewall issue than an issue with the app itself. For example I switched vpn providers cause ProtonVPN messed up my system with how their app and killswitch is implemented & installed on Linux.
