### ISSUE TITLE
[FEATURE] Sanitize forum thread names

### ISSUE THREAD

**Issue by tarchive** [Jules-WinnfieldX/CyberDropDownloader#283]
When downloading a thread it will create a folder in Downloads with the thread name. 90% of the time it's okay but occasionally some idiot will use forbidden characters which will cause some utilities on Windows and even some on Linux to not work.

An example of this is recently i downloaded a thread from SMG that had a newline '\n' in the thread title. 

I understand if this is out of scope for your downloader, but it would be nice if it would sanitize the thread names to remove any forbidden character from any folders and/or files.

**Comment by Jules-WinnfieldX** [comment]
This is supposed to happen, seems it's not stripping '\' properly. I'll try and fix this soon.

https://github.com/Jules-WinnfieldX/CyberDropDownloader/blob/57c5cd1bb8ae8f392a19f33f58d445e8b94f3293/cyberdrop_dl/base_functions/base_functions.py#L70

**Comment by tarchive** [comment]
I just noticed when i `cat` the trouble folder there is a $ before the '\n'. Not sure if that is expected here. 
Here is the output with just the name changed.
`cat: 'Downloads/Some Thread Name'$'\n''https---ofs-com-some-thread-name': Is a directory`

If you need the exact link for testing let me know and I'll pm you on one of our mutual forums.

**Comment by Jules-WinnfieldX** [comment]
The exact link would help for sure, sounds like something is going wrong in something I'm doing.

**Comment by Jules-WinnfieldX** [comment]
Fixed
