### ISSUE TITLE
[BUG] Script doesn't download links that have been already downloaded

### ISSUE THREAD

**Issue by cybermanxx** [Jules-WinnfieldX/CyberDropDownloader#285]
**Describe the bug**
I had 3 bunkr links that i downloaded while one of their servers was down for maintenance. Every mp4 that i downloaded was 5 seconds long, with the same error message from bunkr. So today, after i checked that the specific server was back online, i ran the script one more time with the links I wanted to download.
However, instead of downloading any file, the script runs smoothly, says that every file has been downloaded, "pirging empty directories", "finished donwloading" and "There are partial downloads in the downloads folder"; but there isn't a folder in Downloads.
I deleted the old folders, so that they wouldn't interfere with the script running again, but it seems that broke the script.

**To Help Reproduce**
Download an album (bunkr, but it could maybe work with other websites), delete it completely from the disk, then re-run the script with the same link

**Screenshots**
Script screenshot
![immagine](https://user-images.githubusercontent.com/93735466/208768232-c8874429-cf2b-4cdc-bfc2-99d7962340ef.png) 

**Setup Information**
OS: Win 10 v. 1909
Cyberdrop latest version as of 20/12 (cant find the number)

**Downloader.log file**
[downloader.log](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/10272724/downloader.log)

PS I can add if you want a screenshot of my downloads folder; i didn't want to add it because i dont know if i should cover the names.

**Comment by Jules-WinnfieldX** [comment]
This isn't a bug, it's intended behaviour. To get around it you can delete the download_history file, or use the flag --ignore-history

This is there on purpose so it's not continuously re downloading files from things you've already downloaded, which becomes very important for forum scraping.
