### ISSUE TITLE
[BUG] write_last_post_file overwritten

### ISSUE THREAD

**Issue by LLBlanc** [Jules-WinnfieldX/CyberDropDownloader#287]
Even though the function opens the last post txt in append mode, it seems to only log out the last post URL of the last URL it has scraped
To be clear this only happens if I run cyberdrop-dl separately, since I have a lot of different URLs with different output folders

Steps to help reproduce the behavior:
1. Run cyberdrop-dl on URL X-1 to output folder X-2
2. After that finishes, run cyberdrop-dl on URL Y-1 to output folder Y-2
3. Open last post txt to find only the last post URL for Y-1, the last one

Behavior persists if the individual runs are done on the same CMD window or different one
Parent folder same for output folders X-2 and Y-2

Function would execute correctly if I just chain URLs back to back on the same cyberdrop-dl run, but that's not possible as I intend different scrapes to go to different output folders

**Setup Information**
 - OS: Windows 11 Home
 - cyberdrop-dl 3.6.42.

[downloader.log](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/10283191/downloader.log)

**Comment by Jules-WinnfieldX** [comment]
This is intended behaviour. For the most part. I've stayed true to not creating bloating file counts. Have a set number of files + the users downloads. 

Given what you are doing, I'd recommend creating a batch file that runs your various iterations (X-1, Y-1, etc) and after each run you could get the batch file to automatically rename the last output file. Unfortunately that's about all I can offer
