### ISSUE TITLE
[BUG] Erome links not working

### ISSUE THREAD

**Issue by patelharsh9797** [Jules-WinnfieldX/CyberDropDownloader#290]
**Describe the bug**
No links found during scraping, check passwords or that the urls are accessible
This program does not currently support password protected albums.
But the link are not protected at all.

**Comment by Jules-WinnfieldX** [comment]
As the bug template describes, I need the downloader.log to be able to try and diagnose.

**Comment by patelharsh9797** [comment]
Here is the log file as you required.
Hope that will help fix the problem.

Thnx :)
[downloader.log](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/10349367/downloader.log)

**Comment by Jules-WinnfieldX** [comment]
Do you have any antivirus software?

**Comment by patelharsh9797** [comment]
> Do you have any antivirus software?
not exactly. Just a windows defender!

**Comment by Jules-WinnfieldX** [comment]
Can you normally connect to erome?

**Comment by patelharsh9797** [comment]
no. i had to use vpn for that. 
using "Windscribe" chrome extension.

but i'm getting this error recently. i used erome links in my terminal without vpn before like a month ago and it was working at that time tho.

**Comment by Jules-WinnfieldX** [comment]
If you can't connect to it normally, the program won't be able to either.

**Comment by patelharsh9797** [comment]
I tried with desktop vpn aswell.
With vpn i can access the site but the scrapper is not working.

**Comment by Jules-WinnfieldX** [comment]
VPN's and code execution often times don't play well together. As an example some VPN's aren't system wide, even as desktop apps, and will only apply to some types of traffic or applications such as browsers.

**Comment by patelharsh9797** [comment]
So what should i do to make it work? 
Any better way or any vpn that you will recommend!! xD

**Comment by Jules-WinnfieldX** [comment]
You could try using a proxy, which cyberdrop-dl has support for. I don't have instructions other than that given in the readme. If you want a vpn suggestion. Use Mullvad. Though I can't guarantee it'll fix your problem.

**Comment by patelharsh9797** [comment]
I tried with proxy settings in both within terminal and also from global compter proxy.
In global settings i can access the erome site. but when i tried to scrap it with terminal its not working.

I have attached the screenshot and the log file this time.
if that can help.

![Screenshot (39)](https://user-images.githubusercontent.com/105432105/210935936-249459c6-dbc5-414a-865a-8439ecfed984.png)
[downloader.log](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/10357518/downloader.log)

**Comment by Jules-WinnfieldX** [comment]
It's been the same error in the log for every log which is:

`OSError: [WinError 64] The specified network name is no longer available`

There isn't really anything else here I can suggest or do.

**Comment by patelharsh9797** [comment]
Should i try in different pc?

**Comment by Jules-WinnfieldX** [comment]
You could, but I can't say it'd help. But anything is worth a shot.

**Comment by patelharsh9797** [comment]
tried to fix the error : `OSError: [WinError 64] The specified network name is no longer available`
but now i'm getting this xD :
`asyncio.exceptions.CancelledError`

**Comment by Jules-WinnfieldX** [comment]
Which is essentially a more non-descript error of the same problem. The program can't connect to erome, and the connection is being closed/cancelled.
