### ISSUE TITLE
Can't implement this into my script

### ISSUE THREAD

**Issue by frankfrot30** [Jules-WinnfieldX/CyberDropDownloader#292]
Hi.
I've been trying to implement this into a little script I made with batch file language but for some reason it doesn't detect the login part.

I upload the code in the rar
[DESCARGADOR Y CREADOR DE ENTRADAS.zip](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/10348824/DESCARGADOR.Y.CREADOR.DE.ENTRADAS.zip)

**Comment by Jules-WinnfieldX** [comment]
In the future, you may want to remove your actual password from things you upload onto the internet. Give me the downloader.log file after you try running it.

**Comment by frankfrot30** [comment]
It was my bad, already edited it

Here you have the downloader.log
[downloader.log](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/10348829/downloader.log)

**Comment by frankfrot30** [comment]
Also for some reason, every time I ran the code if I don't put the corrector part it deletes the empty folders

**Comment by Jules-WinnfieldX** [comment]
> It was my bad, already edited it
> 
> Here you have the downloader.log [downloader.log](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/10348829/downloader.log)

You have things backwards, and you're passing socialmediagirls credentials for simpcity and vice versa. Change your script to compensate. 

And by default, the program deletes empty folders upon completion.
