### ISSUE TITLE
Free space requirement

### ISSUE THREAD

**Issue by megabytemaestro** [Jules-WinnfieldX/CyberDropDownloader#293]
Hi,
I've been using your program for some time and have noticed sometime in the past few days you have introduced a new 'free space requirement' feature.

First off, I can acknowledge the potential usefulness of this feature when scraping large folders with 100s/1000s of files, so this isn't a complaint as such.

However, in my case I can't help but find that receiving the message 'Not enough free space to run the program' as I try to scrape an album with 9 images and a 1m13s video in 360p to be a bit funny, as I frequently download to storage devices with little space, and on occasion MicroSD with only a fraction of the required 5GB.

In my attempts to solve the problem, I managed to locate cyberdrop-dl.exe in python's scripts folder and threw together a quick .bat file of 
`cyberdrop-dl [--required-free-space 1] [-i URLS.txt]` 
to no success. I also tried with the variants "1", 1GB and 1 GB with no luck despite having 4GB of free space.

For a Windows user with extremely limited technical knowledge is there a simple workaround to address this inconvenience?
Is there a way to insert Arguments directly inside the Start Windows.bat file to override the free space requirement or even ignore it entirely? 
If so, how would I go about setting the required space to say, for example 500MB or 1GB, or if not what other ways might I achieve this result?

Hope you can help.
Oh, and thank you for creating such a useful program!

**Comment by Jules-WinnfieldX** [comment]
Try without the [ ]'s

But it'll just be a numerical 1 for 1gb. .5 should work as 500mb

**Comment by megabytemaestro** [comment]
Thanks
The .bat worked perfectly with 1 but `cyberdrop-dl --required-free-space .5 -i URLS.txt` produces this error
`cyberdrop-dl: error: argument --required-free-space: invalid int value: '.5'`
Trying with 0.5 also produced the same error

**Comment by Jules-WinnfieldX** [comment]
Well, I guess I was wrong. Seems decimals won't work. You'll have to pick a whole number (0, 1, etc).

**Comment by megabytemaestro** [comment]
Ah I see. Using 0 will ignore the requirement entirely.
Thanks for your help.
