### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by RazFox** [Jules-WinnfieldX/CyberDropDownloader#294]
**Describe the bug**
Good afternoon! 
I downloaded the latest version, 15-20 minutes ago, and an error occurs at startup. 
```
Traceback:
"D:\Soft\start.py" 
Traceback (most recent call last):   
 File "D:\Soft\start.py", line 1, in <module>     
from cyberdrop_dl.main import main as main_dl
 File "D:\Soft\CyberDropDownloader-master\cyberdrop_dl\main.py", line 13, in <module>     
from cyberdrop_dl.scraper.scraper_helper import ScrapeMapper   
 File "D:\Soft\CyberDropDownloader-master\cyberdrop_dl\scraper\scraper_helper.py", line 9, in <module>     
from ..client.client import Client   
 File "D:\Soft\CyberDropDownloader-master\cyberdrop_dl\client\client.py", line 17, in <module>     
from .rate_limiting import AsyncRateLimiter, throttle   
 File "D:\Soft\CyberDropDownloader-master\cyberdrop_dl\client\rate_limiting.py", line 9, in <module>     
from ..base_functions.base_functions import logger   
 File "D:\Soft\CyberDropDownloader-master\cyberdrop_dl\base_functions\base_functions.py", line 9, in <module>     
import psutil as psutil ModuleNotFoundError: No module named 'psutil'
```

**Comment by Jules-WinnfieldX** [comment]
Hey, don't run the code itself, use one of the two installation methods in the readme.

The easier one is to just download https://github.com/Jules-WinnfieldX/CyberDropDownloader/releases/download/Release/Cyberdrop_DL.V3.zip
Then run the script for windows.

**Comment by RazFox** [comment]
I'm sorry. I've been trying to figure out why the download fails, and I seem to be confused about the files. For some reason I can't download from cyberdrop. Most often, the download just hangs for some time at 0%, without downloading anything, and then the script crashes (the console window collapses), and sometimes it also deletes the Downloads directory.
Link example https://cyberdrop.me/a/FqcfSPqc

**Comment by Jules-WinnfieldX** [comment]
I'd need to see the downloader.log file after you try. But it closes automatically likely because you aren't using one of two actual install methods. You shouldn't be running any .py files. 

Cyberdrop though, it's a fun one where most of their servers don't work and all their certificates are expired so there is no way to create a secure connection. Hence nothing gets downloaded.

**Comment by Jules-WinnfieldX** [comment]
Based on the log, you were getting "Error 521: Web server is down" errors. Meaning cyberdrop was having server issues (per usual for them)

**Comment by RazFox** [comment]
> Based on the log, you were getting "Error 521: Web server is down" errors. Meaning cyberdrop was having server issues (per usual for them)

Thank you! Understood. Is there a list of all the errors that the script throws with notes somewhere?) I did not immediately understand the log file. Now I see error numbers in it.

**Comment by Jules-WinnfieldX** [comment]
Those error numbers, when it says "Error Status Code" are HTTP status codes (like 404 being not found), so you'd just have to google HTTP status code 521
