### ISSUE TITLE
[FEATURE] e-hentai.org thread support enhancement

### ISSUE THREAD

**Issue by drumuri** [Jules-WinnfieldX/CyberDropDownloader#296]
e.hentai is a forum with a free hentai doujinshi, manga and image gallery system.

An example would be to download the entire content as an album like this https://e-hentai.org/g/2427415/b4ee1faedf/

It would be very grateful for your help.

Regards.

**Comment by Jules-WinnfieldX** [comment]
Added 4.0.1
