### ISSUE TITLE
[FEATURE] Doodstream

### ISSUE THREAD

**Issue by REDAKUN** [Jules-WinnfieldX/CyberDropDownloader#297]
dood stream links Support 
> https://dood.to
other domains : 
https://dood.cx
https://dood.la
https://dood.pm
https://dood.sh
https://dood.so
https://dood.watch
https://dood.ws
https://dood.re
Thanks

**Comment by Jules-WinnfieldX** [comment]
Can't get the website to function. Won't be able to do this one.
