### ISSUE TITLE
Fatal error in launcher

### ISSUE THREAD

**Issue by SusuyaJuuzo** [Jules-WinnfieldX/CyberDropDownloader#298]
my problem is that i start the bat (wndows) and i have this error

![image](https://user-images.githubusercontent.com/59805992/211580564-a8a99272-5e8b-4d3f-b24f-bbb0ec9590e3.png)

so i dont know what to do

here i put the error that i have in case that the mage dosnt det upload

C:\Users\morev>cyberdrop-dl
Fatal error in launcher: Unable to create process using '"c:\users\morev\appdata\local\programs\python\python39\python.exe"  "C:\Users\morev\AppData\Local\Programs\Python\Python39\Scripts\cyberdrop-dl.exe" ': the system can´t find the specific achive.

if some body can help me to fix this error or tell me what can i do i will be so gratefull thank you for all

**Comment by Jules-WinnfieldX** [comment]
If you have an antivirus, turn it off.

**Comment by SusuyaJuuzo** [comment]
> If you have an antivirus, turn it off.

I tried but stay the same, its my pc it have an issue with android studio and visual studio i used de cyberdrop downloader in other pc and it works fine sorry if i bother someone and i apreciate the answers you give me
