### ISSUE TITLE
[BUG] fapello not working

### ISSUE THREAD

**Issue by iGetUploaded** [Jules-WinnfieldX/CyberDropDownloader#299]
**Describe the bug**
Make sure to read the FAQ here first: https://github.com/Jules-WinnfieldX/CyberDropDownloader/wiki

**To Help Reproduce**
Steps to help reproduce the behavior:
1. Describe the bug accurately. - Trying to download from Fapello but its saying not supported

2. Provide an example album that showcases it (only containing non-copyright SFW images).
https://fapello.com/kylie-jenner/  ( Did hers as an example thats safer then the main one )

3. Make sure you are updated to the latest version to see if it's already fixed.

**Screenshots**

**Setup Information**
 - OS: [e.g. Windows 10, Mac OS X Sierra, etc]
 - Cyberdrop Downloader Version #
OS - Windows 10
Cyberdrop version - 3.3.3

**Downloader.log file**
You need to include the downloader.log file after the issue occurs. Majority of the time it's the only way to diagnose issues. 
[downloader.log](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/10407577/downloader.log)

**Additional context**

**Comment by Jules-WinnfieldX** [comment]
You are on version 3.3.3, fapello support wasn't added until 3.6.17. You need to update Cyberdrop-DL

**Comment by iGetUploaded** [comment]
I downloaded the zip file and tried again now I'm getting this 
![image](https://user-images.githubusercontent.com/54633753/212441388-5e645d32-44a5-4b25-86d6-af4e30cc8da5.png)

**Comment by Jules-WinnfieldX** [comment]
Can you access the site normally?

**Comment by iGetUploaded** [comment]
yes I can

**Comment by Jules-WinnfieldX** [comment]
I doubt it will tell me much with this instance, but shoot me over the downloader.log file

**Comment by Jules-WinnfieldX** [comment]
Any antivirus software?

**Comment by iGetUploaded** [comment]
just windows defender but I have it off

**Comment by iGetUploaded** [comment]
So I just tested it with another link and it scrapes and then downloads perfectly fine so im not sure what's wrong

**Comment by Jules-WinnfieldX** [comment]
Yea I'm confused by this. I'll have to try a bunch of links later to get one to fail for myself.

**Comment by iGetUploaded** [comment]
have you tried the Kylie one to see if it bugs out for you? just tested 3 other links and they work fine

**Comment by Jules-WinnfieldX** [comment]
Yea, both of the ones you've linked have worked for me.

**Comment by iGetUploaded** [comment]
Hmm that's really weird either way its working now tho

**Comment by anon1487** [comment]
Sorry for necro-posting, but I think this is important info.  Fapello links require an ending slash to work properly.

https://fapello.com/kylie-jenner/   -   Will work
https://fapello.com/kylie-jenner    -    Does not work

Both wil scrape fine, but the bottom URL will find no links.

**Comment by Jules-WinnfieldX** [comment]
> Sorry for necro-posting, but I think this is important info. Fapello links require an ending slash to work properly.
> 
> https://fapello.com/kylie-jenner/ - Will work https://fapello.com/kylie-jenner - Does not work
> 
> Both wil scrape fine, but the bottom URL will find no links.

Due to how fapello works, we check the return link on the page requests to make sure we are getting what we were expecting. 

https://fapello.com/kylie-jenner isn't a valid fapello link. It will redirect to https://fapello.com/kylie-jenner/

These links aren't the same, and hence nothing is scraped, because we stop scraping when the two don't equal each other.

I'm adding two lines of code to add a trailing slash when one isn't present, not going to push a release just for this though, so it'll be in the next one whenever it is released.
