### ISSUE TITLE
An existing connection was forcibly closed by the remote host

### ISSUE THREAD

**Issue by KzPop** [Jules-WinnfieldX/CyberDropDownloader#30]
("Connection broken: ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)", ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))

Any Idea why this could be happening ?

**Comment by Jules-WinnfieldX** [comment]
This has become an increasing issue with cyberdrop, essentially its their side dropping the connection. Unfortunately I do not believe there is anything I can do about this.
