### ISSUE TITLE
cyberdrop-dl 

### ISSUE THREAD

**Issue by huyhgtq** [Jules-WinnfieldX/CyberDropDownloader#300]
I couldn't find a way to fix it, tried reinstalling python and it didn't work
![image](https://user-images.githubusercontent.com/75951604/212460037-f1479c8f-732e-4cab-9598-6e14335318f0.png)

**Comment by Jules-WinnfieldX** [comment]
Did you click add python to path when you reinstalled it?

**Comment by Jules-WinnfieldX** [comment]
https://github.com/Jules-WinnfieldX/CyberDropDownloader/wiki#cyberdrop-dl-is-not-a-recognized-internal-command

I can't help more than this. It's due to bad installs on your system.
