### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by LCannotMLG** [Jules-WinnfieldX/CyberDropDownloader#301]
**Describe the bug**
Make sure to read the FAQ here first: https://github.com/Jules-WinnfieldX/CyberDropDownloader/wiki

**To Help Reproduce**
Steps to help reproduce the behavior:
I put in a cyberdrop video file, and it says its a loose file. The downloader is updated, defender is off I have python. I don't know what I'm doing wrong.

**Screenshots**

**Setup Information**
 - OS: Windows 11
 - Cyberdrop Downloader Version: The latest one

**Downloader.log file**
You need to include the downloader.log file after the issue occurs. Majority of the time it's the only way to diagnose issues. 

**Additional context**

![image](https://user-images.githubusercontent.com/84139651/213205048-a9e7c320-9940-482e-ab0b-508d33f2dd14.png)

[downloader.log](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/10447621/downloader.log)

**Comment by Jules-WinnfieldX** [comment]
The Loose Files name is the folder name I've assigned for "loose" files that aren't in albums. 

The issue you are running into however with the error is that as per usual, cyberdrop is broken (this time they've let their SSL Certificate expire again).

**Comment by Jules-WinnfieldX** [comment]
If you are fine with insecure connections you can download it through your browser, the program won't allow insecure connections because that's a massive security risk I don't want part in. 

As for cyberdrop itself, it's basically going the way of the dodo. Consider it dead for the most part.
