### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by MrFlappy0** [Jules-WinnfieldX/CyberDropDownloader#302]
How can up the speed download plss

**Comment by Jules-WinnfieldX** [comment]
You/I can't. It's limited by whatever server you are downloading from. 

It's as fast as it is really going to get.

**Comment by MrFlappy0** [comment]
Can't we increase the number of files processed?

**Comment by Jules-WinnfieldX** [comment]
That's what the --threads argument does. It's default is however many threads your CPU has. Certain websites though, such as bunker have a hard limit of 2 simultaneous downloads, so no bunker for example can't be increased.

**Comment by MrFlappy0** [comment]
okay for coomer how many is possible ?

**Comment by Jules-WinnfieldX** [comment]
Again, you set that yourself with the --threads argument. You should read the readme for all the options you can tinker with. Everything is controllable from your end.
