### ISSUE TITLE
[BUG] can't download simpcity thread

### ISSUE THREAD

**Issue by mc711** [Jules-WinnfieldX/CyberDropDownloader#306]
can't seem to download any simpcity threads. i can access the site normally in browser, but in the CDL log it's giving 403. threads are not password protected...

here is a log
[downloader.log](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/10495334/downloader.log)

**Comment by Jules-WinnfieldX** [comment]
That thread is password protected. Try opening it in incognito.

**Comment by mc711** [comment]
i just tried firefox icognito, i can see the thread...

![Capture](https://user-images.githubusercontent.com/2786469/214466461-625ac6aa-22f2-40a4-92b3-7279b61aa1b2.PNG)

**Comment by Jules-WinnfieldX** [comment]
As is also shown in your picture, you are logged in. If you aren’t logged in, you won’t be able to view the page

**Comment by Jules-WinnfieldX** [comment]
Misunderstanding,  I didn’t see you had provided a login.

**Comment by Jules-WinnfieldX** [comment]
Make sure your password is correctly entered for the program

**Comment by mc711** [comment]
password is correct, very simple password too so idk why it's still throwin 403

**Comment by Jules-WinnfieldX** [comment]
I'm not sure what else to say really. Make sure the password is in quotations if it has special characters in it I guess

**Comment by mc711** [comment]
so i finally figured out the problem. if you notice, it shows a SSL error. i was trying to figure what was causing the error. i thought it might be a bad reference in the scripts because the results are the same whether a password is save or not.

i thought it might something bad in the code, but i saw you output a login error. so i ruled out it was a login issue.

well, all in all. the error is from URL domain redirection. the original "simpcity.st" now redirects to the current domain "simpcity.su" due to the mismatch, it caused the SSL verification to fail.

idk if you might want to code a failsafe, but probably something to keep in mind.

anyways thanks for the quick responses.

**Comment by VladPedro** [comment]
I have the same problem. how to solve it? the password and login are correct. until now everything was working fine
