### ISSUE TITLE
[BUG] Kemono Party No Links Found

### ISSUE THREAD

**Issue by Omnistellar** [Jules-WinnfieldX/CyberDropDownloader#307]
Apologies that I'm not able to technically explain my issue, I don't know much about how all this works but I'm running into a problem where when I attempt to download any link I get the error message "No links found during scraping, check passwords or that the urls are accessible. This program does not currently support password protected albums." 

As far as I can tell the links I'm attempting to scrape are all accessible and none of them are password protected. 

[downloader.log](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/10495439/downloader.log)

If I can provide anything I'm happy to and sorry if I've completely overlooked something.

**Comment by Jules-WinnfieldX** [comment]
Kemono support was unfortunately dropped. They implemented DDOS-Guard recently and I don't want to struggle with trying to bypass it on a repeatable scale. If/When that changes (on either side) I'll bring support back. All the code is still there, it was just disabled.
