### ISSUE TITLE
[FEATURE] Change unsupported_urls for the rewrite

### ISSUE THREAD

**Issue by n30liberal** [Jules-WinnfieldX/CyberDropDownloader#308]
Currently there's no way for the script to know which link the unsupported url came from, but I'm hoping for the rewrite this could be changed? The dream would be for each folder that gets created, the folder would also contain its own unsupported_urls.txt file, i.e. if we're downloading 10 threads, each thread would have it's own unsupported_url file. Currently it's near impossible to parse the unsupported_url file due it to it containing thousands of links and not knowing who each link is for.

**Comment by Jules-WinnfieldX** [comment]
Added 4.0.1
