### ISSUE TITLE
[FEATURE] Add Overall Progress Bar or Indicator

### ISSUE THREAD

**Issue by slitchampion** [Jules-WinnfieldX/CyberDropDownloader#310]
The individual file/folder progress bars are helpful, but it would be tremendous to have an overall progress bar to give a sense of how far along the program is entirely. Given that it does all of the scraping up front, I'd imagine there's a way to track progress overall.

**Comment by Jules-WinnfieldX** [comment]
Completed, closing, it'll be in 4.0
