### ISSUE TITLE
[BUG] Errors downloading from cyberdrop.me

### ISSUE THREAD

**Issue by cuzwhynot123** [Jules-WinnfieldX/CyberDropDownloader#313]
**Describe the bug**
The downloader shows the name of the cyberdrop album and how many files are in it and then sits there like that for an hour. Eventually it goes through all the files saying "Error attempting..."

[downloader.log](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/10531097/downloader.log)

**Comment by Jules-WinnfieldX** [comment]
This isn’t an error with the downloaded, it’s an error with cyberdrop. It’s certificate is expired and the downloaded doesn’t allow insecure connections

**Comment by cuzwhynot123** [comment]
The whole site has expired or just that album?

**Comment by Jules-WinnfieldX** [comment]
The certificate to some (or all) of their file servers.
