### ISSUE TITLE
[FEATURE] Ignore Config File/Custom Commands First

### ISSUE THREAD

**Issue by C-BoT-AU** [Jules-WinnfieldX/CyberDropDownloader#314]
Once `config.yaml` is set to `Apply_Config: true`, attempting to add arguments like `-i` and `-o`  to override the default or custom setup doesn't work.
Default behavior seems to be to check the config file first, then only if `Apply_Config: false` does it check the command lines.

Ideally, Cyberdrop-DL needs to 
1. scan the command line first, 
2. then only where necessary arguments (like source file, output destination, passwords) are missing, does it check `config.yaml`. 
3. Obviously if `config.yaml` is `Apply_Config: false` or missing, it then just uses defaults.
Additionally/Alternatively, have a --ignore-config or similar flag that can be added so that even if `Apply_Config: true`, it ignores the custom config settings

**Comment by Jules-WinnfieldX** [comment]
I don't think I'm going to do this. However, in 4.0.1 you will be able to specify where the name and where the config file you want to run with is located. As a work around, you would be able to specify a config that isn't set to apply.
