### ISSUE TITLE
[BUG] can't download xbunker threads

### ISSUE THREAD

**Issue by kiddogum** [Jules-WinnfieldX/CyberDropDownloader#316]
if i try to download a thread post in xbunker it began to download random files
![Screenshot 2023-01-30 233348](https://user-images.githubusercontent.com/123975377/215537741-98256f1a-ed8d-410e-b5f3-c385fde43f19.png)

[downloader.log](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/10537836/downloader.log)

**Comment by Jules-WinnfieldX** [comment]
Those aren't "random" files, those are links that it is working on from that thread.

**Comment by kiddogum** [comment]
but even if its the links from the thread, it still didn't went into my download, do you know why?

**Comment by Jules-WinnfieldX** [comment]
If you downloaded them before, it won't re-download them unless you tell the program to ignore history.

What you pictured is also just the scraping step, it has to get past that to actually start downloading. Just let it run.

**Comment by kiddogum** [comment]
it really did download!! but it took some time
thankyou for the replies!
