### ISSUE TITLE
[BUG] Bunkr change their link from bunkr.ru to bunkr.su, Please update the downloader 🙏

### ISSUE THREAD

**Issue by samuelkwijaya** [Jules-WinnfieldX/CyberDropDownloader#320]
**Describe the bug**
Everytime you download files using bunkr.ru link, it will says "**Finished downloading. Enjoy :)"** but there is no folder or files shown up in Downloads file.
If you download using bunkr.su, it just the same

**To Help Reproduce**
- Just copy and paste bunkr.ru / bunkr.su link into **URLs.txt**

**Setup Information**
 - OS: Windows 10
 
**Additional context**
Please fix it as soon as it possible 🙏🙏 (bit out of topic but we can't access albums list on bunkr)

**Comment by Jules-WinnfieldX** [comment]
Have you updated to the latest version? 3.6.55?

**Comment by samuelkwijaya** [comment]
> Have you updated to the latest version? 3.6.55?

oh sorry i forgot to update the version, thx 🙏🙏
