### ISSUE TITLE
'cyberdrop-dl' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by solidwangz** [Jules-WinnfieldX/CyberDropDownloader#322]
I've installed the requirements, added a link to the URLS list that I want to download, and when I try to run the Start.bat (windows) I get the message... 'cyberdrop-dl' is not recognized as an internal or external command 

Not sure why this is happening, any help is appreciated

**Comment by Jules-WinnfieldX** [comment]
https://github.com/Jules-WinnfieldX/CyberDropDownloader/wiki#cyberdrop-dl-is-not-a-recognized-internal-command
