### ISSUE TITLE
[FEATURE] Pause/Resume after running out of space during a download.

### ISSUE THREAD

**Issue by uNderdog101** [Jules-WinnfieldX/CyberDropDownloader#325]
**Is your feature request related to a problem? Please describe.**
Currently, if you run out of space during a download, the program gives a "press any key to continue" prompt, "continue" meaning close the window, so you have to restart with scraping after clearing some space.

**Describe the solution you'd like**
Would it be possible to instead of the "press any key..." prompt have an option to continue as if you hadn't run out of space? For example, you run out of space, the program gives a "You have run out of space. Press 'X' to close or press 'R' to resume" prompt, giving you the opportunity to cull the unwanted files to clear space and then press "R" to continue like you hadn't run out of space, without the need for a new scrape.

My current scrape after running out of space is over two hours old, and still going...

**Comment by Jules-WinnfieldX** [comment]
This press any key to continue message isn't actually from Cyberdrop-DL, it comes from the start file. It was put in so that if you just double click to run it, it won't auto close after CDL has finished. 

That being said, this should be possible. to include.

**Comment by Jules-WinnfieldX** [comment]
With how actually complicated this is to add, I'm going to skip this unfortunately. With how many of the filehosts use cookies and other things to ensure timely access, this likely wouldn't be as useful as seems. If it takes you a few hours to notice, a lot of the links would likely already be dead and inaccessible and need to be rescraped anyways.
