### ISSUE TITLE
[BUG] Python error for Gofile on Windows 

### ISSUE THREAD

**Issue by Rocket3192** [Jules-WinnfieldX/CyberDropDownloader#326]
Hello I've been using the script in the past, but today I tried to use it to download from a gofile link and heres what it returned : 

> Traceback (most recent call last):
  File "C:\Users\X\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\X\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\X\AppData\Local\Programs\Python\Python310\Scripts\cyberdrop-dl.exe\__main__.py", line 4, in <module>
  File "C:\Users\X\AppData\Local\Programs\Python\Python310\lib\site-packages\cyberdrop_dl\main.py", line 13, in <module>
    from cyberdrop_dl.scraper.scraper_helper import ScrapeMapper
  File "C:\Users\X\AppData\Local\Programs\Python\Python310\lib\site-packages\cyberdrop_dl\scraper\scraper_helper.py", line 19, in <module>
    from ..crawlers.GoFile_Spider import GofileCrawler
  File "C:\Users\X\AppData\Local\Programs\Python\Python310\lib\site-packages\cyberdrop_dl\crawlers\GoFile_Spider.py", line 4, in <module>
    from gofile import Gofile
ImportError: cannot import name 'Gofile' from 'gofile' (C:\Users\X\AppData\Local\Programs\Python\Python310\lib\site-packages\gofile\__init__.py)

I'm using Windows 10 and the latest version of the script

**Comment by Jules-WinnfieldX** [comment]
How are you running it?

**Comment by thejos241** [comment]
I had the same issue. I resolved it by doing the following:

1. Right click the "Start Windows"
2. Run as Administrator
3. This rebuilt the URLs.txt file
4. Re-added links
5. Run normally (no need to run as administrator each time after)

**Comment by Rocket3192** [comment]
> I had the same issue. I resolved it by doing the following:
> 
> 1. Right click the "Start Windows"
> 2. Run as Administrator
> 3. This rebuilt the URLs.txt file
> 4. Re-added links
> 5. Run normally (no need to run as administrator each time after)

Didn't work for me



> How are you running it?

I just double click on Start Windows.bat

**Comment by Jules-WinnfieldX** [comment]
Try this:
Open command prompt
`pip uninstall gofile`
then
`pip install --upgrade cyberdrop-dl`

**Comment by masterdjboner** [comment]
i have the same issue and neither suggestions have worked for me. worked fine yesterday

Traceback (most recent call last):
  File "C:\Users\X\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\X\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\X\AppData\Local\Programs\Python\Python310\Scripts\cyberdrop-dl.exe\__main__.py", line 4, in <module>
  File "C:\Users\X\AppData\Local\Programs\Python\Python310\lib\site-packages\cyberdrop_dl\main.py", line 13, in <module>
    from cyberdrop_dl.scraper.scraper_helper import ScrapeMapper
  File "C:\Users\X\AppData\Local\Programs\Python\Python310\lib\site-packages\cyberdrop_dl\scraper\scraper_helper.py", line 19, in <module>
    from ..crawlers.GoFile_Spider import GofileCrawler
  File "C:\Users\X\AppData\Local\Programs\Python\Python310\lib\site-packages\cyberdrop_dl\crawlers\GoFile_Spider.py", line 4, in <module>
    from gofile import Gofile
ImportError: cannot import name 'Gofile' from 'gofile' (unknown location)

> Try this: Open command prompt `pip uninstall gofile` then `pip install --upgrade cyberdrop-dl`

C:\Users\X>pip uninstall gofile
WARNING: Skipping gofile as it is not installed.

C:\Users\X>pip install --upgrade cyberdrop-dl
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Requirement already satisfied: cyberdrop-dl in c:\users\X\appdata\local\programs\python\python310\lib\site-packages (3.6.61)
Requirement already satisfied: PyYAML>=6.0 in c:\users\X\appdata\local\programs\python\python310\lib\site-packages (from cyberdrop-dl) (6.0)
Requirement already satisfied: tqdm>=4.64.1 in c:\users\X\appdata\local\programs\python\python310\lib\site-packages (from cyberdrop-dl) (4.64.1)
Requirement already satisfied: aiohttp>=3.8.3 in c:\users\X\appdata\local\programs\python\python310\lib\site-packages (from cyberdrop-dl) (3.8.3)
Requirement already satisfied: myjdapi>=1.1.6 in c:\users\X\appdata\local\programs\python\python310\lib\site-packages (from cyberdrop-dl) (1.1.6)
Requirement already satisfied: aiofiles>=22.1.0 in c:\users\X\appdata\local\programs\python\python310\lib\site-packages (from cyberdrop-dl) (23.1.0)
Requirement already satisfied: setuptools>=65.6.3 in c:\users\X\appdata\local\programs\python\python310\lib\site-packages (from cyberdrop-dl) (65.6.3)
Requirement already satisfied: psutil>=5.9.4 in c:\users\X\appdata\local\programs\python\python310\lib\site-packages (from cyberdrop-dl) (5.9.4)
Requirement already satisfied: yarl>=1.8.2 in c:\users\X\appdata\local\programs\python\python310\lib\site-packages (from cyberdrop-dl) (1.8.2)
Requirement already satisfied: gofile-client>=1.0.1 in c:\users\X\appdata\local\programs\python\python310\lib\site-packages (from cyberdrop-dl) (1.0.1)
Requirement already satisfied: beautifulsoup4>=4.11.1 in c:\users\X\appdata\local\programs\python\python310\lib\site-packages (from cyberdrop-dl) (4.11.1)
Requirement already satisfied: certifi>=2022.12.7 in c:\users\X\appdata\local\programs\python\python310\lib\site-packages (from cyberdrop-dl) (2022.12.7)
Requirement already satisfied: colorama>=0.4.6 in c:\users\X\appdata\local\programs\python\python310\lib\site-packages (from cyberdrop-dl) (0.4.6)
Requirement already satisfied: charset-normalizer<3.0,>=2.0 in c:\users\X\appdata\local\programs\python\python310\lib\site-packages (from aiohttp>=3.8.3->cyberdrop-dl) (2.0.12)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\users\X\appdata\local\programs\python\python310\lib\site-packages (from aiohttp>=3.8.3->cyberdrop-dl) (6.0.2)
Requirement already satisfied: frozenlist>=1.1.1 in c:\users\X\appdata\local\programs\python\python310\lib\site-packages (from aiohttp>=3.8.3->cyberdrop-dl) (1.3.0)
Requirement already satisfied: aiosignal>=1.1.2 in c:\users\X\appdata\local\programs\python\python310\lib\site-packages (from aiohttp>=3.8.3->cyberdrop-dl) (1.2.0)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in c:\users\X\appdata\local\programs\python\python310\lib\site-packages (from aiohttp>=3.8.3->cyberdrop-dl) (4.0.2)
Requirement already satisfied: attrs>=17.3.0 in c:\users\X\appdata\local\programs\python\python310\lib\site-packages (from aiohttp>=3.8.3->cyberdrop-dl) (21.4.0)
Requirement already satisfied: soupsieve>1.2 in c:\users\X\appdata\local\programs\python\python310\lib\site-packages (from beautifulsoup4>=4.11.1->cyberdrop-dl) (2.3.2.post1)
Requirement already satisfied: requests in c:\users\X\appdata\local\programs\python\python310\lib\site-packages (from gofile-client>=1.0.1->cyberdrop-dl) (2.28.0)
Requirement already satisfied: pycryptodome in c:\users\X\appdata\local\programs\python\python310\lib\site-packages (from myjdapi>=1.1.6->cyberdrop-dl) (3.15.0)
Requirement already satisfied: idna>=2.0 in c:\users\X\appdata\local\programs\python\python310\lib\site-packages (from yarl>=1.8.2->cyberdrop-dl) (3.3)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\X\appdata\local\programs\python\python310\lib\site-packages (from requests->gofile-client>=1.0.1->cyberdrop-dl) (1.26.9)

**Comment by masterdjboner** [comment]
ok i did a bit of trouble shooting and i got it working.

i created a brand new one in a venv, which worked.

so i copy/pasted and overwrote the site-packages from the venv to the one in the main python PATH and it now works

**Comment by Jules-WinnfieldX** [comment]
I had a type it should have been
`pip uninstall gofile-client`

**Comment by Rocket3192** [comment]
> I had a type it should have been `pip uninstall gofile-client`

Thanks, it now works again
