### ISSUE TITLE
[BUG] Issue downloading many Bunkr URLs

### ISSUE THREAD

**Issue by LeDongerz** [Jules-WinnfieldX/CyberDropDownloader#327]
**Describe the bug**
Make sure to read the FAQ here first: https://github.com/Jules-WinnfieldX/CyberDropDownloader/wiki

**To Help Reproduce**
Steps to help reproduce the behavior:
1. Many Albums fail to download for no reason/support for Bunkr.su is unclear as well, error is "Error scraping X Site"
3. Some galleries that fail to download include:  https://bunkr.ru/a/oEVRRTpk,  https://bunkr.ru/a/OgPuuLaF, https://bunkr.su/a/LJl11FGK
4. Make sure you are updated to the latest version to see if it's already fixed.

**Screenshots**

**Setup Information**
 - OS: Windows 10
 - Cyberdrop Downloader Version #: Latest version as of 2/9/2023
 -

**Downloader.log file**
You need to include the downloader.log file after the issue occurs. Majority of the time it's the only way to diagnose issues. 
[downloader.log](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/10703796/downloader.log)

**Additional context**

**Comment by Jules-WinnfieldX** [comment]
You aren't on the latest version. Update Cyberdrop-DL

https://github.com/Jules-WinnfieldX/CyberDropDownloader/wiki#how-to-update
