### ISSUE TITLE
[FEATURE] Add "bunkr.su"

### ISSUE THREAD

**Issue by salvamea** [Jules-WinnfieldX/CyberDropDownloader#328]
Hi, you can add "bunkr.su" to the list of Supported Link Types, when i add link to the file.TXT tell me "is not supported currently"

**Comment by Jules-WinnfieldX** [comment]
It is currently already supported, you just need to update cyberdrop-dl

https://github.com/Jules-WinnfieldX/CyberDropDownloader/wiki#how-to-update
