### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by haayfe** [Jules-WinnfieldX/CyberDropDownloader#336]
How do I disable auto-skip on repeated downloads?
I'm trying to download another coomer.party page that now has more posts on it but Cyberdrop just instantly skips the whole thing. The original download is no longer in the downloads folder and moving Cyberdrop to a different location doesn't fix it. I assume it must be something wrong with my config file since I can fix it by completely redownloading Cyberdrop but I'm not sure what.
Any help appreciated. Thanks.
![image](https://user-images.githubusercontent.com/111808387/219527272-f9c6d028-0f99-4ac7-a44f-000220644a75.png)

**Comment by Jules-WinnfieldX** [comment]
https://github.com/Jules-WinnfieldX/CyberDropDownloader/wiki/Config-Options#ignore_history

**Comment by haayfe** [comment]
Ah, thanks very much. Stupid for not seeing that.
