### ISSUE TITLE
[BUG] Downloads "media unavailable due to an on-going server maintenance" video file from bunkr

### ISSUE THREAD

**Issue by jerrywoo96** [Jules-WinnfieldX/CyberDropDownloader#338]
**Describe the bug**
Prevent downloading of mp4 files that is "media unavailable due to an on-going server maintenance" when scraping forums.
Instead, mark this as not downloaded.

![image](https://user-images.githubusercontent.com/26324139/219800729-aef4a7c1-587c-4054-ac71-df54e51fd6df.png)

**To Help Reproduce**
Scrape this forum.
https://tinyurl.com/2w58y8u9

**Setup Information**
 - OS: Windows 10 22H2, Python 3.10 x64
 - Cyberdrop Downloader Version 3.6.64
 
 PS, I tried using the latest 4.x.x version of cyberdrop-dl, it also stops downloading the forum midway and never completes.

**Comment by Jules-WinnfieldX** [comment]
This is already done in V4, if there are other issues, please open a new issue for it.
