### ISSUE TITLE
Can't find pictures on putmega file

### ISSUE THREAD

**Issue by LFS900** [Jules-WinnfieldX/CyberDropDownloader#34]
I tried downloading from the following URL: https://putme.ga/album/example
However the link is locked by a password which is why I fear it cannot find any files. Not sure. But everytime I try, it closes immediately. When I try an older version I can see this error "https://putme.ga/album/example Couldn't find pictures."
Are password protected links supported?

**Comment by Jules-WinnfieldX** [comment]
Password protected albums are currently not supported. There's no easy way for me to implement it and make it easy for the average end user to supply the password. I could potentially do it using user input on each link that is necessary. But this would require essentially spoofing the outgoing html call with the password, or more likely requiring a rewrite to be able to handle dynamic web pages.
