### ISSUE TITLE
[BUG] unsupported.csv missing links

### ISSUE THREAD

**Issue by h82b8** [Jules-WinnfieldX/CyberDropDownloader#340]
**Describe the bug**
when scraping a thread on simpcity it does not add unsupported links to the unsupported links .csv

**To Help Reproduce**
Steps to help reproduce the behavior:
scrape any thread 

**Setup Information**
 - OS: Windows 10
 - Cyberdrop Downloader Version # 4.0.34

here is the log
[downloader.log](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/10777746/downloader.log)

**Comment by Jules-WinnfieldX** [comment]
I can't replicate this, however it's important to note that some links and files will not be fully completed in writing until after the program has completely exited. Meaning, you need to wait for the program to fully complete before going through these files.

**Comment by h82b8** [comment]
If I let it run and finish the csv still is empty, I tried not using the config instead just using commands, but no change. 

any ideas what I could try to get it working as intended?

**Comment by Jules-WinnfieldX** [comment]
https://github.com/Jules-WinnfieldX/CyberDropDownloader/wiki/Config-Options#output_unsupported_urls

make sure you set this to true

**Comment by h82b8** [comment]
it is set to true, i did try it again just to be sure tho, same result

in the downloader.log it says this:
File "C:\Users\mos\AppData\Local\Programs\Python\Python310\lib\site-packages\cyberdrop_dl\scraper\Scraper.py", line 356, in map_url
    await f.write(f"{str(url_to_map)},{str(referer)},{title}\n")
  File "C:\Users\mos\AppData\Local\Programs\Python\Python310\lib\site-packages\aiofiles\threadpool\utils.py", line 45, in method
    return (yield from self._loop.run_in_executor(self._executor, cb))
  File "C:\Users\mos\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\mos\AppData\Local\Programs\Python\Python310\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\ub791' in position 95: character maps to <undefined>
2023-02-20 18:06:42,144:ERROR:base_events:base_events.py:1758:Task exception was never retrieved

some googling around came up with stuff related to utf-8 encoding, 

i'm not sure what could be wrong with my install
win 10, python 3.10, pip is up2date as well

any other guess what i could try? or what might cause this behavior

**Comment by Jules-WinnfieldX** [comment]
What causes the behaviour with the error you just ran into, is a unicode character (랑) being in one of the links or titles, and the program not being able to encode it to the default output (almost always utf-8)

**Comment by Jules-WinnfieldX** [comment]
4.0.36 will strip all unicode characters from the titles before writing to the unsupported file.

**Comment by h82b8** [comment]
just tested it, works great now!

thank you very much
