### ISSUE TITLE
[FEATURE] Preform case insensitive check before creating new folders. Rename match to expected case and reuse. 

### ISSUE THREAD

**Issue by tarchive** [Jules-WinnfieldX/CyberDropDownloader#343]
### Problem
The general problem is that old versions CDL use different folder names than what are used in the current version. 

When folder names completely change, it's only a minor annoyance as there may be some files that are redownloaded. 
When the folder name spelling stays the same and only the case is changed, this can becomes a big issue depending os/filesystem/filesharing settings, which in worse cases can lead to data loss.

Here is an example of what i'm talking about. Back in Nov 2022, using the current version at that time, i scrapped a kemono user and a folder called `username (Kemono.party)` was created. 
Yesterday when scraping the same user with 4.0.33 a new folder called `username (kemono.party)` was created.

Specifically for my environment, I can see both folders in Windows from my network share to my NAS. If i try to enter the folders both take me to the same one folder. If i do any write action (rename/cut/paste) the other folder with be instantly deleted without warning.
Through trial and error I've learned that I don't have this issue when accessing the same share from my Linux computer. So now when i notice the duplicate named folder i must use my Linux computer to merge the contents before doing anything from Windows.
Again, depending on your os/filesystem/filesharing settings you may not experience the the problem the same way or even at all.

### Solution
The solution i propose is very simple. Preform a case insensitive check before creating any new folders and if a folder exists it should be renamed to the correct case and reused.

### Additional
The the caveat with this solution is that if the expected folder already exists then it would not preform any check for other matching folders with casing differences. This is an intended result to avoid having to handle merging folders which IMO getting out of the scope of this tool.
Also, if should more than one match exist with different casing but no match for expected folder name then just use the first match for renaming and reusing. 
Again done to avoid handling folder merges which is easy enough for the user to do at their own convenience and does no pose the same issue as if the folders only had differing case

Let me know what you think.

**Comment by Jules-WinnfieldX** [comment]
https://github.com/Jules-WinnfieldX/CyberDropDownloader/blob/0be6b3487a3a8c947ecdf612aad496df925c2977/cyberdrop_dl/client/client.py#L138

This is where the folder creation happens, functionally, this is already a test for if a directory of the same name (regardless of case) exists. There really isn't a better test I could write for it. At least that easily comes to mind. If this fails to recognize such folder already exists, it's likely that near any other check I could think of would also fail. 

I'm this duplicate folder (with differing cases) happens occasionally in some setups, but there doesn't seem to be an easy way to avoid it, even much larger and more sophisticated programs such as Syncthing fail to combat this.
