### ISSUE TITLE
[FEATURE] The site: BUNKR, changed all its site addresses from BUNKR.RU to BUNKR.SU, plz update 

### ISSUE THREAD

**Issue by JImRubbish** [Jules-WinnfieldX/CyberDropDownloader#344]
**Is your feature request related to a problem? Please describe.**
Yes, the app can no longer download stuff from BUNKR cuz this problem of changing their address name.

**Describe the solution you'd like**
Update the code to accommodate their change(BUNKR.RU to BUNKR.SU) on the site address

**Additional context**
Their current links are all in this form: https://bunkr.su/

PS: Love what you created, this app is amazing, saves lotta time for people. I wish you a happy day, sir

**Comment by Jules-WinnfieldX** [comment]
Cyberdrop-DL has already updated for this, you just need to update it on your machine.

**Comment by Jules-WinnfieldX** [comment]
https://github.com/Jules-WinnfieldX/CyberDropDownloader/wiki/Frequently-Asked-Questions#how-to-update

**Comment by JImRubbish** [comment]
Thanks man, all the good work

**Comment by reddere** [comment]
BUNKR.SU is not working anymore, what's the website they changed to, again? @JImRubbish @Jules-WinnfieldX

**Comment by Jules-WinnfieldX** [comment]
bunkr.la
