### ISSUE TITLE
[BUG] bunkr.su unable to download from Cyberdrop_DL.V4

### ISSUE THREAD

**Issue by kkma24** [Jules-WinnfieldX/CyberDropDownloader#346]
[downloader.log](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/10813266/downloader.log)

File "C:\Users\kkma2\AppData\Local\Programs\Python\Python310\lib\site-packages\cyberdrop_dl\crawlers\Bunkr_Spider.py", line 42, in fetch
    build_id = json.loads(soup.select_one("script[id=__NEXT_DATA__]").get_text())
AttributeError: 'NoneType' object has no attribute 'get_text'

I can understand that this part is a problem

But can't fix it...

**Comment by Jules-WinnfieldX** [comment]
You are on an incredibly old version. I suggest you update. https://github.com/Jules-WinnfieldX/CyberDropDownloader/wiki/Frequently-Asked-Questions#how-to-update
