### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Ryan69132** [Jules-WinnfieldX/CyberDropDownloader#347]
**Describe the bug**
trying to download https://bunkr.su/a/b3xbcLbu

**To Help Reproduce**
pasted this url https://bunkr.su/a/b3xbcLbu in the url.txt
and startet the windows.bat for cyberdropdownloader.

**Setup Information**
 - OS:  windows 10 version 22H2 (Build: 19045.2604)
 - Cyberdrop Downloader Version  the newest 

**Downloader.log file**
You need to include the downloader.log file after the issue occurs. Majority of the time it's the only way to diagnose issues. 

added the logs
[downloader.log](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/10816214/downloader.log)

**Comment by Jules-WinnfieldX** [comment]
"Connection timeout to host"

You're connection timed out, that's an issue with your connection, not an issue with the downloader.

**Comment by Ryan69132** [comment]
alright thank you
