### ISSUE TITLE
[FEATURE] Changing download folder

### ISSUE THREAD

**Issue by Hellothere95** [Jules-WinnfieldX/CyberDropDownloader#349]
Can i change the download folder? All the downloads is filling up my C Drive. Can i somehow change that?

**Comment by Jules-WinnfieldX** [comment]
https://github.com/Jules-WinnfieldX/CyberDropDownloader/wiki/Config-Options#output_folder

Just put the path in the output_folder option

**Comment by Hellothere95** [comment]
Do i have to change the "WindowsPath" or the  (' Downloads ') to the folder i wanna use? I want to use my externe harddrive with the folder named D:\CL Downloads

**Comment by Jules-WinnfieldX** [comment]
You can make it simply 
`output_folder: "d:\CL Downloads"`

**Comment by Hellothere95** [comment]
It still downloads to my C: Drive

**Comment by Jules-WinnfieldX** [comment]
you have to change apply_config at the top to true.

**Comment by Hellothere95** [comment]
still the same. I changed the Output_folder where it says Windows path ( 'Downloader' ) to d:\CL Downloads and then i changed the {'apply_jdownloader': False to true and clicked save. But it just resets and won't change the download folder.

**Comment by Jules-WinnfieldX** [comment]
did you put d:\CL Downloads in quotation marks?

**Comment by Jules-WinnfieldX** [comment]
try changing the \ to a /

**Comment by Hellothere95** [comment]
Do i have to change the WindowsPath or the ( 'Downloads' ) to d:\CL Downloads ?

**Comment by Hellothere95** [comment]
I just copied the adress directly from the drive and it says d:\CL Downloads ?

**Comment by Jules-WinnfieldX** [comment]
> You can make it simply `output_folder: "d:\CL Downloads"`

You can make it exactly as I said it here. With the quotations. As I said in my last comment you may need to change it to d:\\CL Downloads or d:/CL Downloads because \ is an escape character and might be read wrong by python.

**Comment by Hellothere95** [comment]
![image](https://user-images.githubusercontent.com/125223201/221097333-6c3ab262-13c0-498c-8c48-66b9071552a1.png)
Like this?

**Comment by Jules-WinnfieldX** [comment]
No. That's the downloader.log file. You need to change it in the config file.

**Comment by Hellothere95** [comment]
Oh. The config.yaml file? How do i open that?

**Comment by Jules-WinnfieldX** [comment]
Right click and open with your text editor.

**Comment by Hellothere95** [comment]
Perfect! Thank you. I couldn't figure out how to open the yaml file so i thought it was the other download folder. Everthing works now!

**Comment by Hellothere95** [comment]
Everytime i try to download it says "There are partial downloads in the downloads folder" What does that mean?

**Comment by Jules-WinnfieldX** [comment]
As the message would suggest, there are partial downloads in the download folder from downloads that didn’t complete in previous runs.

**Comment by Hellothere95** [comment]
How do i remove those? I've deleted the last used links but when i insert new links i get that message

**Comment by Jules-WinnfieldX** [comment]
Delete the .part files in the downloads folder.

**Comment by Hellothere95** [comment]
I dont have that file

**Comment by Jules-WinnfieldX** [comment]
You must, or else you wouldn't get that message. The .part is the file extension. So it'd be something like ImAVideo.mp4.part
