### ISSUE TITLE
bunkr.is: Videos/mp4 files with Unicode symbols in the filename fail to download

### ISSUE THREAD

**Issue by MikeDoubleU** [Jules-WinnfieldX/CyberDropDownloader#35]
#### Issue description
When downloading videos/mp4 files with Unicode symbols in the filename, it fails with a conversion error:
`'latin-1' codec can't encode character '\u2019' in position 87: ordinal not in range(256)`
`Failed attempt 1 for Its-getting-warmer-outside,-so-it’s-a-perfect-time-to-remind-you-of-all-the-super-hot-summertime-fun-I-enjoy!-pVMg1JUh.mp4`
Its not a filename issue, because the same filename with a .jpg extension downloads just fine. It also seems to be independent from the file size.

#### Steps to reproduce the issue

1. Add the following Test Link to the URL.txt file: https://bunkr.is/a/zkGCNfxs .
2. Run the start.bat.
3. The jpgs download without any problem, but the mp4 fails.

#### What's the expected result?

- All files should download correctly.

#### What's the actual result?

- The mp4 file fails to download with the above error message.

#### Additional details
Windows 10 21H1
Python 3.9.7
CyberDropDownloader 1.5.1

**Comment by Jules-WinnfieldX** [comment]
Just put out 1.5.2 to fix this issue. Requests library attempts to encode all strings to the latin-1 codec, for non conforming characters this errors out which is the issue you were facing. 

Please re-open the issue if this causes adverse effects or if it doesn't work for you.
