### ISSUE TITLE
[BUG] Cyberdrop_DL crashes when trying to use "skip_download_mark_completed" Flag

### ISSUE THREAD

**Issue by RevENGE-code** [Jules-WinnfieldX/CyberDropDownloader#350]
**Describe the bug**
Program crashes when trying to mark something as downloaded.

**To Help Reproduce**
Steps to help reproduce the behavior:
1. set skip_download_mark_completed to true
2. Run Cyberdrop Downloader Version 4.0.52

**Screenshots**
<img width="1088" alt="Bildschirm­foto 2023-02-24 um 05 44 20" src="https://user-images.githubusercontent.com/54822494/221094735-f8d067d0-5399-41ee-957d-e9caf5b79c27.png">

**Setup Information**
 - OS: MacOS Ventura 13.2.1 (22D68)
 - Cyberdrop Downloader Version 4.0.52 (under github release)

**Downloader.log file**
[downloader.log](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/10820784/downloader.log)

**Comment by Jules-WinnfieldX** [comment]
4.0.53 should fix this. Released now
