### ISSUE TITLE
bunkr.us.to not working

### ISSUE THREAD

**Issue by Leboxis** [Jules-WinnfieldX/CyberDropDownloader#353]
![image](https://user-images.githubusercontent.com/97406795/221426803-e62f8f45-c4eb-4ec4-810e-5436d2f2ce4c.png)

**Comment by Jules-WinnfieldX** [comment]
Not a clue what bunkr.us.to is, but I'm assuming it isn't a real endpoint of bunkr. Change them to bunkr.su/a/...
