### ISSUE TITLE
Latest update bug

### ISSUE THREAD

**Issue by ungallama** [Jules-WinnfieldX/CyberDropDownloader#354]
Hi, first of all thank you for developing this tool.
OKey, so the problem started few days ago after the latest update, I dont know exactly when because I haven't used it for 2 weeks. It just doesn't download, stuck at 0 and moves on. I leave it running some time but all the files fail to download. Tried many times, different links, same result. It used to work fine, I used it for about two month no problems. Here's the log input file : https://gofile.io/d/uPxdvU
Sorry if the bug report is messy, first time actually posting one in gifthub.
EDIT : jpg.church links work, bunkre too but severly limited (13kB/s). Looks like only cyberdrop doesnt

**Comment by Jules-WinnfieldX** [comment]
Speeds are dependent on the server speed, most of which are dealing with issues currently (like bunkr).

As for cyberdrop, the site is essentially dead. You can open the link you put in and try to download it manually and you'll see what I mean.
