### ISSUE TITLE
[BUG] Bunkr.su not working [download failed]

### ISSUE THREAD

**Issue by ItsMSouza** [Jules-WinnfieldX/CyberDropDownloader#355]
![dsac](https://user-images.githubusercontent.com/126608469/221943997-49cc5f75-bf0e-4b53-8893-fe64a4b59999.png)
Since early morning file download from bunkr.su is not working. Until yesterday everything was normal

**Comment by Jules-WinnfieldX** [comment]
I need to see the downloader.log file

**Comment by ItsMSouza** [comment]
[downloader.log](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/10853758/downloader.log)

**Comment by Jules-WinnfieldX** [comment]
That downloader.log is empty. Run it again with the link, then send it to me.

**Comment by ItsMSouza** [comment]
[downloader.log](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/10853971/downloader.log)

**Comment by Jules-WinnfieldX** [comment]
Pretty simply, the files are under maintenance. You can open the link and try to download them yourself to verify.
