### ISSUE TITLE
[BUG] CyberDrop Downloader does not download

### ISSUE THREAD

**Issue by acidpuff** [Jules-WinnfieldX/CyberDropDownloader#359]
Absolutely nothing downloads, I do not know what the problem is.
I attach a .log file.
Link to CyberDrop archive, which I wanted to download: https://cyberdrop.me/a/kwaUmbYMС

![image](https://user-images.githubusercontent.com/88398516/222437611-b40f8349-6111-4279-940b-2410bb967490.png)
![image](https://user-images.githubusercontent.com/88398516/222437628-f9b59488-aae0-4cfd-9265-206909dda6da.png)
[downloader.log](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/10871635/downloader.log)

**Comment by Jules-WinnfieldX** [comment]
Cyberdrop is dead. Try and download them manually and you'll see.
