### ISSUE TITLE
bunkr video http error 429 too many request

### ISSUE THREAD

**Issue by jerrywoo96** [Jules-WinnfieldX/CyberDropDownloader#36]
bunkr album id: dmbW3gZR

429 Client Error: Too Many Requests for url: the file url
        Failed attempt 1 for the file name

btw i think u forgot to update the version number in the python file.

![image](https://user-images.githubusercontent.com/26324139/141806852-747c518f-3b0d-4a08-8d80-d345902f8ba3.png)

**Comment by Jules-WinnfieldX** [comment]
https://github.com/Jules-WinnfieldX/CyberDropDownloader/releases/tag/1.5.4

Try this. This will have proper handling for that HTTP response.

**Comment by Jules-WinnfieldX** [comment]
nevermind, gimme a few hours

**Comment by Jules-WinnfieldX** [comment]
https://github.com/Jules-WinnfieldX/CyberDropDownloader/releases/tag/1.5.6

Best I can do is add a delay to when things are retried in the case of a 429 error. That's what I've done here. You seem to only be downloading 1 item at a time. If you're also downloading on your browser that could be why you were having the issue. Bunkr only allows 2 simultaneous downloads currently
