### ISSUE TITLE
[FEATURE]  Add "https://cyberfile.me/"

### ISSUE THREAD

**Issue by piperpuple1** [Jules-WinnfieldX/CyberDropDownloader#363]
Hi, you can add "https://cyberfile.me/" to the list of Supported Link Types, when i add link to the file.TXT tell me "is not supported currently"

**Comment by Jules-WinnfieldX** [comment]
It's already supported, you likely just need to update your installation: https://github.com/Jules-WinnfieldX/CyberDropDownloader/wiki/Frequently-Asked-Questions#how-to-update
