### ISSUE TITLE
[FEATURE] Redgifs support

### ISSUE THREAD

**Issue by Loidauk** [Jules-WinnfieldX/CyberDropDownloader#364]
**Is your feature request related to a problem? Please describe.**
Not able to download gifs from Redgifs. Ex. from SimpCity thread

**Describe the solution you'd like**
Able to download from Redgifs. 
If possible in HD.

**Additional context**

**Comment by Jules-WinnfieldX** [comment]
Redgifs support was removed as they changed how their media links are created to include a bunch of different hashes as well as the users IP. It likely won't be re-added

**Comment by Paramirage** [comment]
> Redgifs support was removed as they changed how their media links are created to include a bunch of different hashes as well as the users IP. It likely won't be re-added

Then please remove the site from the supported site in the website as it is misleading

**Comment by Jules-WinnfieldX** [comment]
> > Redgifs support was removed as they changed how their media links are created to include a bunch of different hashes as well as the users IP. It likely won't be re-added
> 
> Then please remove the site from the supported site in the website as it is misleading

That was over a year ago. It's been re-added.
