### ISSUE TITLE
[BUG] Coomer.party problem

### ISSUE THREAD

**Issue by RockinRonRobin** [Jules-WinnfieldX/CyberDropDownloader#369]
Can't download album from coomer. Here's the log.

[downloader.log](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/10951754/downloader.log)

**Comment by Jules-WinnfieldX** [comment]
You or Coomer failed the SSL handshake. Cyberdrop-DL doesn't allow insecure connections by default. Make sure you can connect to it securely normally, you aren't being blocked by them, and they aren't being blocked by an antivirus you are running. But this isn't an issue with the downloader itself, it's an issue on your end.
