### ISSUE TITLE
partial downloads in the downloads folder" What does that mean?[BUG]

### ISSUE THREAD

**Issue by Hellothere95** [Jules-WinnfieldX/CyberDropDownloader#370]
Everytime i try to download, it says "There are partial downloads in the downloads folder" What does that mean?

![image](https://user-images.githubusercontent.com/125223201/224585595-13662781-7640-4520-b695-72f652e0c7b3.png)

**Comment by ms6676749** [comment]
It means what it says. Some downloads are incomplete. Try searching for "*.part" files to get an idea which files did not finish downloading.
