### ISSUE TITLE
Re: Redownloading Full Albums

### ISSUE THREAD

**Issue by schade5** [Jules-WinnfieldX/CyberDropDownloader#375]
Hi Jules,

I am no coder and am trying to redownload an album that I previously downloaded to get the previous and updated stuff. Thinking that the album would be redownloaded in full, I deleted the old stuff, but no CyberDropDownloader doesn't download any of the stuff that I just deleted. 

I understand this feature is put in to prevent redownloading the same files over and over again, but since I deleted the previous files, I will need to redownload the whole album.

Is there a workaround for this or something I can do to fix this?

**Comment by Jules-WinnfieldX** [comment]
You can set ignore_history in the config.yaml file to true (as well as apply_config) and it will ignore the history and redownload whatever links you give it.
