### ISSUE TITLE
downloader.py — No such file or directory

### ISSUE THREAD

**Issue by Canis1Majoris** [Jules-WinnfieldX/CyberDropDownloader#38]
Getting this error 
./downloader.py': [Errno 2] No such file or directory

Can't see. this file in releases

**Comment by Jules-WinnfieldX** [comment]
It's in the source code zip.

**Comment by Jules-WinnfieldX** [comment]
Sorry. With the new version you need the new start file. The name has changed to main.py

**Comment by Jules-WinnfieldX** [comment]
Oh, I didn't change the mac file.

**Comment by Jules-WinnfieldX** [comment]
https://github.com/Jules-WinnfieldX/CyberDropDownloader/releases/tag/2.1.1
I'm tired haha. Here you go.

**Comment by Canis1Majoris** [comment]
Thanks! Moved on but still some errors :( 
Is putme.ga still supported?
