### ISSUE TITLE
[BUG] Remove special symbols from download path

### ISSUE THREAD

**Issue by yokkkoso** [Jules-WinnfieldX/CyberDropDownloader#388]
**Describe the bug**
Some services support special characters in titles like "\n" "\t", and when using the separate-posts option, a syntax error is throwing when creating a folder. This can be fixed with replacing all this symbols in download path to space

**To Help Reproduce**
Steps to help reproduce the behavior:
1. Find post with \t or \n symbol (This for example https://kemono.party/patreon/user/16112298/post/62642285)
2. Try to download It

**Setup Information**
 - OS: Windows 11 22H2
 - Cyberdrop Downloader Version:  4.0.92

**Comment by Jules-WinnfieldX** [comment]
Fixed in 4.0.95
