### ISSUE TITLE
[SSL: CERTIFICATE_VERIFY_FAILED]

### ISSUE THREAD

**Issue by Canis1Majoris** [Jules-WinnfieldX/CyberDropDownloader#39]
Is putme.ga still supported?  
![image](https://user-images.githubusercontent.com/79000976/144754331-9e215eb6-0c77-47cc-bdd4-d700d6f63885.png)

**Comment by Jules-WinnfieldX** [comment]
It is... The new connection system I'm using seems to cause a fuss on mac. Looking for a fix that isn't just disabling ssl verification.

**Comment by Jules-WinnfieldX** [comment]
Try this one: https://github.com/Jules-WinnfieldX/CyberDropDownloader/releases/tag/2.1.2

**Comment by Canis1Majoris** [comment]
You're incredibly fast! Testing )

**Comment by Canis1Majoris** [comment]
OMG! Finally! Thank you so much!
