### ISSUE TITLE
 why simpcity login isn't working or am i doing it wrong? 

### ISSUE THREAD

**Issue by ghost** [Jules-WinnfieldX/CyberDropDownloader#391]
i'm kinda new so it's confusing

**Comment by Jules-WinnfieldX** [comment]
I need more info than this, at the very least, the downloader.log file and what you are trying to do.

**Comment by infantgladvin** [comment]
> I need more info than this, at the very least, the downloader.log file and what you are trying to do

First i copied the page link from simpcity and pasted my link on my comment prompt after cyberdrop-dl but throws errors 
i tired login and password too but it still throws error

**Comment by Jules-WinnfieldX** [comment]
how did you add the username and password

**Comment by infantgladvin** [comment]
i added like this --simpcity-password xxxxxx --simpcity-username xxxxxx
*link* but this method only works on comment prompt not the url page and
started start windows batch file

**Comment by Jules-WinnfieldX** [comment]
So put your credentials in the config file and set apply config to true.

**Comment by infantgladvin** [comment]
Thanks, I'll check it out.
