### ISSUE TITLE
[FEATURE] How do I adjust the download location?

### ISSUE THREAD

**Issue by rvanny** [Jules-WinnfieldX/CyberDropDownloader#393]
How do I adjust the download location?

I've tried adjusting this line from main.py;

    parser.add_argument("-o", "--output-file", type=Path, help="folder to download files to", default="/Users/r......"

But it still downloads files to my Downloads folder.

How do I fix this?

**Comment by Jules-WinnfieldX** [comment]
You shouldn't be running from python files either way, you should be running it from a start script or command line pip install as outlined in the readme.

You'd use the -o followed by a directory in command prompt.
`cyberdrop-dl -o "C:/Downloads/"`

Or by changing it in the config.yaml file and enabling Apply Config (true)

**Comment by rvanny** [comment]
> true

This worked thanks!
