### ISSUE TITLE
jpg.fish updated their domain to jpg.fishing

### ISSUE THREAD

**Issue by TheDoctor40** [Jules-WinnfieldX/CyberDropDownloader#395]
Seems like jpg.fish changed their domain to jpg.fishing. Downloader now tries to scrape, finishes scraping, but doesn't start downloading. Tried on a different uploaded photo as well, same result. Tried using a different service to check (cyberdrop), that works fine, so seems to be specific to jpg.fishing.

Don't know if it'll help, but I will attach the downloader.log file for the album I'm trying to download.

[downloader.log](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/11110179/downloader.log)

**Comment by Jules-WinnfieldX** [comment]
fixed 4.0.97
