### ISSUE TITLE
[BUG] Erome only first page being download, if page number passed in url, it throws error

### ISSUE THREAD

**Issue by abhishek-notes** [Jules-WinnfieldX/CyberDropDownloader#397]
**Describe the bug**
The first page videos for erome are being downloaded properly, but for any other page, it gives the error : 

`Error: https://www.erome.com/Loove69_com?page=2`

Attached download.log file
[downloader.log](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/11115659/downloader.log)

**To Help Reproduce**
Pick any page from erome website on browser and add URL in url.txt file, and run the cyberdrop-dl using python

Eg URL : https://www.erome.com/Loove69_com?page=2

**Setup Information**
 - OS: Mac OS
 - Cyberdrop Downloader Version # 4.0.97

**Downloader.log file**
Included

**Comment by Jules-WinnfieldX** [comment]
I'll get to this, it'll just be a bit.

**Comment by abhishek-notes** [comment]
Great Jules, really appreciate it! Also great work with the whole thing!

**Comment by abhishek-notes** [comment]
Hi Jules, hope you are well, just wanted to follow up if you had time to look into this. Thanks a lot in advance.

**Comment by Jules-WinnfieldX** [comment]
Sorry, haven't had a chance to. Been excessively busy in my personal life.

**Comment by abhishek-notes** [comment]
Oh, sure, no problem, I understand, have a look when you get some time. Thanks :)

**Comment by Jules-WinnfieldX** [comment]
Will be added in 4.1.11 later today.
