### ISSUE TITLE
Confirmation when rip is done.

### ISSUE THREAD

**Issue by goodboi69** [Jules-WinnfieldX/CyberDropDownloader#4]
Please add a confirmation at the end of the ripping process so that we know what we ripped is done.

**Comment by Jules-WinnfieldX** [comment]
Hey, there already is a confirmation. "Finished - Press enter to exit"

Is there something different you were thinking of, or a change you'd suggest to that?

**Comment by goodboi69** [comment]
I didn't get a confirmation on completion. It just sat there with the cursor blinking for 4 hours. When I tried to re-rip the link. It gives a confusing completion message: "Press enter to quit". Perhaps change the wording to that as well?

**Comment by Jules-WinnfieldX** [comment]
The exact string on the 1.0.4 and 1.0.5 release, and I'm pretty sure one or two more prior to that is "Finished. Press enter to quit." You can see it at the bottom of the code in downloader.py [here](https://github.com/Jules-WinnfieldX/CyberDropDownloader/blob/master/downloader.py). I can't comment on the blinking cursor, but there is a completion message already that has "Finished" in the text.

**Comment by goodboi69** [comment]
I downloaded the new v1.0.5 and it gives me the completion message now. But now it doesn't tell you what is downloading it just says "downloading...".

**Comment by Jules-WinnfieldX** [comment]
Correct, you can see the commit information here regarding that change. 
https://github.com/Jules-WinnfieldX/CyberDropDownloader/commit/ace16fbefa303895a3ce5b785640f639f9cf4570

I'm still trying to get the formatting of the data output how I want it, until then it's going to be like this.

**Comment by Jules-WinnfieldX** [comment]
> I'm still trying to get the formatting of the data output how I want it, until then it's going to be like this.

Any time I try and get the formatting proper using a process lock the entire program breaks. Or swapping the entire program to use threads and thread locks. For some reason doing so causes an exception to not function and therefor the program doesn't trip a restart on a file download. It just spits out an empty file as if the download was complete. 

Without having a lock, I don't want to have print statements ("Downloading X") as the unclean output of prints going onto the same line upsets me.

I'm trying.
