### ISSUE TITLE
"We've stored the partial result and will retry"

### ISSUE THREAD

**Issue by mohsinmumtazm** [Jules-WinnfieldX/CyberDropDownloader#40]
When trying to download multiple folders, the download hangs and then everything stops with this error that I have attached in the file.
[Error.txt](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/7660761/Error.txt)

**Comment by Jules-WinnfieldX** [comment]
Can you upload the logs.log from that failed run?

**Comment by mohsinmumtazm** [comment]
[logs.log](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/7661280/logs.log)
This is the log, as for failed run, I will try to reproduce the error

**Comment by Jules-WinnfieldX** [comment]
Just confirming, you are on the latest version of Cyberdrop Downloader (2.1.2) as I took the URLs you are trying to scrape out of your log and I haven't been able to reproduce.

What OS are you using?

**Comment by mohsinmumtazm** [comment]
Yes I am on 2.1.2, and I was also not able to reproduce this error by scaping the same 53 links again

**Comment by Jules-WinnfieldX** [comment]
I would assume this was likely a result of a server issue on Cyberdrop's part.

**Comment by Jules-WinnfieldX** [comment]
If you run into more issues, feel free to open another issue or reopen this one. But as it's working for you currently I am going to close this one.
