### ISSUE TITLE
[FEATURE] How do I change the location where all the main operating files are being stored?

### ISSUE THREAD

**Issue by rvanny** [Jules-WinnfieldX/CyberDropDownloader#400]
How do I change the location where all the main files are being stored. For example, the URLs.txt, config.yaml, the download logs. If I move the cyberdrop downloader folder, these files seem to always reappear back in main User folder for my computer. I would rather these files be somewhere else on my computer, because they are rather out in the open. 

How do I move them?

**Comment by Jules-WinnfieldX** [comment]
The config file, or command line options, read through the wiki here on the GitHub
