### ISSUE TITLE
Downloader has trouble with hyphens in URL

### ISSUE THREAD

**Issue by anon1487** [Jules-WinnfieldX/CyberDropDownloader#41]
When an album uses hyphens, it is ignored when added to URL.txt.
Example: https://www.putme.ga/album/testing-hyphen-usage.rY6gJ

Command Line Message:
URLs.txt exists
Traceback (most recent call last):
  File "D:\OFFLOAD\Downloads\CyberDropDownloader-2.1.3\main.py", line 74, in <module>
    asyncio.get_event_loop().run_until_complete(main())
  File "C:\Users\[USER]\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "D:\OFFLOAD\Downloads\CyberDropDownloader-2.1.3\main.py", line 63, in main
    raise ValueError('No links found, check the URL.txt')
ValueError: No links found, check the URL.txt

D:\OFFLOAD\Downloads\CyberDropDownloader-2.1.3>pause
Press any key to continue . . 
[URLs.txt](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/7692478/URLs.txt)
.

**Comment by Jules-WinnfieldX** [comment]
Hey there, appreciate you creating the test album to show it. It isn't actually the hyphens. It's the 'www.'

https://github.com/Jules-WinnfieldX/CyberDropDownloader/releases/tag/2.1.4

This should solve your issue.

**Comment by anon1487** [comment]
Thank you!  Glad you know what actually caused the issue.  Works great now!
