### ISSUE TITLE
[BUG] BUNKR error: 403

### ISSUE THREAD

**Issue by Kenneth-Rosenstroem** [Jules-WinnfieldX/CyberDropDownloader#411]
**Describe the bug**
I started having problems with bunkr today giving error: 403

**Setup Information**
 - OS: Windows 11
 - Cyberdrop Downloader Version # 4.0.99 

**Downloader.log file**
https://www.dropbox.com/s/51j5ghkmpmxxw3s/downloader.log?dl=0

Latest Python.

This occurs only on some bunkr folders, been successful with a few today, but most give this error.

Please advise.

**Comment by Jules-WinnfieldX** [comment]
should be fixed in 4.1.1

**Comment by Kenneth-Rosenstroem** [comment]
Thank you.
