### ISSUE TITLE
[BUG] Download failed with error: unicode encode error

### ISSUE THREAD

**Issue by NiicOw974** [Jules-WinnfieldX/CyberDropDownloader#412]
Hello, I encounter an error when I try to download a video with an acute accent in the name of this one.

Indeed when trying to download it fails with the error:
"UnicodeEncodeError: 'charmap' codec can't encode character \u0301 in position X: character maps to <undefined>"

I'm on windows 10.

**Comment by Jules-WinnfieldX** [comment]
can you upload the downloader.log file after you try for me?

**Comment by NiicOw974** [comment]
[downloader.log](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/11144372/downloader.log)
[error_example.txt](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/11144377/error_example.txt)
Error example show you error log in prompt (powershell)

**Comment by Jules-WinnfieldX** [comment]
Update to 4.1.1. It will fix the download issues you have. The unicode error is a separate error in the logging. I'll deal with it when I can

**Comment by NiicOw974** [comment]
How I can update to 4.1.1. The master release is in version 4.0.99.

Sorry I'm beginner on GitHub

**Comment by Jules-WinnfieldX** [comment]
Assuming you installed through a start script or through pip in the command prompt (one of these two is how you should be doing it) https://github.com/Jules-WinnfieldX/CyberDropDownloader/wiki/Frequently-Asked-Questions#how-to-update

**Comment by NiicOw974** [comment]
Thanks for your help.
