### ISSUE TITLE
[BUG] It seems to be skipping or failing every file on bunkr.la downloads.

### ISSUE THREAD

**Issue by rvanny** [Jules-WinnfieldX/CyberDropDownloader#413]
It was working very well when I using this to download bunkr.su files. But for some reason since bunkr.su got switched over to bunkr.la, none of my files seems to be downloading. I've tried manually downloading the files and I can do that no problem. For some reason the when I use the cyberdrop downloader it goes through every file, one by one, and either skips or fails to download them. This seems to be happening for all urls that I input. Sometimes, it skips them, other times it fails them.

Any feed back?

Here is an example; url was in the URLs.txt file, but instead of downloading the files it failed for all of them.
https://bunkr.la/a/JS6kIZNz

Here is an screen shot of the finished output.
<img width="468" alt="Screen Shot 2023-04-05 at 3 22 48 PM" src="https://user-images.githubusercontent.com/129000589/230224859-ca71baf4-99f7-4079-bc27-d3544169bb03.png">

**Comment by Jules-WinnfieldX** [comment]
https://github.com/Jules-WinnfieldX/CyberDropDownloader/wiki/Frequently-Asked-Questions#how-to-update

Update to 4.1.1

**Comment by rvanny** [comment]
Solved, thanks
