### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Kenneth-Rosenstroem** [Jules-WinnfieldX/CyberDropDownloader#418]
**Describe the bug**

Getting 403 on coomer

aiohttp.client_exceptions.ClientResponseError: 403, message='Forbidden', url=URL('https://coomer.party/onlyfans/user/vivianroseofficial')
2023-04-14 11:10:20,764:DEBUG:base_functions:base_functions.py:47:Error: https://coomer.party/onlyfans/user/vivianroseofficial
2023-04-14 11:10:20,764:DEBUG:Coomeno_Spider:Coomeno_Spider.py:147:403, message='Forbidden', url=URL('https://coomer.party/onlyfans/user/vivianroseofficial')
2023-04-14 11:10:20,764:DEBUG:base_functions:base_functions.py:47:Finished: https://coomer.party/onlyfans/user/vivianroseofficial

**Setup Information**
 - OS: [e.g. Windows 11]
 - Cyberdrop Downloader Version #4.1.01

**Downloader.log file**
https://www.dropbox.com/s/9exl0mkmyhyapk1/downloader.log?dl=0

Thanks for your hard work :)

**Comment by Jules-WinnfieldX** [comment]
403 is the Forbidden HTTP status response. You can google it for more information.

**Comment by Kenneth-Rosenstroem** [comment]
I know what it means.

The result is that CyberDropDownloader can't finish the cue.

| Files Complete: 0 - Files Skipped: 48 - Files Failed: 0 |

Checking for incomplete downloads
Purging empty directories
Finished downloading. Enjoy :)
*There are partial downloads in the downloads folder.*

No matter how many times I restart, the result is the same, 48 files can't
download.

/Best regards - Kenneth Rosenstrøm - Кенет Росенстрьом

Mobile: +359 879 070 429
Email: ***@***.***

**Comment by Kenneth-Rosenstroem** [comment]
And it continues, entering 6 fresh links, downloader just plain refuses to download anything.

Links:

https://coomer.party/onlyfans/user/vickyaisha
https://bunkr.la/a/12zzzMXW
https://bunkr.la/a/o3zE0jSv
https://bunkr.la/a/LjvvodfD
https://bunkr.la/a/Bfa8JXXh
https://bunkr.la/a/QiZjYYr4

Logfile:
https://www.dropbox.com/s/ftx1cfg6vn9gei8/downloader2.log?dl=0

Prompt:
| Files Complete: 0 - Files Skipped: 48 - Files Failed: 0 |

Checking for incomplete downloads
Purging empty directories
Finished downloading. Enjoy :)
There are partial downloads in the downloads folder.

No download folder was created as well.

**Comment by Jules-WinnfieldX** [comment]
And you'd know 403 isn't an issue for the downloader. It's an issue connecting to the website (which in this case still isn't the downloader). It's because both sites have turned on DDOS-Guard

**Comment by Kenneth-Rosenstroem** [comment]
Sure, and the sites check your browser client....downloader does not report back as a web browser if I understand it, thus a bug right. 

Just thought you could bypass that in the downloader, as the browsers do. 

Thanks for your time.

**Comment by Jules-WinnfieldX** [comment]
The program does report as a browser, in the headers. There is no way to bypass it. While it's not intended behavior, it's not a bug. It's a limitation.

**Comment by Kenneth-Rosenstroem** [comment]
Got it, thanks again.
The subject is closed from here, Guess we have to patiently wait for them to open up again.

**Comment by kazemaru64** [comment]
FYI I updated to 4.1.11 today and about 500/600 of my first downloads bunkr.la completed. Then this issue began for me when I tried again. I reverted to 4.1.01 and the issue seemingly has gone away. I was able to download the rest of those files plus a handful of files at another link from bunkr.la without issue.

I don't know enough about it to know why downgrading _might have_ resolved the issue

**Comment by Jules-WinnfieldX** [comment]
Downgrading won't change anything. Coincidence. Bunkr handling nor download handling was changed in any substantive way to affect it.
