### ISSUE TITLE
[FEATURE] Add Gofile support

### ISSUE THREAD

**Issue by DeepSeaOne** [Jules-WinnfieldX/CyberDropDownloader#42]
Quite a few posts use Gofile album links, which contain files that must be downloaded individually. Would be a nice addition to have Gofile support added

**Comment by Jules-WinnfieldX** [comment]
I've had this request a few times, and I'm not ruling it out. However, Gofile is a dynamic webpage and as such, I'd need to find a way to dynamically load content in the script. I might be mistaken about this, but from what I've seen this will require additional downloads by end users. I'll look back into this though and try and develop a working concept to see how easy it can be done.

**Comment by iLeeaal** [comment]
> Quite a few posts use Gofile album links, which contain files that must be downloaded individually. Would be a nice addition to have Gofile support added

Jdownloader2 works on gofile.

**Comment by Jules-WinnfieldX** [comment]
Added support
