### ISSUE TITLE
[FEATURE] Capability to specify user-agent

### ISSUE THREAD

**Issue by sonicshake** [Jules-WinnfieldX/CyberDropDownloader#420]
**Is your feature request related to a problem? Please describe.**
It occurred to me that some issues related to scraping some sites such may be helped by allowing a specific user-agent to be specified, such that the site is not able to easily distinguish an unattended user (cyberdrop-dl) from an attended one (me).

**Describe the solution you'd like**
Allow the http user-agent for all http client requests to be set/overridden in config.yaml.

**Additional context**
Some other scrapers have this feature for the specific reason that some sites match the authenticated user against a specific user-agent (i.e. browser version). I am not sure if this is relevant for the sites that cyberdrop-dl supports.

**Comment by Jules-WinnfieldX** [comment]
Will be included in next version release.
