### ISSUE TITLE
[FEATURE] Support for Nudostar

### ISSUE THREAD

**Issue by Loidauk** [Jules-WinnfieldX/CyberDropDownloader#426]
**Is your feature request related to a problem? Please describe.**
Can't scrape Nudostar forum.

**Describe the solution you'd like**
Support for Nudostar forum threads just like Simpcity.
As per UI it could seem to be based on the same or something similiar to Simpcity

**Additional context**
https://nudostar.com/forum/

**Comment by Jules-WinnfieldX** [comment]
4.1.16 includes nudostar forum support.
