### ISSUE TITLE
[FEATURE] Support For Onlyfans

### ISSUE THREAD

**Issue by FastAndreiiii** [Jules-WinnfieldX/CyberDropDownloader#427]
hello, maybe what I'm asking is a lot because I've seen all over github and downloading is very difficult with everything that exists at the moment, and I'd like it to be easier to download an onlyfans profile and if it could be compatible with the script your

**Comment by Jules-WinnfieldX** [comment]
I won't be doing this. 

Use either of these.
https://github.com/DIGITALCRIMINALS/OnlyFans
https://github.com/datawhores/ofscraper/
