### ISSUE TITLE
[BUG] Simpcity 403 error

### ISSUE THREAD

**Issue by LoneWolf993** [Jules-WinnfieldX/CyberDropDownloader#428]
**Fails to download simpcity threads**
Simpcity seems to have added a ddos protection which causes scraping to fail even with username and password

**To Help Reproduce**
Steps to help reproduce the behavior:
Try to download any thread from simpcity

**Screenshots**
![image](https://user-images.githubusercontent.com/66156681/232289592-330cd340-97d8-4a08-a5a2-52d341c4cd55.png)

**Setup Information**
 - OS: Windows 11
 - Cyberdrop Downloader Version 4.1.11

**Downloader.log file**
[downloader.log](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/11241769/downloader.log)

**Additional context**
I tried using another downloader and kind of got around the problem by logging in via an inbuilt browser, I guess this can be got around by using a cookie file.

**Comment by Jules-WinnfieldX** [comment]
As you said, it's due to DDOS-Guard. There is no patch or work around. It'll probably start working again in a few days.

**Comment by LoneWolf993** [comment]
> As you said, it's due to DDOS-Guard. There is no patch or work around. It'll probably start working again in a few days.

Is there any way to use a cookie file for the website?

**Comment by Jules-WinnfieldX** [comment]
not that I'm aware of.

**Comment by LoneWolf993** [comment]
I see. Any idea how long before it starts working again?

**Comment by Jules-WinnfieldX** [comment]
No way to know unfortunately

**Comment by SaulKriheli** [comment]
I can confirm I tried to scrape right now and it worked.
If I don't update this comment assume everything is working well.
