### ISSUE TITLE
[Question] Is there any way to see the links I scraped?

### ISSUE THREAD

**Issue by YEET1201** [Jules-WinnfieldX/CyberDropDownloader#429]
Is there any way to see the links I scraped fromthe forums like simpcity? I got it to work with a socialmediagirls post but the links did not get put into a new .txt file? Is this normal and what would happen if I closed the downloader? would I have to scrape the links from start again?

**Comment by Jules-WinnfieldX** [comment]
You can see what the program scraped in the log file.
