### ISSUE TITLE
Cant download with the command line

### ISSUE THREAD

**Issue by Mortem20** [Jules-WinnfieldX/CyberDropDownloader#43]
Hello I have tried to download the cyberdrop downloader in py but when I copy and paste the line: paru -Sy cyberdropdownloader-bin then py say Syntax Error and I dont know how to fix that. Can anybody say to me whats the issue? 
To me: I am not a every day python user so it can be that its a error from my side
![Screenshot (746)](https://user-images.githubusercontent.com/77106157/147565129-abe48f82-fee4-4005-b446-9490abbb658b.png)

**Comment by Jules-WinnfieldX** [comment]
You followed the arch linux instructions not the windows instructions. 

Just download from here: https://github.com/Jules-WinnfieldX/CyberDropDownloader/releases

and use the start.bat
