### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by jbsparrow** [Jules-WinnfieldX/CyberDropDownloader#431]
**Is your feature request related to a problem? Please describe.**
When using the `--skip-hosts` flag, the hosts will still show up during scraping.

**Describe the solution you'd like**
The host that is being skipped should not show up during scraping. Even if the hosts are immediately skipped, it causes confusion.

**Additional context**
<img width="572" alt="PowerShell 20-04-23 1143x70 0c8896d9-5531-482a-ae62-b199add4ad95" src="https://user-images.githubusercontent.com/56100195/233256127-fee14b12-1d6f-4f67-8a62-002b829780c8.png">

**Comment by Jules-WinnfieldX** [comment]
![image](https://user-images.githubusercontent.com/61347133/233256762-96c67ee8-be9c-4072-a93e-1449654fab61.png)
When picked up properly, the hosts are skipped. 

I'm unsure if the arguments work when calling the EXE like that.
