### ISSUE TITLE
[BUG] SimpCity 400 Error Bad Request

### ISSUE THREAD

**Issue by andzzzzz** [Jules-WinnfieldX/CyberDropDownloader#437]
Since upgrading to Kubuntu 23.04 I get: "ClientResponseError: 400, message='Bad Request'"

Traceback (most recent call last):
  File "/home/xxxx/.local/pipx/venvs/cyberdrop-dl/lib/python3.10/site-packages/cyberdrop_dl/crawlers/Xenforo_Spider.py", line 113, in fetch
    await self.simpcity.login(session, url, self.quiet)
  File "/home/xxxx/.local/pipx/venvs/cyberdrop-dl/lib/python3.10/site-packages/cyberdrop_dl/crawlers/Xenforo_Spider.py", line 54, in login
    text = await session.get_text(domain)
  File "/home/xxxx/.local/pipx/venvs/cyberdrop-dl/lib/python3.10/site-packages/cyberdrop_dl/client/client.py", line 37, in wrapper
    return await func(self, *args, **kwargs)
  File "/home/xxxx/.local/pipx/venvs/cyberdrop-dl/lib/python3.10/site-packages/cyberdrop_dl/client/client.py", line 87, in get_text
    async with self.client_session.get(url, ssl=self.client.ssl_context) as response:
  File "/home/xxxx/.local/pipx/venvs/cyberdrop-dl/lib/python3.10/site-packages/aiohttp/client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "/home/xxxx/.local/pipx/venvs/cyberdrop-dl/lib/python3.10/site-packages/aiohttp/client.py", line 643, in _request
    resp.raise_for_status()
  File "/home/xxxx/.local/pipx/venvs/cyberdrop-dl/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 1005, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 400, message='Bad Request', url=URL('https://simpcity.su/login')

**Comment by Jules-WinnfieldX** [comment]
What country are you in?

**Comment by andzzzzz** [comment]
Germany, but also tried Austria via vpn, but had the same issue.

**Comment by Jules-WinnfieldX** [comment]
Try again in a few hours and see if it's still a problem. It seems like the forum is undergoing maintenance and might be acting strangely

**Comment by andzzzzz** [comment]
Sadly, the error still persists

**Comment by Jules-WinnfieldX** [comment]
what happens if you open that login page in an incognito browser. Does it load properly without any input on your end

**Comment by andzzzzz** [comment]
Yes, i just tried librewolf and firefox private browsing and no issues here: 
![image](https://user-images.githubusercontent.com/74650667/234062733-c09bab54-d158-4621-93e0-83eaf1a1081c.png)

**Comment by Jules-WinnfieldX** [comment]
Try enabling config and changing the user_agent to whatever matches your browser. You can google it and it'll output whatever yours is.

**Comment by Jules-WinnfieldX** [comment]
do either of you use an anti-virus software?

**Comment by fadeinflames** [comment]
> do either of you use an anti-virus software?

clear vds in hetzner )

**Comment by Jules-WinnfieldX** [comment]
So this happens to some people on Ubuntu, Kubuntu, Windows 10, (probably more). Regardless of location, user_agent, or anti-virus. 

Lovely.

**Comment by the444xg** [comment]
Hey Jules, it seems to detect the script only on the login page. 
I was testing using a saved session cookie from before this protection was implemented and I'm able to scrap the first page of a thread, when it tries the next page it looses the session, i have no idea why...was just testing.
Maybe that gives you an idea on what to do.
Also the cookie idea i would be a good idea to minimize issues like this one in the future.
It  would be as simple as this using pickle:

```python
    try:
        with open(session_file, "rb") as f:
            cookies = pickle.load(f)
    except FileNotFoundError:
        cookies = None
    # Set up session and login
    cookiejar = aiohttp.CookieJar(quote_cookie=False)
    async with aiohttp.ClientSession(
        headers=headers,
        raise_for_status=True,
        cookie_jar=cookiejar,
        cookies=cookies,
    ) as session:
        # If cookies dont work, log in
        session = await login(session)
        # Save session
        if session:
            with open(session_file, "wb") as f:
                pickle.dump(session.cookie_jar.filter_cookies(
                    base_url.strip("/")), f)
```

**Comment by Jules-WinnfieldX** [comment]
> Hey Jules, it seems to detect the script only on the login page. I was testing using a saved session cookie from before this protection was implemented and I'm able to scrap the first page of a thread, when it tries the next page it looses the session, i have no idea why...was just testing. Maybe that gives you an idea on what to do. Also the cookie idea i would be a good idea to minimize issues like this one in the future. It would be as simple as this using pickle:
> 
> ```python
>     try:
>         with open(session_file, "rb") as f:
>             cookies = pickle.load(f)
>     except FileNotFoundError:
>         cookies = None
>     # Set up session and login
>     cookiejar = aiohttp.CookieJar(quote_cookie=False)
>     async with aiohttp.ClientSession(
>         headers=headers,
>         raise_for_status=True,
>         cookie_jar=cookiejar,
>         cookies=cookies,
>     ) as session:
>         # If cookies dont work, log in
>         session = await login(session)
>         # Save session
>         if session:
>             with open(session_file, "wb") as f:
>                 pickle.dump(session.cookie_jar.filter_cookies(
>                     base_url.strip("/")), f)
> ```

I've confirmed there is no new detection, and nothing has changed in Cyberdrop-DL's end. 

In regards to pickling cookies, this would probably be mostly pointless, as the expirations happen often before cyberdrop-dl even finishes, or they only last a few hours longer. 

This could be related to issues on SimpCity's end. But I have no way to verify as I can't recreate this for myself.

**Comment by the444xg** [comment]
I am using the same session cookie file for at least a month now. It still works like i said.

**Comment by Jules-WinnfieldX** [comment]
> I am using the same session cookie file for at least a month now. It still works like i said.

I understand that. However, it adds a level of complexity I don't want to touch or bother supporting. Dealing with cookies is a PITA.

**Comment by the444xg** [comment]
I understand, i just implemented this to test...to make it robust would take more work.
Anyways i think i got it working fully working after upgrading aiohttp to v3.8.4 https://github.com/aio-libs/aiohttp/releases/tag/v3.8.4
However it works only when i run with python3 start.py
Once i run setup.py build it stops working again and the binary also does not work

I tried multiple times, just clone master, change requirements to aiohttp v3.8.4 pip install -r requirements.txt and it works.

Hope it helps.

**Comment by Jules-WinnfieldX** [comment]
> I understand, i just implemented this to test...to make it robust would take more work. Anyways i think i got it working fully working after upgrading aiohttp to v3.8.4 https://github.com/aio-libs/aiohttp/releases/tag/v3.8.4 However it works only when i run with python3 start.py Once i run setup.py build it stops working again and the binary also does not work
> 
> I tried multiple times, just clone master, change requirements to aiohttp v3.8.4 pip install -r requirements.txt and it works.
> 
> Hope it helps.

Just to confirm, you're saying upgrading aiohttp fixed the issue for you?

I can update the requirements and put out a new version if that's the case.

**Comment by the444xg** [comment]
Yes. Using it right now with start.py.

No idea why the build does not work.

**Comment by Jules-WinnfieldX** [comment]
For those affected by this. 4.1.14 should hopefully fix it.

**Comment by Jules-WinnfieldX** [comment]
It seems to be an issue with Yarl 1.9.2 in conjunction with aiohttp.
