### ISSUE TITLE
possibility to download folders in putmega

### ISSUE THREAD

**Issue by keeskroket** [Jules-WinnfieldX/CyberDropDownloader#45]
When I want to download an putmega account and it has folders inside I'd like the program to download all those folders, it seems now it doesnt do that

**Comment by Jules-WinnfieldX** [comment]
This isn't forgotten, and is something I am debating on implementing along with individual file links.

**Comment by Jules-WinnfieldX** [comment]
Late but got around to this. See new release and read me.
