### ISSUE TITLE
[FEATURE] coomer.party dates

### ISSUE THREAD

**Issue by benniblot** [Jules-WinnfieldX/CyberDropDownloader#455]
**Is your feature request related to a problem? Please describe.**

I'm trying to deduplicate my files when scraping and a proper set date would do a lot to help me with it and also make it take less time.

**Describe the solution you'd like**

When downloading files from coomer.party dates (times) being downloaded with the files itself and then set for the creation/modification date

**Additional context**

![image](https://user-images.githubusercontent.com/47495914/236283482-9a76be04-9f9b-4c1e-b256-f49db9e5dd88.png)
![image](https://user-images.githubusercontent.com/47495914/236283525-319a6f22-727b-4241-a4e7-4849486ff5dd.png)

**Comment by Jules-WinnfieldX** [comment]
I won't be passing the dates through to the downloader like that, nor setting the created/modified date. 

What I will do is add the date to the folder title when using separate_posts.

**Comment by benniblot** [comment]
you mean every image from the same date gets put into a folder with the corresponding date in the name?

**Comment by Jules-WinnfieldX** [comment]
included in 4.2.1
