### ISSUE TITLE
[BUG] jpg.fishing fail

### ISSUE THREAD

**Issue by ungallama** [Jules-WinnfieldX/CyberDropDownloader#456]
Ive read the issue is fixed but Im on the latest update 4.1.25 and the issue is still here
Scrapping works and after that it fails to download all the files
other sites work fine
Here the log if it helps
[downloader.log](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/11400696/downloader.log)

**Comment by Jules-WinnfieldX** [comment]
I'm aware. It'll be fixed in the next update before the end of week.

**Comment by Jules-WinnfieldX** [comment]
Fixed in 4.2.1
