### ISSUE TITLE
"cyberdrop is not recognized as an internal command or external, an operable program or a batch file." [BUG]

### ISSUE THREAD

**Issue by rafashady** [Jules-WinnfieldX/CyberDropDownloader#461]
![imagem_2023-05-08_021623952](https://user-images.githubusercontent.com/32526083/236739825-bfcade1a-c4f5-4e68-96a6-a55baa26c138.png)
my cyberdrop stopped working and is giving this error message

**Comment by Jules-WinnfieldX** [comment]
https://github.com/Jules-WinnfieldX/CyberDropDownloader/wiki/Frequently-Asked-Questions#cyberdrop-dl-is-not-a-recognized-internal-command

I'm assuming you updated python, or something else and the paths didn't update. The easiest fix is to uninstall everything, all python versions, etc. Start from scratch.

**Comment by rafashady** [comment]
I found out that for some reason it only works with python version 3.10.4

**Comment by Jules-WinnfieldX** [comment]
3.10.4 is the recommended. It works with anything from 3.7-3.11
