### ISSUE TITLE
[BUG] Error when trying to scrape simpcity apparently not when specified page is given(Invalid IPv6 URL)

### ISSUE THREAD

**Issue by BdakColi** [Jules-WinnfieldX/CyberDropDownloader#464]
here is the log when no page is specified
[downloader.log](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/11478496/downloader.log)
and here is the log when page 2 is specified
[downloader.log](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/11478527/downloader.log)
which works fine, i just close mid scrape to upload the log,
simpcity is blocked in my country but i am connected to singapore through surfshark both time

**Comment by Jules-WinnfieldX** [comment]
This isn't an issue with the program, more likely an issue with what you have setup and it being blocked in your country. I'd recommend using a proxy over vpns for stuff like this.
