### ISSUE TITLE
[BUG]Issues relating to jpg(church/fish)

### ISSUE THREAD

**Issue by VisionProlonged** [Jules-WinnfieldX/CyberDropDownloader#467]
**Describe the bug**
The endpoints for jpg church have changed and show error 404 and 522 for valid url's. 

**To Help Reproduce**
Thread download from : [Thread Link](https://simpcity.su/threads/grinchie-puppiwii.22836/)
The numbered url's are taken from downloader.log along with the error codes and beneath them working urls with different endpoint.

<b>All links are NSFW</b>

For error 404's. 
1.https://simp4.jpg.fish/3b7852883a6061676.jpg
=>https://simp4.jpg.church/3b7852883a6061676.jpg

2.https://simp4.jpg.fish/2e9e5e4bba4e3125d.jpg 
=>https://simp4.jpg.church/2e9e5e4bba4e3125d.jpg

For error 522's.
1.https://simp2.jpg.fish/1125x1298_052dc25e2469931216b481055459df9f.jpg
=>https://simp4.jpg.fish/1125x1298_052dc25e2469931216b481055459df9f.jpg
=>https://simp2.jpg.church/1125x1298_052dc25e2469931216b481055459df9f.jpg

2.https://simp2.jpg.fish/1125x1284_59501778b092aaa8b2ef4ad90455ca15.jpg
=>https://simp4.jpg.fish/1125x1284_59501778b092aaa8b2ef4ad90455ca15.jpg
=>https://simp2.jpg.church/1125x1284_59501778b092aaa8b2ef4ad90455ca15.jpg

**Setup Information**
 - Fedora 37
 - Version : cyberdrop-dl 4.2.28

**Downloader.log file**
[downloader.log](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/11506124/downloader.log)

**Additional context**
The downloader.log file does not have the exact same url's (as in the issue) but exhibit the same problem.

**Comment by Jules-WinnfieldX** [comment]
Great bug report. Not sure how much of this is due to their website issues at the moment, and how much is things changing. The site itself has been inaccessible for me (up and down) over the last day-ish. I can't do anything till it's back up properly anyways.

**Comment by Jules-WinnfieldX** [comment]
I was wrong this is fixed in 4.2.29
