### ISSUE TITLE
[BUG] Many failed or Skipped

### ISSUE THREAD

**Issue by ZeroRaven23** [Jules-WinnfieldX/CyberDropDownloader#476]
In this case, it would be more to ask about why there can be so many failures/skipped like this.

![imagem_2023-05-23_192010722](https://github.com/Jules-WinnfieldX/CyberDropDownloader/assets/79873070/c92ecca0-473d-4621-a86f-3d4658291702)

**Comment by Jules-WinnfieldX** [comment]
Please follow the bug template. It's there for a reason. I need to see the downloader.log file.
