### ISSUE TITLE
[BUG] Many Files Skipped or Failed

### ISSUE THREAD

**Issue by ZeroRaven23** [Jules-WinnfieldX/CyberDropDownloader#477]
**Describe the bug**
In this case, it would be more to ask about why there can be so many failures/skipped like this.

**Screenshots**

**Setup Information**
 - OS: Windows 11
 - Cyberdrop Downloader Version 4.2.44

**Download
[downloader.log](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/11548906/downloader.log)

![image](https://github.com/Jules-WinnfieldX/CyberDropDownloader/assets/79873070/51016dbc-164a-4583-b610-e7a599b711f0)

**Comment by Jules-WinnfieldX** [comment]
Thank you. 

The skipped files are pretty much always files that you have downloaded in the past. You can tell the program to ignore history in the config if you wish to.

The failed files for you are bunkr server issues/maintenance, coomer/kemono rate limiting (accessing the site too much, too quickly), pixeldrain not allowing downloads for files over the api (too much traffic to those files, you can get around it with a premium pixeldrain account), and a lot of permission denied errors from E-Hentai (probably were scraped too long ago), or the servers are fucked.

**Comment by ZeroRaven23** [comment]
thank you so much, i was wondering <3
Anything come back here if you have other problems
