### ISSUE TITLE
Adding a download speed limiter to settings.py

### ISSUE THREAD

**Issue by ColouringPriest** [Jules-WinnfieldX/CyberDropDownloader#48]
Downloading multiple small files is not a problem, but when it's set to download large files, it tends to hog all the bandwidth and slowing my internet to a crawl.

**Comment by MitchPetersen** [comment]
Not something I've thought of. I will look into it.

**Comment by Jules-WinnfieldX** [comment]
Not something I've thought of, I will look into it.

**Comment by ColouringPriest** [comment]
Thank you. I'm sorry to say that I'm not good enough to do it myself, so this is appreciated.

**Comment by Jules-WinnfieldX** [comment]
Unfortunately I do not believe this to be a possibility. My best suggestion would be to schedule the downloads during off hours of usage.

**Comment by ColouringPriest** [comment]
Thank you for trying, I appreciate it.
