### ISSUE TITLE
[FEATURE] Limit cyberfile simutaneous downloads to 2

### ISSUE THREAD

**Issue by gibson-kim** [Jules-WinnfieldX/CyberDropDownloader#480]
**Is your feature request related to a problem? Please describe.**

Downloading an album or albums from cyberfile -- I must restart it again and again because while the first 2 files are being downloaded the other ones fail/get skipped due to cyberfile's simultaneous download restriction.

**Describe the solution you'd like**

Change this for immediate solution
Longer term solution -- give users easy way to limit simultaneous downloads by domain or in general. Or give an easy way to make cyberdrop automatically restart after 'finishing'.

**Comment by Jules-WinnfieldX** [comment]
4.2.49 limits it to 2.

The feature you are asking for already exists: https://github.com/Jules-WinnfieldX/CyberDropDownloader/wiki/Config-Options#max_concurrent_downloads_per_domain
