### ISSUE TITLE
[FEATURE] Stop downloads

### ISSUE THREAD

**Issue by qarkai** [Jules-WinnfieldX/CyberDropDownloader#483]
**Is your feature request related to a problem? Please describe.**
Not sure if this is bug or feature.
Now running can't be stopped except for Ctrl-C which causes KeyboardInterrupt exception. It's not handled and looks ugly. Moreover if I do this during actual download, cursor disappears until program restarted and finished successfully. I suspect `rich` hides cursor but it doesn't matter.

**Describe the solution you'd like**
I'd like to be able to stop running at any step without exception tracebacks or disappeared cursor or any other issues. Doesn't matter how I stop program: by standard `Ctrl-C` or some custom hotkey, e.g. `s`.

**Comment by Jules-WinnfieldX** [comment]
The keyboard exception should be properly caught. Not sure what to do about the hidden cursor, I haven't seen that before

**Comment by Jules-WinnfieldX** [comment]
Hmmm. It seems in order to get no tracebacks out of what I have written for this, 3.11 is required. I've also attempted a fix for the cursor issue, but not entirely sure if it works. I can push it in a commit, but I'll likely wait to push to pypi for a bit.

**Comment by Jules-WinnfieldX** [comment]
I'm wrong on my statement. I am running 3.11...

Downloader is throwing a lot of `RuntimeError: Event loop is closed.` errors upon keyboard interrupt. Not entirely sure currently how to contain those.

**Comment by Jules-WinnfieldX** [comment]
I'm spamming at this point, but latest commit should have the ability to handle both these issues. Going to close for now, unless you determine I'm mistaken.
