### ISSUE TITLE
[FEATURE] Optional check for incomplete downloads and empty directories

### ISSUE THREAD

**Issue by woopnar** [Jules-WinnfieldX/CyberDropDownloader#485]
**Is your feature request related to a problem? Please describe.**
I Have a lot of folders on my Downloads folder and that causes a very slow check for incomplete downloads and empty directories. Besides, that check is very disk demanding slowing other things running on my NAS.

**Describe the solution you'd like**
I would like an option on configs to skip those steps, showing that the current run left partial downloads is very helpful. I know I have part files on that folder I don't need 2 hours to know that.

**Additional context**
2023-06-01 17:06:47,210:DEBUG:base_functions:base_functions.py:54:Checking for incomplete downloads
2023-06-01 17:14:58,091:DEBUG:base_functions:base_functions.py:54:Purging empty directories
2023-06-01 18:57:42,295:DEBUG:base_functions:base_functions.py:54:Finished downloading. Enjoy :)

**Comment by Jules-WinnfieldX** [comment]
I will do this, it's at the bottom of my to do list though. It'd make a lot more sense to clear out that folder, you can easily do it with the optional sorting CDL has baked in.

**Comment by Jules-WinnfieldX** [comment]
This will be added in the next release (probably later today), it's implemented now, just not rolled out. Gonna close this for now.
