### ISSUE TITLE
[FEATURE] Google Drive support

### ISSUE THREAD

**Issue by Swearinbag** [Jules-WinnfieldX/CyberDropDownloader#487]
I've noticed that Google Drive isn't supported. Via this feature request I'd like to request for this to be added.

**Comment by Jules-WinnfieldX** [comment]
I've never considered this. I'll see how viable it is, if it is, I'll add it.

**Comment by Jules-WinnfieldX** [comment]
Google drive is a nightmare to support for me currently. So I'm going to say this is a no go for now.
