### ISSUE TITLE
[BUG] FileExistsError: [WinError 183]

### ISSUE THREAD

**Issue by Aliaksandr3by** [Jules-WinnfieldX/CyberDropDownloader#49]
FileExistsError: [WinError 183] Cannot create a file when that file already exists: "1855.download" -> "1855.jpg"

**Comment by Jules-WinnfieldX** [comment]
Can you upload your logs.log from that run?

**Comment by Aliaksandr3by** [comment]
you can try downloads the link of https://putmega.com/janise_10

**Comment by Jules-WinnfieldX** [comment]
So you've hit an extremely odd edge case. Before downloading starts, we check if that file already exists, we don't check again (currently) after the full download is complete and we go to rename the file (1855.download -> 1855.jpg). 

The album you linked has a ton of duplicate images in it, all with the same file names. The issue you've run into is that both downloads for 1855.jpg started at the same time, one finished before the other. Essentially before the download started the file didn't exist, when it finished, it already existed. I can put in a check for when renaming, but if you were to simply try and re-run the utility as is currently (without deleting the previous files downloaded), it should finish without issues.

This race condition is rare, and didn't happen for example when I downloaded that album. But I'll deal with it in a little bit.

**Comment by Aliaksandr3by** [comment]
I add code to your ones.
will  dublicate be ignored ?

```
try:


except Exception as e:
    logging.error(e)
    pass
```

**Comment by Jules-WinnfieldX** [comment]
Use this
https://github.com/Jules-WinnfieldX/CyberDropDownloader/releases/tag/2.2.1

**Comment by Aliaksandr3by** [comment]
I think it is working) thx
