### ISSUE TITLE
[FEATURE] File & Directory maximum name length config specifier

### ISSUE THREAD

**Issue by IsriusQQ** [Jules-WinnfieldX/CyberDropDownloader#491]
**Is your feature request related to a problem? Please describe.**
When using CyberdropDL to download files from Kemono, I use the 'separate_posts: true' config option and a bulk rename tool to rename the individual files using the directory's name, but sometimes the post's name is cut off early so I can't find the full name.

**Describe the solution you'd like**
It would be nice to be able to specify the min / max file name in the config.yaml file.

**Additional context**
Looking at previous posts I see feature Issue #16, if the file name length can't be adjusted I'm sorry to waste your time.

version 4.2.75 of Cyberdrop Downloader
I think I have both Python 3.11.4 and 3.10.10 installed, but I'm not sure how can I tell which cyberdrop DL is using? Does it matter?

**Comment by Jules-WinnfieldX** [comment]
max file and folder name lengths will be added in the next release. As a warning, this value doesn't account for filename iterations if name collisions are hit. '1.jpg', '1 (1).jpg'
