### ISSUE TITLE
[FEATURE] add download completion post-operation

### ISSUE THREAD

**Issue by dmcslt** [Jules-WinnfieldX/CyberDropDownloader#494]
**Is your feature request related to a problem? Please describe.**
Add post-download actions, such as: move to another path

**Describe the solution you'd like**
Provides an option to perform custom script actions

**Additional context**

**Comment by Jules-WinnfieldX** [comment]
This will be something I add in the future, when I have everything else padded down and working properly. 

it'll likely be linked a post-op script, .sh or .bat file and the program will run it after completion.

**Comment by Jules-WinnfieldX** [comment]
My above solution here really doesn't make much sense. Any post-op script, can easily be handled just like most people are already handling CDL, with a start file. You'd just edit it and add it in below what is already there. But for other things, CDL already has a post-op sorter build in, it just needs to be configured and enabled in the config or through CLI.
