### ISSUE TITLE
[BUG] Re-scraping does not get new files

### ISSUE THREAD

**Issue by richiema32** [Jules-WinnfieldX/CyberDropDownloader#496]
**Describe the bug**
Rerunning the script on past models I've scraped before does not scrap updated files. I have tried to utilise the ignore cache and ignore history addons but it still finished the scrap immediately and did not download any new files.

**To Help Reproduce**
Simply rerun the script accordingly 

**Setup Information**
 - Windows 10 Cybderdrop V.4.1.16

**Downloader.log file**
[downloader.log](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/11730642/downloader.log)

**Comment by Jules-WinnfieldX** [comment]
ignore_cache will rescrape posts on coomer, but it only caches posts that it has seen and scraped. If there are new posts, it scrapes them every run. There likely just aren't any new posts.

**Comment by richiema32** [comment]
Undortunately o

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by richiema32** [comment]
Unfortunately I've confirmed theres new posts as well as new links that I've added in there but it's not rescraping.

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Jules-WinnfieldX** [comment]
I'd need to see the download_history.sql file then, and a link to an example post.

**Comment by Jules-WinnfieldX** [comment]
Nevermind. It'd help if I read your post. Dude, you need to update Cyberdrop-DL. You are like 100 versions behind, and coomer changed.

**Comment by Jules-WinnfieldX** [comment]
https://github.com/Jules-WinnfieldX/CyberDropDownloader/wiki/Frequently-Asked-Questions#how-to-update

**Comment by richiema32** [comment]
Oh shit my bad, thanks for taking the time to respond. Appreciate it.

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Jules-WinnfieldX** [comment]
This happens a lot more than you'd think haha, no worries.
