### ISSUE TITLE
[BUG] Freeze when there's an error connecting to jdownloader

### ISSUE THREAD

**Issue by the444xg** [Jules-WinnfieldX/CyberDropDownloader#497]
**Describe the bug**
If a timeout occurs when connecting to the jdownloader api before start scraping, the program freezes.
Other errors like too many requests or authentication errors freezes the program as well.
It won't go past the Starting screen:
Starting Cyberdrop-DL
We are running version 4.2.94 of Cyberdrop Downloader

**To Help Reproduce**
Steps to help reproduce the behavior:
1. put an wrong authentication info to the jdownloader api
2. start the program with jdownloader enabled

**Setup Information**
 - OS: Ubuntu 22
 - Cyberdrop Downloader 4.2.94

**Downloader.log file**
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/aiorun.py", line 237, in new_coro
    await coro
  File "/usr/local/lib/python3.10/dist-packages/cyberdrop_dl/main.py", line 276, in director
    Scraper = ScrapeMapper(args, client, SQL_Helper, False, error_writer)
  File "/usr/local/lib/python3.10/dist-packages/cyberdrop_dl/scraper/Scraper.py", line 78, in __init__
    self.jdownloader = JDownloader(args['JDownloader'], quiet)
  File "/usr/local/lib/python3.10/dist-packages/cyberdrop_dl/scraper/JDownloader_Integration.py", line 23, in __init__
    self.jdownloader_agent = self.jdownloader_setup()
  File "/usr/local/lib/python3.10/dist-packages/cyberdrop_dl/scraper/JDownloader_Integration.py", line 35, in jdownloader_setup
    jd.connect(self.jdownloader_username, self.jdownloader_password)
  File "/usr/local/lib/python3.10/dist-packages/myjdapi/myjdapi.py", line 1215, in connect
    response = self.request_api("/my/connect", "GET", [("email", email),
  File "/usr/local/lib/python3.10/dist-packages/myjdapi/myjdapi.py", line 1401, in request_api
    raise (MYJDApiException.get_exception(error_msg["src"], error_msg["type"], msg))
myjdapi.exception.MYJDAuthFailedException:
	SOURCE: MYJD
	TYPE: AUTH_FAILED

**Additional context**
Maybe it's unrelated but during the download phase sometimes the program freezes when a file download timeouts.
It's rare but happens mostly with slower hosts.
In past versions it would just skip to the next file/album/thread

**Comment by Jules-WinnfieldX** [comment]
Will look into the JDownloader. 

The download freeze is something I know about, changes were made to allow large files to be able to download (removal of read timeouts), I need to find a way to change how it works for when no data is written. It's just a complicated problem I haven't figured out how to tackle yet, but it's the next thing I intend to do.

**Comment by the444xg** [comment]
The removal of read timeouts would explain the freezes when your internet connection reconnects? In older versions it would timeout and retry using the new/reestablished connection or just move on the the next file.
I mention it because if I remember correctly, an error to jdownloader auth would exit the program immediately as well.

Thanks for looking into it.

**Comment by Jules-WinnfieldX** [comment]
Yea, there's only a connection timeout now. After CDL connects, there are no longer any timeouts (in current form). I removed the read timeout (timeouts while reading data) as some files can take hours to download. So in current form, if cdl can connect, but isn't being fed data to start the download, or there is no error thrown from the connection, it freezes and there are no timeouts to break it out of that state.

Jdownloader handling has changed, but admittedly I didn't change it enough to justify testing it entirely. I'll look at it probably tomorrow.

**Comment by Jules-WinnfieldX** [comment]
jdownloader will be fixed in the next release. Testing out my fix for the freezing currently. Trying not to break things. Gonna close this for now.
