### ISSUE TITLE
[BUG] Can't install via pip on Linux

### ISSUE THREAD

**Issue by qarkai** [Jules-WinnfieldX/CyberDropDownloader#498]
**Describe the bug**
Can't install via `pip` on Linux if distro implements [PEP 668](https://peps.python.org/pep-0668/).
[Arch Linux](https://gitlab.archlinux.org/archlinux/packaging/packages/python/-/commit/547eee4deb54fda2a3892997145b57de37301c5d), [Debian](https://salsa.debian.org/python-team/packages/python-pip/-/blob/c3744ba06306335cd4ba68cfadd43d59bff5a9ac/debian/NEWS), [Fedora Linux](https://fedoraproject.org/wiki/Changes/PythonMarkExternallyManaged) and their derivatives already support it or going to.
Error looks like this
```sh
$ pip install cyberdrop-dl
error: externally-managed-environment
```
`Start Linux.sh` script is broken too since it uses `pip`.

I guess this script and README should be updated.

**To Help Reproduce**
Steps to help reproduce the behavior:
1. Use Linux distro which support PEP 668.
2. Try to install using pip under the hood.

**Setup Information**
 - OS: Arch Linux
 - Cyberdrop Downloader Version n/a

**Additional context**
Authors of PEP 668 [recommend](https://peps.python.org/pep-0668/#guide-users-towards-virtual-environments) using `pipx`.
Another option is using `--break-system-packages` flag but it's not recommended.

**Comment by Jules-WinnfieldX** [comment]
Readme has been updated with a note, and the start script for linux has been changed from pip3 to pipx
