### ISSUE TITLE
[BUG] Kemono/Coomer - The download of a profile gets stuck.

### ISSUE THREAD

**Issue by AboutToVanish** [Jules-WinnfieldX/CyberDropDownloader#499]
## When trying to download a Kemono/Coomer profile, there are three situations:
- The program gets stuck downloading a file and doesn't continue. 
- Sometimes the download doesn't start at all.
- Also, the download speed is very slow 153 kB/s. I have a 100Mbps internet connection. But I suppose this is an issue with the Kemono/Coomer server.

![image](https://github.com/Jules-WinnfieldX/CyberDropDownloader/assets/137119775/0794d9d9-a5c7-483e-a6ca-c6c54fb96505)

When reviewing the log, in some cases I get a "**_Too Many Requests_**" or "**_Bad Gateway_**" error.

**OS**: Windows 10 - 22H2 - 19045.3086
**CyberDropDownloader version**: 4.2.96

I attach the downloader.log file:
[downloader.log](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/11793783/downloader.log)

**Comment by Jules-WinnfieldX** [comment]
Coomer itself is facing a lot of web issues currently. After they are resolved, if the 429 - Too Many Requests error is still happening this can be revisited. Until then I'm going to close this, as it doesn't seem to be CDL related for the most part.
