### ISSUE TITLE
[FEATURE] Error checking (File Size Comparison)

### ISSUE THREAD

**Issue by Trinthakis** [Jules-WinnfieldX/CyberDropDownloader#50]
Is it possible to implement any error checking into the program?
Often from CyberDrop half the files will fail to properly download.
I know [gallery-dl](https://github.com/mikf/gallery-dl) compares file sizes to make sure they match, can something like this be added?

**Comment by Jules-WinnfieldX** [comment]
Hey, this is already a feature that exists and is working in the program. https://github.com/Jules-WinnfieldX/CyberDropDownloader/blob/c2aebd93ad1e71a6b132e572445cfec0b3ae5888/utils/downloaders.py#L103-L129

When connections close (which is a common issue with Cyberdrop), we write the partial file (what we've already downloaded), then retry and continue from the point where it left off. You'll see these partial files as .download files when a download fails. If the end file downloaded is only a partial file, that'd be an it would be an issue with Cyberdrop itself or the source files. 

As always though, make sure you are on the latest version.
