### ISSUE TITLE
[Help] Mac

### ISSUE THREAD

**Issue by diegonoceli** [Jules-WinnfieldX/CyberDropDownloader#504]
**Describe the bug**
I downloaded the last relased version.
Using a macbook, after followed MAC USERS READ THIS.txt file, I tried to run the file Start Mac Alternate.command I received an erro.

ERROR: Could not build wheels for aiohttp, frozenlist, which is required to install pyproject.toml-based projects

**Screenshots**
<img width="566" alt="Captura de Tela 2023-07-05 às 16 07 51" src="https://github.com/Jules-WinnfieldX/CyberDropDownloader/assets/20445488/6e95e751-616e-4c47-9250-0f9aa98173e3">

**Setup Information**
 - OS: Mac Os 13.4.1 (22F82)
 - Cyberdrop Downloader Version v4

**Comment by Jules-WinnfieldX** [comment]
What about the regular mac start file?
