### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by kabirnarain** [Jules-WinnfieldX/CyberDropDownloader#506]
**Describe the bug**
Guys I am a decent tech-savvy user. However, you have made shit so complicated that even a decent user cannot follow how to install and use your software. Let alone basic users...

You dont have a clear installation method or approach for basic users.. Or if you only want to target advanced computer users then its your choice.

Have some basic isntallation guide a step by step guide. I have been struggling to upgrade / install my old version and unable to do so for last 2/3 weeks. I have installed many python versions I dont know how many shit distributions of yours and it just does not work for me.. Its highly frustating and hope you have a clue.;

I am giving up on your software as you guys have made it so bloody confusing and shit its better to look elsewhere..

**Setup Information**
 - OS: [e.g. Windows 10, Mac OS X Sierra, etc]
 - Cyberdrop Downloader Version #

**Downloader.log file**
You need to include the downloader.log file after the issue occurs. Majority of the time it's the only way to diagnose issues. 

**Additional context**

**Comment by Jules-WinnfieldX** [comment]
https://github.com/Jules-WinnfieldX/CyberDropDownloader#script-method

The script method couldn't get more basic. Maybe read the readme instead of being ignorant.

**Comment by kabirnarain** [comment]
Mate with all due respect I have gone through it. You guys are assuming people to be expert in Python and other computer operations. The script option does not work for me..

I am using windows 11. I have saved the Cyberdrop_DL.V4 on my computer, extracted the zip file. I run the windows.bat and nbothing happens... a command prompt opens and vanishes. 

I have tried the PIP install also,- there you directly start from Run pip3 install cyberdrop-dl in command prompt/terminal. Are you sure this will work for every user...???? No as you will have to probably go to the directory or path python and pip are installed... This is what I am saying.

I am not ignorant. I guess you are too arrogant to acknowledge that the methods to install and use the software are suitable for intermideate to advanced user. All I am suggesting is that have a very basic guide somewhere a step by step kind of User guide if possible. Rest You are the man.. Its your S/W. I cant do much but to be forced not to use it...

**Comment by Jules-WinnfieldX** [comment]
Mate. You are ignorant. You lack knowledge and understanding, it's what it means. It's not a bad thing. 

Instead of lashing out about it, you should come questioning, with a desire to understand. I have helped thousands of users install and operate the software. Instead, you come combative. 

I am well aware a project like this, with the vast amount of options can be confusing, not to mention pip and python itself. That's why the script method exists. There quite literally is no easier way. The instructions I provided encompass the steps in full. If it doesn't work for you, ask about it. There's likely an easy fix on your end. But instead you discount it as not working when it very likely is because you fucked up somewhere or missed something.

Learn some humility. 

So do you want me help, or do you want to fuck off?

**Comment by kabirnarain** [comment]
Mate I have tried my enough followed most of the articles and got frustated and wrote the comments. Honestly, I dont know Python. However, I have good understanding of systems, operating systems, programming language etc. Still I got confused and have not been able to sucessfully install the software. Hence, I had to make the comments I did, as I am not a rookie.

Sure, I am game lets try and hopefully one of us will acknowledge the shortcommings. I aint the one to fuck off, bring it on!! 
Let me know, I am good to go..

My Environment:

WIndows 11, 
Python 3.10 and 3.11 both installed
pip 23.0.1 from C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\site-packages\pip (python 3.10)

**Comment by Jules-WinnfieldX** [comment]
You don't need to know anything programming related to use something like this for one. But lets just move past that. 

Just run the start.bat file in cmd and post the full output.

**Comment by Jules-WinnfieldX** [comment]
Also, hold up. Did you install python from the windows store? Because that path looks like you installed it from the windows store.

**Comment by kabirnarain** [comment]
Yes, last installation of Python 3.11 is from WIndows store. Also, as I mentioned nothing happens when I run the batch file. However, I will try again. The command prompt opens up and vanishes. I even looked in task manager thinking its running in background.. I will try again. now.

**Comment by Jules-WinnfieldX** [comment]
So. Windows store installations won't work. As it says in the readme, you need to install python using the python installer from the python website, and you need to click the add to path checkbox during installation. You should uninstall what you have now and do that. 

When I say run the start.bat in cmd, I don't mean double clicking to run, I mean opening command prompt and running it inside there. You can drag and drop, or navigate to it with cd.

**Comment by kabirnarain** [comment]
Cyberdrop_DL.V4 this is the version I am using now. its extracted in C:\Downloads and running it from the same path

**Comment by kabirnarain** [comment]
Okay, so attachin the screenshot for you. The file runs and reaches to a point where it asks to press any key to continue but the moment you press a key it vanishes..
![Screenshot 2023-07-09 041336](https://github.com/Jules-WinnfieldX/CyberDropDownloader/assets/118614270/6f88f07f-6e2f-4e3b-8a55-360600371a12)

**Comment by Jules-WinnfieldX** [comment]
So as I said in the last message, you didn't click the add to path button during installation. You could go through the hassle of messing with environmental variables yourself, or you could do the easier thing of uninstalling the versions of python you have now, and redoing the installation using the installer from the python website linked in the readme. The picture on the readme shows the checkbox button you need to select.

**Comment by kabirnarain** [comment]
I think I did and also manually added the path in the System Environment file. But let me try to uninstall as you are suggesting and install again from the linked python site in readme.

Will update what happens next. ALso, I still maintain it is a bit confusing the initial installation and setup process, You may want to relook for basic and novice users...

**Comment by kabirnarain** [comment]
Mate its working now, all smiles you have no clue....I cant tell you how releived and happy I am. Your software is being used a a managed filetransfer for me. I have been using cyberdrop for more than 2 years now and suddenly I was unable to use it. 

Also, appreciate you on a personal level. I am not sure if you are the CEO or Founder, but I know for sure this is your baby, One cannot defend and support better than how you did today, I salute you. Its a reflection of our and your teams hardwork and the confidence you have in what you've built!!

Thanks a ton, and a few Coffees are on your way Mate!!

**Comment by Jules-WinnfieldX** [comment]
Cyberdrop itself is basically dead (both the website and downloads), wish I could change the name of this tool at this point, but it's basically cemented in stone (almost 1 million total downloads, should hit that next week). 

It's just me doing this, I don't have any direct relation with any of the sites the tool supports. I'm just some guy and this is my pet project I've been making and building better for almost 3 years. After so much time, I get a bit jaded on what people say, but always here to support and help people through issues. I don't really get anything out of it beyond the kindness of strangers donations.
