### ISSUE TITLE
[FEATURE] Auth proxys

### ISSUE THREAD

**Issue by Fackym** [Jules-WinnfieldX/CyberDropDownloader#507]
There is already proxy support but not for authenticated proxy's

**Describe the solution you'd like**
Support for password and user authenticated proxy's

**Comment by Jules-WinnfieldX** [comment]
Authentication credentials can be passed in proxy URL:

session.get("http://python.org",
            proxy="http://user:pass@some.proxy.com")

see here: https://docs.aiohttp.org/en/stable/client_advanced.html?highlight=proxy#proxy-support
