### ISSUE TITLE
[BUG] check_for_partial_files_and_empty_dirs flag is ignored and is treated as True always

### ISSUE THREAD

**Issue by SethBodine** [Jules-WinnfieldX/CyberDropDownloader#509]
**Describe the bug**

The argument --check-for-partial-files-and-empty-dirs appears to be ignored (or not being referenced correctly), resulting in the purge_dir function being called via main.py.

**To Help Reproduce**

The following approaches have been tried:
- --check-for-partial-files-and-empty-dirs False
- --check-for-partial-files-and-empty-dirs=False
- --check-for-partial-files-and-empty-dirs 0
- change check_for_partial_files_and_empty_dirs in cyberdrop_dl/base_functions/config_schema.py from True to False and not specifying the argument

Execute CyberDropDownloader with one of above approaches and purge_dir will still execute.

Can confirm latest version is being run

**Setup Information**
 - OS: Ubuntu
 - Deployment: git clone https://github.com/Jules-WinnfieldX/CyberDropDownloader.git
 - Python: v3 with virtualenv
 - exe: python3 start.py
 - version: 4.2.135

**Comment by Jules-WinnfieldX** [comment]
You'd also need to change apply_config to true in the config, it'll overwrite any command args you pass though, you'd need to use only the config for configuration. 

Going to leave this open until the arg is fixed.
