### ISSUE TITLE
Idea / Feature: Add cyberdrop album ID to downloaded folder name

### ISSUE THREAD

**Issue by Alexowo** [Jules-WinnfieldX/CyberDropDownloader#51]
This is helpful for if more than one folder / album link has the same name.

**Comment by Jules-WinnfieldX** [comment]
I've been mulling over this idea. I don't want to do this by default. I could add it as an option in the settings to include the album id. Acceptable?

**Comment by Jules-WinnfieldX** [comment]
I've added the option to add the ID to folder names in 2.3.4
