### ISSUE TITLE
[BUG] purge_dir function in base_functions.py called by main.py does not execute against the specific album folder

### ISSUE THREAD

**Issue by SethBodine** [Jules-WinnfieldX/CyberDropDownloader#510]
**Describe the bug**

When purge_dir is executed it attempts to clean up args['Files']['output_folder'] but does not factor in that files are downloaded into a album folder.

In the event that the output folder contains other files and folders this clean-up can take several hours instead of several seconds.

**Workaround**

The workaround would be to specify the output folder as a subfolder, which would then result in a more restricted scope, but would add an additional folder into the tree (not ideal).

**Setup Information**

OS: Ubuntu
Deployment: git clone https://github.com/Jules-WinnfieldX/CyberDropDownloader.git
Python: v3 with virtualenv
exe: python3 start.py
version: 4.2.135

**Additional context**

An additional (https://github.com/Jules-WinnfieldX/CyberDropDownloader/issues/509) has been raised to address the flag to disable the clean-up process.

**Comment by Jules-WinnfieldX** [comment]
This is correct, but not a bug. It is intended behavior. The output folder is not meant to be a storage folder
