### ISSUE TITLE
[FEATURE] Use default system dirs

### ISSUE THREAD

**Issue by qarkai** [Jules-WinnfieldX/CyberDropDownloader#512]
**Is your feature request related to a problem? Please describe.**
Applications should keep their cache/config files in default system directories. E.g. for Linux there is [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) which tells that cache should be stored in `~/.cache/<app>` dir, config files in `~/.config/<app>` dir and so on.
I guess other OSes have their own rules, see https://github.com/platformdirs/platformdirs#example-output

**Describe the solution you'd like**
Save `config.yaml` in user config dir, `download_history.sqlite` in user data dir, `downloader.log` in user log dir, `internal_variable_cache.yaml` in user cache dir and so on.
Add new flag, e.g. `--portable` to keep all files in current run dir.
If files exist in current run dir they should override files in user dirs, i.e. do not open `/user_config_dir/config.yaml` if `config.yaml` exists in current dir.

**Comment by Jules-WinnfieldX** [comment]
Should probably be done, it'll be a while before I get around to wanting to tackle this though.
