### ISSUE TITLE
[BUG] Program stops before it starts.

### ISSUE THREAD

**Issue by L3sb0t** [Jules-WinnfieldX/CyberDropDownloader#523]
The program is started normally via the Start Windows file. I'm prompted to upgrade Cyberdrop. Then a list of requirments that've already been met read out, like so:
M:\Cyberdrop D3>pip install --upgrade cyberdrop-dl
Requirement already satisfied: cyberdrop-dl in c:\users\MyName\appdata\local\programs\python\python37-32\lib\site-packages (4.2.162)
Requirement already satisfied: aiofiles>=0.8.0 in c:\users\MyName\appdata\local\programs\python\python37-32\lib\site-packages (from cyberdrop-dl) (0.8.0)
Requirement already satisfied: aiohttp>=3.8.4 in c:\users\MyName\appdata\local\programs\python\python37-32\lib\site-packages (from cyberdrop-dl) (3.8.4)
Requirement already satisfied: aiolimiter>=1.1.0 in c:\users\MyName\appdata\local\programs\python\python37-32\lib\site-packages (from cyberdrop-dl) (1.1.0)
Requirement already satisfied: aiorun>=2023.7.2 in c:\users\MyName\appdata\local\programs\python\python37-32\lib\site-packages (from cyberdrop-dl) (2023.7.2)
Requirement already satisfied: asyncpraw>=7.7.0 in c:\users\MyName\appdata\local\programs\python\python37-32\lib\site-packages (from cyberdrop-dl) (7.7.0)
Requirement already satisfied: beautifulsoup4>=4.12.2 in c:\users\MyName\appdata\local\programs\python\python37-32\lib\site-packages (from cyberdrop-dl) (4.12.2)
Requirement already satisfied: certifi>=2023.5.7 in c:\users\MyName\appdata\local\programs\python\python37-32\lib\site-packages (from cyberdrop-dl) (2023.5.7)
Requirement already satisfied: myjdapi>=1.1.7 in c:\users\MyName\appdata\local\programs\python\python37-32\lib\site-packages (from cyberdrop-dl) (1.1.7)
Requirement already satisfied: PyYAML>=6.0 in c:\users\MyName\appdata\local\programs\python\python37-32\lib\site-packages (from cyberdrop-dl) (6.0)
Requirement already satisfied: rich>=13.4.2 in c:\users\MyName\appdata\local\programs\python\python37-32\lib\site-packages (from cyberdrop-dl) (13.4.2)
Requirement already satisfied: setuptools>=68.0.0 in c:\users\MyName\appdata\local\programs\python\python37-32\lib\site-packages (from cyberdrop-dl) (68.0.0)
Requirement already satisfied: tqdm>=4.65.0 in c:\users\MyName\appdata\local\programs\python\python37-32\lib\site-packages (from cyberdrop-dl) (4.65.0)
Requirement already satisfied: yarl>=1.9.2 in c:\users\MyName\appdata\local\programs\python\python37-32\lib\site-packages (from cyberdrop-dl) (1.9.2)
Requirement already satisfied: attrs>=17.3.0 in c:\users\MyName\appdata\local\programs\python\python37-32\lib\site-packages (from aiohttp>=3.8.4->cyberdrop-dl) (22.1.0)
Requirement already satisfied: charset-normalizer<4.0,>=2.0 in c:\users\MyName\appdata\local\programs\python\python37-32\lib\site-packages (from aiohttp>=3.8.4->cyberdrop-dl) (2.1.1)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\users\MyName\appdata\local\programs\python\python37-32\lib\site-packages (from aiohttp>=3.8.4->cyberdrop-dl) (6.0.2)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in c:\users\MyName\appdata\local\programs\python\python37-32\lib\site-packages (from aiohttp>=3.8.4->cyberdrop-dl) (4.0.2)
Requirement already satisfied: frozenlist>=1.1.1 in c:\users\MyName\appdata\local\programs\python\python37-32\lib\site-packages (from aiohttp>=3.8.4->cyberdrop-dl) (1.3.3)
Requirement already satisfied: aiosignal>=1.1.2 in c:\users\MyName\appdata\local\programs\python\python37-32\lib\site-packages (from aiohttp>=3.8.4->cyberdrop-dl) (1.3.1)
Requirement already satisfied: asynctest==0.13.0 in c:\users\MyName\appdata\local\programs\python\python37-32\lib\site-packages (from aiohttp>=3.8.4->cyberdrop-dl) (0.13.0)
Requirement already satisfied: typing-extensions>=3.7.4 in c:\users\MyName\appdata\local\programs\python\python37-32\lib\site-packages (from aiohttp>=3.8.4->cyberdrop-dl) (4.4.0)
Requirement already satisfied: importlib_metadata<5.0,>=1.3 in c:\users\MyName\appdata\local\programs\python\python37-32\lib\site-packages (from aiolimiter>=1.1.0->cyberdrop-dl) (4.13.0)
Requirement already satisfied: aiosqlite<=0.17.0 in c:\users\MyName\appdata\local\programs\python\python37-32\lib\site-packages (from asyncpraw>=7.7.0->cyberdrop-dl) (0.17.0)
Requirement already satisfied: asyncio-extras<=1.3.2 in c:\users\MyName\appdata\local\programs\python\python37-32\lib\site-packages (from asyncpraw>=7.7.0->cyberdrop-dl) (1.3.2)
Requirement already satisfied: asyncprawcore<3,>=2.1 in c:\users\MyName\appdata\local\programs\python\python37-32\lib\site-packages (from asyncpraw>=7.7.0->cyberdrop-dl) (2.3.0)
Requirement already satisfied: update-checker>=0.18 in c:\users\MyName\appdata\local\programs\python\python37-32\lib\site-packages (from asyncpraw>=7.7.0->cyberdrop-dl) (0.18.0)
Requirement already satisfied: soupsieve>1.2 in c:\users\MyName\appdata\local\programs\python\python37-32\lib\site-packages (from beautifulsoup4>=4.12.2->cyberdrop-dl) (2.3.2.post1)
Requirement already satisfied: requests in c:\users\MyName\appdata\local\programs\python\python37-32\lib\site-packages (from myjdapi>=1.1.7->cyberdrop-dl) (2.28.1)
Requirement already satisfied: pycryptodome in c:\users\MyName\appdata\local\programs\python\python37-32\lib\site-packages (from myjdapi>=1.1.7->cyberdrop-dl) (3.15.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\MyName\appdata\local\programs\python\python37-32\lib\site-packages (from rich>=13.4.2->cyberdrop-dl) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\MyName\appdata\local\programs\python\python37-32\lib\site-packages (from rich>=13.4.2->cyberdrop-dl) (2.14.0)
Requirement already satisfied: colorama in c:\users\MyName\appdata\local\programs\python\python37-32\lib\site-packages (from tqdm>=4.65.0->cyberdrop-dl) (0.4.6)
Requirement already satisfied: idna>=2.0 in c:\users\MyName\appdata\local\programs\python\python37-32\lib\site-packages (from yarl>=1.9.2->cyberdrop-dl) (3.4)
Requirement already satisfied: async-generator>=1.3 in c:\users\MyName\appdata\local\programs\python\python37-32\lib\site-packages (from asyncio-extras<=1.3.2->asyncpraw>=7.7.0->cyberdrop-dl) (1.10)
Requirement already satisfied: zipp>=0.5 in c:\users\MyName\appdata\local\programs\python\python37-32\lib\site-packages (from importlib_metadata<5.0,>=1.3->aiolimiter>=1.1.0->cyberdrop-dl) (3.15.0)
Requirement already satisfied: mdurl~=0.1 in c:\users\MyName\appdata\local\programs\python\python37-32\lib\site-packages (from markdown-it-py>=2.2.0->rich>=13.4.2->cyberdrop-dl) (0.1.2)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\MyName\appdata\local\programs\python\python37-32\lib\site-packages (from requests->myjdapi>=1.1.7->cyberdrop-dl) (1.26.12)
 
then this message appears:

M:\Cyberdrop D3>cyberdrop-dl
Running using command line arguments. If you are trying to use the config file, change 'Apply_Config' to True

and the program stops in its tracks. I've tried to run the file with the 'Apply_Config' at 'true' and in its default of 'false' but there's no difference. A URL on my URL list was https://simpcity.su/threads/ana-hilenna.13523/

OS: Windows 11 Home Version 10.0.22621 Build 22621

Downloader.log file:
2023-07-19 08:02:44,641:DEBUG:selector_events:selector_events.py:53:Using selector: SelectSelector
2023-07-19 08:02:44,642:DEBUG:aiorun:aiorun.py:162:Entering run()
2023-07-19 08:02:44,642:DEBUG:selector_events:selector_events.py:53:Using selector: SelectSelector
2023-07-19 08:02:44,642:DEBUG:aiorun:aiorun.py:249:Creating default executor
2023-07-19 08:02:44,643:ERROR:base_events:base_events.py:1608:Task exception was never retrieved
future: <Task finished coro=<run.<locals>.new_coro() done, defined at C:\Users\MyName\AppData\Local\Programs\Python\Python37-32\lib\site-packages\aiorun.py:209> exception=NotImplementedError()>
Traceback (most recent call last):
  File "C:\Users\MyName\AppData\Local\Programs\Python\Python37-32\lib\site-packages\aiorun.py", line 219, in new_coro
    await coro
  File "C:\Users\MyName\AppData\Local\Programs\Python\Python37-32\lib\site-packages\cyberdrop_dl\main.py", line 279, in director
    await clear()
  File "C:\Users\MyName\AppData\Local\Programs\Python\Python37-32\lib\site-packages\cyberdrop_dl\base_functions\base_functions.py", line 54, in clear
    clear_screen_proc = await asyncio.create_subprocess_shell('cls' if os.name == 'nt' else 'clear')
  File "C:\Users\MyName\AppData\Local\Programs\Python\Python37-32\lib\asyncio\subprocess.py", line 202, in create_subprocess_shell
    stderr=stderr, **kwds)
  File "C:\Users\MyName\AppData\Local\Programs\Python\Python37-32\lib\asyncio\base_events.py", line 1503, in subprocess_shell
    protocol, cmd, True, stdin, stdout, stderr, bufsize, **kwargs)
  File "C:\Users\MyName\AppData\Local\Programs\Python\Python37-32\lib\asyncio\base_events.py", line 463, in _make_subprocess_transport
    raise NotImplementedError
NotImplementedError

**Comment by Jules-WinnfieldX** [comment]
This issue might be caused because you are using a 32 bit version of python. Uninstall the version you have, and install 3.10.9, the 64 bit version of it.

**Comment by L3sb0t** [comment]
That worked; thanks! I don't know why the program was using an older version of Python as I had a newer version it was defaulting to before.
