### ISSUE TITLE
[Question] Retry Failed Downloads

### ISSUE THREAD

**Issue by hbednar** [Jules-WinnfieldX/CyberDropDownloader#525]
I have finished downloading all files but some have failed and there are a number of part files. 
I would like to retry just the ones that have failed, is this possible.

**Comment by Jules-WinnfieldX** [comment]
By running the same input links again, yes

**Comment by hbednar** [comment]
I am running it again but using --ignore-history as it skips everything otherwise. but it seems to be taking a while to sort  through the completed downloads and maybe even redownloading them before skipping

**Comment by Jules-WinnfieldX** [comment]
It's skipping everything otherwise as in the past it already downloaded the files you are trying to download. 

I'm not sure what you mean by your second statement.

**Comment by Jules-WinnfieldX** [comment]
If the file exists, and is the size expected, it won't redownload again. So just don't move any of the files, and keep re-running the links until you get all that you want downloaded
