### ISSUE TITLE
Ignore Cache and Ignore History Command

### ISSUE THREAD

**Issue by Shaquantina** [Jules-WinnfieldX/CyberDropDownloader#531]
The ignore cache and ignore history command are not working for me. I have tried to uninstall and install with python, and when i run the cyberdrop-dl command the amount of files I have to download decreases instead of increasing.

**Comment by Jules-WinnfieldX** [comment]
Both are working as intended. I think you have a misconception of what both of these commands actually do.

Ignore Cache ignores the cached page data for coomer and kemono. It doesn't have an effect here.

Ignore History tells the program to download any file it finds while scraping **even if** it was downloaded previously in the past.

**Comment by Shaquantina** [comment]
I understand but it isn't working for me

**Comment by Shaquantina** [comment]
First it stated 0 of 2500 files completed, now its states "0 of 1554 Files Completed"

**Comment by Jules-WinnfieldX** [comment]
That doesn't have to do with either of these things, that would have to do with Cyberdrop-DL **finding** less files to download.
