### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by haayfe** [Jules-WinnfieldX/CyberDropDownloader#532]
Getting the error "'cyberdrop-dl' is not recognized as an internal or external command, operable program or batch file" when attempting to download something this morning. Everything is updated and I am not sure what is causing this bug. Any help appreciated.

**Comment by Jules-WinnfieldX** [comment]
https://github.com/Jules-WinnfieldX/CyberDropDownloader/wiki/Frequently-Asked-Questions#cyberdrop-dl-is-not-a-recognized-internal-command

uninstall any python versions you have, start from scratch. Make sure to click the add to path button on install. Python doesn't overwrite itself if you try to "update" it. Just stick with whatever version you install (you should install 3.10.9)
