### ISSUE TITLE
[BUG] Handling of character "&" in Filename URL

### ISSUE THREAD

**Issue by trdrdtrded** [Jules-WinnfieldX/CyberDropDownloader#534]
**Describe the bug**
It appears when scraping from Bunkr, the "&" in the filename URL is being replaced with "&amp;" ultimately causing a 404 error. 

**To Help Reproduce**
Steps to help reproduce the behavior:
1. See attached log for specific URL.
2. Run cyberdrop-dl with the Bunkr album URL.
3. cyberdrop-dl will try to download two files but cant due to the ampersand substitution.
I have not tested against other sites.

**Setup Information**
 - OS: [Linux computer 5.15.0-69-generic
 - Cyberdrop Downloader Version 4.2.169

[downloader.log](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/12216960/downloader.log)

**Comment by Jules-WinnfieldX** [comment]
4.2.171
Just released, fixes this.
