### ISSUE TITLE
[BUG] SimpCity login using session cookie not working

### ISSUE THREAD

**Issue by ductai199x** [Jules-WinnfieldX/CyberDropDownloader#539]
**Describe the bug**
I was not able to scrape the SimpCity forum using the new login session feature.

**To Help Reproduce**
Steps to help reproduce the behavior:
1. Using Google Chrome, log in to SimpCity using username and password
2. Open Cookie Editor, grab value for the `xf_session` field of the cookie for `simpcity.su`
3. Use this value with command `cyberdrop-dl.exe --simpcity-xf-session-cookie <cookie>`
4. Get Error
5. Open downloader.log and see:
```
2023-08-08 19:07:53,861:DEBUG:Xenforo_Spider:Xenforo_Spider.py:209:Error encountered while handling ...
Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\cyberdrop_dl\crawlers\Xenforo_Spider.py", line 206, in fetch
    await self.forums[domain].login(session, url, parse_spec, self.quiet)
  File "C:\Python39\lib\site-packages\cyberdrop_dl\crawlers\Xenforo_Spider.py", line 120, in login
    raise FailedLoginFailure()
cyberdrop_dl.base_functions.error_classes.FailedLoginFailure: Failed login.
```

**Setup Information**
 - OS: Windows 10
 - Cyberdrop Downloader Version #4.2.178

**Comment by Jules-WinnfieldX** [comment]
I will not be offering walk through support for this. It is confirmed working through both config and CLI. The only thing I can tell you is to wrap it in quotes, and only paste the actual value itself, not `value: CODE`. You just want the code.

This will be made easier in the upcoming rewrite.

**Comment by ductai199x** [comment]
I did exactly that, copying only the value itself, wrapped it in quotes but it's not working for me for some reason. Also, I tried the command both normally and with a VPN but that didn't work either

**Comment by Jules-WinnfieldX** [comment]
Try using one of the two browsers I mention in the FAQ

**Comment by ductai199x** [comment]
yep, I tried both Google Chrome and Firefox. I did say in my original report that I used Chrome.

**Comment by Jules-WinnfieldX** [comment]
The only other advice I can give you, is make you aren't exporting the *.simpcity

**Comment by vajdao** [comment]
Also, make sure that config.yaml 's first line:

`Apply_Config: **false**`
is set to **true**
It's very easy to miss this one out ;)

**Comment by ClonedBoy** [comment]
I think it might be what I was experiencing with other browser other than Firefox.

https://github.com/Jules-WinnfieldX/CyberDropDownloader/issues/536#issuecomment-1670432674

**Comment by vajdao** [comment]
I noticed that the OP exported `xf_session` cookie string instead of `xf_user`, despite it being mentioned [here](https://github.com/Jules-WinnfieldX/CyberDropDownloader/wiki/Frequently-Asked-Questions#how-do-i-get-the-xf_session-cookie-value-for-simpcity-forum-scraping), however the documentation has changed since then, so the OP had different information back then (xf_session) - [this](https://github.com/Jules-WinnfieldX/CyberDropDownloader/wiki/Frequently-Asked-Questions/1d2ae6437edccc0aa309b87adf125641cfb5a819) revision in the documentation version prooves him/her.

**Comment by ClonedBoy** [comment]
You are correct. With the current version and the use of xf_user, it seems to be working normally with the exported value from Brave - at least for me. xf_session not required at the moment, haven't had that issue with the value anymore.

**Comment by vajdao** [comment]
> You are correct. With the current version and the use of xf_user, it seems to be working normally with the exported value from Brave - at least for me. xf_session not required at the moment, haven't had that issue with the value anymore.

I'm glad to hear that. I'm very happy I could help. Happy datahoarding, enjoy :)
