### ISSUE TITLE
Rename the folder

### ISSUE THREAD

**Issue by Keshiraze** [Jules-WinnfieldX/CyberDropDownloader#54]
Greetings.
I would like to know if in this latest version (currently 2.3.2) it is possible to change the name of the folder that is created when saving the gallery, let me explain.

Currently the gallery folder is left with the name of the gallery (example: "my gallery") and in previous versions it was left with the following syntax my gallery _40 files __ 34.38 MB_ _ CyberDro

I clarify, I have tried to do it by editing the file utils/downloaders.py but unfortunately I don't know how to program in python and I couldn't.

I really appreciate the reply.

PDTA: I hope you understand, my English is not very good and it works with google translator.

**Comment by Jules-WinnfieldX** [comment]
Currently this is not supported by the program. The gallery folder however shouldn't have the "40 files __ 34.38 MB _ CyberDro" in the name. It should just be named as "my gallery".

**Comment by Jules-WinnfieldX** [comment]
I'll potentially add this as a setting in the next update.

**Comment by Jules-WinnfieldX** [comment]
I've added the option to add the ID to folder names in 2.3.4
