### ISSUE TITLE
[BUG] Unable to Scrape From Specific Thread on SimpCity

### ISSUE THREAD

**Issue by SuperPoorMan** [Jules-WinnfieldX/CyberDropDownloader#540]
Scraping this thread here: https://simpcity.su/threads/narga_lifestream-narga-aoki.35185/#post-174456
Yields error messages in the console while running the bat file in windows 10.

However scrapping a thread such as this website here: https://simpcity.su/threads/pumpur_mur.35564/
Yields 0 issues and runs perfectly fine. 

To reproduce? Just put both of these lovely links into the URL.txt file, run the bat file, and you will see the first link spit out an error, and the second link will begin scrapping ever single post, link, and image within the thread.

Not entirely sure why, but it only affects that specific thread and no the other mentiond. Could it be an issue with the hyphens? Not sure, I don't know how to code, but know how to spot an error :)

Using Cyberdrop 4.2.178
Windows 10 22H2

**Comment by Jules-WinnfieldX** [comment]
Please resubmit this using the template, and include the downloader.log file to showcase errors you are referring to.

**Comment by Jules-WinnfieldX** [comment]
Eh, I won't be that mean, just upload the downloader.log after running the first link

**Comment by Jules-WinnfieldX** [comment]
Or a copy paste of said error messages

**Comment by SuperPoorMan** [comment]
Wanna know something really funny? It works now... I don't know why. Also I thought what I wrote was sufficent enough, sorry for the lack of detail
