### ISSUE TITLE
[FEATURE] add --user-agent flag

### ISSUE THREAD

**Issue by the444xg** [Jules-WinnfieldX/CyberDropDownloader#541]
**Is your feature request related to a problem? Please describe.**
When using just the cli without relying on config.yml I'm unable to set the user agent.

**Describe the solution you'd like**
Add the flag --user-agent so we are able to set it using the cli

**Comment by Jules-WinnfieldX** [comment]
The upcoming version will overwrite config values with command prompt values. config will also apply for default. So I'm going to close this for now, and it can be revisited later if need be.
