### ISSUE TITLE
[BUG] Not getting old fish/church files

### ISSUE THREAD

**Issue by jodoze** [Jules-WinnfieldX/CyberDropDownloader#542]
**The bug**
The program gets "fish" links from albums that used to be .church, which now are .fish, but the download files are still .church.
I think it used to work in previous releases.

**To Help Reproduce**
Steps to help reproduce the behavior:
1. Add an album or file that used to be .church.
2. Example:
REFERER
https://jpg.fish/img/pic-285.YXymqI
Errored download URL
https://simp1.jpg.fish/images/2022/03/15/pic-285.jpg
_Desired working URL_
https://simp1.jpg.church/images/2022/03/15/pic-285.jpg
3. Either run through command line or bat.
 
**Setup Information**
 - OS: Windows 10
 - Cyberdrop Downloader Version **4.2.178**

**Downloader.log file**
[downloader.log](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/12307928/downloader.log)

**Comment by Jules-WinnfieldX** [comment]
Seems they've made a change or have server problems. simp 1&3&5 have a faster .fish counterpart. But it doesn't seem to be connectable currently. 

4.2.179 is going out now that'll fix this.
