### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by BubiBalboa** [Jules-WinnfieldX/CyberDropDownloader#548]
**Is your feature request related to a problem? Please describe.**
The "Finished downloading" screen informs the user about completed, skipped and failed downloads but there is no information about the download folder or URL so it's not easy to act on the provided information. 

**Describe the solution you'd like**
Please add the download folder and download URL to the "finished downloading" screen.

**Comment by Jules-WinnfieldX** [comment]
Both of these are either provided by the user, or they are in the directory you are running Cyberdrop-DL in. Beyond that, there is no limit to the amount of URLs you can run through Cyberdrop-DL at one time. it is not feasible to print them all on the finish screen.
