### ISSUE TITLE
Simpcity error

### ISSUE THREAD

**Issue by 011110001** [Jules-WinnfieldX/CyberDropDownloader#549]
**Describe the bug**
After the update that changed xf_session to xf_user in simpcity I'm getting errors to download any topic

**To Help Reproduce**
Command line: cyberdrop-dl --simpcity-xf-user-cookie {my token}

**Screenshots**

**Setup Information**
 - OS: Win10 22H2
 - Cyberdrop Downloader Version 4.2.184

**Downloader.log file**
[downloader.log](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/12328182/downloader.log)

**Comment by Jules-WinnfieldX** [comment]
286477

**Comment by Jules-WinnfieldX** [comment]
I cannot help with cookie related issues. It is not a fault of the program. Switch to using the config or generate a new cookie with a different browser and try again.
