### ISSUE TITLE
[FEATURE] arm64-v8a/armeabi-v7a library support

### ISSUE THREAD

**Issue by thesuperfatcat** [Jules-WinnfieldX/CyberDropDownloader#55]
During the installation with termux for the phone, requirements.txt libraries have installation problems for arm CPUs. 
Maybe I didn't install properly, but I still wanted to ask.

**Comment by Jules-WinnfieldX** [comment]
This isn't possible. This wasn't designed for use on a phone, and isn't possible to make work on a phone with the libraries used.
