### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by AdyTZa619** [Jules-WinnfieldX/CyberDropDownloader#551]
After download more files from coomer and jpg1.su   i think they blocke my ip adress  , i tray to connect with vpn and work  fine

**Comment by AdyTZa619** [comment]
![image](https://github.com/Jules-WinnfieldX/CyberDropDownloader/assets/137645268/75f345ae-6dcb-4e45-a8d0-8ea950b0fd87)
Error from simpcity without VPN

**Comment by AdyTZa619** [comment]
![image](https://github.com/Jules-WinnfieldX/CyberDropDownloader/assets/137645268/3002403a-a5a0-4b72-87b3-bf9f384125e2)
With VPN work , but i cant download with Cyberdrop_DL.V4

**Comment by AdyTZa619** [comment]
![image](https://github.com/Jules-WinnfieldX/CyberDropDownloader/assets/137645268/0881dbaa-a416-4889-99bf-5610fc566e70)

**Comment by Jules-WinnfieldX** [comment]
> ![image](https://user-images.githubusercontent.com/137645268/260709898-3002403a-a5a0-4b72-87b3-bf9f384125e2.png) With VPN work , but i cant download with Cyberdrop_DL.V4

Then you need a system wide VPN. Not a browser VPN. Try something like Mullvad.
