### ISSUE TITLE
[FEATURE] Scrape specific page on forum

### ISSUE THREAD

**Issue by eskaviam** [Jules-WinnfieldX/CyberDropDownloader#553]
**Is your feature request related to a problem? Please describe.**
On my use case, I'm using it on multiple cloud server, either I'm blind or there is no yet feature that allow to only scrape until x page of the forum.

**Describe the solution you'd like**
An option to scrape/download to x page of forum

in my use case so I can run multiple cloud server for faster scraping & downloading
example:
cloud server 1 is scraping from page 1 to 2
cloud server 2 is scraping from page 3 to 4
etc

**Comment by Jules-WinnfieldX** [comment]
This is too niche a feature, and honestly there is no good way to implement this from a user perspective (that I find acceptable). I'd recommend instead focusing on scraping different forum threads on different servers.
