### ISSUE TITLE
[QUESTION] How can I get this to run on jailbroken iOS?

### ISSUE THREAD

**Issue by nicebro3** [Jules-WinnfieldX/CyberDropDownloader#557]
I have a jailbroken iOS device that has a terminal and Python installed but whenever I run cyberdrop-dl, I run into numerous errors that I have no idea how to solve.

Here is a screenshot: 
![image](https://github.com/Jules-WinnfieldX/CyberDropDownloader/assets/142936407/9dc2a717-ab95-42fe-9e4c-48418fdfc45e)

Looking at it, it says I need cchardet which I have tried installing, but when installing I run into another issue with that as well:

![E956C866-1247-4417-9241-465B76CAE59F](https://github.com/Jules-WinnfieldX/CyberDropDownloader/assets/142936407/7dc2a79b-8de2-42ef-987e-3a1bd5afc59e)

Would you happen to know how to fix these issues to allow iOS to run cyberdrop-dl? Thank you.

**Comment by Jules-WinnfieldX** [comment]
I do not offer support for running via mobile devices. The program itself does not have implicit support for mobile devices. 

You do not seem to have a complete python installation however.
