### ISSUE TITLE
[BUG] Returning Errors for bunkrr.su links

### ISSUE THREAD

**Issue by hershdna** [Jules-WinnfieldX/CyberDropDownloader#559]
Returning "Forbidden" error messages for bunkrr.su links, says to be a client issue but the links are active and can be downloaded from the site. 

[downloader.log](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/12450276/downloader.log)

**Comment by Jules-WinnfieldX** [comment]
This isn't a bug.
