### ISSUE TITLE
[FEATURE] Change JDownloader download dir

### ISSUE THREAD

**Issue by BosonHair** [Jules-WinnfieldX/CyberDropDownloader#561]
**Is your feature request related to a problem? Please describe.**
JDownloader2 files are in a different directory.

**Describe the solution you'd like**
Would be great to add to the config to change the jdownloader directory for downloader if files have been sent there to match the cyberdrop one.

**Comment by Jules-WinnfieldX** [comment]
I'm going to change it to match CDL's, however it won't be configurable on it's own (it'll always match download dir for cdl)
