### ISSUE TITLE
Ability to setup multiple download directories in URL file

### ISSUE THREAD

**Issue by BosonHair** [Jules-WinnfieldX/CyberDropDownloader#564]
I was hoping there'd be some functionality for cyberdrop to put downloads in multiple folders driven by a config/url file similar to gallery-dl. 

In gallery-dl you can add this to your config/text files for it to know to add the below links in the directory:
-G base-directory ="OUTPUT DIR"

**Comment by Jules-WinnfieldX** [comment]
You can already do this. Just create multiple config files, each with different download directories, and run them separately using `--config-file`

https://github.com/Jules-WinnfieldX/CyberDropDownloader/wiki/Command-Line-Arguments#arguments
