### ISSUE TITLE
[BUG] Bunkr scrape error

### ISSUE THREAD

**Issue by darkwind1q** [Jules-WinnfieldX/CyberDropDownloader#565]
Downloader instantly spit out error message when attempting to download from Bunkr, but is fine for other sites
1. https://bunkrr.su/a/2PpIDUGD

2. Here is the output with the error message
   
![2](https://github.com/Jules-WinnfieldX/CyberDropDownloader/assets/103967333/ad702dde-41c5-4a43-914b-5450a39c4ca2)

[downloader.log](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/12480431/downloader.log)

I am on the latest version on windows 10

**Comment by Jules-WinnfieldX** [comment]
It's due to DDOS-Guard. There is no fix.
