### ISSUE TITLE
[BUG] SimpCity is no longer functional due to DDoS-Guard protection

### ISSUE THREAD

**Issue by CodexScript** [Jules-WinnfieldX/CyberDropDownloader#567]
**Describe the bug**
After a maintenance period last night, SimpCity is now using DDoS-Guard protection. When trying to scrape a simpcity URL, the downloder immediately fails.

**To Help Reproduce**
Steps to help reproduce the behavior:
1. Attempt to scrape any SimpCity forum URL

**Screenshots**
![image](https://github.com/Jules-WinnfieldX/CyberDropDownloader/assets/67811878/e41aad52-e2c4-48ac-9cb9-e60160ad15fd)

**Setup Information**
 - OS: Windows 11
 - Cyberdrop Downloader Version 4.2.194

**Downloader.log file**
[downloader.log](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/12516238/downloader.log)

**Additional context**
There is another project, [FlareSolverr](https://github.com/FlareSolverr/FlareSolverr) that functions as a proxy, which is able to solve Cloudflare and DDoS-Guard captchas. It does not behave like a normal proxy, and as such, cannot be applied in the config.yaml. Implelenting this may solve this issue.

**Comment by Jules-WinnfieldX** [comment]
Simpcity has been utilizing DDOS-Guard since it’s creation (essentially). This also isn’t a bug. There is no work around.

you’ll just have to keep trying and wait for ddos-guard to settle down.

**Comment by Jules-WinnfieldX** [comment]
I will look into providing flaresolverr support though
