### ISSUE TITLE
[FEATURE] add possibilities for parsing links from the URLs.txt

### ISSUE THREAD

**Issue by Aliaksandr3by** [Jules-WinnfieldX/CyberDropDownloader#57]
Sometimes I want copy/paste text from a forum, but it has a "trash", and I must clean links with REGX or something as that.
I think will be fine if your program will be it by itself.

![image](https://user-images.githubusercontent.com/11432724/155461907-0a2079c6-63dd-4616-b029-fafe67ff3881.png)

**Comment by Jules-WinnfieldX** [comment]
I actually quite like this idea. It would also make the program more robust (probably). The urls.txt thing has needed an update for a while I just haven't decided where to take it. This will be a stepping stone.

**Comment by Aliaksandr3by** [comment]
you might create some think like "rawURLs.txt" (for raw text) and then, if this file exists, to parse clean URLs to "URLs.txt"

**Comment by Jules-WinnfieldX** [comment]
I'm just going to try and make a generic regex statement to cover urls.txt entirely. Currently being this:
`(?:http.*?)(?=('|$|\n|\r\n|\r|\"))`
Which should grab everything from http up until a "'" or '"' or until end of line, which should cover both cases. I just want to test a bit more to make sure that it's not going to have adverse effects.

**Comment by Aliaksandr3by** [comment]
[URLs.txt](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/8130312/URLs.txt)

I taste it, and it has some error

**Comment by Jules-WinnfieldX** [comment]
(?:http.*?)(?=('|$|\n|\r\n|\r)|\"|\[) works in that case. The only download to this method is it captures duplicates. 
`'https://putmega.com/image/OAqoUu'`
`'https://s4.putmega.com/1817x2423_d950b526d07cb4b8a7b817cb0fb28314.jpg'`
These are the same image. The program will end up skipping the second one and it shouldn't cause issues. But there might be a race condition here. Haven't thought about it hard enough.

**Comment by Jules-WinnfieldX** [comment]
I've included this in 2.3.4
