### ISSUE TITLE
All Coomer, Kemono, SMG, and SC errors.

### ISSUE THREAD

**Issue by nrop359** [Jules-WinnfieldX/CyberDropDownloader#570]
**Describe the bug**
### my "start windows.bat" file has: 

"**_cyberdrop-dl
pause_**"

### I have a seperate "update.bat" file with:

"**_pip install --upgrade cyberdrop-dl
python.exe -m pip install --upgrade pip
pause_**"

When trying to scrape any amount of links from various places, none of them work, the scraping says starting, error, finished.

**To Help Reproduce**

I just use the start windows.bat file to start my scrape and it shows all links as started, error then finished

**Screenshots**

![Screenshot (66)](https://github.com/Jules-WinnfieldX/CyberDropDownloader/assets/144271454/4ad8766f-b64e-47bb-87aa-4f480c48f3d6)
![Screenshot (67)](https://github.com/Jules-WinnfieldX/CyberDropDownloader/assets/144271454/af41a83d-5fea-4f68-a598-54e40b561cbd)

**Setup Information**

Windows 10
![Screenshot (68)](https://github.com/Jules-WinnfieldX/CyberDropDownloader/assets/144271454/e7e7c865-dc8d-44e4-bcbc-71cea442c62e)

**Downloader.log file**

[downloader.log](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/12551649/downloader.log)

**Comment by Jules-WinnfieldX** [comment]
This isn't a bug with the program, it's an issue with your machine connecting to those hosts, or an SSL related issue on your machine. 

If you need a VPN to connect to those websites regularly, it isn't working.

**Comment by nrop359** [comment]
I don't use a VPN, and I don't know what any of this means, where would I even begin to look for a solution? 
Since I can still access the pages themselves just fine.
