### ISSUE TITLE
[BUG] cyberdrop.me subdomains don't work while the actual domain is perfectly fine

### ISSUE THREAD

**Issue by sohailoo** [Jules-WinnfieldX/CyberDropDownloader#571]
**Describe the bug**
when scarping cyberdrop.me for image it will give a link similar to this https://fs-05.cyberdrop.me/fakefilename.jpg which doesn't work and will give error code 522 ( that's a cyberdrop problem not the script), but the problem could be fixed by removing the subdomain 

**To Help Reproduce**
1- try to download a an image from any gallery for example  https://fs-03.cyberdrop.me/image%20(173)-mYBmvNLq.jpg
2- it will give you error 522 (a problem with cyberdrop host not the script) 
3- no remove the subdomain from the link https://cyberdrop.me/image%20(173)-mYBmvNLq.jpg
4- the image loads without problems and can be downloaded 

a fix to this would be to remove the subdomains after scarping the links to download. the script will have collected a bunch of links with different subdomains. https://fs-03.cyberdrop.me, https://fs-02.cyberdrop.me .... , before trying to download the links the script should remove all the subdomains. this way it will download without problems and won't get stuck trying to connect to a host that doesn't work

**Comment by Jules-WinnfieldX** [comment]
While Cyberdrop itself is fucked and should be considered dead. You are right. 4.2.197 going up now.
