### ISSUE TITLE
[BUG] coomer.party time and date capture

### ISSUE THREAD

**Issue by jamr1167** [Jules-WinnfieldX/CyberDropDownloader#573]
**Describe the bug**
When downloading from coomer.party with the separate posts function enabled, it no longer prefixes the date and time of the post to the sub-folder.

**To Help Reproduce**
Steps to help reproduce the behavior:
run with coomer.party url in url.txt

**Screenshots**

**Setup Information**
 Windows 10
Cyberdrop Downloader Version 4.2.199

[downloader.log](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/12568630/downloader.log)

**Comment by c0d3m0nky** [comment]
Also happening to me
Ubuntu 22.04.2 LTS
Cyberdrop Version 4.2.199

**Comment by jamr1167** [comment]
coomer.party recently changed the display on their posts, it used to just have a date and time, now it has:  
Published: 2023-09-07 13:22:48
Imported: 2023-09

**Comment by Jules-WinnfieldX** [comment]
4.2.201
