### ISSUE TITLE
[BUG] bunkrr.su failing to scrape

### ISSUE THREAD

**Issue by TheDoctor40** [Jules-WinnfieldX/CyberDropDownloader#574]
**Describe the bug**
Seems like Bunkr has updated their domain again, this time to https://bunkrr.su/ . Ever since this change, scraping fails for this site, on any album I try. I do notice that bunkrr.su (with the double 'r') is not in the list of supported sites, only bunkr with the single 'r' is.
I've made it a habit to always run "pip install --upgrade" before a download to make sure I'm up to date.

**Setup Information**
 - OS: Windows 11
 - Cyberdrop Downloader Version #4.2.202

**Downloader.log file**
[downloader.log](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/12586461/downloader.log)

**Comment by Jules-WinnfieldX** [comment]
Bunkrr.su is supported. 

The supported domains text just hasn't been updated to explicity mention it.

It's failing because of DDOS-Guard.

**Comment by Jules-WinnfieldX** [comment]
There isn't anything wrong. It's due to the fact CDL doesn't use a browser. You either need to wait a few hours and try again, or download whatever it is manually.
