### ISSUE TITLE
[FEATURE] ImageFap Support

### ISSUE THREAD

**Issue by GarethFreeman** [Jules-WinnfieldX/CyberDropDownloader#575]
**Is your feature request related to a problem? Please describe.**
I have seen a lot of imagefap albums that I like but have nowhere to rip them consistently and would like some assistance with this.

**Describe the solution you'd like**
I would very much appreciate if you could add the site to the list of supported sites.

**Additional context**

**Comment by Jules-WinnfieldX** [comment]
Duplicate of https://github.com/Jules-WinnfieldX/CyberDropDownloader/issues/521
