### ISSUE TITLE
[BUG] Simpcity.st should be Simpcity.su

### ISSUE THREAD

**Issue by BosonHair** [Jules-WinnfieldX/CyberDropDownloader#576]
Somewhere simpcity.st changed to simpcity.su and I'm getting errors when trying to pull from them.

**Comment by Jules-WinnfieldX** [comment]
Simpcity.su has been supported for almost a year, you likely need to update if they aren't working.

**Comment by BosonHair** [comment]
Is pipx latest: 4.2.202 ?

**Comment by Jules-WinnfieldX** [comment]
Yes

**Comment by Jules-WinnfieldX** [comment]
If you are getting errors, I'd need to see the downloader.log file to tell you why.

**Comment by BosonHair** [comment]
I uninstalled and reinstalled. Will check that out if I see the error again. Thanks!
