### ISSUE TITLE
[BUG] Fapello.su "Error: javascript:void(0);"

### ISSUE THREAD

**Issue by notFaad** [Jules-WinnfieldX/CyberDropDownloader#579]
**Describe the bug**
When downloading from Fapello i'm provided with "Error: javascript:void(0);"

**To Help Reproduce**
Steps to help reproduce the behavior:
1. Describe the bug accurately.
3. Provide an example album that showcases it (if applicable) (Any fapello model with videos)
4. Make sure you are updated to the latest version to see if it's already fixed. (Done)

**Screenshots**
![Screenshot 2023-09-16 042231](https://github.com/Jules-WinnfieldX/CyberDropDownloader/assets/142156289/4cb483f6-561e-417c-beb9-cddb6f3cbdae)
![Screenshot 2023-09-16 042406](https://github.com/Jules-WinnfieldX/CyberDropDownloader/assets/142156289/68568818-216b-4aa0-a8fe-a6c4e177ea52)

**Setup Information**
 - OS: [Windows 10]
 - Cyberdrop Downloader Version [4.2.202]

**Downloader.log file**
[downloader.log](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/12634605/downloader.log)

**Additional context**
no Additional context.

**Comment by notFaad** [comment]
I think the program crawls all "div.content > div > a".
Images gives the url in href (Which works)
Videos gives a "javascript:void(0);" in href
Videos are connected to a saint.to site

**Comment by notFaad** [comment]
it can be fixed if you download the videos from saint.to

**Comment by Jules-WinnfieldX** [comment]
As Fapello scrapes from larger other sites that are already supported, I'm in no rush to fix this. It'll be fixed in the next major release, whenever that happens.

**Comment by Jules-WinnfieldX** [comment]
In V5
