### ISSUE TITLE
[FEATURE] add support for CATBOX

### ISSUE THREAD

**Issue by asdgif** [Jules-WinnfieldX/CyberDropDownloader#580]
It already has 'not supported' support so why not add genuine support please? haha

**Comment by Jules-WinnfieldX** [comment]
Any domain that isn't on an internal approved list will say it's not supported. I didn't add anything to say that specifically for that host.

**Comment by asdgif** [comment]
Oh, gotcha.
But, no plan to add support to it then?

**Comment by Jules-WinnfieldX** [comment]
It'll be added at some point if it can be, but I can't give an ETA.

**Comment by Jules-WinnfieldX** [comment]
If you'd still like this, please make a new feature request with the actual full link for the host (and properly fill out the feature request form
