### ISSUE TITLE
[BUG] bunkr changed to bunkrr

### ISSUE THREAD

**Issue by B10-boy** [Jules-WinnfieldX/CyberDropDownloader#581]
**Describe the bug**
bunkr.su domain changed to bunkrr.su. bunkrr.su gives error message and does not work.

**To Help Reproduce**
See screenshot

**Screenshots**
![Screenshot](https://github.com/Jules-WinnfieldX/CyberDropDownloader/assets/81786683/d6063522-2631-46c8-bc89-321435d388b3)

**Setup Information**
 - OS: Mac OS X Ventura
 - Cyberdrop Downloader Version #4.2.202

**Downloader.log file**
[downloader.log](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/12644494/downloader.log)

**Additional context**
None

**Comment by Jules-WinnfieldX** [comment]
Your error has nothing to do with any domain changes (bunkrr.su is supported). It's due to ddos-guard.

**Comment by B10-boy** [comment]
<div></div><div>Your error has nothing to do with any domain changes (bunkrr.su is supported). It's due to ddos-guard.
<br/>
<br/>-- 
<br/>Reply to this email directly or view it on GitHub:
<br/>https://github.com/Jules-WinnfieldX/CyberDropDownloader/issues/581#issuecomment-1722702853
<br/>You are receiving this because you authored the thread.
<br/>
<br/>Message ID: ***@***.***&gt;</div>
