### ISSUE TITLE
[BUG] bunkrr.su "Error"

### ISSUE THREAD

**Issue by networksaint** [Jules-WinnfieldX/CyberDropDownloader#584]
**Describe the bug**
When downloading from bunkrr.su i'm provided with Error and skipped the downloading process
also skipped incomplete downloads

**To Help Reproduce**
Steps to help reproduce the behavior:
1. Describe the bug accurately.
2. Provide an example album that showcases it (if applicable)
3. Make sure you are updated to the latest version to see if it's already fixed.

**Screenshots**
![screenshot_167](https://github.com/Jules-WinnfieldX/CyberDropDownloader/assets/23276496/5f9dbf6c-e21d-4254-9395-ff43871a695c)
![screenshot_168](https://github.com/Jules-WinnfieldX/CyberDropDownloader/assets/23276496/1b7f2e8f-dac2-4b3e-b509-24399bbd8a41)

**Setup Information**
 - OS: [Windows 11 Pro]
 - Cyberdrop Downloader Version [4.2.204]

**Downloader.log file**
[downloader.log](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/12678594/downloader.log)

**Additional context**

**Comment by Jules-WinnfieldX** [comment]
It's not an error in the program, it's ddos-guard.

**Comment by Patient6038** [comment]
I'm assuming there's nothing you can do to bypass it for now correct?

**Comment by Jules-WinnfieldX** [comment]
You'd be correct. It's just a keep trying thing.

**Comment by networksaint** [comment]
its because the files inside that bunkr link are under maintenance
ive tried with the working link and its working fine and downloaded correctly
i already make the video and uploaded to youtube [https://www.youtube.com/watch?v=MQyE879xqVI](url)

**Comment by Jules-WinnfieldX** [comment]
> its because the files inside that bunkr link are under maintenance ive tried with the working link and its working fine and downloaded correctly i already make the video and uploaded to youtube

You are incorrect. As I already stated above, and as shows in the log, his failure was due to DDOS-Guard. Not maintenance.

**Comment by networksaint** [comment]
true, but the interesting thing is i had no idea if its like partially ddos guard
but i can downloaded the other one, even play the video normally

![screenshot_175](https://github.com/Jules-WinnfieldX/CyberDropDownloader/assets/23276496/d2e89263-77e0-4143-b846-d99b2ec62c5b)

![screenshot_176](https://github.com/Jules-WinnfieldX/CyberDropDownloader/assets/23276496/daf852be-9a2d-40e9-95ec-9899f88d511e)

while the other one different link couldnt even play the video and it says media temporarily not available due to server maintenance

![screenshot_174](https://github.com/Jules-WinnfieldX/CyberDropDownloader/assets/23276496/5eff22d4-9601-4b87-ab68-93b43a9cca6c)

**Comment by Jules-WinnfieldX** [comment]
> true, but the interesting thing is i had no idea if its like partially ddos guard but i can downloaded the other one, even play the video normally

DDOS-Guard isn't consistent, and will impact people differently. It comes and goes as it pleases, which is why I said "just keep trying" essentially. You won't see DDOS-Guard in your browser, or if you do, it'll only be for a few seconds. Maintenance is entirely different and yes, is just a wait till it's over.

**Comment by networksaint** [comment]
got it, so thats why one link are working and the other one isn't
i learn something here, thanks mate for the replies.
