### ISSUE TITLE
[FEATURE]ADD Hotpic.cc

### ISSUE THREAD

**Issue by GarethFreeman** [Jules-WinnfieldX/CyberDropDownloader#585]
**Is your feature request related to a problem? Please describe.**
There is media on this site that I want to rip but have nowhere to get them.
**Describe the solution you'd like**
I would greatly appreciate it the developer could add this to the list of supported sites.

![Screenshot 2023-09-22 at 16-17-37 signup](https://github.com/Jules-WinnfieldX/CyberDropDownloader/assets/86075581/0efed7ab-44a5-498e-bfb9-b3b194fe4971)

**Comment by Jules-WinnfieldX** [comment]
In V5
