### ISSUE TITLE
[FEATURE] Min / Max file size

### ISSUE THREAD

**Issue by thomasdaley2** [Jules-WinnfieldX/CyberDropDownloader#587]
To avoid downloading 100's of 3 second vids having a minimum dl file size to help weed out tiny videos that arent worth the time.

**Comment by Jules-WinnfieldX** [comment]
https://github.com/Jules-WinnfieldX/CyberDropDownloader/wiki/Config-Options#filesize_minimum_videos

**Comment by thomasdaley2** [comment]
Thank you,  Sorry i didnt find it myself.
