### ISSUE TITLE
[FEATURE] Implement XDG Directory Structure

### ISSUE THREAD

**Issue by 8ullyMaguire** [Jules-WinnfieldX/CyberDropDownloader#588]
**Is your feature request related to a problem? Please describe.**
Currently, when running the CyberDropDownloader, it creates a few files (such as the YAML configuration file and log files) in the directory from which the program is executed. This can lead to clutter and disorganization, making it difficult to manage these files.

**Describe the solution you'd like**
I propose that CyberDropDownloader should follow the XDG directory structure, which is a widely-accepted standard for organizing user-specific files on Linux systems. This would involve placing the YAML configuration file in the `XDG_CONFIG_HOME` directory (usually `~/.config/`) and log files in the `XDG_CACHE_HOME` directory (usually `~/.cache/`). By adhering to this structure, the application will be more organized and user-friendly.

**Additional context**
The XDG Base Directory Specification is a standard that defines where user-specific files should be stored on Linux systems. By following this specification, CyberDropDownloader will be more consistent with other applications and provide a better user experience.

**Comment by Jules-WinnfieldX** [comment]
So the issue here is the primary user base for the program knows nothing about anything. Moving files into "hidden" folders for them, would be as though they simply don't exist. 

With that being said, V5 if it is ever released will be following a stricter directory approach, but it might now necessarily be XDG.

**Comment by 8ullyMaguire** [comment]
If the primary user base doesn't know anything the program shouldn't be creating any files other than the ones the user explicitly asks for. I just used it with a URL and it created three files in a path where I didn't want to have any files, just because I happened to call the program from there. I don't want the program doing things I don't ask for.

**Comment by Jules-WinnfieldX** [comment]
Hard disagree, especially when I'm the one maintaining and troubleshooting user related issues. These files are necessary.

If you don't want it doing those things, use the config or cli args, and tell it where to put the files yourself.
