### ISSUE TITLE
[FEATURE]Are the new domain of bunkr supported?

### ISSUE THREAD

**Issue by UltZephir** [Jules-WinnfieldX/CyberDropDownloader#591]
Tried to download from the new bunkr domain (bunkrr) and the programm says there is no valid links
![image](https://github.com/Jules-WinnfieldX/CyberDropDownloader/assets/66739916/cd26457e-e678-496f-9fdf-4fa2ab61ed49)

**Comment by Jules-WinnfieldX** [comment]
Then you didn't put the link in the urls.txt file properly or you are running as admin and you shouldn't be
