### ISSUE TITLE
[BUG] [FEATURE] Bunkr 403 Errors/Add ability to use browser cookies

### ISSUE THREAD

**Issue by DGrimace** [Jules-WinnfieldX/CyberDropDownloader#600]
When using this downloader for Bunkrr.su or related Bunkr sites recently, I keep getting Error 403 messages 'Forbidden'

Similar to this from the "Errored_Scrape_URLs.csv":
    https://bunkrr.su/a/*,"403, message='Forbidden', url=URL('https://bunkrr.su/a/*')"

This is because Bunkrr recently added DDos Guard and a way around this seems to be enabling browser cookie usage. 
I found a similar issue here: https://github.com/mikf/gallery-dl/issues/1370

**Comment by Jules-WinnfieldX** [comment]
I wasn't entirely sure if exporting DDOS-Guard cookies would work. Was going to test it soon for V5. But haven't gotten to it yet.

**Comment by Jules-WinnfieldX** [comment]
In any case, this will be a V5 thing when I can get back around to working on it.

**Comment by Jules-WinnfieldX** [comment]
JDownloader really isn't built to handle custom cookies.

Either way, assuming Bunkr's plans haven't changed, this feature will be short lived, and scraping will be essentially non-existent on the site. If his plans come to fruition I'll have to drop support for that site.

**Comment by Lukas-Sturm** [comment]
@Jules-WinnfieldX what plans do you mean ? Are they trying to be scrape proof, I wonder how ?

**Comment by Jules-WinnfieldX** [comment]
In V5
