### ISSUE TITLE
[BUG] Upgrade failing

### ISSUE THREAD

**Issue by yohuan94** [Jules-WinnfieldX/CyberDropDownloader#601]
Getting this error when trying to run app.
Any help would be appreciated.
------------------------------------------------------------------------------------

Building wheels for collected packages aiohttp, yarl, frozenlist, multidict
  Building wheel for aiohttp (pyproject.toml) ... error
  error subprocess-exited-with-error

  × Building wheel for aiohttp (pyproject.toml) did not run successfully.
  │ exit code 1
  ╰─ [94 lines of output]
      
       Accelerated build 
      
      running bdist_wheel
      running build
      running build_py
      creating build
      creating buildlib.win-amd64-cpython-312
      creating buildlib.win-amd64-cpython-312aiohttp
      copying aiohttpabc.py - buildlib.win-amd64-cpython-312aiohttp
      copying aiohttpbase_protocol.py - buildlib.win-amd64-cpython-312aiohttp
      copying aiohttpclient.py - buildlib.win-amd64-cpython-312aiohttp
      copying aiohttpclient_exceptions.py - buildlib.win-amd64-cpython-312aiohttp
      copying aiohttpclient_proto.py - buildlib.win-amd64-cpython-312aiohttp
      copying aiohttpclient_reqrep.py - buildlib.win-amd64-cpython-312aiohttp
      copying aiohttpclient_ws.py - buildlib.win-amd64-cpython-312aiohttp
      copying aiohttpconnector.py - buildlib.win-amd64-cpython-312aiohttp
      copying aiohttpcookiejar.py - buildlib.win-amd64-cpython-312aiohttp
      copying aiohttpformdata.py - buildlib.win-amd64-cpython-312aiohttp
      copying aiohttphdrs.py - buildlib.win-amd64-cpython-312aiohttp
      copying aiohttphelpers.py - buildlib.win-amd64-cpython-312aiohttp
      copying aiohttphttp.py - buildlib.win-amd64-cpython-312aiohttp
      copying aiohttphttp_exceptions.py - buildlib.win-amd64-cpython-312aiohttp
      copying aiohttphttp_parser.py - buildlib.win-amd64-cpython-312aiohttp
      copying aiohttphttp_websocket.py - buildlib.win-amd64-cpython-312aiohttp
      copying aiohttphttp_writer.py - buildlib.win-amd64-cpython-312aiohttp
      copying aiohttplocks.py - buildlib.win-amd64-cpython-312aiohttp
      copying aiohttplog.py - buildlib.win-amd64-cpython-312aiohttp
      copying aiohttpmultipart.py - buildlib.win-amd64-cpython-312aiohttp
      copying aiohttppayload.py - buildlib.win-amd64-cpython-312aiohttp
      copying aiohttppayload_streamer.py - buildlib.win-amd64-cpython-312aiohttp
      copying aiohttppytest_plugin.py - buildlib.win-amd64-cpython-312aiohttp
      copying aiohttpresolver.py - buildlib.win-amd64-cpython-312aiohttp
      copying aiohttpstreams.py - buildlib.win-amd64-cpython-312aiohttp
      copying aiohttptcp_helpers.py - buildlib.win-amd64-cpython-312aiohttp
      copying aiohttptest_utils.py - buildlib.win-amd64-cpython-312aiohttp
      copying aiohttptracing.py - buildlib.win-amd64-cpython-312aiohttp
      copying aiohttptypedefs.py - buildlib.win-amd64-cpython-312aiohttp
      copying aiohttpweb.py - buildlib.win-amd64-cpython-312aiohttp
      copying aiohttpweb_app.py - buildlib.win-amd64-cpython-312aiohttp
      copying aiohttpweb_exceptions.py - buildlib.win-amd64-cpython-312aiohttp
      copying aiohttpweb_fileresponse.py - buildlib.win-amd64-cpython-312aiohttp
      copying aiohttpweb_log.py - buildlib.win-amd64-cpython-312aiohttp
      copying aiohttpweb_middlewares.py - buildlib.win-amd64-cpython-312aiohttp
      copying aiohttpweb_protocol.py - buildlib.win-amd64-cpython-312aiohttp
      copying aiohttpweb_request.py - buildlib.win-amd64-cpython-312aiohttp
      copying aiohttpweb_response.py - buildlib.win-amd64-cpython-312aiohttp
      copying aiohttpweb_routedef.py - buildlib.win-amd64-cpython-312aiohttp
      copying aiohttpweb_runner.py - buildlib.win-amd64-cpython-312aiohttp
      copying aiohttpweb_server.py - buildlib.win-amd64-cpython-312aiohttp
      copying aiohttpweb_urldispatcher.py - buildlib.win-amd64-cpython-312aiohttp
      copying aiohttpweb_ws.py - buildlib.win-amd64-cpython-312aiohttp
      copying aiohttpworker.py - buildlib.win-amd64-cpython-312aiohttp
      copying aiohttp__init__.py - buildlib.win-amd64-cpython-312aiohttp
      running egg_info
      writing aiohttp.egg-infoPKG-INFO
      writing dependency_links to aiohttp.egg-infodependency_links.txt
      writing requirements to aiohttp.egg-inforequires.txt
      writing top-level names to aiohttp.egg-infotop_level.txt
      reading manifest file 'aiohttp.egg-infoSOURCES.txt'
      reading manifest template 'MANIFEST.in'
      warning no files found matching 'aiohttp' anywhere in distribution
      warning no previously-included files matching '.pyc' found anywhere in distribution
      warning no previously-included files matching '.pyd' found anywhere in distribution
      warning no previously-included files matching '.so' found anywhere in distribution
      warning no previously-included files matching '.lib' found anywhere in distribution
      warning no previously-included files matching '.dll' found anywhere in distribution
      warning no previously-included files matching '.a' found anywhere in distribution
      warning no previously-included files matching '.obj' found anywhere in distribution
      warning no previously-included files found matching 'aiohttp.html'
      no previously-included directories found matching 'docs_build'
      adding license file 'LICENSE.txt'
      writing manifest file 'aiohttp.egg-infoSOURCES.txt'
      copying aiohttp_cparser.pxd - buildlib.win-amd64-cpython-312aiohttp
      copying aiohttp_find_header.pxd - buildlib.win-amd64-cpython-312aiohttp
      copying aiohttp_headers.pxi - buildlib.win-amd64-cpython-312aiohttp
      copying aiohttp_helpers.pyi - buildlib.win-amd64-cpython-312aiohttp
      copying aiohttp_helpers.pyx - buildlib.win-amd64-cpython-312aiohttp
      copying aiohttp_http_parser.pyx - buildlib.win-amd64-cpython-312aiohttp
      copying aiohttp_http_writer.pyx - buildlib.win-amd64-cpython-312aiohttp
      copying aiohttp_websocket.pyx - buildlib.win-amd64-cpython-312aiohttp
      copying aiohttppy.typed - buildlib.win-amd64-cpython-312aiohttp
      creating buildlib.win-amd64-cpython-312aiohttp.hash
      copying aiohttp.hash_cparser.pxd.hash - buildlib.win-amd64-cpython-312aiohttp.hash
      copying aiohttp.hash_find_header.pxd.hash - buildlib.win-amd64-cpython-312aiohttp.hash
      copying aiohttp.hash_helpers.pyi.hash - buildlib.win-amd64-cpython-312aiohttp.hash
      copying aiohttp.hash_helpers.pyx.hash - buildlib.win-amd64-cpython-312aiohttp.hash
      copying aiohttp.hash_http_parser.pyx.hash - buildlib.win-amd64-cpython-312aiohttp.hash
      copying aiohttp.hash_http_writer.pyx.hash - buildlib.win-amd64-cpython-312aiohttp.hash
      copying aiohttp.hash_websocket.pyx.hash - buildlib.win-amd64-cpython-312aiohttp.hash
      copying aiohttp.hashhdrs.py.hash - buildlib.win-amd64-cpython-312aiohttp.hash
      running build_ext
      building 'aiohttp._websocket' extension
      error Microsoft Visual C++ 14.0 or greater is required. Get it with Microsoft C++ Build Tools httpsvisualstudio.microsoft.comvisual-cpp-build-tools
      [end of output]

  note This error originates from a subprocess, and is likely not a problem with pip.
  ERROR Failed building wheel for aiohttp
  Building wheel for yarl (pyproject.toml) ... error
  error subprocess-exited-with-error

  × Building wheel for yarl (pyproject.toml) did not run successfully.
  │ exit code 1
  ╰─ [49 lines of output]
      CUsersitzwiAppDataLocalTemppip-build-env-y8sdhu4foverlayLibsite-packagessetuptoolsconfigsetupcfg.py293 _DeprecatedConfig Deprecated config in `setup.cfg`
      !!

              
              The license_file parameter is deprecated, use license_files instead.

              By 2023-Oct-30, you need to update your project and remove deprecated calls
              or your builds will no longer be supported.

              See httpssetuptools.pypa.ioenlatestuserguidedeclarative_config.html for details.
              

      !!
        parsed = self.parsers.get(option_name, lambda x x)(value)
      
       Accelerated build 
      
      running bdist_wheel
      running build
      running build_py
      creating build
      creating buildlib.win-amd64-cpython-312
      creating buildlib.win-amd64-cpython-312yarl
      copying yarl_quoting.py - buildlib.win-amd64-cpython-312yarl
      copying yarl_quoting_py.py - buildlib.win-amd64-cpython-312yarl
      copying yarl_url.py - buildlib.win-amd64-cpython-312yarl
      copying yarl__init__.py - buildlib.win-amd64-cpython-312yarl
      running egg_info
      writing yarl.egg-infoPKG-INFO
      writing dependency_links to yarl.egg-infodependency_links.txt
      writing requirements to yarl.egg-inforequires.txt
      writing top-level names to yarl.egg-infotop_level.txt
      reading manifest file 'yarl.egg-infoSOURCES.txt'
      reading manifest template 'MANIFEST.in'
      warning no previously-included files matching '.pyc' found anywhere in distribution
      warning no previously-included files matching '.cache' found anywhere in distribution
      warning no previously-included files found matching 'yarl.html'
      warning no previously-included files found matching 'yarl.so'
      warning no previously-included files found matching 'yarl.pyd'
      no previously-included directories found matching 'docs_build'
      adding license file 'LICENSE'
      writing manifest file 'yarl.egg-infoSOURCES.txt'
      copying yarl__init__.pyi - buildlib.win-amd64-cpython-312yarl
      copying yarl_quoting_c.pyi - buildlib.win-amd64-cpython-312yarl
      copying yarl_quoting_c.pyx - buildlib.win-amd64-cpython-312yarl
      copying yarlpy.typed - buildlib.win-amd64-cpython-312yarl
      running build_ext
      building 'yarl._quoting_c' extension
      error Microsoft Visual C++ 14.0 or greater is required. Get it with Microsoft C++ Build Tools httpsvisualstudio.microsoft.comvisual-cpp-build-tools
      [end of output]

  note This error originates from a subprocess, and is likely not a problem with pip.
  ERROR Failed building wheel for yarl
  Building wheel for frozenlist (pyproject.toml) ... error
  error subprocess-exited-with-error

  × Building wheel for frozenlist (pyproject.toml) did not run successfully.
  │ exit code 1
  ╰─ [33 lines of output]
      
       Accelerated build 
      
      running bdist_wheel
      running build
      running build_py
      creating build
      creating buildlib.win-amd64-cpython-312
      creating buildlib.win-amd64-cpython-312frozenlist
      copying frozenlist__init__.py - buildlib.win-amd64-cpython-312frozenlist
      running egg_info
      writing frozenlist.egg-infoPKG-INFO
      writing dependency_links to frozenlist.egg-infodependency_links.txt
      writing top-level names to frozenlist.egg-infotop_level.txt
      reading manifest file 'frozenlist.egg-infoSOURCES.txt'
      reading manifest template 'MANIFEST.in'
      warning no previously-included files matching '.pyc' found anywhere in distribution
      warning no previously-included files matching '.pyd' found anywhere in distribution
      warning no previously-included files matching '.so' found anywhere in distribution
      warning no previously-included files matching '.lib' found anywhere in distribution
      warning no previously-included files matching '.dll' found anywhere in distribution
      warning no previously-included files matching '.a' found anywhere in distribution
      warning no previously-included files matching '.obj' found anywhere in distribution
      warning no previously-included files found matching 'frozenlist.html'
      no previously-included directories found matching 'docs_build'
      adding license file 'LICENSE'
      writing manifest file 'frozenlist.egg-infoSOURCES.txt'
      copying frozenlist__init__.pyi - buildlib.win-amd64-cpython-312frozenlist
      copying frozenlist_frozenlist.pyx - buildlib.win-amd64-cpython-312frozenlist
      copying frozenlistpy.typed - buildlib.win-amd64-cpython-312frozenlist
      running build_ext
      building 'frozenlist._frozenlist' extension
      error Microsoft Visual C++ 14.0 or greater is required. Get it with Microsoft C++ Build Tools httpsvisualstudio.microsoft.comvisual-cpp-build-tools
      [end of output]

  note This error originates from a subprocess, and is likely not a problem with pip.
  ERROR Failed building wheel for frozenlist
  Building wheel for multidict (pyproject.toml) ... error
  error subprocess-exited-with-error

  × Building wheel for multidict (pyproject.toml) did not run successfully.
  │ exit code 1
  ╰─ [74 lines of output]
      
       Accelerated build 
      
      running bdist_wheel
      running build
      running build_py
      creating build
      creating buildlib.win-amd64-cpython-312
      creating buildlib.win-amd64-cpython-312multidict
      copying multidict_abc.py - buildlib.win-amd64-cpython-312multidict
      copying multidict_compat.py - buildlib.win-amd64-cpython-312multidict
      copying multidict_multidict_base.py - buildlib.win-amd64-cpython-312multidict
      copying multidict_multidict_py.py - buildlib.win-amd64-cpython-312multidict
      copying multidict__init__.py - buildlib.win-amd64-cpython-312multidict
      running egg_info
      writing multidict.egg-infoPKG-INFO
      writing dependency_links to multidict.egg-infodependency_links.txt
      writing top-level names to multidict.egg-infotop_level.txt
      reading manifest file 'multidict.egg-infoSOURCES.txt'
      reading manifest template 'MANIFEST.in'
      warning no previously-included files matching '.pyc' found anywhere in distribution
      warning no previously-included files found matching 'multidict_multidict.html'
      warning no previously-included files found matching 'multidict.so'
      warning no previously-included files found matching 'multidict.pyd'
      warning no previously-included files found matching 'multidict.pyd'
      no previously-included directories found matching 'docs_build'
      adding license file 'LICENSE'
      writing manifest file 'multidict.egg-infoSOURCES.txt'
      CUsersitzwiAppDataLocalTemppip-build-env-hghq7hc0overlayLibsite-packagessetuptoolscommandbuild_py.py204 _Warning Package 'multidict._multilib' is absent from the `packages` configuration.
      !!

              
              ############################
              # Package would be ignored #
              ############################
              Python recognizes 'multidict._multilib' as an importable package[^1],
              but it is absent from setuptools' `packages` configuration.

              This leads to an ambiguous overall configuration. If you want to distribute this
              package, please make sure that 'multidict._multilib' is explicitly added
              to the `packages` configuration field.

              Alternatively, you can also rely on setuptools' discovery methods
              (for example by using `find_namespace_packages(...)``find_namespace`
              instead of `find_packages(...)``find`).

              You can read more about package discovery on setuptools documentation page

              - httpssetuptools.pypa.ioenlatestuserguidepackage_discovery.html

              If you don't want 'multidict._multilib' to be distributed and are
              already explicitly excluding 'multidict._multilib' via
              `find_namespace_packages(...)find_namespace` or `find_packages(...)find`,
              you can try to use `exclude_package_data`, or `include-package-data=False` in
              combination with a more fine grained `package-data` configuration.

              You can read more about package data files on setuptools documentation page

              - httpssetuptools.pypa.ioenlatestuserguidedatafiles.html

              [^1] For Python, any directory (with suitable naming) can be imported,
                    even if it does not contain any `.py` files.
                    On the other hand, currently there is no concept of package data
                    directory, all directories are treated like packages.
              

      !!
        check.warn(importable)
      copying multidict__init__.pyi - buildlib.win-amd64-cpython-312multidict
      copying multidictpy.typed - buildlib.win-amd64-cpython-312multidict
      running build_ext
      building 'multidict._multidict' extension
      error Microsoft Visual C++ 14.0 or greater is required. Get it with Microsoft C++ Build Tools httpsvisualstudio.microsoft.comvisual-cpp-build-tools
      [end of output]

  note This error originates from a subprocess, and is likely not a problem with pip.
  ERROR Failed building wheel for multidict
Failed to build aiohttp yarl frozenlist multidict
ERROR Could not build wheels for aiohttp, yarl, frozenlist, multidict, which is required to install pyproject.toml-based projects

**Comment by Jules-WinnfieldX** [comment]
Don't use python 3.12, use python 3.11
