### ISSUE TITLE
[BUG] https://cyberfile.me folder downloads fail

### ISSUE THREAD

**Issue by gashtal** [Jules-WinnfieldX/CyberDropDownloader#605]
**Describe the bug**
Downloading folders from cyberfile.me fail at scraping stage. Downloading single files, however, works fine.

**To Help Reproduce**
Steps to help reproduce the behavior:
1. Try downloading any folder from cyberfile.me
2. Example (NSFW): https://cyberfile.me/folder/57d7b556ce6699fe715d810c78992bb8/Maud_Franklen

**Screenshots**
![image](https://github.com/Jules-WinnfieldX/CyberDropDownloader/assets/27990818/381c6349-3568-46fc-82f9-b3c8fc6d827c)

**Setup Information**
 - OS: Ubuntu 22.04
 - Cyberdrop Downloader Version 4.2.214

**Downloader.log file**
[downloader.log](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/13197329/downloader.log)

**Additional context**
Source of the problem per the log:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/cyberdrop_dl/crawlers/CyberFile_Spider.py", line 73, in get_folder_id
    nodeId = int(script_func.split(',')[1].replace("'", ""))
ValueError: invalid literal for int() with base 10: 'b64d'
```

**Comment by Jules-WinnfieldX** [comment]
Fixed in 4.2.215
