### ISSUE TITLE
[FEATURE] Rewrite sorting to have more options (such as parent folder name), flexible filenames

### ISSUE THREAD

**Issue by minicoz** [Jules-WinnfieldX/CyberDropDownloader#606]
**Is your feature request related to a problem? Please describe.**
No its not a problem. I would like to be able to append the folder name to the file name while sorting.

**Describe the solution you'd like**
Add the parent directory name to the sorted filename. The reason why is due to some of the folders containing the models set photo including set name an date. This information is lost when we move the raw file over to the sorted directory.

Added an alphanumeric filter so that the parent directory removed any extra characters that might make the file name longer than needed.

**Additional context**
Opened a PR before, got feedback, then closed it for this feature request. 

https://github.com/Jules-WinnfieldX/CyberDropDownloader/pull/604

**Comment by Jules-WinnfieldX** [comment]
In V5
