### ISSUE TITLE
[FEATURE] Add Bunkrr.su support

### ISSUE THREAD

**Issue by Y2K350** [Jules-WinnfieldX/CyberDropDownloader#607]
Hey, I've noticed there is a new mirror of Bunkr that is coming up a lot that doesn't seem supported. It is Bunkrr.su (notice with two "R"s instead of one). Is there any plan to add this to the list of supported mirrors? I would really appreciate it! Thank you for all your hard work!

**Comment by Jules-WinnfieldX** [comment]
This has been supported for months. You need to update cyberdrop-dl

https://github.com/Jules-WinnfieldX/CyberDropDownloader/wiki/Frequently-Asked-Questions#how-to-update

**Comment by Y2K350** [comment]
Hi, thank you so much for your fast reply!

I suppose I should preface this with the fact that I am currently using build 4.2.217 which as I understand is the current build? I am running this on a Debian 12 machine with python 3.11.2 currently. Perhaps I am doing something else wrong? I have updated using the command pip3 install --upgrade cyberdrop-dl before each use of the application.

It appears all other types of links including different Bunkr mirrors work.

Below is the output code I receive when I attempt to update the software.


Requirement already satisfied: cyberdrop-dl in ./venv/lib/python3.11/site-packages (4.2.217)
Requirement already satisfied: aiofiles>=0.8.0 in ./venv/lib/python3.11/site-packages (from cyberdrop-dl) (0.8.0)
Requirement already satisfied: aiohttp>=3.8.6 in ./venv/lib/python3.11/site-packages (from cyberdrop-dl) (3.8.6)
Requirement already satisfied: aiolimiter>=1.1.0 in ./venv/lib/python3.11/site-packages (from cyberdrop-dl) (1.1.0)
Requirement already satisfied: aiorun>=2023.7.2 in ./venv/lib/python3.11/site-packages (from cyberdrop-dl) (2023.7.2)
Requirement already satisfied: asyncpraw>=7.7.1 in ./venv/lib/python3.11/site-packages (from cyberdrop-dl) (7.7.1)
Requirement already satisfied: beautifulsoup4>=4.12.2 in ./venv/lib/python3.11/site-packages (from cyberdrop-dl) (4.12.2)
Requirement already satisfied: certifi>=2023.7.22 in ./venv/lib/python3.11/site-packages (from cyberdrop-dl) (2023.7.22)
Requirement already satisfied: myjdapi>=1.1.7 in ./venv/lib/python3.11/site-packages (from cyberdrop-dl) (1.1.7)
Requirement already satisfied: platformdirs>=3.11.0 in ./venv/lib/python3.11/site-packages (from cyberdrop-dl) (3.11.0)
Requirement already satisfied: PyYAML>=6.0.1 in ./venv/lib/python3.11/site-packages (from cyberdrop-dl) (6.0.1)
Requirement already satisfied: rich>=13.6.0 in ./venv/lib/python3.11/site-packages (from cyberdrop-dl) (13.6.0)
Requirement already satisfied: setuptools>=68.2.2 in ./venv/lib/python3.11/site-packages (from cyberdrop-dl) (68.2.2)
Requirement already satisfied: tqdm>=4.66.1 in ./venv/lib/python3.11/site-packages (from cyberdrop-dl) (4.66.1)
Requirement already satisfied: yarl>=1.9.2 in ./venv/lib/python3.11/site-packages (from cyberdrop-dl) (1.9.2)
Requirement already satisfied: attrs>=17.3.0 in ./venv/lib/python3.11/site-packages (from aiohttp>=3.8.6->cyberdrop-dl) (23.1.0)
Requirement already satisfied: charset-normalizer<4.0,>=2.0 in ./venv/lib/python3.11/site-packages (from aiohttp>=3.8.6->cyberdrop-dl) (3.3.0)
Requirement already satisfied: multidict<7.0,>=4.5 in ./venv/lib/python3.11/site-packages (from aiohttp>=3.8.6->cyberdrop-dl) (6.0.4)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in ./venv/lib/python3.11/site-packages (from aiohttp>=3.8.6->cyberdrop-dl) (4.0.3)
Requirement already satisfied: frozenlist>=1.1.1 in ./venv/lib/python3.11/site-packages (from aiohttp>=3.8.6->cyberdrop-dl) (1.4.0)
Requirement already satisfied: aiosignal>=1.1.2 in ./venv/lib/python3.11/site-packages (from aiohttp>=3.8.6->cyberdrop-dl) (1.3.1)
Requirement already satisfied: aiosqlite<=0.17.0 in ./venv/lib/python3.11/site-packages (from asyncpraw>=7.7.1->cyberdrop-dl) (0.17.0)
Requirement already satisfied: asyncprawcore<3,>=2.1 in ./venv/lib/python3.11/site-packages (from asyncpraw>=7.7.1->cyberdrop-dl) (2.3.0)
Requirement already satisfied: update-checker>=0.18 in ./venv/lib/python3.11/site-packages (from asyncpraw>=7.7.1->cyberdrop-dl) (0.18.0)
Requirement already satisfied: soupsieve>1.2 in ./venv/lib/python3.11/site-packages (from beautifulsoup4>=4.12.2->cyberdrop-dl) (2.5)
Requirement already satisfied: requests in ./venv/lib/python3.11/site-packages (from myjdapi>=1.1.7->cyberdrop-dl) (2.31.0)
Requirement already satisfied: pycryptodome in ./venv/lib/python3.11/site-packages (from myjdapi>=1.1.7->cyberdrop-dl) (3.19.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in ./venv/lib/python3.11/site-packages (from rich>=13.6.0->cyberdrop-dl) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in ./venv/lib/python3.11/site-packages (from rich>=13.6.0->cyberdrop-dl) (2.16.1)
Requirement already satisfied: idna>=2.0 in ./venv/lib/python3.11/site-packages (from yarl>=1.9.2->cyberdrop-dl) (3.4)
Requirement already satisfied: typing_extensions>=3.7.2 in ./venv/lib/python3.11/site-packages (from aiosqlite<=0.17.0->asyncpraw>=7.7.1->cyberdrop-dl) (4.8.0)
Requirement already satisfied: mdurl~=0.1 in ./venv/lib/python3.11/site-packages (from markdown-it-py>=2.2.0->rich>=13.6.0->cyberdrop-dl) (0.1.2)
Requirement already satisfied: urllib3<3,>=1.21.1 in ./venv/lib/python3.11/site-packages (from requests->myjdapi>=1.1.7->cyberdrop-dl) (2.0.6)

**Comment by Jules-WinnfieldX** [comment]
I'd need to see a log then of this mirror not working.
