### ISSUE TITLE
Nudostar[BUG]

### ISSUE THREAD

**Issue by neuri48** [Jules-WinnfieldX/CyberDropDownloader#608]
posts with multiple images will only scrape the thumbnails of the image and not download the actual file

**Comment by Jules-WinnfieldX** [comment]
Can't replicate. Please fill out the actual bug report, and include a log file. Mentioning specific files that are only thumbs.

**Comment by neuri48** [comment]
here's  the dowload log

https://pastebin.com/3DSrmjUz

**Comment by Jules-WinnfieldX** [comment]
I'd need you to find the specific post where this is happening, as I can't see it

**Comment by neuri48** [comment]
https://nudostar.com/forum/threads/sarah-mcdaniel-krotchy.64074/post-1165041

**Comment by Jules-WinnfieldX** [comment]
Ahhh. I see what's happening. Damn you nudostar for doing it opposite of literally everyone else. 

4.2.218 going up.
