### ISSUE TITLE
[BUG] Skipped files even though they're not images

### ISSUE THREAD

**Issue by richiema32** [Jules-WinnfieldX/CyberDropDownloader#609]
**Describe the bug**
Using the scraper for just one URL: https://coomer.su/onlyfans/user/msmichiganmelons
The only additional option i use is the "exclude-images" option, which normally works fine but it's refusing to scrape videos off this even though i can see videos. It's not even producing a directory for the scrape in the download folder. I've also tried running it with the additionan of -ignore-cache but that didnt work either. 

**To Help Reproduce**
Add https://coomer.su/onlyfans/user/msmichiganmelons to URL text file
Run via Windows Powershell (ran in admin) with "cyberdrop-dl --exclude-images
Scrape completes, no new files downloaded and several files skipped as per below screenshot. I've confirmed theres no folder in the downloads folder with these files already downloaded.

**Screenshots**
![image](https://github.com/Jules-WinnfieldX/CyberDropDownloader/assets/83547038/0b45fb35-0089-464b-9079-c533670f012b)

**Setup Information**
Windows 10
Cybderdrop version 4.2.218
[downloader.log](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/13246655/downloader.log)

**Downloader.log file**

[downloader.log](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/13246655/downloader.log)

**Additional context**

**Comment by Jules-WinnfieldX** [comment]
It's because you've downloaded all those files in the past. --ignore-history.
