### ISSUE TITLE
[BUG] Failed on initial launch

### ISSUE THREAD

**Issue by oski1994** [Jules-WinnfieldX/CyberDropDownloader#612]
**Describe the bug**
The Windows batch files is crashing on initial launch.

**To Help Reproduce**
I reinstalled Python with the path checked.

**Screenshots**
 
![Screenshot 2023-11-03 132544](https://github.com/Jules-WinnfieldX/CyberDropDownloader/assets/149833076/2f10465e-9d9a-4350-8768-c28d89a675cc)

![Screenshot 2023-11-03 132854](https://github.com/Jules-WinnfieldX/CyberDropDownloader/assets/149833076/769fefba-9ede-4ec3-b8ee-f9ab571b6669)

**Setup Information**
 - OS: Windows 10
 - Cyberdrop Downloader Version 4.2
 - Python 3.20 64 bit

**Comment by Jules-WinnfieldX** [comment]
Downgrade to python 3.11
