### ISSUE TITLE
[BUG] Number of download threads reduced to 1

### ISSUE THREAD

**Issue by Kenneth-Rosenstroem** [Jules-WinnfieldX/CyberDropDownloader#615]
**Describe the bug**
All domains are reduced to one thread. 
Example: Coomer was 4 threads before, it now only downloads 1 by 1 and takes forever.
Bunkr was 2 threads, now also reduced to 1.

**To Help Reproduce**
Steps to help reproduce the behaviour:
1. Downloads 1 thread pr. domain.

**Setup Information**
 - OS: Windows 10, 11 python-3.11.2-amd64
 - Cyberdrop Downloader Version  4.2.218

**Downloader.log file**
https://www.dropbox.com/s/253ymyevqwbwpci/downloader.log?dl=0

**Additional context**
It may be on purpose, not sure, if so, you can complete this bug report.

**Comment by Jules-WinnfieldX** [comment]
I'll need to test out Coomer myself (it doesn't have said limiter), but bunkr was specifically limited to 1. Due to DDOS-Guard. 1 simultaneous helps.

**Comment by Kenneth-Rosenstroem** [comment]
I understand regarding bunkr, but still, I can open 4 instances of Cyperdrop, with 4 different download folders on bunkr, and they still go well. The same goes for Coomer, 4 different instances, but each with 1 thread.

Thanks for looking into it.

**Comment by Jules-WinnfieldX** [comment]
There's multiple reasons why you shouldn't do that. But the primary being that'll get your DDOS warnings, and ratelimits a lot sooner. Bunkr itself for videos is limited to 2 download instances at a single time. That's a server side limit, not a CDL limit.

**Comment by Jules-WinnfieldX** [comment]
Your log file is full of ratelimits from coomer. You've likely either hit the ratelimits server side, or you were running multiple instances. Which would explain why it's slow.

**Comment by Kenneth-Rosenstroem** [comment]
It was slow before I stated multiple instances. This was just a little test run to create a small log file for you.
I know about bunkr, but restarting the cyberdrop over and over again eventually gets all the files.

But since the last update, one 1 thread pr. domain.

**Comment by Jules-WinnfieldX** [comment]
Then your primary issue is hitting Coomers rate limits. Take a break for 24 hrs or so and try it again.

**Comment by Kenneth-Rosenstroem** [comment]
Will give that a try. Thanks for your time, Jules.

Cheers.
