### ISSUE TITLE
Issue with Python312

### ISSUE THREAD

**Issue by ds61234** [Jules-WinnfieldX/CyberDropDownloader#619]
ran into an issue with failing to build wheels for aiohttp with Python 3.1.2. Resolved with the solution in the link. Hope this helps someone. 

https://stackoverflow.com/questions/77388920/warning-c4996-py-optimizeflag-deprecated-in-3-12-aiohttp-websocket-c3042/77388956#77388956

**Comment by Jules-WinnfieldX** [comment]
This issue isn't something that is wrong with Cyberdrop-DL. It's an error with AIOHTTP. 

You've already found the solution (downgrade to python 3.11). When AIOHTTP releases a new official version, I'll update the requirements to support it. Until then nothing I can do.
