### ISSUE TITLE
[BUG] I can't update to the latest version

### ISSUE THREAD

**Issue by axel845845** [Jules-WinnfieldX/CyberDropDownloader#62]
Does anyone know the command to update?

**Comment by Jules-WinnfieldX** [comment]
There is no command. You just download the latest source code from the releases page and replace the files.

**Comment by axel845845** [comment]
> No hay comando. Simplemente descargue el código fuente más reciente de la página de versiones y reemplace los archivos.

Oh thank you very much, sorry for my ignorance
