### ISSUE TITLE
[BUG] Stuck at We are running version 4.2.219 of Cyberdrop Downloader

### ISSUE THREAD

**Issue by ravioli6994** [Jules-WinnfieldX/CyberDropDownloader#620]
**Describe the bug**
Whenever I run the windows script, the app looks for updates and starts but then it gets stuck at the following screen: 

![image](https://github.com/Jules-WinnfieldX/CyberDropDownloader/assets/150402984/f43d65b3-19bf-4f16-8084-3164ab0a6889)

**To Help Reproduce**
Steps to help reproduce the behavior:
Start the windows app

**Screenshots**
![image](https://github.com/Jules-WinnfieldX/CyberDropDownloader/assets/150402984/f136f533-d216-44ae-aa90-c0729daec272)

**Setup Information**
 - OS: Windows 10
 - Cyberdrop Downloader Version 4.2.219

**Comment by Jules-WinnfieldX** [comment]
are you running as admin?
