### ISSUE TITLE
[FEATURE] Print total/downloaded/remaining total file size in the download screen

### ISSUE THREAD

**Issue by gashtal** [Jules-WinnfieldX/CyberDropDownloader#621]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Is it possible to have the total size, currently downloaded size, and also remaining size of the files/albums that are being downloaded also printed along with the number of files/albums? This will be extremely helpful to, for example, tell if there is enough disk space left to download all the [remaining] files or not, specifically for cases where several albums are being downloaded together.

**Comment by Jules-WinnfieldX** [comment]
Not possible for most sites, so it's not something I'm likely going to implement. Just utilize the free space required config arg.
