### ISSUE TITLE
[FEATURE] Download only date range

### ISSUE THREAD

**Issue by cewong2** [Jules-WinnfieldX/CyberDropDownloader#623]
Is it possible to request that only posts from a certain date range e.g. 10-01-2023 through 10-31-2023 be downloaded from posts for sites with postings like Coomer, Kimono etc.?

I understand you can use the --separate-posts flag and it will ad a date to the folder, but I'm thinking more of if we only want things from a certain date range.

**Comment by Jules-WinnfieldX** [comment]
Not currently. I also think this is likely too niche a feature for me to really add. You can download individual posts from Coomer however. 

Worth noting as the date range is recent, download history is tracked, so things won't be redownloaded if you run the same link.

**Comment by cewong2** [comment]
I think this would be useful for any "forum" based scraped too, especially for someone only needing to scrape newer posts, etc. Yes there's a manual way of doing it with individual posts, but sometimes there can be 50-100 posts in a single day too. (sorry I should've mentioned more than just Coomer as that was the first one that came to mind on the list). Also potentially someone moving over from another archival system that might have years of history, to have to redownload it all just to have it tracked into the history might be cumbersome as well. (just my 2-cents, and maybe something to keep in mind for the future)
