### ISSUE TITLE
[BUG] Cyberdrop.me 429 Too many requests

### ISSUE THREAD

**Issue by waitaminuteholup** [Jules-WinnfieldX/CyberDropDownloader#627]
**Describe the bug**
When attempting to scrape an album from cyberdrop.me it only scrapes a few things before getting a "Too many requests" error and failing all further scraping.

**Setup Information**
 - OS: [e.g. Windows 10, Mac OS X Sierra, etc]
 - Cyberdrop Downloader Version #

**Downloader.log file**
aiohttp.client_exceptions.ClientResponseError: 429, message='Too Many Requests',

**Additional context**
Is there anyway to download large cyberdrop albums through cyberdrop-dl?

**Comment by Jules-WinnfieldX** [comment]
Should be fine with the latest version 4.2.225
