### ISSUE TITLE
The number of simultaneous downloads.

### ISSUE THREAD

**Issue by IIJlOXOCIIAJl** [Jules-WinnfieldX/CyberDropDownloader#63]
Is it possible to somehow reduce the number of simultaneous downloads? For example, up to 2 or up to 3. If it is possible, then how to do it
![12](https://user-images.githubusercontent.com/95716704/157080020-07a5c32f-b8d0-447f-ad2b-a95601f26016.png)
.

**Comment by Jules-WinnfieldX** [comment]
Change the threads number in settings.py

**Comment by IIJlOXOCIIAJl** [comment]
> Change the threads number in settings.py

Need to change the top and bottom lines
![2](https://user-images.githubusercontent.com/95716704/157085172-f8b84882-f5dd-4b15-9f8a-f58c85b97e35.png)
?

**Comment by Jules-WinnfieldX** [comment]
Line 8, Lines 2-6 are comments that explain what everything is.

**Comment by IIJlOXOCIIAJl** [comment]
> Line 8, Lines 2-6 are comments that explain what everything is.

Thanks for the clarification.
