### ISSUE TITLE
[BUG] Cyberdrop raises 'host replacement is not allowed for relative URLs' with cyberdrop.me Archive-Links

### ISSUE THREAD

**Issue by S3rg3-X** [Jules-WinnfieldX/CyberDropDownloader#630]
**Describe the bug**
The URLs.txt contains

![image](https://github.com/Jules-WinnfieldX/CyberDropDownloader/assets/151625269/f489143c-2e99-46d2-a3f8-413ecc21d033)

When running Cyberdrop, it fails both downloads with the reason 'host replacement is not allowed for relative URLs'.
cyberdrop itself works and the download of said archives work.

**To Help Reproduce**
Steps to help reproduce the behavior:
Do above

**Screenshots**
![image](https://github.com/Jules-WinnfieldX/CyberDropDownloader/assets/151625269/02c37d2c-ac92-447b-9f15-220d028670b8)

**Setup Information**
 - OS: Raspbian
 - Cyberdrop Downloader Version: 4.2.216 (freshly updated today)#

**Downloader.log file**
You need to include the downloader.log file after the issue occurs. Majority of the time it's the only way to diagnose issues. 
[downloader.log](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/13425022/downloader.log)

**Comment by S3rg3-X** [comment]
Hi, thanks for answering. I did update as [your wiki ](https://github.com/Jules-WinnfieldX/CyberDropDownloader/wiki/Frequently-Asked-Questions#how-to-update) describes but pip did not show any newer versions.

Now i manually downloaded the newer version and it seems to work.
But despite it shows an error, it still downloads the full album successfully.

![image](https://github.com/Jules-WinnfieldX/CyberDropDownloader/assets/151625269/284ac5ae-f10a-472f-8318-b2d5c49049fc)

![image](https://github.com/Jules-WinnfieldX/CyberDropDownloader/assets/151625269/1b9e33c9-a8a4-4b25-a7ff-886747f63ddc)

**Comment by Jules-WinnfieldX** [comment]
I'd need to see the log for that
