### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Quaso00** [Jules-WinnfieldX/CyberDropDownloader#632]
Hello, I've been using the program smoothly for a long time. First of all, I would like to thank you for providing us with such a useful program. Before getting into the topic, I want to mention that English is not my native language, and I'm using a translation program to write these. If I make any mistakes, I apologize in advance. Now, let me move on to the issue I'm experiencing with the program. I started using another pip application, and during this time, I haven't used Cyberdrop at all. When I tried to use Cyberdrop again, I received the warning I will add below. I have tried every possible solution, but there is no improvement. I haven't installed or uninstalled any programs that could interfere with the program, so unfortunately, I can't tell you what might be causing this issue. The only helpful information I have is the warning that appears when I start the program:
[error.txt](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/13462530/error.txt)

**Comment by Jules-WinnfieldX** [comment]
Cyberdrop-DL does not support python 3.12 right now. You’ll need to uninstall python 3.12 and install python 3.11

**Comment by Quaso00** [comment]
Hello, the error I encountered when deleting Python 12 is resolved. This time, while I can download using 'cyberdropdownloader-master,' I am encountering an error when downloading via 'cyberdrop_DL.V4.' The error message is as follows
[error.txt](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/13462610/error.txt)

**Comment by Jules-WinnfieldX** [comment]
What did you use to install 3.11?
