### ISSUE TITLE
[BUG] Application locks up

### ISSUE THREAD

**Issue by bewbylover** [Jules-WinnfieldX/CyberDropDownloader#636]
**Describe the bug**
When completing the scan or in the process of scanning "https://nudostar.com/forum/threads/jackiebabigirl.65551/" the application locks up and stays that way over night.  

**To Help Reproduce**
Steps to help reproduce the behavior:
1. Populate URLs.txt with "https://nudostar.com/forum/threads/jackiebabigirl.65551/" only
2. Configure the appropriate logins.
3. Start the application.

**Screenshots**

**Setup Information**
 - OS: Ubuntu 20.04.6 LTS
 - python 3.7
 - Cyberdrop Downloader Version # 4.2.226

**Downloader.log file**
You need to include the downloader.log file after the issue occurs. Majority of the time it's the only way to diagnose issues. 

**Additional context**
I waited about 15 minutes but I could have left it that way for hours.
[downloader.log](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/13467919/downloader.log)
![Screenshot from 2023-11-26 11-58-40](https://github.com/Jules-WinnfieldX/CyberDropDownloader/assets/152096820/54a781e5-285b-493f-8330-81b269072496)

**Comment by Jules-WinnfieldX** [comment]
Fixed in 4.2.227

**Comment by bewbylover** [comment]
Thanks it is working now.
