### ISSUE TITLE
[BUG] Error message / scripts hangs (EVERY TIME) at startup

### ISSUE THREAD

**Issue by Ace-Cook** [Jules-WinnfieldX/CyberDropDownloader#640]
**Describe the bug**
For about the past week, EVERY time I try to run CDD, it fails (hangs up) at startup with the following message:
> Z:\CyberDropDownloader> CyberDrop-dl
> Running using command line arguments. If you are trying to use the config file, change 'Apply_Config' to True

For "fun", I tried changing the specified argument in  'Apply_Config' to True -- still hangs up, does not run.
HAVE ALSO UNINSTALLED, REINSTALLED 3-4 TIMES, made sure everything was updated to latest version, etc -- same result.
NOTHING has worked to get around this.

**Screenshots**
![2023-11-28 CyberDropDownloader startup error](https://github.com/Jules-WinnfieldX/CyberDropDownloader/assets/120410609/748fc8de-9c28-44a0-a568-4daac9e01633)

**Setup Information**
 - OS: Windows 10
 - Cyberdrop Downloader Version # 4.2.231

**Downloader.log file**
2023-11-28 04:09:30,137:DEBUG:proactor_events:proactor_events.py:633:Using proactor: IocpProactor

**Additional context**
This started about a week ago.  Have been using CDD regularly for MONTHS without incident.  Frequently prompted to update (awesome!); updates install without incident; also running the latest Python for Windows (python-3.12.0-amd64).

Thanks for any help you can provide.

**Comment by Jules-WinnfieldX** [comment]
> HAVE ALSO UNINSTALLED, REINSTALLED 3-4 TIMES

Do you mean you uninstalled and reinstalled python?

**Comment by Jules-WinnfieldX** [comment]
I think you're issue might be that you're downloading the code base. Can't confirm though. Have you tried the pip/start script method?

**Comment by Ace-Cook** [comment]
No, I don't know that method.  Didn't realize you were here in realtime.  If you could walk me through the exact procedure, I can do it right now ....

**Comment by Jules-WinnfieldX** [comment]
Try downloading the V4 zip here: https://github.com/Jules-WinnfieldX/CyberDropDownloader/releases/tag/Release

put in a link or two in the urls file, and run the start windows bat file

**Comment by Ace-Cook** [comment]
Roger that!

Installing from zip file right now ....

**Comment by Ace-Cook** [comment]
Meant to say "RUNNING from the zip file right now" ....

WOW.  Same error.  After doing all the required update checks, it hangs at the exact same point, after the message:

"Running using command line arguments. If you are trying to use the config file, change 'Apply_Config' to True"

**Comment by Jules-WinnfieldX** [comment]
As a sanity check, to confirm, you aren't running anything as admin?

**Comment by Ace-Cook** [comment]
No..  Just your unaltered batch file.  Is it possible my recently updated Python.exe is running in admin mode without me consciously choosing to start it that way?  Is there a place to check?

**Comment by Jules-WinnfieldX** [comment]
Nah, that should be fine. 

As a second test. Can you try moving the CDL folder to the desktop?

**Comment by Ace-Cook** [comment]
Done.  Ran Start Windows.bat from desktop.  Only 1 link in URLs.txt -- nothing fancy.  Same result.

**Comment by Ace-Cook** [comment]
(from within the V4 FOLDER on the desktop)

**Comment by Jules-WinnfieldX** [comment]
Hmmm. Alright.

Can you try uninstalling 3.12 and install 3.11.4?

**Comment by Ace-Cook** [comment]
Wait ... just realized, there's nothing in that folder but startup batch files and the downloader.  My actually prior installations were on an EXTERNAL drive array.  I'm guessing this batch file is finding your actual code (and Python) via existing PATHS etc.  What's the definitive way to completely purge all traces of CDD and do a "fresh install" on the Windows boot drive?

**Comment by Jules-WinnfieldX** [comment]
So. Complex question.

But it's probably not doing what you think it's doing. The program is likely getting stuck before it can even create any files. 

My current theory is that AIORun (a library I use for CDL) is not compatible with 3.12, hence the asking to downgrade to 3.11.4

But, with that being said. using the pip method (which is used in the script method), simply uninstalling python should remove essentially everything. 

Also not sure if python will play nice if it's installed on an external drive.

**Comment by Jules-WinnfieldX** [comment]
If you were using the python files themselves before, there is no linking that'll take place

**Comment by Ace-Cook** [comment]
OK.  Best I can remember, Python is installed on the BOOT (C:) drive like every other windows app, and CDD was "installed" (basically, just unzipped, right?) on my "Z:" drive.  This setup has worked for literally 2 years -- (since before our last conversation here, where my VPN was interfering with ALL connections.  One of your updates (or one of the VPN's updates) seemed to clear up that problem and it never recurred.  CDD was working for me nonstop without incident for many months in an unchanged (external drive location) thru many updates UNTIL about 2 weeks ago.  The only changes since have been in an effort to get around this startup error.  But I'm happy to tear it out and start from scratch.  I just don't want to miss any pieces lurking in folders I'm not thinking to look in.

**Comment by Ace-Cook** [comment]
Found a possible explanation ... actually have (had) Python 3.11.3 64-bit AND 3.12 64-bit installed.  Thought older version was removed a couple days ago during the 3.12 install, but apparently not.  UNINSTALLING BOTH right now.

**Comment by Ace-Cook** [comment]
PS -- I never "run" Python as an app.  I just run YOUR script and Python does whatever it's required to do by your config.  It's always been transparent to me.  I only interact with your UI.  So, effectively, the only thing I'm ever "running" is your script via the startup .bat file, which I modified last year to run in a continuous loop to retry incomplete/failed files in each link until all files are downloaded (without any duplicates, thanks to your nifty log file working so well).

**Comment by Jules-WinnfieldX** [comment]
You'll probably like the new version that's about to come out soon.

**Comment by Ace-Cook** [comment]
I'm sure I will ... I read your progress dashboard last night.  Looks like another awesome leap forward.

**Comment by Ace-Cook** [comment]
OK, all traces of Python are uninstalled.  So, if I just learned about CDL today and you were instructing me on the BEST install setup for Windows 10, EXACTLY what do you want me to install and in what order?

**Comment by Jules-WinnfieldX** [comment]
https://www.python.org/downloads/release/python-3114/
windows 64 bit installer from above,
make sure you add python to path, as always.

Download that V4 zip as you did. Put links in the txt file, run it. It should take care of the rest.

**Comment by Ace-Cook** [comment]
Ahhhhh ... also found FOUR versions of Python data files in C:\Users\Me\AppData\Local\Programs\Python dating back to Python 3.9 -- just deleted ALL of that.

**Comment by Ace-Cook** [comment]
BREAKTHROUGH !

Unzipped fresh V4 into folder on desktop, adding a single gofile page to URLs and no longer hanging as before. 

So, almost home.  BUT, now I'm getting the "normal" Windows errors that "pip install --upgrade, etc ..."  and  " 'cyberdrop-dl' is not recognized as an internal or external command"

What did I forget to do?

**Comment by Jules-WinnfieldX** [comment]
would 99% of the time be forgetting the path checkbox during installation. Also bedtime here, but I'll reply when I can

**Comment by Ace-Cook** [comment]
OK, THANKS for all the personal help ... I understand (pretty sure I checked the box), but I'm past the insurmountable error message and this is basic windows stuff, so I'll figure it out.  SLEEP WELL and godspeed with V5.  You're awesome!

**Comment by Jules-WinnfieldX** [comment]
Feel free to reopen this if you haven't resolved it, but I'm going to close this for now.
