### ISSUE TITLE
[FEATURE] bring back some of the command-line switches from v4

### ISSUE THREAD

**Issue by baccccccc** [Jules-WinnfieldX/CyberDropDownloader#643]
I am a fan of your project and I'm sponsoring it here on GitHub. However, you're making my life way more difficult with v5 changes. I realize that sometimes tradeoffs must be done in the name of progress. But please, at least consider adding back the `--output-folder` parameter.

I have a long list of forum threads I (re)download periodically. I want to keep these jobs completely separate from one another. The reason is, I frequently examine the logs manually (Errored_Download_URLs.csv, Errored_Scrape_URLs.csv and Unsupported_URLs.csv). And I do not want the same log to have entries from different jobs/different forum threads.

Previously, in v4, I achieved this by changing the _current location_ to a different folder each time before I run the app to download a new forum thread. I also download each thread to a separate folder specified as `--output-folder`.

I realize a can achieve the same (more or less) in v5 by creating multiple configs, one per forum thread. But that would be a bunch of manual work. I would like to avoid that and keep using the command line parameters.

**Comment by Jules-WinnfieldX** [comment]
I'm not sure it's entirely possible. But I will try at some point.

**Comment by ViperCode7** [comment]
Yeah, same here. Used to drop a text file with list on it and it would download. Seems like -i was deemed unnecessary. Now I have no idea how to initiate it fast. I can go the convoluted route of having to manually create a config with a download list every time, since I don't wand the links in one file, nor do I want the past links to be reparsed, but man, was this really necessary?

**Comment by Jules-WinnfieldX** [comment]
// Files
--input-file                       : Manually specify the URLs.txt file to load (path)
--output-folder                    : Manually specify the download directory (path)
--config-file                      : Manually specify the config file to load (path)
--appdata-folder                   : Manually specify where you want to program to store it's AppData folder

Is this sufficient?

**Comment by Jules-WinnfieldX** [comment]
please re-open if the above is insufficient

**Comment by ViperCode7** [comment]
Yes, that's more than sufficient. Thanks!

**Comment by baccccccc** [comment]
> // Files --input-file : Manually specify the URLs.txt file to load (path) --output-folder : Manually specify the download directory (path) --config-file : Manually specify the config file to load (path) --appdata-folder : Manually specify where you want to program to store it's AppData folder
> 
> Is this sufficient?

sorry, I'm a bit late. Thanks for having `--output-folder` parametrized. That's a major improvement for me.

but I'd say the rest is slightly confusing.

1. What exactly is `AppData` folder? Maybe some explanation in documentation could help.

2. Still no way to move logs (including list of errors) into separate folder? (I prefer them to be in output folder, but others can have different scenarios). I know I can manually move them into that folder after the app finishes, and this what I'm doing right now. But it would still be more flexible if we could specify that path as another parameter.

**Comment by Jules-WinnfieldX** [comment]
The AppData folder is where the configs, cache, history DB, and logs are stored. It's the location for CDL to store the files it needs to run. Making things cleaner rather than dumping to a single dir. 

Can you open a new req for --log-folder?
