### ISSUE TITLE
[BUG] Rate Limiting Isssues

### ISSUE THREAD

**Issue by alwayscurious419** [Jules-WinnfieldX/CyberDropDownloader#647]
**Describe the bug**
Rate Limit settings appears to be broken

**To Help Reproduce**
Imported config from V4 which included rate limit settings
Rate limiting settings in Global are not changeable in the UI (see attached file)
Running cyberdrop-dl produces error result checking the file size on every file (also attached)

**Screenshots**
Attached

**Setup Information**
 - OS: Debian 12
 - Cyberdrop Downloader Version # 5.0.14
<img width="991" alt="RatelimitBug-Log" src="https://github.com/Jules-WinnfieldX/CyberDropDownloader/assets/152872399/f44db12c-4f4b-4b66-8dea-47b34e0481a9">
<img width="345" alt="RateLimitBug" src="https://github.com/Jules-WinnfieldX/CyberDropDownloader/assets/152872399/83a9888b-a2ed-4891-8160-e488fc9927c1">

**Comment by Jules-WinnfieldX** [comment]
This should be sorted in 5.0.17 (both issues)
