### ISSUE TITLE
[BUG] 'poetry' is not recognized as an internal or external command, operable program or batch file

### ISSUE THREAD

**Issue by VladPedro** [Jules-WinnfieldX/CyberDropDownloader#649]
'poetry' is not recognized as an internal or external command, operable program or batch file

It happens when I select download.
![2023-12-04 165059](https://github.com/Jules-WinnfieldX/CyberDropDownloader/assets/94541256/67587a90-e9a3-4726-ab65-e55348ef5032)

**Comment by Maqiic** [comment]
try to install poetry manually: https://python-poetry.org/docs/#installing-with-pipx 

curl -sSL https://install.python-poetry.org | python -
 or 
pip install poetry
