### ISSUE TITLE
[FEATURE] wirking wuth putmega/sub albums

### ISSUE THREAD

**Issue by Aliaksandr3by** [Jules-WinnfieldX/CyberDropDownloader#65]
this program don't work with subfolder from putmega.

![image](https://user-images.githubusercontent.com/11432724/157219307-ebe82c0b-1aef-4835-a241-c2291069281d.png)

example: only +18 years old
[https://putmega.com/album/rocksy-light-full-collection.ryAqq/sub](url)

**Comment by Jules-WinnfieldX** [comment]
replying so I remember also to add Erome support

**Comment by Jules-WinnfieldX** [comment]
Hey, this is complete.

**Comment by Aliaksandr3by** [comment]
thx.
but, I think it is not working. It downloads photos only from the main page, but don't from the Sub Albums.

**Comment by Jules-WinnfieldX** [comment]
Toss me a link you are using to test this.

**Comment by Aliaksandr3by** [comment]
+18
https://putmega.com/album/rocksy-light-full-collection.ryAqq/sub

**Comment by Jules-WinnfieldX** [comment]
take off the /sub and it'll work. It's filtering out due to it considering the /sub as a duplicate url. I'll patch that in the next release, but that's the work around for you.

**Comment by Aliaksandr3by** [comment]
thx, it worked.
