### ISSUE TITLE
[BUG] Unhandled exception; stopping loop: 'Task exception was never retrieved'

### ISSUE THREAD

**Issue by VladPedro** [Jules-WinnfieldX/CyberDropDownloader#650]
I am using the quickstart version. i installed the latest version of python. i got this error when running the script.
![2023-12-04 165059](https://github.com/Jules-WinnfieldX/CyberDropDownloader/assets/94541256/2e63c8c1-920e-4673-b055-880a80c09e3d)

**Comment by Jules-WinnfieldX** [comment]
You'll need to upgrade python to 3.10 or higher. You can see how to do that here: https://jules-winnfieldx.gitbook.io/cyberdrop-dl/quick-start
