### ISSUE TITLE
Skipped by configuration

### ISSUE THREAD

**Issue by LFS900** [Jules-WinnfieldX/CyberDropDownloader#651]
I used to be able to download everything perfectly but since the update, it just skips ALL the files. I haven't configured anything, I even tried importing my old configuration but it just keeps skipping ALL files. I'm not the best with these programs. But the default settings do this.

**Comment by asdgif** [comment]
Yeah, same...

I was in the middle of downloads and had to restart my comp. Normally it just continues where it left off when I close it but now I came back
only for it to say that it is on version .5 even though it isn't and even though I never wanted to upgrade.
So, tried the new version and tried to import all the others from the previous build but it doesn't even want to even attempt to identify the files and is re-downloading everything from the very beginning.

The previous build (.4) is just skipping everything now.

**Comment by Jules-WinnfieldX** [comment]
> I used to be able to download everything perfectly but since the update, it just skips ALL the files. I haven't configured anything, I even tried importing my old configuration but it just keeps skipping ALL files. I'm not the best with these programs. But the default settings do this.

in the ui -> manage configs -> edit config -> edit ignore options

make sure none of the circles are filled in.

**Comment by LFS900** [comment]
![afbeelding_2023-12-04_183000755](https://github.com/Jules-WinnfieldX/CyberDropDownloader/assets/94140540/019f8f4e-04bf-404f-89ad-4e34cce5cf14)
None of them are marked

**Comment by Jules-WinnfieldX** [comment]
And when you try to download, all the files are skipped as by configuration?

**Comment by asdgif** [comment]
Yeah, it just skips it.

At first it was saying that it, "downloads failure" then it mentioned to get the new .5 build
Tried both, not working anymore

**Comment by asdgif** [comment]
New version works but it doesn't bother to check for my previously downloaded files that I put in its folder

**Comment by LFS900** [comment]
> > I think the update that was pushed somehow overwrote all of the previous builds.
> > I looked at the download page for .5 and says if I use command prompt, etc for downloads I don't need the update but I was forced to get it and have it anyways?
> > Nothing is ticked for me either in the new version.
> 
> By command prompt, that means you do the pip install yourself.
> 
> By the sounds of it, you are using a start script, which runs in cmd.

Yes, I'm using CMD indeed. 
![afbeelding_2023-12-04_183343246](https://github.com/Jules-WinnfieldX/CyberDropDownloader/assets/94140540/38b4e4de-24e6-4314-b54a-280c7e9bf2f1)
I still use the "start windows"

**Comment by asdgif** [comment]
![Screenshot_874](https://github.com/Jules-WinnfieldX/CyberDropDownloader/assets/145245235/329d43c4-e041-41ec-a99a-b54e94887b36)

This is all that it prints

**Comment by LFS900** [comment]
![image](https://github.com/Jules-WinnfieldX/CyberDropDownloader/assets/94140540/6094509c-ce98-40ca-929e-81af5c5f144a)

**Comment by Jules-WinnfieldX** [comment]
> ![Screenshot_874](https://private-user-images.githubusercontent.com/145245235/287782918-329d43c4-e041-41ec-a99a-b54e94887b36.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3MTE1OTYsIm5iZiI6MTcwMTcxMTI5NiwicGF0aCI6Ii8xNDUyNDUyMzUvMjg3NzgyOTE4LTMyOWQ0M2M0LWUwNDEtNDFlYy1hOTlhLWI1NGU5NDg4N2IzNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwNFQxNzM0NTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mODkyNTBjMTcwZWVkNGJkYTQwNjU1OTYwYzAzMDlkZDJlMWU1YjQyZTAxZTY4YmIyOGZlOWVhMjM4OWVmMmUzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1e0743mRRIv4kslkEJG0r1lMpPJQxDjD-lGFMr9p9EE)
> 
> This is all that it prints

Yea. So this isn't skipping anything. It's just the urls.txt file being a different file. Try editing it in the UI

**Comment by Jules-WinnfieldX** [comment]
> ![image](https://private-user-images.githubusercontent.com/94140540/287783129-6094509c-ce98-40ca-929e-81af5c5f144a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3MTE2MzUsIm5iZiI6MTcwMTcxMTMzNSwicGF0aCI6Ii85NDE0MDU0MC8yODc3ODMxMjktNjA5NDUwOWMtY2U5OC00MGNhLTkyOWUtODFhZjVjNWYxNDRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA0VDE3MzUzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVmNmYxY2YyODFhNWU1MzZlOTRhNjc2YTg4YmZiMjQ3ZGU4YjE2ZmQwZjAyYjYxZjdjZDRjOGU1N2VlODJhY2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4qGtDr4BbGRyEipbbSV6zC7qdOeIHZ3l_nRax558OUo)

Can you send me the downloader.log file? 

https://jules-winnfieldx.gitbook.io/cyberdrop-dl/frequently-asked-questions#where-is-the-downloader.log-file

**Comment by asdgif** [comment]
Tried changing the directory of the URLs.txt file to the location of the downloader (even though it was also in AppData) with no success, still skipping.

**Comment by Jules-WinnfieldX** [comment]
> Tried changing the directory of the URLs.txt file to the location of the downloader (even though it was also in AppData) with no success, still skipping.

Oh I see. Yea. I'll try and fix that now.

**Comment by asdgif** [comment]
The new files (from .5) that were generated went into Cyberdrop_DL.V4(2)\Downloads\Cyberdrop-DL Downloads| that directory, even when I try to move my files there it still skips and on the new version, again, it doesn't bother to detect the files already present.

**Comment by Jules-WinnfieldX** [comment]
> The new files (from .5 even though this was on .4) that were generated went into Cyberdrop_DL.V4(2)\Downloads\Cyberdrop-DL Downloads| that directory, even when I try to move my files there it still skips and on the new version, again, it doesn't bother to detect the files already present.

As I keep saying the download directory has changed, unless you change it in the config. 

One thing at a time my guy. 

If you're saying you've changed them, then I'd need to see the log file.

**Comment by asdgif** [comment]
.4 has the Downloads directory and .5 has a new downloads directory, Downloads\Cyberdrop-DL Downloads

How would other people know this? If they were forced to get the .5 update anyways then their files are presumably "lost" too.

Is it possible just to roll it back or how do I opt out lol It was working perfect and flawlessly for me before.

Also, things are being re-directed to my windows drive and appdata, you're telling me that I have to go into the UI to redirect and reset? ehhh brother, also found out that every downloader has a global setting now so looks like downloading other versions doesn't matter or even if you have configs setup in the previous version's folder.


Edit: Okay, got it to work but now scraping has a queue, won't detect the other folders because now there is a new directory for the URLs so it is creating a whole nother folder and REDOWNLOADING everything.

**Comment by asdgif** [comment]
![Screenshot_875](https://github.com/Jules-WinnfieldX/CyberDropDownloader/assets/145245235/ea5805b6-a036-41a7-8ec0-2c1da347edc6)

For example, this is why old files can't be detected and I have no idea why scraping now has a queue rather than going through everything first and then downloading like the previous versions.

**Comment by asdgif** [comment]
Ahh, I see. 

Sorry I'm doing 4 things at once including work so
![Screenshot_876](https://github.com/Jules-WinnfieldX/CyberDropDownloader/assets/145245235/848cecc5-5833-487f-9484-fc1ab89bf228)

This fixed all my issues.

**Comment by asdgif** [comment]
@LFS900 See if that also fixes your issue (:

**Comment by Jules-WinnfieldX** [comment]
@LFS900 I figured out your issue.

It's skip_download_mark_complete is set as true. It was set as true somehow for some people in the config transfer. 

Set it to false.

**Comment by LFS900** [comment]
No, I figured out what it was. Something stupid. You did help me however! As I was checking out the file to change that configurations to false, I noticed it skipped the files due to insufficient space. The download folder was changed to my C drive. Which was too full. All downloads should go to my D drive. I changed the output folder and everything works just fine.

**Comment by Jules-WinnfieldX** [comment]
Love it. Glad you got it working
