### ISSUE TITLE
[FEATURE] Replace OpenCV

### ISSUE THREAD

**Issue by qarkai** [Jules-WinnfieldX/CyberDropDownloader#653]
**Is your feature request related to a problem? Please describe.**
Using `opencv-python` only for getting video metadata looks like overkill. It pulls a lot of dependencies if installed via distro's package manager (not pip/pipx).

**Describe the solution you'd like**
Use something more specific for the task. e.g. `ffmpeg-python`, `get-video-properties`, `enzyme` (probably outdated) etc.
If this is not an option could you at least make OpenCV an optional dependency?

**Comment by Jules-WinnfieldX** [comment]
I was trying to find something such as get-video-properties. Not sure how it didn't cross my path. I'll replace it now.

**Comment by Jules-WinnfieldX** [comment]
Going up now. 5.0.24

**Comment by qarkai** [comment]
Probably `get-video-properties` can also replace `mutagen`.
