### ISSUE TITLE
[BUG] Unhandled exception; stopping loop: 'Task exception was never retrieved' after v5 upgrade

### ISSUE THREAD

**Issue by Bobothebo** [Jules-WinnfieldX/CyberDropDownloader#655]
**Describe the bug**
When i try to download i get this error above the colorful status screen.
"Cyberdrop Downloader (V5.0.14)
Current Config: Default
? What would you like to do? Download
Unhandled exception; stopping loop: 'Task exception was never retrieved'
Traceback (most recent call last):
  File "/home/dave/.local/lib/python3.8/site-packages/cyberdrop_dl/scraper/scraper.py", line 323, in map_urls
    scrape_item: ScrapeItem = await self.manager.queue_manager.url_objects_to_map.get()
  File "/usr/lib/python3.8/asyncio/queues.py", line 163, in get
    await getter
RuntimeError: Task <Task pending name='Task-45' coro=<ScrapeMapper.map_urls() running at /home/dave/.local/lib/python3.8/site-packages/cyberdrop_dl/scraper/scraper.py:323>> got Future <Future pending> attached to a different loop"

It just hangs at the download screen. 

**Setup Information**
 - OS: Linux 5.4.0-166-generic #183-Ubuntu
 - Cyberdrop Downloader Version 5.0.14

[downloader.log](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/13550792/downloader.log)

**Comment by Jules-WinnfieldX** [comment]
I'll leave this open, but locked. You will need to upgrade to python 3.10 or 3.11 (not 3.12).

You can find how to do that here: https://jules-winnfieldx.gitbook.io/cyberdrop-dl/quick-start
