### ISSUE TITLE
Poetry could not find a pyproject.toml file in N:\ or its parents

### ISSUE THREAD

**Issue by rdsxfn2004** [Jules-WinnfieldX/CyberDropDownloader#657]
I have Cyberdrop in one of my external drives and I can download fine but the error in the Title keeps coming up.

![image](https://github.com/Jules-WinnfieldX/CyberDropDownloader/assets/148468123/a96ee11d-b27b-4507-8f23-c93edc817905)
**Setup Information**
 - OS: [e.g. Windows 10, Mac OS X Sierra, etc]
 - Cyberdrop Downloader Version # V5.0.26

**Downloader.log file**

**Additional context**

**Comment by Jules-WinnfieldX** [comment]
This can be ignored. It doesn't actually hinder anything

**Comment by rdsxfn2004** [comment]
I noticed it does not stop anything from running.  Just wanted to report it.  Thanks!  You do an awesome job!
