### ISSUE TITLE
[?] 429 HTTP Status

### ISSUE THREAD

**Issue by Aliaksandr3by** [Jules-WinnfieldX/CyberDropDownloader#658]
I don't know why, but I got plenty of 429 HTTP Status with cyberdrop .
429 Too Many Requests
maybe it is a bug?
if  I copy the link to browser all work as good.

![image](https://github.com/Jules-WinnfieldX/CyberDropDownloader/assets/11432724/7883c3e6-372d-408d-88c8-b4ea64ef95e2)

**Comment by Jules-WinnfieldX** [comment]
It's not really a bug. It's cyberdrop saying you're accessing too much too fast. The internal ratelimits try to prevent it, but only so good I can try and make them.

**Comment by Aliaksandr3by** [comment]
might you do randomize that will swap random hosts?

**Comment by Aliaksandr3by** [comment]
e.g. no cyberdrop in sequence.

**Comment by Jules-WinnfieldX** [comment]
You can increase the delay between downloads in the config, I believe for Cyberdrop it's already set to 1 second internally.

**Comment by Aliaksandr3by** [comment]
can you tell to me where is it?
\Cyberdrop-DL\Cyberdrop-DL\Configs\Default\settings.yaml

**Comment by Jules-WinnfieldX** [comment]
it's in global settings, one folder up from that
