### ISSUE TITLE
[BUG] celebforum support

### ISSUE THREAD

**Issue by secondapejs** [Jules-WinnfieldX/CyberDropDownloader#659]
I've just upgraded to V5 and I tried downloads with my common forums (simpcity and socialmediagirls) and everything works fine.
Celebforum doesn't work although I'm pretty sure I provided the right credentials (login + xf user cookie) in "authentification.yaml". 
It gets stuck in the scraping process (screenshot)

![Screenshot 2023-12-04 223347](https://github.com/Jules-WinnfieldX/CyberDropDownloader/assets/132111898/0f5a21fd-d676-44db-87bd-ef23ee9cd522)

**Setup Information**
 - OS: Windows 11
 - Cyberdrop Downloader Version: 5.0.26

Downloader.log file
 
[downloader.log](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/13551558/downloader.log)

**Comment by secondapejs** [comment]
Maybe it is a Layer 8 problem, I'm not 100% sure, maybe u can test it with some login credentials of you

**Comment by Jules-WinnfieldX** [comment]
Try removing the XF token and see if it solves the issue for you

**Comment by secondapejs** [comment]
I tried that and unfortunately it's the same outcome

**Comment by Jules-WinnfieldX** [comment]
Possibly. Though unsure. Special characters do weird things.

**Comment by secondapejs** [comment]
okay i changed my password now and this wasn't the fix. Is there some way u can test it yourself if celebforum works on your system?

**Comment by Jules-WinnfieldX** [comment]
Yea. I'm calling it quits for today though. I'll look tomorrow

**Comment by Maqiic** [comment]
Yeah same issue here, scraper gets frozen and even escape from console does not work

**Comment by yada-yoda** [comment]
I noticed with smg forum if you login in a private window, it's asking for a captcha, would this be part of the issue? It's a 410 http error on my end.

**Comment by Jules-WinnfieldX** [comment]
> I noticed with smg forum if you login in a private window, it's asking for a captcha, would this be part of the issue? It's a 410 http error on my end.

yes. You need to use the XF session cookie for it, either manually or using the built in extractor in the UI.

**Comment by Jules-WinnfieldX** [comment]
> > > I noticed with smg forum if you login in a private window, it's asking for a captcha, would this be part of the issue? It's a 410 http error on my end.
> > 
> > 
> > yes. You need to use the XF session cookie for it, either manually or using the built in extractor in the UI.
> 
> For me the scrapper shows even with the session cookie 0 Files

toss me a log, and I'll look.
