### ISSUE TITLE
[BUG] 2.3.5 doesn't works while 2.3.4 still does

### ISSUE THREAD

**Issue by jtm666** [Jules-WinnfieldX/CyberDropDownloader#66]
\Python\Python310\site-packages\twisted\internet\main.py", line 32, in installReactor
    raise error.ReactorAlreadyInstalledError("reactor already installed")
twisted.internet.error.ReactorAlreadyInstalledError: reactor already installed

^ Something like that, anyway thank you for your contribution, nice downloader.

**Comment by jtm666** [comment]
update: ok so did some download early and it seems that does has it issue as you have mentioned in the changelog (resulting in a empty video file), but 2.3.5 simply doesn't work, not for me at least

**Comment by jtm666** [comment]
update 2: Sorry this is probably my fault since 2.3.5 does work now after realizing I forgot to turn off anti-virus, testing it now, will update ones the results are in.

**Comment by jtm666** [comment]
update 3: Yep seems that downloader 2.3.5 is working probably and download 2 files at a time, case closed.

**Comment by dn8sh6HY** [comment]
I've been getting the same reactor error - how did you fix that? I don't have antivirus running.

**Comment by Jules-WinnfieldX** [comment]
> I've been getting the same reactor error - how did you fix that? I don't have antivirus running.

https://github.com/Jules-WinnfieldX/CyberDropDownloader/archive/refs/heads/master.zip
try this.

Sorry for high jacking jtm666.
