### ISSUE TITLE
[FEATURE] remove (source) tag from folder name

### ISSUE THREAD

**Issue by hrm-princess-fluffybutt** [Jules-WinnfieldX/CyberDropDownloader#661]
**Is your feature request related to a problem? Please describe.**
when downloading from xx from source, it will create a folder: xx (source)

**Describe the solution you'd like**
Please have a config option to switch between "xx (source)" and "xx"

the second one doesn't have the (source) appended to it

**Additional context**
.party sites used to be the only one that had the (source) appendage. now everything has it. choice please.

**Comment by Proutbedaine** [comment]
> **Is your feature request related to a problem? Please describe.** when downloading from xx from source, it will create a folder: xx (source)
> 
> **Describe the solution you'd like** Please have a config option to switch between "xx (source)" and "xx"
> 
> the second one doesn't have the (source) appended to it
> 
> **Additional context** .party sites used to be the only one that had the (source) appendage. now everything has it. choice please.

That'd be indeed very much appreciated. c:

**Comment by Jules-WinnfieldX** [comment]
--remove-domains-from-folder-names (and similar config setting)
