### ISSUE TITLE
[BUG] - Poetry error with Windiows Start file

### ISSUE THREAD

**Issue by NiicOw974** [Jules-WinnfieldX/CyberDropDownloader#662]
OS : Windows 11
Python version : 3.11.4

When I execute the windows start file in release package, all download are successfull but I have finaly this error message :

Installing Cyberdrop-Dl

Poetry could not find a pyproject.toml file in C:\Users\User\Downloads\Cyberdrop_DL.V5 or its parents
usage: cyberdrop-dl [-h] [-V] [--config CONFIG] [--download] [--download-all-configs]
                    [--block-download-sub-folders] [--disable-download-attempt-limit] [--disable-file-timestamps]
                    [--include-album-id-in-folder-name] [--include-thread-id-in-folder-name]
                    [--remove-generated-id-from-filenames] [--skip-download-mark-completed]
                    [--maximum-image-size MAXIMUM_IMAGE_SIZE] [--maximum-video-size MAXIMUM_VIDEO_SIZE]
                    [--maximum-other-size MAXIMUM_OTHER_SIZE] [--minimum-image-size MINIMUM_IMAGE_SIZE]
                    [--minimum-video-size MINIMUM_VIDEO_SIZE] [--minimum-other-size MINIMUM_OTHER_SIZE]
                    [--exclude-videos] [--exclude-images] [--exclude-audio] [--exclude-other]
                    [--ignore-coomer-ads]
                    [--skip-hosts {bunkrr,celebforum,coomer,cyberdrop,cyberfile,e-hentai,erome,fapello,f95zone,gofile,hotpic,ibb.co,imageban,imgbox,imgur,img.kiwi,jpg.church,jpg.homes,jpg.fish,jpg.fishing,jpg.pet,jpeg.pet,jpg1.su,jpg2.su,jpg3.su,kemono,leakedmodels,mediafire,nudostar.com,nudostar.tv,omegascans,pimpandhost,pixeldrain,postimg,reddit,redd.it,redgifs,rule34.xxx,rule34.xyz,saint,scrolller,simpcity,socialmediagirls,toonily,xbunker,xbunkr}]
                    [--only-hosts {bunkrr,celebforum,coomer,cyberdrop,cyberfile,e-hentai,erome,fapello,f95zone,gofile,hotpic,ibb.co,imageban,imgbox,imgur,img.kiwi,jpg.church,jpg.homes,jpg.fish,jpg.fishing,jpg.pet,jpeg.pet,jpg1.su,jpg2.su,jpg3.su,kemono,leakedmodels,mediafire,nudostar.com,nudostar.tv,omegascans,pimpandhost,pixeldrain,postimg,reddit,redd.it,redgifs,rule34.xxx,rule34.xyz,saint,scrolller,simpcity,socialmediagirls,toonily,xbunker,xbunkr}]
                    [--ignore-history] [--skip-check-for-partial-files] [--skip-check-for-empty-folders]
                    [--delete-partial-files] [--send-unsupported-to-jdownloader]
                    [link ...]
cyberdrop-dl: error: unrecognized arguments: --portable
Appuyez sur une touche pour continuer...

Can you help me ?

**Comment by Jules-WinnfieldX** [comment]
Yea. https://github.com/Jules-WinnfieldX/CyberDropDownloader/releases/tag/Release

download the 5.1 zip here, and try the file in it.

**Comment by NiicOw974** [comment]
Sorry I had not seen the new version. Indeed with version 5.1 everything is back in order.

Thank you for your reactivity

**Comment by Jules-WinnfieldX** [comment]
No worries, I kinda snuck it out there quickly hoping to get it out before more people downloaded the old one.
