### ISSUE TITLE
[FEATURE] Reintroduce Pixl support

### ISSUE THREAD

**Issue by slitchampion** [Jules-WinnfieldX/CyberDropDownloader#665]
V5 removed Pixl support. Please consider reintroducing support for Pixl.

**Comment by Jules-WinnfieldX** [comment]
As pixl is shutting down, I won't be re-adding support.

**Comment by baccccccc** [comment]
well, arguably, *because* it's shutting down, we need an option to bulk download the remaining contents the most at this time :)
