### ISSUE TITLE
I'm not able to update the version from from 4 to 5 even after I uninstall and installed v5 it keeps saying you are on v4 update to v5 why[BUG]

### ISSUE THREAD

**Issue by poojitha-poojip** [Jules-WinnfieldX/CyberDropDownloader#666]
**Describe the bug**
I'm not able to update the version from from 4 to 5 even after I uninstall and installed v5 it keeps saying you are on v4 update to v5 why[BUG]
Make sure to read the FAQ here first: https://github.com/Jules-WinnfieldX/CyberDropDownloader/wiki

**To Help Reproduce**
Steps to help reproduce the behavior:

- Not able to  upgrade to v5

**Screenshots**
[Image 1](https://imgur.com/YQQt2Re)
[Image 2
](https://imgur.com/Mgb3dct)
**Setup Information**
 - OS: Windows 11
 - Cyberdrop Downloader Version v5.1

**Downloader.log file**
You need to include the downloader.log file after the issue occurs. Majority of the time it's the only way to diagnose issues.

**Comment by Jules-WinnfieldX** [comment]
You likely are on a python version below 3.10, You'll need to update it. You can see here how to: https://jules-winnfieldx.gitbook.io/cyberdrop-dl/quick-start
