### ISSUE TITLE
[BUG] can't update

### ISSUE THREAD

**Issue by kissnyul** [Jules-WinnfieldX/CyberDropDownloader#667]
When I try to update from v4 i always get the same error.

"urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)>"

**Setup Information**
 - OS: Mac OS X Sonoma 14.2
 - Cyberdrop Downloader Version v.5.1.

**Comment by Maqiic** [comment]
Open the folder /Applications/Python 3.x (x is the version you are running).
Double click the Install Certificates.command. It will open a terminal and install the certificate.

**Comment by Jules-WinnfieldX** [comment]
What Magiic stated is correct and should fix it.
