### ISSUE TITLE
Traceback frozen runpy

### ISSUE THREAD

**Issue by rdsxfn2004** [Jules-WinnfieldX/CyberDropDownloader#670]
AppData being renamed AppData_OLD

Ran the bat file yesterday no issues.  Today, getting the below error.  Restarted computer already

![image](https://github.com/Jules-WinnfieldX/CyberDropDownloader/assets/148468123/293101ca-f562-46b0-adf9-53203718d907)

**Setup Information**
 - OS: Windows 11
 - Cyberdrop Downloader Version # 5.0.35

DOwnloader.log file does not show error, just old file from last night

**Comment by Jules-WinnfieldX** [comment]
Here's what you need to do: 

Put all the files and folders in `C:\Users\JFeen\AppData\Local\Cyberdrop-DL\Cyberdrop-DL` into a new folder called `AppData`

Move that `AppData` folder you just made to wherever you are running the script. 

Then delete the Cyberdrop-DL folder in `C:\Users\JFeen\AppData\Local\`

**Comment by rdsxfn2004** [comment]
Performed those tasks in above comment and got the following error:

![image](https://github.com/Jules-WinnfieldX/CyberDropDownloader/assets/148468123/f9f01e66-04bd-4216-859b-3155b893f6a0)

**Comment by Jules-WinnfieldX** [comment]
Easier fix on that one. https://github.com/Jules-WinnfieldX/CyberDropDownloader/releases/tag/Release

grab the 5.1 zip there and use the start file that's inside it instead of the current one you are. 

Sorry for the rollercoaster
