### ISSUE TITLE
[FEATURE] Stop making imaginary "changes" to URLs.txt

### ISSUE THREAD

**Issue by crimzind** [Jules-WinnfieldX/CyberDropDownloader#675]
**Is your feature request related to a problem? Please describe.**
I don't use the in-app URLs editor. I'm doing what I've been doing since I started using CDL, and I keep my URLs.txt open in a NotePad++ tab. Every time CDL runs now, it updates the file in some way, but doesn't make any actual changes. It triggers NP++ prompting me to reload the (still identical content-wise) file. I've often got unsaved notes or other URLs in that doc for future use that I'd rather stop getting prompts to accidentally toss.

**Describe the solution you'd like**
Just... stop saving non-"changes" to that doc that, please.

**Comment by Jules-WinnfieldX** [comment]
I'll sort that out soon

**Comment by crimzind** [comment]
I appreciate that.

**Comment by Jules-WinnfieldX** [comment]
Just pushed 5.0.44

It should stop URLs.txt being touched inappropriately
