### ISSUE TITLE
[FEATURE] interface modification

### ISSUE THREAD

**Issue by Gaetann18** [Jules-WinnfieldX/CyberDropDownloader#676]
hello, since the new interface one no longer sees the folders being downloaded as before. Will it come back?
Thank you for your work !

**Comment by Jules-WinnfieldX** [comment]
Hey Gaetann,

The newest version should have moved downloads back to the directory you are running Cyberdrop-DL from. 

If that's not what you mean, you may need to clarify for me

**Comment by Gaetann18** [comment]
Not that at all, on the front download interface in the middle of the screen we had a progress bar/link/folder being downloaded. Now we no longer have this option.

**Comment by Jules-WinnfieldX** [comment]
Ohhh, yea. No that's unfortunately gone. it wouldn't have worked well with having downloads going at the same time as the scraping.
