### ISSUE TITLE
[BUG] V4 Database not Imported to V5

### ISSUE THREAD

**Issue by yada-yoda** [Jules-WinnfieldX/CyberDropDownloader#677]
**Describe the bug**
My Cyberdropdownloader updated to V5 and no longer understand if past URLs have been downloaded or not.

**To Help Reproduce**
Steps to help reproduce the behavior:
1. Launch CyberDrop

**Setup Information**
 - OS: Windows 10
 - Cyberdrop Downloader Version #5

**Downloader.log file**
It becomes blank after each time the bat file is used to start since the bat file from V4 had the upgrade cybderdopdl inside of it - it almost reinstalls a new instance pretty much.

**Additional context**
I have this hosted on the D drive, but that shouldn't matter as in the past it worked fine. I did notice that Cyberdrop V5 created a AppData folder at the root of the Cryberdrop folder once installed, in the past it was located in the actual C drive appdata folder, which seems to be empty now. To make matters worse it seems the folder names also have a new naming conjunction with the scraped site in parenthesis - example past name: Loose Bunkr Files, new name: Loose Files (Bunkr) etc.

**Comment by Jules-WinnfieldX** [comment]
It's been a rollercoaster the last couple days. But yes. It was in appdata now it's in the directory where your start file is. It was directly copied over from the appdata folder that is now empty. 

As for the history, it should've been imported automatically, but if it wasn't, you can likely find it in Old_Files next to the new appdata folder, and you can import it using the ui in the tool.
