### ISSUE TITLE
[BUG] Multiple "(1)" in partial downloads

### ISSUE THREAD

**Issue by eldar-dniaprouski** [Jules-WinnfieldX/CyberDropDownloader#678]
**Describe the bug**
Unfinished partial downloads get (1) in name. If next try also fails there are will be (1) (1) and so on until it downloaded.

**To Help Reproduce**
Just try to download something big and lose connection.

**Screenshots**
![2023-12-05_223144](https://github.com/Jules-WinnfieldX/CyberDropDownloader/assets/58551098/09cd6f6b-3abd-49e3-9b67-5ad24d0773bf)
![2023-12-05_223154](https://github.com/Jules-WinnfieldX/CyberDropDownloader/assets/58551098/5ed27685-8ffa-4cf4-aa49-048ab242dbd8)

**Comment by Jules-WinnfieldX** [comment]
yikes

**Comment by Jules-WinnfieldX** [comment]
Can you provide a log file? https://jules-winnfieldx.gitbook.io/cyberdrop-dl/frequently-asked-questions#where-is-the-downloader.log-file

**Comment by eldar-dniaprouski** [comment]
[downloader.zip](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/13572332/downloader.zip)

**Comment by eldar-dniaprouski** [comment]
It's started with one (1), now it's like this. I've deleted first files unfortunately.
![2023-12-05_230117](https://github.com/Jules-WinnfieldX/CyberDropDownloader/assets/58551098/20b6bc37-5932-40b4-8376-a5989e4a495e)

**Comment by Jules-WinnfieldX** [comment]
This one will be a bit more tricky. But can you send me your cyberdrop.db file from ./appdata/cache

**Comment by eldar-dniaprouski** [comment]
File is to big, here Google Drive link
https://drive.google.com/file/d/1q6j12nMYjQh8hSF4mRFUUDyiEr2QtLUN/view?usp=sharing

**Comment by eldar-dniaprouski** [comment]
Thank you. Will wait for solution.

**Comment by Jules-WinnfieldX** [comment]
5.0.39 is going up now. 

Fun thing here, you already downloaded that file previously. So it likely won't download with 5.0.39, but it should also fix the (1) issue.

**Comment by eldar-dniaprouski** [comment]
Thank you very much. I'll try it right away.

**Comment by eldar-dniaprouski** [comment]
It seems working alright. Thanks again.
