### ISSUE TITLE
[BUG] Bunkr download video doesn't works [2.4.0]

### ISSUE THREAD

**Issue by NimbusCloudVoid** [Jules-WinnfieldX/CyberDropDownloader#68]
**Describe the bug**
A clear and concise description of what the bug is. INCLUDE THE FULL STACK TRACE.
Did the usual thing but this time 2 bunkr links i wanted to download didn't worked
 
**To Help Reproduce**
Steps to help reproduce the behavior:
1. Describe the bug accurately.
Dunno if i'm allowed to post nsfw links from bunkr so if you need them just tell me and i will post them
 
2. Provide an example album that showcases it (only containing non-copyright SFW images).

3. Make sure you are updated to the latest version to see if it's already fixed.
I'm on the latest version to date [2.4.0]

**Screenshots**
https://i.imgur.com/JiC6Q3P.png

**Setup Information**
 - OS: Win10
 - Cyberdrop Downloader Version #2.4.0

**Additional context**
Add any other context about the problem here. Bonus points for uploading your logs.log file.
https://i.imgur.com/iEsesQy.png sorry, i don't have a paste bin for the logs

**Comment by Jules-WinnfieldX** [comment]
Toss me those links then I'll just edit the comment to remove them when I have them. Will make it a lot easier for testing

**Comment by NimbusCloudVoid** [comment]
https://stream.bunkr.is/v/[OnlyFans]-Electra-Rayne-&-Dredd---Third-Appearance-(23-01-2022)-1080p-q4AEqiYF.mp4
https://stream.bunkr.is/v/[OnlyFans]-Wednesday-Nyte-&-Dredd-(28-02-2022)-1080p-0CYxkmdq.mp4
here

**Comment by Jules-WinnfieldX** [comment]
https://github.com/Jules-WinnfieldX/CyberDropDownloader/archive/refs/heads/master.zip
try this. This should fix it. I'll post it as an actual release after I help some other people and see if there are more bugs that need fixing.

**Comment by NimbusCloudVoid** [comment]
It works! Thanks!
