### ISSUE TITLE
[BUG] Crashed while sorting on v5.0.41 (see logs)

### ISSUE THREAD

**Issue by Proutbedaine** [Jules-WinnfieldX/CyberDropDownloader#680]
**Describe the bug**
Crashed while sorting on v5.0.41 (see logs)

**Screenshots**
![image](https://github.com/Jules-WinnfieldX/CyberDropDownloader/assets/81118140/b193d293-755d-4fb1-9e43-8844c741ab82)

**Setup Information**
 - OS: Win10 
 - Cyberdrop Downloader Version # 5.0.41

**Downloader.log file**
[downloader.log](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/13572814/downloader.log)

**Comment by Jules-WinnfieldX** [comment]
5.0.42 should solve that.
