### ISSUE TITLE
[BUG] Crashed while sorting on 5.0.42 (see logs)

### ISSUE THREAD

**Issue by Proutbedaine** [Jules-WinnfieldX/CyberDropDownloader#681]
**Describe the bug**
Crashed while sorting on 5.0.42 (see logs)

**Screenshots**
![image](https://github.com/Jules-WinnfieldX/CyberDropDownloader/assets/81118140/84e38ce2-607c-4b0c-bc09-023445a72f50)

**Setup Information**
 - OS: Win10 
 - Cyberdrop Downloader Version # 5.0.42

**Downloader.log file**
[downloader.log](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/13573322/downloader.log)

**Comment by Jules-WinnfieldX** [comment]
5.0.43. If it can't open the image, it'll use a "unknown" string value for the resolution if you're including that in the sort filename.
