### ISSUE TITLE
[FEATURE] specify config location

### ISSUE THREAD

**Issue by hrm-princess-fluffybutt** [Jules-WinnfieldX/CyberDropDownloader#682]
**Is your feature request related to a problem? Please describe.**
specifying the config right now only takes the name of the config, not path. it only looks in the folder it's launched from, or in the case of the initial versions of v5 appdata

**Describe the solution you'd like**
--config should be able to take paths

**Comment by Jules-WinnfieldX** [comment]
5.0.44 introduces
--input-file
--output-folder
--config-file
--appdata-folder
