### ISSUE TITLE
[FEATURE] multiple instance, multiple logs using same config

### ISSUE THREAD

**Issue by hrm-princess-fluffybutt** [Jules-WinnfieldX/CyberDropDownloader#683]
**Is your feature request related to a problem? Please describe.**
running multiple instances using the same config is no longer possible
it now locks the .log file, which will result in erroring out of any further instances

**Describe the solution you'd like**
maybe don't overwrite .log?
timestamp new ones each time, some sort of cleanup function to only keep newest 5-10?

**Additional context**
i usually pass links to the program straight from my browser
i have a giant urls.txt backlog but so many new things catch my eye
so i think it's been like at least half a year since i've run off a urls.txt
i use the same config for marking things as complete. i pop in the cli arg for it, but use the same config. i often mark things a complete while something else is downloading and that too doesn't work due to the locked .log

**Comment by SethBodine** [comment]
Possibly provide an argument to specify a new location for the cache location, that appears to be the big issue where locking occurs

to be frank the AppData folder contents could be broken up into cache/DB (currently creating multiple AppData Folders), global settings (I'm leveraging sym links for these), and profile (which the arg exists)

**Comment by SethBodine** [comment]
That said, leveraging a single cache db would be great too :)

**Comment by Jules-WinnfieldX** [comment]
Multiple instance has always been a grey zone, something that has partially worked in V4, and more so doesn't in V5. The program itself was designed around running a single instance, like any application. Work arounds exist for multi-instance, but I won't be adding implicit support.
