### ISSUE TITLE
[BUG] CDL doesn't seem to be resuming partial downloads as well as it used to.

### ISSUE THREAD

**Issue by crimzind** [Jules-WinnfieldX/CyberDropDownloader#684]
**Describe the bug**
Uh, CDL seems to be frequently making new instances of downloads instead of resuming partials. I'm regularly finding (1), (1) (1), (1)..., etc. partials now. I wasn't having this happen with previous versions.

**To Help Reproduce**
Steps to help reproduce the behavior:
I'm not sure, maybe there's a setting I've flagged somewhere contributing to this, but I'm not sure. I assume that downloads are failing for one reason or another, CDL finishes what it can/will, I reopen it to resume/reattempt what didn't finish, and for whatever reason, it's not consistently continuing from the previous files.

**Screenshots**
![image](https://github.com/Jules-WinnfieldX/CyberDropDownloader/assets/1254414/c54bc60d-a924-4b6e-b7f6-e6845c8fa9fb)

**Setup Information**
 - OS: Windows 10
 - Cyberdrop Downloader Version # V5.0.43

**Downloader.log file**
Seems my log file is blank (but I'm also an anxious individual who isn't really comfortable blasting out my NSFW content.😓)

**Comment by Jules-WinnfieldX** [comment]
Do me a favor and message me on discord. I'm going to need a few files from you to figure this out.

**Comment by Jules-WinnfieldX** [comment]
I think I just solved this about an hour ago with .42

Delete the (1)... files and see if they come back. If they do, reopen this issue.
