### ISSUE TITLE
[FEATURE] Option to restart.

### ISSUE THREAD

**Issue by crimzind** [Jules-WinnfieldX/CyberDropDownloader#685]
**Is your feature request related to a problem? Please describe.**
Currently, CDL does what it can with the URL list, and then finishes, and then closes, and you're presented with only the option to press any key to continue (closing the terminal/CMD-prompt).

**Describe the solution you'd like**
I'd like to be returned to the main menu, with a brief summary of the Completed/Skipped/Failed results, so that I can just select "Download" again without having to re-launch CDL. If the CDL session could track which links didn't complete, and I could just retry those instead of re-scraping entire threads again, that'd be nice, too. The "Retry failed" hasn't seemed to work for me.

**Comment by Jules-WinnfieldX** [comment]
The retry failed won't scrape links that fail to scrape, it'll do links that fail to download. 

Unfortunately if I do this, it's going to be a while from now.

**Comment by Jules-WinnfieldX** [comment]
I think this would likely do more harm than good, with the amount of people running the tool autonomously, I'm going to reject this for now.

**Comment by baccccccc** [comment]
dunno, it looks to me that DDoS-guard sometimes prevents you from scraping, not only from downloading. I think it's a worthwhile idea, even if not a high priority. I had a similar proposal in further discussion of #688.
