### ISSUE TITLE
[FEATURE] Tracking previous forum scrape history.

### ISSUE THREAD

**Issue by crimzind** [Jules-WinnfieldX/CyberDropDownloader#687]
I wish there was an option for CDL to better track forum scrape history. You toss it a forum thread with dozens of pages. It runs, you get some things, some things fail, you run CDL again, repeat. Eventually you get everything, no errors, all good. But every time you have issues downloading stuff and have to restart, or after you did get everything and some time goes by, and you want to grab whatever has been added since you last finished, if you toss it the thread, CDL's going to try and scrape from the beginning. Yeah, it'll check the DB and ignore/skip links it's already grabbed, but a ton of time is still being spent going through that process, and a bunch of unnecessary traffic/requests are being sent to whoever's hosting the content. It seems really wasteful/inefficient (and I feel a bit guilty for the unneeded activity).

I wish that CDL would track which post# for a thread was the last-completed (no Fails/Errors), and scrape from that post forward, instead of going through the whole thread again every time. Maybe track the post #s that did have errors/fails, and try those again in addition to new posts, instead of the whole thread over and over. The main issue I could see is missing some posts that might have been edited with new URLs. Maybe CDL could check to see if any posts have been edited since the last time it scraped, and check those edited posts and compare the links to the DB and grab anything new, but that's really not a big deal, for me. 

And I'm not suggesting this be the default, simply some more options I wish I had, more or less.

I know there are options to output failed/unsupported URLs, and one could grab those, but then when you put those into the URLs list, it doesn't maintain the same folder-structure where you already have partial downloads, so then you need to manually move things around folders, and it's just a pain.

Additionally, those output files don't seem to be... cumulative? Unless it's changed since the last time I tried, the Failed and Unsupported output files only seem to maintain URLs from the last scrape attempt, and tosses anything from previous runs. I wish it would be an ongoing list, with failed/unsupported entries just appended (and those individual entries removed if it does manage to finish one of the URLs.)

**Comment by Jules-WinnfieldX** [comment]
This kinda already exists. Just not automated for you. 

Under logs in the config folder the last scraped post in a forum thread is saved in the file Last Scraped Forum Posts.

This log is rewritten every run.

**Comment by Jules-WinnfieldX** [comment]
For failed downloads (not failed scrapes) there is the retry failed option in the UI. It looks at all files that have failed to download, and tries them again, in the exact file location they were originally supposed to be downloaded.

**Comment by alwayscurious419** [comment]
I'm in a similar situation as OP.  In the past, I've used separate config and URL files for the forum, and done the "rename Last Scraped Forum Post to URL.txt" dance in a shell script.  However, it would be nice to be able to have that automagically happen - I haven't looked at the DB, but maybe there's a way to just store the last post in the DB for each URL and read from that?  Instead of passing the last post number in the URL file?  

A different way to attack this could be a feature I've been thinking about posting - allowing for multiple URL files.  That way, I can just add the Last Scraped file to the list and bam, it'll use that?

**Comment by Jules-WinnfieldX** [comment]
update_last_forum_post in config
