### ISSUE TITLE
[BUG] Crashed while sorting on v5.0.54 (see logs)

### ISSUE THREAD

**Issue by Proutbedaine** [Jules-WinnfieldX/CyberDropDownloader#690]
**Describe the bug**
Crashed while sorting on v5.0.54 (see logs)

**Screenshots**
![image](https://github.com/Jules-WinnfieldX/CyberDropDownloader/assets/81118140/c5f53f5d-79df-4630-97f6-b4c79aac10c7)

**Setup Information**
 - OS: Win10 
 - Cyberdrop Downloader Version # 5.0.54

**Downloader.log file**
[downloader.log](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/13576611/downloader.log)

**Comment by qarkai** [comment]
Could you run `ffprobe.exe -select_streams v:0 -show_streams -print_format json` on that file? `ffprobe.exe` is in `videoprops` directory from your screenshot.

**Comment by Proutbedaine** [comment]
> Could you run `ffprobe.exe -select_streams v:0 -show_streams -print_format json` on that file? `ffprobe.exe` is in `videoprops` directory from your screenshot.

Yesterday an hour or two after posting this bug, I got the idea to simply move the file somewhere else entirely in the meantime so I could start my sorting-only profile again and see if it went through the rest without issue that time (which it did, yay!). 

**But** now for the bug itself at hand. I did try to open it because there was no thumbnails generated and I wondered if it was corrupted or actually an MP4 that was purely sounds and no image. And it was! It's actually an MP4 with no video stream at all and with only sound (dunno who was the brilliant person that did that but yeah lol). 

So do you still need me to do that or would that in itself answer your question? 👀 
Feel free to let me know if you still need me to do so!

**Comment by Jules-WinnfieldX** [comment]
5.0.64 should deal with this.
