### ISSUE TITLE
[BUG] to create a work folder

### ISSUE THREAD

**Issue by Aliaksandr3by** [Jules-WinnfieldX/CyberDropDownloader#691]
if I to run command of cyberdrop-dl , it create all folders in the path where I run it.
might is be good idea to create a isolate workspace for files?
![image](https://github.com/Jules-WinnfieldX/CyberDropDownloader/assets/11432724/7a59971e-aa16-4f93-92dd-3a441ff880cd)

**Comment by Aliaksandr3by** [comment]
but where is I have to start the program?  from user folder? can I always start from my folder?

**Comment by Aliaksandr3by** [comment]
messing up in the appdata folder is bad idea

**Comment by Jules-WinnfieldX** [comment]
The AppData folder you took a screenshot above has nothing to do with the actual AppData folder on your computer.

**Comment by Aliaksandr3by** [comment]
yah, I know, But if I start powershell I got 
![image](https://github.com/Jules-WinnfieldX/CyberDropDownloader/assets/11432724/5bb02f1f-6680-454d-924c-f84a3c5131cc)

and there the real folder ?

**Comment by Jules-WinnfieldX** [comment]
There is a language barrier here, I'm not sure what you are asking.

**Comment by Aliaksandr3by** [comment]
oh sorry, my English is bad.
thx for you're work
