### ISSUE TITLE
[BUG] Pixeldrain videos in not working why

### ISSUE THREAD

**Issue by poojitha-poojip** [Jules-WinnfieldX/CyberDropDownloader#692]
**Describe the bug**
Pixeldrain videos in not working why, it  keeps saying scrape failure.

**Screenshots**
[Image 1
](https://imgur.com/p3TraWZ)

**Setup Information**
 - OS: Windows 11
 - Cyberdrop Downloader Version 5.1

**Comment by Jules-WinnfieldX** [comment]
https://jules-winnfieldx.gitbook.io/cyberdrop-dl/frequently-asked-questions#where-is-the-downloader.log-file

I'd need to see the log file.

**Comment by poojitha-poojip** [comment]
[downloader.log](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/13577871/downloader.log)
