### ISSUE TITLE
[FEATURE] More error types than just HTTP Status and Unknown

### ISSUE THREAD

**Issue by Dorentil** [Jules-WinnfieldX/CyberDropDownloader#694]
**Is your feature request related to a problem? Please describe.**
When downloading, I noticed, that most errors tend to be "unknown" and that makes it difficult to see, what the error is. One error I had (especially on an older version yesterday) is that something was wrong with the destination path. I assume, that the path was wrongly set by me, because I fixed it by setting it again. But if such an error could have been named instead of unknown, I would have found it more easily.

Also the pure amount of "Unknown" errors seems kind of high.

**Describe the solution you'd like**
It would be great if more types of errors would be identified. Errors thrown by the OS for example.

![2023-12-06_13-15](https://github.com/Jules-WinnfieldX/CyberDropDownloader/assets/99742937/d3e1b894-fd33-4cf8-a9d8-9a62aa947cbc)

**Comment by Jules-WinnfieldX** [comment]
Added more fine grain in 5.1.6
