### ISSUE TITLE
[FEATURE] Ability to target different URLstxt files with command argument

### ISSUE THREAD

**Issue by yada-yoda** [Jules-WinnfieldX/CyberDropDownloader#695]
**Is your feature request related to a problem? Please describe.**
Sometimes we have "one off" downloads of bunkr albums or files that are never updated and other times there are repeated downloads of forums or checks of that forum that are updated.

**Describe the solution you'd like**
it would be nice to have the option to have a separate text file and extra .bat file that could target that separate text file to update from the latest forums. I understand the path can be changed in the config but it would be great to be able to have this ability for quick access rather than having to change the config each time or select a profile within the program.

Examples:
```
cyberdrop-dl URLs2.txt
pause
```

```
cyberdrop-dl URLs.txt
pause
```

**Additional context**

**Comment by Jules-WinnfieldX** [comment]
You can do this --input-file

https://jules-winnfieldx.gitbook.io/cyberdrop-dl/reference/cli-arguments
