### ISSUE TITLE
[BUG] error downloading album from jpg.church

### ISSUE THREAD

**Issue by scottula1** [Jules-WinnfieldX/CyberDropDownloader#70]
I get an error message when trying to download the following album from jpg.church: https://jpg.church/album/p1nksq4rkl3z.EqND

I'm using windows 10. I'm using version 2.5.0. That URL is the only item in the URLs.txt file.

Here's the error in my terminal: 

URLs.txt exists
Traceback (most recent call last):
  File "C:\Users\scott\Downloads\CyberDropDownloader-2.5.0\main.py", line 92, in <module>
    asyncio.get_event_loop().run_until_complete(main())
  File "C:\Users\scott\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\Users\scott\Downloads\CyberDropDownloader-2.5.0\main.py", line 80, in main
    raise ValueError('No links found, check the URL.txt\nIf the link works in your web browser, please open an issue ticket with me.')
ValueError: No links found, check the URL.txt
If the link works in your web browser, please open an issue ticket with me.

C:\Users\scott\Downloads\CyberDropDownloader-2.5.0>pause
Press any key to continue . . .

**Comment by Jules-WinnfieldX** [comment]
The program doesn't support password protected albums as of current

**Comment by scottula1** [comment]
Oh, that makes total sense. Thanks for the quick response!
