### ISSUE TITLE
[BUG] Failing to install 5.0.67 reverting to 4.2.231

### ISSUE THREAD

**Issue by bewbylover** [Jules-WinnfieldX/CyberDropDownloader#701]
**Describe the bug**
Failing to install 5.0.67 reverting to 4.2.231.  This has been a problem for me since attempting to move to 5.0.20.

**To Help Reproduce**
Steps to help reproduce the behavior:
1. Downloaded the latest zip from https://github.com/Jules-WinnfieldX/CyberDropDownloader/releases
2. Installed Python 3.12.
3. Unzipped.
4. Ran the script, provided the error message in the screenshot

**Screenshots**
![Screenshot from 2023-12-06 15-55-10](https://github.com/Jules-WinnfieldX/CyberDropDownloader/assets/152096820/76fbe46c-de89-45a3-9388-0086bebb4bf9)

**Setup Information**
 - OS: Ubuntu 20.04.6 LTS
 - python 3.12
- Cyberdrop Downloader Version # 4.2.231

**Downloader.log file**
[downloader.log](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/13592914/downloader.log)

**Additional context**

**Comment by Jules-WinnfieldX** [comment]
This is because you likely have multiple versions of python installed (along with multiple versions of Cyberdrop-DL)

You can see this probably if you run the command `which cyberdrop-dl`

I think thats the command on linux anyways.

**Comment by bewbylover** [comment]
I purged some of the previous versions that didn't appear to have been purged.  I think the virtual python environment is working, now I am getting these error messages.
[errors.txt](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/13594938/errors.txt)

I would have included the downloader.log, but it isn't being populated yet.

**Comment by Jules-WinnfieldX** [comment]
Yea, didn't really expect your setup to work. Some of the things Cyberdrop-DL relies on, aren't compatible with Python 3.12 yet. 

You could probably find a way around it, but the easiest thing to do would be uninstall 3.12 and use 3.11 (I personally use 3.11.4)

**Comment by Jules-WinnfieldX** [comment]
No worries, glad it's workin for ya.
