### ISSUE TITLE
[BUG] Can't quit out gracefully

### ISSUE THREAD

**Issue by sideloading** [Jules-WinnfieldX/CyberDropDownloader#702]
**Describe the bug**
When attempting to quit mid-download using CTRL+C (no effect), requires CTRL+\ to force quit. 

**To Help Reproduce**
Steps to help reproduce the behavior:
1. Begin download
2. Do CTRL+C (has no effect), CTRL+\ to force quit

**Setup Information**
 - OS: Ubuntu 20.04.6 LTS
 - Cyberdrop Downloader Version #V5.0.69

**Comment by marioaugustorama** [comment]
I identified the same error!

**Comment by Jules-WinnfieldX** [comment]
5.0.118 fixes the Ctrl + C issue.

**Comment by Jules-WinnfieldX** [comment]
Reopening as I've had to revert these changes.

**Comment by Jules-WinnfieldX** [comment]
5.1.2 just released that should do the above, it now has a hard requirement of python 3.11
