### ISSUE TITLE
[BUG] I cant download from JPG3

### ISSUE THREAD

**Issue by PauloTorrente** [Jules-WinnfieldX/CyberDropDownloader#703]
Im trying this and its not working
Albums: /a/jpg3.su/restofthelink
Did I miss something?

**Comment by Jules-WinnfieldX** [comment]
I'll need to see a downloader.log file where this happens

**Comment by Jules-WinnfieldX** [comment]
There's some confusion here. You don't need to put it as `albums: /a/....` Just put the regular `https://jpg3.su/a/...` link in the urls file

**Comment by Jules-WinnfieldX** [comment]
That's not an album. It's a users profile. 

5.0.72 adds handling for it. You'll need to update.
