### ISSUE TITLE
[FEATURE]  A way to deal with completed download URLs in Terminal editor

### ISSUE THREAD

**Issue by kr222** [Jules-WinnfieldX/CyberDropDownloader#704]
**Is your feature request related to a problem? Please describe.**
After completing downloads from several links, the URLs remain in the URLs.txt file, and as a result, also remain in the URLs editor in the Terminal window. 

Currently there seems to be no way to Ctrl-A + backspace away all the URLs in Terminal, and the URLs have to be manually deleted by holding down backspace.

**Describe the solution you'd like**
Either: Hotkey to clear URLs.txt in Terminal window, could be a less frequently used key (e.g. "Insert" , "| \", or "~") to prevent accidental presses/ a key combination with modifiers (e.g. Ctrl+Backspace) 

Or: Automatically clear URLs individually after download completion

Thanks!

**Comment by Jules-WinnfieldX** [comment]
From my current understanding, I don't believe this to be possible.
