### ISSUE TITLE
[BUG] Cyberdrop 403

### ISSUE THREAD

**Issue by jodoze** [Jules-WinnfieldX/CyberDropDownloader#705]
**Describe the bug**
It is unable to scrape embedded/album links in forums or even download direct links in the URLs.txt.
403 - HTTP status code 403: Forbidden
Scrape Failures (403 HTTP Status): 19
In Chrome browsers, links without "www" also return 403. So I don't believe it's only Cyberdrop-dl fault.

**To Help Reproduce**
Steps to help reproduce the behavior:
Add these links in the URLs and run the program, all SFW.
https://cyberdrop.me/a/1
https://cyberdrop.me/f/wmdMfHJAhjslCI
https://cyberdrop.me/e/wmdMfHJAhjslCI

https://www.cyberdrop.me/a/1
https://www.cyberdrop.me/f/wmdMfHJAhjslCI
https://www.cyberdrop.me/e/wmdMfHJAhjslCI

**Setup Information**
 - OS: Windows 10
 - Cyberdrop Downloader Version V5.0.75
 - Current Config: Default

**Downloader.log file**
[downloader.log](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/13604775/downloader.log)

**Comment by Jules-WinnfieldX** [comment]
403 is essentially DDOS-Guard.

**Comment by benjaminosaka** [comment]
What is the solution here? I tried editing `authentication.yaml` and populating the `DDOS-Guard` with no success.

**Comment by angelfire76** [comment]
> What is the solution here? I tried editing `authentication.yaml` and populating the `DDOS-Guard` with no success.
Did the same thing for Bunkrr, still seeing 403 HTTP scrape failures. :(

**Comment by lollos73** [comment]
> > What is the solution here? I tried editing `authentication.yaml` and populating the `DDOS-Guard` with no success.
> 
> Did the same thing for Bunkrr, still seeing 403 HTTP scrape failures. :( Maybe that's because of VPN, have changed my VPN server and it's still same.

same but don't use vpn and same problem on jdownloader... someyhing is changed in last hours? 2 hours ago work fine

**Comment by crimzind** [comment]
Having the same issue, here.
Tried pulling DDOS cookies automatically, double checked it manually, unable to get it to work again.

**Comment by baccccccc** [comment]
Yes, there's certainly something going on. I too have a bunch of repeated 403's even with repeated launch attempts. Although I don't think there's a lot you can do about it, except maybe try to more closely mimic a human (fewer attempts per second, random delays between attempts, etc.)

**Comment by kened0ferreira** [comment]
He can use "Python Try Except" to mimic a human behavior.

**Comment by Jules-WinnfieldX** [comment]
> He can use "Python Try Except" to mimic a human behavior.

Not particularly. The key thing missing here is an actual browser.

**Comment by Senpai1995** [comment]
i keep getting 403'd as well have no idea how to fix this...

**Comment by kened0ferreira** [comment]
I tried downloading it manually from bunkr and it won't accept more than two simultaneous downloads.
Perhaps limiting the number of simultaneous downloads to two will solve the problem.

**Comment by Jules-WinnfieldX** [comment]
> I tried downloading it manually from bunkr and it won't accept more than two simultaneous downloads. Perhaps limiting the number of simultaneous downloads to two will solve the problem.

CDL already limits it to 1.

**Comment by DawgNewb** [comment]
Hey I just keep getting 403 even tho I used VPN. It would normally work before but now it doesn't.
I also tried to put cookies with bunkrr_ddg1 bunkrr_ddg2 bunkrr_ddgid, still not work.

**Comment by Gitphex** [comment]
Same error here.

Scrape Failures:
Scrape Failures (403 HTTP Status): 1

Greetings.

**Comment by bo5591** [comment]
I'm having the same issue! any ideas on a fix anyone???

**Comment by blankmuppet** [comment]
hopefully fixed soon, in the meantime I've been using "JDownloader 2" for Bunkrr folders
