### ISSUE TITLE
[FEATURE] Proxy CLI arg

### ISSUE THREAD

**Issue by gashtal** [Jules-WinnfieldX/CyberDropDownloader#707]
**Is your feature request related to a problem? Please describe.**
Will the proxy support from v4 make a comeback in v5? That is pretty much the only reliable way to bypass DDoS-Guard.

**Comment by gashtal** [comment]
@Jules-WinnfieldX No way to pass the proxy via command-line like v4? The `--proxy` argument is no longer there it seems.

**Comment by Jules-WinnfieldX** [comment]
if you put it in that config, it applies to all runs of CDL.

**Comment by gashtal** [comment]
@Jules-WinnfieldX With the `--proxy` argument, I can run `cyberdrop-dl --proxy proxy1 link1` and `cyberdrop-dl --proxy proxy2 link2` in parallel. I guess that will no longer be possible with the configuration file, correct?

**Comment by Jules-WinnfieldX** [comment]
ahh, I see.

**Comment by Jules-WinnfieldX** [comment]
Added in 5.1.5 (going up soon)

**Comment by gashtal** [comment]
Great, thank you. 👍
