### ISSUE TITLE
[BUG] DEBUG events showing up on console

### ISSUE THREAD

**Issue by alwayscurious419** [Jules-WinnfieldX/CyberDropDownloader#708]
**Describe the bug**
Not sure if this is a configuration setting I missed (or set incorrectly) - but I'm getting DEBUG events for scrape start / finished, and download starting/skip/finished to the top line of the console.  This is causing the UI to "flash" (I'm using the new windows terminal, so this isn't the same as the other flashing thing with the v4 UI) - as DEBUG events are written to the console then the newUI rewrites the display.  Because it's flashing, it's really difficult for me to pull a screenshot.  This may be a feature request, but can I change the log level to suppress success-type events (scrapes, etc) and just output warnings/errors?

**Setup Information**
Debian Bookworm from command line (cyberdrop-dl --download)
cyberdrop-dl 5.0.85

**Comment by Jules-WinnfieldX** [comment]
Can you show a screen of those debug messages being posted to console?

It really shouldn't do that. There is no stream handler to sys out.

I just want to see and verify before I put in a ton of work for this.

**Comment by Jules-WinnfieldX** [comment]
Seems to more be a symptom of running in an OpenSSH client, but I'll see what I can cook.

**Comment by BlueFear1** [comment]
It's flashing at my console too at normal downloads even though I don't get any debug messages.

**Comment by alwayscurious419** [comment]
> It's flashing at my console too at normal downloads even though I don't get any debug messages.

Just chiming in because I've seen this issue in the past.  You may be using a terminal that doesn't support the UI very well?  (cmd and Powershell both had this happen for me.)  If you're on windows I'd recommend the new "Windows Terminal" (I think there's a link in the project wiki).

**Comment by BlueFear1** [comment]
> > It's flashing at my console too at normal downloads even though I don't get any debug messages.
> 
> Just chiming in because I've seen this issue in the past. You may be using a terminal that doesn't support the UI very well? (cmd and Powershell both had this happen for me.) If you're on windows I'd recommend the new "Windows Terminal" (I think there's a link in the project wiki).

Thank you. New terminal solved the issue.

**Comment by alwayscurious419** [comment]
Hey @Jules-WinnfieldX - just wanted to note that this is still occurring on 102 - the prior commenter was referring to the flashing he was experiencing using old terminal.  I'm still seeing debug events posting to the console using OpenSSH in Windows Terminal.

**Comment by Jules-WinnfieldX** [comment]
> Hey @Jules-WinnfieldX - just wanted to note that this is still occurring on 102 - the prior commenter was referring to the flashing he was experiencing using old terminal. I'm still seeing debug events posting to the console using OpenSSH in Windows Terminal.

I likely don't think this is something that I can fix for you. But out of curiousity, why are you using openssh to run it

**Comment by alwayscurious419** [comment]
> > Hey @Jules-WinnfieldX - just wanted to note that this is still occurring on 102 - the prior commenter was referring to the flashing he was experiencing using old terminal. I'm still seeing debug events posting to the console using OpenSSH in Windows Terminal.
> 
> I likely don't think this is something that I can fix for you. But out of curiousity, why are you using openssh to run it

Appreciate everything you've done (cappuccino donated!) and I totally get it if this is an edge case.  I'm 100% good with this never getting fixed LOL, but wanted to report any bugs that I've seen.  For my case, I have a separate Proxmox/Debian-Docker box from Windows client that I use to run the job through cron.  It's just much more stable, reliable, and it-just-works for recurring infrastructure stuff.  Normally, it just runs in the background - but when I need to make changes or tweaks for new versions, I need to login to the host through ssh (the server is also headless).  Like the above, other terminal types can produce other UI issues - so I moved over to Windows Terminal, which with PowerShell _(as I understand it)_ uses openSSH by default.  If there's a better option I'm 100% good with hearing about it - I'm always learning!!

**Comment by Jules-WinnfieldX** [comment]
--log-level (and config equivalent) will be included in 5.1.3 later tonight, it uses pythons logging numerical value you can find here: https://docs.python.org/3/library/logging.html#levels

ie: for error you'd put 40.
