### ISSUE TITLE
[FEATURE] NoUI setting to suppress all UI events

### ISSUE THREAD

**Issue by alwayscurious419** [Jules-WinnfieldX/CyberDropDownloader#709]
**Is your feature request related to a problem? Please describe.**
Somewhat related to bug report #708 - I believe there used to be an option to suppress the newUI and use the "old" version.  Since I'd like to run cyberdrop-dl as a service in cron, there's really no need (or use) to run an UI for progress.  

**Describe the solution you'd like**
Command line switch or configuration setting to disable the UI completely and not write to stdout - just log to logging files/folders.

**Comment by Jules-WinnfieldX** [comment]
--no-ui entirely disables the UI

This will be available in 5.1.3 later tonight
