### ISSUE TITLE
[BUG] Exit gracefully & downloading the same files over and over

### ISSUE THREAD

**Issue by bewbylover** [Jules-WinnfieldX/CyberDropDownloader#712]
**Describe the bug**
I don't seem to have a way to gracefully exit the program.  From time to time I exit the program to get the new updates with Ctrl+c, and then "ps -ef" and "kill -9 \<cdd PID\>" because it never seems to catch the Ctrl+C and exit gracefully.  When I resume I have generally moved the downloaded things to a new location to free up space.  Each time the images (gif & jpg, but probably more) download again.  Is there a better way to exit the application?  And would it be possible to mark downloaded images as complete once they have completed downloading to prevent the repeated downloads?

**To Help Reproduce**
Steps to help reproduce the behavior:
1. Populate URLs.txt with https://xbunker.nu/threads/sophie-mudd.6583/
2. Make sure Downloads is empty.
3. Start the application and exit while downloading, I downloaded 16 files then Ctrl+C.
4. Move the files in Downloads elsewhere.
5. Restart the application wait for 16 files to download, then Ctrl+C.
6. Compare the directories with a duplicate checker, 10 identical files 9 gif 1 jpg.

**Screenshots**
N/A

**Setup Information**
 - OS: Ubuntu 20.04.6 LTS
 - python 3.11.6
 - Cyberdrop Downloader V5.0.99

**Downloader.log file**
I can't find a log file, let me know what would be helpful

**Additional context**

**Comment by Jules-WinnfieldX** [comment]
5.0.118 fixes the Ctrl + C issue. 

If the redownloading is still an issue, please open a new ticket specifically for that with the log file (./appdata/configs/<config>/logs)

**Comment by bewbylover** [comment]
Thanks, I will check.  118 has a bug
