### ISSUE TITLE
[FEATURE] - Pornpics.com support 

### ISSUE THREAD

**Issue by manlikechrisgray** [Jules-WinnfieldX/CyberDropDownloader#715]
Would it be possible to add support to scrape all the galleries from a pornstar or even a from a specific gallery related to said person on the Pornpics.com website.. 

**Example links:**

https://www.pornpics.com/pornstars/PORNSTAR 

https://www.pornpics.com/galleries/GALLERY NAME HERE

Thanks

**Comment by Jules-WinnfieldX** [comment]
Not possible due to their use of Javascript
