### ISSUE TITLE
[FEATURE] download from coomer with filename format like that

### ISSUE THREAD

**Issue by darkplace77** [Jules-WinnfieldX/CyberDropDownloader#716]
add Published date in filename like that
actual filename is: 362123453_going for a travel_01_123dcxdq-4260-421c-71ab-eaea1247748856
i want to be: 20231012-362123453_going for a travel_01_123dcxdq-4260-421c-71ab-eaea1247748856
20231012 is the published date

**Comment by Jules-WinnfieldX** [comment]
I want to preserve the OG filenames. 

However, for you I've added these two wildcards in the sort function: 

file_date_us - The modified date of the file (YYYY-DD-MM)
file_date_ca - The modified date of the file (YYYY-MM-DD)

If you weren't aware CDL already sets the date on the file as the published date from coomer.

This will be out in 5.1.3 releasing later tonight
