### ISSUE TITLE
[BUG] i.ibb.co image embeds only download thumbnail

### ISSUE THREAD

**Issue by ne0lith** [Jules-WinnfieldX/CyberDropDownloader#717]
**Describe the bug**
It seems embeds on SC from i.ibb.co (image urls at least, havent tested albums) are only retrieving the thumbnail/embed image, and not the full size image.

**Comment by Jules-WinnfieldX** [comment]
Can you provide an example link?

**Comment by Jules-WinnfieldX** [comment]
fixed in 5.1.3 later tonight
