### ISSUE TITLE
[proposal] to create the folder when need, to test when folder is exist 

### ISSUE THREAD

**Issue by Aliaksandr3by** [Jules-WinnfieldX/CyberDropDownloader#718]
it is add testing for a folder, it is exist or not
to create the folder when need, to test when folder is exist 
e.g. to download of folder

**Comment by Jules-WinnfieldX** [comment]
This is already the case

**Comment by Aliaksandr3by** [comment]
![image](https://github.com/Jules-WinnfieldX/CyberDropDownloader/assets/11432724/0bb294a7-f6d3-403d-b655-05657d75ad89)

**Comment by Aliaksandr3by** [comment]
is is not will create the folder when I change folder of dowbloads

**Comment by Jules-WinnfieldX** [comment]
give it the full path
