### ISSUE TITLE
[BUG] Log files overwritten without running a Download

### ISSUE THREAD

**Issue by alwayscurious419** [Jules-WinnfieldX/CyberDropDownloader#719]
**Describe the bug**
Creates log file before initiating download

**To Help Reproduce**
I have cyberdrop outputting to log and error files.  Was troubleshooting some throttling issues and wanted to use the new UI to update the config files.  Did not run a download - just ran cyberdrop-dl, edited the config file, and quit.  When I looked back at the log and error files, I see that they have been overwritten with new logs/error files - even though I didn't run a download.

**Screenshots**
Attached

**Setup Information**
Debian bookworm
Cyberdrop-dl v 5.0.102

**Downloader.log file**
It's 0 ;)
<img width="459" alt="ZeroFIles" src="https://github.com/Jules-WinnfieldX/CyberDropDownloader/assets/152872399/4b5575d7-90dd-42f5-9603-5f7e31470901">

**Comment by Jules-WinnfieldX** [comment]
Will be fixed in 5.1.3 (releases tonight)

**Comment by Jules-WinnfieldX** [comment]
https://github.com/Jules-WinnfieldX/CyberDropDownloader/commit/2e5c054f6d5fe36279658b2bb22f46e4fbe908e5
