### ISSUE TITLE
ValueError: No links found, check the URL.txt

### ISSUE THREAD

**Issue by Harachai** [Jules-WinnfieldX/CyberDropDownloader#72]
Traceback (most recent call last):
  File "F:\CyberDropDownloader-2.5.4\main.py", line 92, in <module>
    asyncio.get_event_loop().run_until_complete(main())
  File "C:\Users\Selene\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "F:\CyberDropDownloader-2.5.4\main.py", line 80, in main
    raise ValueError('No links found, check the URL.txt\nIf the link works in your web browser, please open an issue ticket with me.')
ValueError: No links found, check the URL.txt
If the link works in your web browser, please open an issue ticket with me.

**Comment by Jules-WinnfieldX** [comment]
I need your logs.log file

**Comment by Harachai** [comment]
[logs.log](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/8304827/logs.log)

**Comment by Harachai** [comment]
It's passworded, I can give you the password

**Comment by Jules-WinnfieldX** [comment]
That makes this easy, this program cannot currently handle password protected albums

**Comment by Harachai** [comment]
Can you add a check or thing for password protected albums?

**Comment by Jules-WinnfieldX** [comment]
I can do that. I'll add it in the next release.
