### ISSUE TITLE
[BUG] Coomer's FileNotFoundError

### ISSUE THREAD

**Issue by DohnJoe2** [Jules-WinnfieldX/CyberDropDownloader#722]
**Describe the bug**
When scraping a Coomer profile, some posts fail to download with an 1 HTTP Error. 

**To Help Reproduce**
Steps to help reproduce the behavior:
1. Describe the bug accurately.
Instead of downloading the post normally it throws an 1 HTTP Error, skips the file and then deletes the folder beacuse it's empty. Here's an example error text of a failed download from **Download_Error_URLs.csv**: _1 - FileNotFoundError(2, 'No such file or directory')._

2. Provide an example album that showcases it (if applicable)
[https://coomer.su/onlyfans/user/leirnin_](https://coomer.su/onlyfans/user/leirnin_) **(profile)**
https://coomer.su/onlyfans/user/leirnin_/post/746935993 **(post that fails)**
https://coomer.su/onlyfans/user/leirnin_/post/752218419 **(post that fails)**

3. Make sure you are updated to the latest version to see if it's already fixed.
Using Cyberdrop Downloader (V5.0.104).

**Screenshots**

**Setup Information**
 - OS: Windows 10
 - Cyberdrop Downloader Version 5.0.104
 - Python 3.11.6

**Downloader.log file** 
https://pastebin.com/46TA8ySk

**Additional context**
It doesn't seem to be the problem on Coomer's end because I tested with two other downloaders and they download successfully.

**Comment by Jules-WinnfieldX** [comment]
I can't replicate this, though I've heard of it before, try updating, and running again. If it still occurs, reopen the issue.

**Comment by DohnJoe2** [comment]
Has to do something with the **"max_folder_name_length": 300** command. I've put it back to the default of 65 and it started downloading without problems. I used 300 in v4 and never got this error before.

**Comment by Jules-WinnfieldX** [comment]
Just realized it's probably the ..

**Comment by Jules-WinnfieldX** [comment]
But Windows has a max folder name length of 256, 300 would be over that.

**Comment by Jules-WinnfieldX** [comment]
nevermind, I am stripping out the ..

**Comment by Jules-WinnfieldX** [comment]
5.0.117 going up now should fix your issue.

**Comment by DohnJoe2** [comment]
I can confirm that it works now. Thank you! 🙌
