### ISSUE TITLE
0 downloads[BUG]

### ISSUE THREAD

**Issue by neromarcer** [Jules-WinnfieldX/CyberDropDownloader#723]
**Describe the bug**
I've been trying to download it, but it turns out it doesn't download anything, I tried several different links, but it gives the same result

![Captura de tela 2023-12-14 165852](https://github.com/Jules-WinnfieldX/CyberDropDownloader/assets/153863917/7a3e2edf-38ad-4cf5-81a9-6afa175cfac8)

 - OS:  Windows 10
 - Cyberdrop Downloader Version 5

**Comment by Jules-WinnfieldX** [comment]
Then you are putting urls in the incorrect urls file. Use the UI to edit the location.
