### ISSUE TITLE
[BUG] latest update just resorted all my albums into a single folder

### ISSUE THREAD

**Issue by mc711** [Jules-WinnfieldX/CyberDropDownloader#724]
after updating to v5 couple weeks ago, sorted folders were moved correctly,

have been using it recently with no problems. just used it today now EVERYTHING is only in 3 folders (Images, Videos, Other)

now i have to re-sort everything manually...

i really appreciate CD-DL, but why was there so much changes to folder structure?

2 years of content just got clusterfucked in one update SMDH

**Comment by mc711** [comment]
@Jules-WinnfieldX nice of you to ignore this problem. but i found the problem and solution

there is a major issue when you converted old configs to V5.

Problem:
when you import/convert the old config, original download location was "Downloads" it will retain this is the V5 config as "Downloads" but default Sort folder is converted to "Downloads/Cyberdrop-DL Sorted Downloads" 

Solution:
during import, old config should be converted to the new handle "Downloads\Cyberdrop-DL Downloads" otherwise files will download into "Downloads" and also sort all files in "Downloads/Cyberdrop-DL Sorted Downloads" 

Other solution:
 add an exception to ignore the sort folder on Sort. 

hope you can add this solution to prevent other people from this pain

**Comment by Jules-WinnfieldX** [comment]
This initially read as a user issue. I'm dealing with health issues right now so I'm not inclined to do much about those at the moment. 

However, you are correct, and I've implemented your other suggested solution. https://github.com/Jules-WinnfieldX/CyberDropDownloader/commit/02786c2f1948785a4b9b372d7948ebccc7102ef6

**Comment by mc711** [comment]
no worries. get well soon. happy holidays.
