### ISSUE TITLE
[BUG] Permissions to run Cyberdrop DL v.5 on mac

### ISSUE THREAD

**Issue by fedemariani74** [Jules-WinnfieldX/CyberDropDownloader#725]
Hello, 
I've had some download problems with version 3.11:
  _File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:992)>_

so I tried to download the 5.01 but I can't open the Startmac.command file for permissions problems.

_The “Start Mac.command” file cannot be executed because you do not have appropriate access privileges._
![Schermata 2023-12-15 alle 15 14 22](https://github.com/Jules-WinnfieldX/CyberDropDownloader/assets/38221409/598f0fd9-1d64-4f78-8d74-32a6921a2ebb)

I checked the file access privileges with cmd+I and set them with everyone read and write, but doesnt work.
![Schermata 2023-12-15 alle 15 17 05](https://github.com/Jules-WinnfieldX/CyberDropDownloader/assets/38221409/756001dc-b609-431c-b32b-d1113c95afea)

What can I do?
Thank you in advance
Best wishes.

**Comment by Jules-WinnfieldX** [comment]
You also need to set execute on the file. 

As for the [SSL: CERTIFICATE_VERIFY_FAILED] error,

Go to your applications folder, then python folder, and run the `install certificates` file. Then delete the venv folder wherever you are running Cyberdrop-DL, and try again.

**Comment by fedemariani74** [comment]
Thank you. I've installed the certificates.
How can delete the Venv folder?

How can set executo on the v.5 file?
Thanks again.

**Comment by nerdytraveller** [comment]
I have the same problem, haven't been able to fix it...

**Comment by Jules-WinnfieldX** [comment]
`chmod 755 <drag file into terminal>` then hit enter.

**Comment by fedemariani74** [comment]
It report this.
Start Mac.command: Permission denied

why?
