### ISSUE TITLE
[BUG] DDOS-guard

### ISSUE THREAD

**Issue by neromarcer** [Jules-WinnfieldX/CyberDropDownloader#726]
**Describe the bug**
I've been trying to download it, but this ends up happening. What can it be?

**Screenshots**
![image](https://github.com/Jules-WinnfieldX/CyberDropDownloader/assets/153863917/71da7c02-cb73-43e2-884e-a6dae0733f56)

**Setup Information**
 - OS: Windows 10
 - Cyberdrop Downloader Version 5

**Comment by Jules-WinnfieldX** [comment]
DDOS-Guard as it says
