### ISSUE TITLE
[FEATURE] choose options with numbers 

### ISSUE THREAD

**Issue by manlikechrisgray** [Jules-WinnfieldX/CyberDropDownloader#727]
**Describe the solution you'd like**
The ability to input a number for a selected option.. When using it on android it requires the use of arrows to select an option but we don't have up & down etc.. So being able to type an option instead.. E.g

                             
What would you like to do? Select an option: 
1) Download
2)  Download (All Configs)
3) Retry Failed Downloads
4) Edit URLs File

**Comment by Jules-WinnfieldX** [comment]
Android isn't technically supported by me (for numerous reasons, but primary being I don't own one), but the easy work around here is to edit the configs manually, and use --download when starting cyberdrop-dl.
