### ISSUE TITLE
[BUG] 118 crashes

### ISSUE THREAD

**Issue by bewbylover** [Jules-WinnfieldX/CyberDropDownloader#728]
**Describe the bug**
Started seelcted download and got this error message:

```
An error occurred, please report this to the developer
unhandled errors in a TaskGroup (1 sub-exception)
  + Exception Group Traceback (most recent call last):
  |   File "/home/kris/Downloads/Cyberdrop_DL.V5.1/venv/lib/python3.11/site-packages/cyberdrop_dl/main.py", line 84, in director
  |     await runtime(manager)
  |   File "/home/kris/Downloads/Cyberdrop_DL.V5.1/venv/lib/python3.11/site-packages/cyberdrop_dl/main.py", line 44, in runtime
  |     async with taskgroup.TaskGroup() as task_group:
  |   File "/usr/lib/python3.11/asyncio/taskgroups.py", line 147, in __aexit__
  |     raise me from None
  | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "/home/kris/Downloads/Cyberdrop_DL.V5.1/venv/lib/python3.11/site-packages/cyberdrop_dl/downloader/downloader.py", line 108, in run
    |     await self._semaphore.acquire()
    |           ^^^^^^^^^^^^^^^^^^^^^^^
    | AttributeError: 'Field' object has no attribute 'acquire'
    +------------------------------------
```

**To Help Reproduce**
Steps to help reproduce the behavior:
1. Shared URL.txt [URLs.txt](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/13693367/URLs.txt)
2. Start application, select download.
3. Error outputs before downloading begins, scraping too.

**Screenshots**
N/A

**Setup Information**
 - OS: Ubuntu 20.04.6 LTS
 - python 3.11.6
 - Cyberdrop Downloader V5.0.118

**Downloader.log file**
[downloader.log](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/13693364/downloader.log)

**Additional context**

**Comment by Jules-WinnfieldX** [comment]
5.0.121 is going up now, can you try and see if it fixes the crash?

**Comment by bewbylover** [comment]
Yes, that fixed it.  Thanks!
