### ISSUE TITLE
[HELP] Why my downloads are being scrapped ? (DDOS-GUARD)

### ISSUE THREAD

**Issue by Remzi744** [Jules-WinnfieldX/CyberDropDownloader#729]
Hello, i was trying to download a few videos from bunkrr.su and this happens when i tried to download :

![image](https://github.com/Jules-WinnfieldX/CyberDropDownloader/assets/107936972/3bff6f85-c646-43d9-8cab-14b2e3b72493)

 - OS: Windows 10
 - Cyberdrop Downloader Version #V5.0.121

Downloader.log file : 

[downloader.log](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/13693453/downloader.log)

**Comment by Jules-WinnfieldX** [comment]
As the error says, it's because of DDOS-Guard preventing the program from accessing the webpage.

**Comment by Remzi744** [comment]
> As the error says, it's because of DDOS-Guard preventing the program from accessing the webpage.

How can I disable it please ?

**Comment by Jules-WinnfieldX** [comment]
You can't. It's not part of CDL, it's part of Bunkr.

**Comment by Remzi744** [comment]
> You can't. It's not part of CDL, it's part of Bunkr.

Ohhh, okkk thanks !
