### ISSUE TITLE
[BUG] The program closes without even downloading anything

### ISSUE THREAD

**Issue by MrxHellsing** [Jules-WinnfieldX/CyberDropDownloader#73]
**Describe the bug**
Links are not being downloaded and the app closes itself after starting.

**To Help Reproduce**
Steps to help reproduce the behavior:
1. Added bunkr.is links and started the app, the app starts and closes after prompting to press any key to continue.
2. The log file says that the files already exists but the download folder is completely empty
3. Using the latest version

**Setup Information**
 - OS: [ Windows 10 Pro 64 bit, 20H2, OS Build 19042.1526 ]
 - Cyberdrop Downloader Version 2.5.4

**Additional context**
[logs.log](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/8309005/logs.log)

https://user-images.githubusercontent.com/29206412/159117708-5d7dbaee-0ec1-4d39-8741-418391ad7771.mp4

**Comment by Jules-WinnfieldX** [comment]
The logs.log file looks like it's from a previous successful run. Can you run this command in command prompt and try again?

pip install --upgrade selenium

You are getting a brief output of an error before the window closes that is rooted in the selenium import in the download python file.

**Comment by MrxHellsing** [comment]
It seems to be working now, I will give an update after completion.

**Comment by MrxHellsing** [comment]
All files have been downloaded successfully.
