### ISSUE TITLE
[FEATURE] Separate parameter for log folder

### ISSUE THREAD

**Issue by baccccccc** [Jules-WinnfieldX/CyberDropDownloader#732]
as mentioned in #643, #683 and perhaps some other requests.

some of us may have reasons to keep logs separate, or to have all of them in a specific folder. (E.g., when running parallel downloads, or to examine logs manually after each run.)

v4 stored logs in the current directory, so we could manipulate app's behavior by changing current directory. But v5 always uses a defined path for logs.

today, there's apparently a setting for log path in config file (`settings.yaml → log_folder`) but not in the command line.

also, logs are not part of `AppData` folder structure. (Which is probably a good thing.)

this is the request to have a command-line parameter (such as `--log-folder`) for all the text files CDL produces. (Including `downloader.log`, `*.txt` and `*.csv` files and whatever additional diagnostic output can be produced in the future.)

some other folks might want additional fine-tuning, e.g. separate path for each file and/or parametrized file names. I personally don't need that. Just a separate folder with all the default names will work for me.

**Comment by Jules-WinnfieldX** [comment]
So a big caveat here, is if you are running multiple instances at once, with the same log folder, it will error out if the log files have the same names.

But as per my other messages, 5.1.5 (soon)
