### ISSUE TITLE
[BUG] NudoStar

### ISSUE THREAD

**Issue by MarkH1966** [Jules-WinnfieldX/CyberDropDownloader#733]
The following URL breaks the scraper 

https://nudostar.com/forum/threads/post-your-wife-uk.41314

Error Log as Follows;

ERROR    : 2023-12-18 12:56:49,152 : utilities.py:81 : Traceback (most recent call last):
  File "D:\xxxxxx\CyberDropDownloader\venv\Lib\site-packages\cyberdrop_dl\utils\utilities.py", line 56, in wrapper
    return await func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\xxxxxx\CyberDropDownloader\venv\Lib\site-packages\cyberdrop_dl\scraper\crawlers\nudostar_crawler.py", line 80, in forum
    post_number = int(url_parts[-1].strip("/")) if len(url_parts) == 2 else 0
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'your-wife-uk.41314'

INFO     : 2023-12-18 12:56:49,153 : utilities.py:81 : Scrape Finished: https://nudostar.com/forum/threads/post-your-wife-uk.41314

**Comment by Jules-WinnfieldX** [comment]
fixed in newest update.
