### ISSUE TITLE
[Feature] Include effective `url.txt` path to `downloader.log`

### ISSUE THREAD

**Issue by baccccccc** [Jules-WinnfieldX/CyberDropDownloader#734]
When troubleshooting my launch scripts, I noticed that whenever I specify `--input-file` in the command line, the `downloader.log` has no mention of it. Instead, it just dumps my default `input_file` from `settings.yaml`. This might provide an impression that the default `url.txt` is being used, even when it's not. In other words, the app behaves correctly (the file is consumed per `--input-file` parameter) but the log cannot confirm it.

**Comment by baccccccc** [comment]
oh shit wrong label. Sorry, I was lazy and changed the tag in the title, but I should have started from scratch.

**Comment by Jules-WinnfieldX** [comment]
will be added in 5.1.5
