### ISSUE TITLE
[FEATURE] do not create empty `URLs.txt`

### ISSUE THREAD

**Issue by baccccccc** [Jules-WinnfieldX/CyberDropDownloader#735]
(ok now it's a proper feature and not a bug hopefully)

I never ever use the default `URLs.txt`. It just does not fit my scenarios. 99% of the time I just provide a single URL in command line. And 1% of the time (mostly when troubleshooting something) I provide my custom path via `--input-file`.

Of course, I understand the reason why many people might want to use single `URLs.txt` and have its path in the config. I'm just not one of those people. So, I just set the default value to `c:\some\bogus\path.txt` and forget about it.

However, I noticed that every time the app runs, it creates an empty `path.txt` there. I would prefer it not to. It's not the end of the world of course but just seems excessive and wasteless.

**Comment by Jules-WinnfieldX** [comment]
will add in 5.1.5
