### ISSUE TITLE
[FEATURE] prepend `bukrr.su` with `www.` to avoid DDoS-Guard

### ISSUE THREAD

**Issue by baccccccc** [Jules-WinnfieldX/CyberDropDownloader#736]
In #731 discussion, some smart person noticed that if you change `bunkrr.su` links so that they start with `www.` apparently it helps circumvent DDoS-Guard.

e.g.

- original (failing) link: `https://bunkrr.su/a/<bla>`
- modified (working) link: `https://www.bunkrr.su/a/<bla>`

I tried it and—surprisingly—it works.

1. I found four occasions in my recent logs where scraping bunkr was _repeatedly_ failing with DDoS-Guard to no avail. (Tried it multiple times, it's always failing. Some other bunkr links were ok. I have no idea what's wrong with those particular links.)
2. Verified that I can access those links with a browser with no problem. (Importing DDoS-Guard cookies from browser does not help in this particular case.)
3. Created a temporary `url.txt` with those four links.
4. Used this `url.txt` with CDL and observed the same DDoS-Guard failures during scrape.
5. Edited the `url.txt` and prepended each link with `www.`.
6. No more DDoS-guard, and download succeeded.

Sounds like an easy fix. Except that those links come from a forum thread. And of course, I cannot go to the forum and ask people to edit their links.

Moreover, I have no idea for how long it will keep working.

But _maybe_ add a feature to CDL that if a link fails without `www.` then add `www.` and retry? Maybe it will sometimes help not only with bunkr but other services, too. And _maybe_ even removing `www.` will help in some similar cases.

**Comment by Jules-WinnfieldX** [comment]
will be added in 5.1.5
