### ISSUE TITLE
[BUG] Issue when installing: cyberdrop-dl is not recognised as an internal or external command, operable program or batch file

### ISSUE THREAD

**Issue by haayfe** [Jules-WinnfieldX/CyberDropDownloader#737]
Have installed latest python and updated pip on computer, downloaded cyberdrop and attempted to run it. It begins to download depencies but fails at "building wheels for collected packages: miltidict, lz4 and says "subprocess-exited-with-error".
Please let me know what I can do to fix this. Thanks!

**Comment by Jules-WinnfieldX** [comment]
uninstall python 3.12 and install 3.11
