### ISSUE TITLE
[BUG] Cant run script : Line 50 error main.py

### ISSUE THREAD

**Issue by A-Random-Mf** [Jules-WinnfieldX/CyberDropDownloader#74]
**Describe the bug**
File "./main.py", line 50
logging.debug(f"We are running version {current_version} of Cyberdrop Downloader")

Main.py doesn’t run

**To Help Reproduce**
Steps to help reproduce the behavior:
1. Install python 3.9.x
2. Git clone latest cd downloader
3. Attempt to run ./Start.sh after chmod
4. All requirements installed. Main.py throws error

**Setup Information**
 - OS: Linux
 - Cyberdrop Downloader Version : Latest git pull

**Comment by Jules-WinnfieldX** [comment]
Can you provide the full trace

**Comment by A-Random-Mf** [comment]
You’re saying run python3 -v main.py?

**Comment by Jules-WinnfieldX** [comment]
You provided the line number and the line it happened at, but not the actual error itself. I don't have linux to test this on.

**Comment by A-Random-Mf** [comment]
Fixed. Issues with python installation
