### ISSUE TITLE
[FEATURE] Add sort option to UI

### ISSUE THREAD

**Issue by mc711** [Jules-WinnfieldX/CyberDropDownloader#740]
after "retry failed downloads", successful downloads are not sorted. 

either add manual sort option in menu or set "retry failed downloads" to sort after completion

**Comment by Jules-WinnfieldX** [comment]
No can do on the second, as retried downloads can be from any config (with different download folders, different sorting schema's and locations, etc). The first I can probably add.

**Comment by Jules-WinnfieldX** [comment]
Added
