### ISSUE TITLE
[BUG] Fapello not working anymore

### ISSUE THREAD

**Issue by TheMarkedOne1** [Jules-WinnfieldX/CyberDropDownloader#742]
**Describe the bug**
Everytime I try to run a download from Fapello, I get 403 HTTP Status and nothing is downloaded. I'm not sure if this classifies as a 'bug', but the website on my browser works.

**To Help Reproduce**
Steps to help reproduce the behavior:
1. Downloading links from Fapello doesn't work anymore, it was working yesterday.
2. https://fapello.com/bar-refaeli/ it happens with all albums I've tried.
3. Currently on version 5.1.12.

**Setup Information**
 - OS: Windows 10
 - Cyberdrop Downloader Version 5.1.12

**Downloader.log file**
I closed it before it finished but it happens for all the URLs I have in the .txt file.
[downloader.log](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/13710772/downloader.log)

**Additional context**
There seems to be a security check on the website so perhaps that is causing it now?

**Comment by Jules-WinnfieldX** [comment]
You're browser likely has a VPN built in, and your regular system does not. Or it's whatever security check you are referring to. Which CDL inherently cannot bypass.

**Comment by TheMarkedOne1** [comment]
My browser is definitely not using any VPN, and it was working fine before so it must be the security check. It says it's checking if my connection is secure and then it loads the site normally. Does this mean CDL will no longer work with Fapello going forward?

**Comment by Jules-WinnfieldX** [comment]
Take a break from scraping the site, and it'll eventually work for you again. But that's not something I can "fix". it's a bad site anyways, it just reposts things that are on every other site.

**Comment by TheMarkedOne1** [comment]
Yeah, just find it convenient when I've had a busy day but will do, thank you. Also want to take this oppotunity to thank you for CDL! All the best =)
