### ISSUE TITLE
[BUG] Duplicate file downloading

### ISSUE THREAD

**Issue by bewbylover** [Jules-WinnfieldX/CyberDropDownloader#743]
**Describe the bug**
Though greatly improved, still seeing duplicate images download for a couple of scrapes.  Both instances are in the download.log

**To Help Reproduce**
Steps to help reproduce the behavior:
1. Populate URLs.txt with https://simpcity.su/threads/tessa-fowler.9928/
2. Download, Ctrl+C once these 4 files download into "Tessa Fowler (SimpCity)2/Loose Files (JPGChurch)":
- 2022-07-17_1_3452x1936_b4584caa29afc2c1738677e6ae9fb1ef.jpg
- 2022-07-17_2_3455x1939_ba9b9356ef86ded65b8e75323de2bb62.jpg
- 2022-07-17_3_3455x1926_4d0c3e65de0455ac15100a43bbe62d32.jpg
- 2022-07-17_4_3439x1925_8f5cef40d3d1cca87fce861f9a953711.jpg
3. Empty downloads.
4. Start downloads again and wait until they download again, then Ctrl+C.
5. Compare the files with a duplicate checker, and validate they are identical.

**Screenshots**
N/A

**Setup Information**
 - OS: Ubuntu 20.04.6 LTS
 - python 3.11.6
 - Cyberdrop Downloader V5.1.13

**Downloader.log file**
Log 1 [downloader.log](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/13711278/downloader.log)
Log 2 [downloader.log](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/13711261/downloader.log)

**Additional context**
Let me know what else you might need.

**Comment by Jules-WinnfieldX** [comment]
the cyberdrop.db file would be a big help

**Comment by bewbylover** [comment]
https://drive.google.com/file/d/1mh42ysG6YT7hjhrzNCIs0htnfuYCWQE3/view?usp=sharing

**Comment by Jules-WinnfieldX** [comment]
5.1.14 Should fix this. It's going up now. It'll require one more download of the repeat files. 

What's happening is the files are technically on two different sites pixl (which downloaded as no_crawler) and jpg3.su (sharex). The DB only allowed one of the files to be entered into the DB, and the other was never being entered and marked as complete, so it kept re-downloading.

**Comment by bewbylover** [comment]
Makes sense, thank you.
