### ISSUE TITLE
[FEATURE]Update the user_agent to fix problems with DDOS-Guard

### ISSUE THREAD

**Issue by LePistole-glitch** [Jules-WinnfieldX/CyberDropDownloader#744]
I had problems with DDoS-Guard downloads, but I updated the user agent (firefox v120.0.1) in the global_settings.yaml file and was able to download again.

This may be a workaround to fix problems with services that are using DDoS-Guard.

**Comment by baccccccc** [comment]
Previously, it did seem to me that updating user-agent to match your actual browser (that you use for visiting websites, obtaining cookies, etc.) helps a lot in avoiding DDoS-Guard. Nowadays the impact is not easily noticeable, but I feel like it's still there.
