### ISSUE TITLE
[BUG] jpg church links get scraped again, not instantly skipped, even though they have previously been downloaded

### ISSUE THREAD

**Issue by Wrestor** [Jules-WinnfieldX/CyberDropDownloader#745]
**Describe the bug**
Like stated in the title, jpg church links get scraped again, not instantly skipped, even though they have previously been downloaded and are/should be in the database(history)

**To Help Reproduce**
(Desired) Behavior in V4
in cyberdrop-dl==4.2.231 (V4)
1. Download a jpg church album in whole (in my ex. "https://jpg3.su/a/melimtx.zmTD")
2. Try to scrape it again
3. Cyberdrop-dl v4 will skip all links near instantly, since they have already by downloaded.

(Actual) Behavior in V5
in cyberdrop-dl==5.1.15
1. Download a jpg church album in whole (in my ex. "https://jpg3.su/a/melimtx.zmTD")
2. Try to scrape it again
3. Cyberdrop-dl v5 will **not** skip all links near instantly, it will put every individual scrape link in its “Queue”, and go one by one

**Recording**
Desired Behavior (V4, 4.2.231)

https://github.com/Jules-WinnfieldX/CyberDropDownloader/assets/54822494/c3d27d88-2b39-43e9-a916-8c9b16f45d76

Actual Behavior (V5, 5.1.15)

https://github.com/Jules-WinnfieldX/CyberDropDownloader/assets/54822494/31a77684-a3ad-46ec-b375-030236427eb1

**Setup Information**
 - OS: macOS 14.2.1 (23C71)
 - Cyberdrop Downloader Version 5.1.15

**Downloader.log file**
[downloader.log V5](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/13720272/downloader.log)
[downloader.log V4](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/13720306/downloader.log)

**Additional context**
Why is this happening?

**Comment by Jules-WinnfieldX** [comment]
This was done as links in V4 were checked based on album as well as url path. V5 currently only does URL path
