### ISSUE TITLE
[BUG] omega scans only scraping first displayed season

### ISSUE THREAD

**Issue by hrm-princess-fluffybutt** [Jules-WinnfieldX/CyberDropDownloader#746]
**Describe the bug**
this has a toggle for "seasons" https://omegascans.org/series/the-main-character-is-the-villain
i don't think cdl switches between them
right now it only get the one that's first displayed, for the linked page it is the second season

**Comment by Jules-WinnfieldX** [comment]
Not going to be possible to switch between the tabs with CDL.

**Comment by Jules-WinnfieldX** [comment]
Yea, ain't worth the ridiculous effort.
