### ISSUE TITLE
[FEATURE] Fast Scrape for Bunkrr Albums Based on Page Source

### ISSUE THREAD

**Issue by gashtal** [Jules-WinnfieldX/CyberDropDownloader#747]
**Is your feature request related to a problem? Please describe.**
From what I understand, CDL scrapes the links from bunkrr albums one by one, and each scrape requires and individual query to bunkrr. Apart from being a fairly slow process, bunkrr seems to now be outright issuing temporary IP bans after ~100 non-stop scrapes.

**Describe the solution you'd like**
I noticed that the thumbnails for files in a bunkrr album pretty much give away the full download link, and it should be fairly simple to just download the album page's source, and generate all the final links from that, instead of querying the links one by one. To demonstrate, let's take the snippet of the page source an album below:

![image](https://github.com/Jules-WinnfieldX/CyberDropDownloader/assets/27990818/eb684649-e91d-4e4c-a2f3-3f8525ca234f)

The thumbnail link is given as `https://i-kebab.bunkr.ru/thumbs/fehgalvao_world.elite.ladies_00789-lsESw5tV.png`. The file extension can also be extracted as `.gif` from a few lines below. To get the final link, we simply need to remove `/thumbs` from the thumbnail link and replace the file extension with the correct one. This gives `https://i-kebab.bunkr.ru/fehgalvao_world.elite.ladies_00789-lsESw5tV.gif`, which lead to the final file. This seems to at least work for video and image files. Not sure if it also works for zip/rar files as they seemingly have a generic thumbnail and I currently don't have an example to check. Worst case scenario, zip/rar files can be individually detected from the page source and scraped separately.

**Comment by Jules-WinnfieldX** [comment]
That could work. I'll play around with it.

**Comment by Jules-WinnfieldX** [comment]
5.1.22 takes advantage of this. Thanks for the leg work.

**Comment by gashtal** [comment]
Fantastic! 😁
