### ISSUE TITLE
[BUG]Not recognizing nsfw.xxx urls

### ISSUE THREAD

**Issue by ibigfire** [Jules-WinnfieldX/CyberDropDownloader#748]
**Describe the bug**
I am under the impression that the tool supports nsfw.xxx posts, if I'm wrong then disregard.  But when I use a nsfw.xxx url it returns it as an Unsupported URL.

**To Help Reproduce**
Steps to help reproduce the behavior:
I put the URL: https://nsfw.xxx/post/a-country-ride-879959?page=9 into the URLs.txt file and the downloader.log tells me that it won't download the URL because it is unsupported.

I can provide a list of other URLs as well, none of my nsfw.xxx URLs seem to be recognized.

**Setup Information**
 - OS: Windows 10
 - Cyberdrop Downloader Version 5.1.21

**Downloader.log file**
[downloader.log](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/13752350/downloader.log)

**Comment by Jules-WinnfieldX** [comment]
nsfw.xxx was removed as a supported host as the website is god awful to deal with.

**Comment by ibigfire** [comment]
While a bit disappointing I completely understand and relate, as it being awful to deal with is *exactly* why I was looking for a tool to help since I'm having to deal with it currently due it having content that is no longer available anywhere else online.

Thanks a lot for the response, I appreciate it, all the best to ya.

**Comment by Jules-WinnfieldX** [comment]
If it didn't have random ass posts to non-related things in the feed, I'd still be supporting it. Might circle back to it, but it's god awful.

**Comment by serveral1** [comment]
I know this is a close issue but I'd rather have a random unrelated post and manually delete with those myself, perhaps a disclaimer could be added regarding the site's support?
