### ISSUE TITLE
[BUG] Cannot update/replace password after password change via the UI

### ISSUE THREAD

**Issue by Dorentil** [Jules-WinnfieldX/CyberDropDownloader#750]
**Describe the bug**
I had to change my password for simpcity.su today. Then I noticed that updating the password in cyberdrop-dl doesn't seem to work. When I go to "manage configs" -> "edit authentification values" -> "edit forum authentication values" (the use of authentication and authentification seems a bit inconsistent btw) -> "browser cookie extraction" -> "firefox", I assume, that it extracts the new cookie from everything it can find, but it still results in "scrape failures (failed login): 1". I already logged in in firefox esr (which is installed by default on Debian) and the manually installed Firefox. So both versions should have the cookie. Idk how cyperdrop-dl finds the location of the cookies of firefox and therefore I have no idea from which one it tries to import.

**To Help Reproduce**
Steps to help reproduce the behavior:
1. Import old password from V4 config
2. use successfully
3. change password
4. no option in UI to enter new password
5. try to import cookie instead, since that is the only option
6. doesn't work

**Setup Information**
 - OS: Debian 12
 - Cyberdrop Downloader Version 5.1.22

**Downloader.log file**
[downloader.log](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/13756165/downloader.log)

**Comment by Jules-WinnfieldX** [comment]
In the log provided there is no XF cookies in the auth file, and there is only a user/pass for xbunker.

**Comment by Jules-WinnfieldX** [comment]
make sure you press done in the ui until you reach the main menu again for the configs to be saved.
