### ISSUE TITLE
[BUG] Bunkr is sending garbage files in DDOS state

### ISSUE THREAD

**Issue by bewbylover** [Jules-WinnfieldX/CyberDropDownloader#751]
**Describe the bug**
I guess I am just curious if we are marking the download as complete with these files, or if we will try again.

**To Help Reproduce**
Steps to help reproduce the behavior:
1. Hard to reproduce, have to be close to DDOS state with them, then my guess is post scrape pre download we enter DDOS state and download a file like what I attached.

**Screenshots**
N/A

**Setup Information**
 - OS: Ubuntu 20.04.6 LTS
 - python 3.11.6
 - Cyberdrop Downloader V5.1.22

**Downloader.log file**
[downloader.zip](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/13756402/downloader.zip)

**Additional context**
Here is an example file: 
https://github.com/Jules-WinnfieldX/CyberDropDownloader/assets/152096820/58f950bf-7163-46b1-9e94-0e9b192c0340

**Comment by Jules-WinnfieldX** [comment]
Not sure there's much I can do about that currently. I'd need to see your cyberdrop.db file and the actual filename of what that video was.

**Comment by bewbylover** [comment]
saved as "%5Btanyabahtina-WadeRepack%5D__1-aU9XkxK2.mp4" for an example.  Uploaded the file, the log, and the DB here https://drive.google.com/drive/folders/1MFPUZb6yn7zS8gEDYsDZXeegrBdOeLW-?usp=sharing

Let me know if it works.

Also I am not sure why but the log stopped generating 5.5 hours ago, and the application just stopped without exiting.  Scrape and downloads were empty on the window.  I noticed it when I went to search the log for the file name.  The bunkr link is https://bunkrr.su/a/EZzUeVjs if that helps.

**Comment by bewbylover** [comment]
Update, figured out the log issue, ran out of space on the folder where the downloads are which probably broke things.  I guess the limit isn't working quit right, it should have stopped at 5GB.

**Comment by Jules-WinnfieldX** [comment]
Should be resolved in 5.1.24

**Comment by Jules-WinnfieldX** [comment]
5.1.25 should address the free space thing
