### ISSUE TITLE
[BUG] Reaching the space limit doesn't exit the program

### ISSUE THREAD

**Issue by bewbylover** [Jules-WinnfieldX/CyberDropDownloader#753]
**Describe the bug**
Once the space threshold was crossed the application stopped downloading and scraping, but doesn't exit the program gracefully.

**To Help Reproduce**
Steps to help reproduce the behavior:
1. Start application, adjust threshold to be close to free space.
2. Fill up download location, application will skip files to download and scrape, but not exit.

**Screenshots**
![Screenshot from 2023-12-24 09-00-35](https://github.com/Jules-WinnfieldX/CyberDropDownloader/assets/152096820/89215dab-0f1d-4b21-9d95-7f0e24ccdb2a)

**Setup Information**
 - OS: Ubuntu 20.04.6 LTS
 - python 3.11.6
 - Cyberdrop Downloader V5.1.25

**Downloader.log file**
[downloader.zip](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/13762410/downloader.zip)

**Additional context**
Unrelated to the exit, If possible it would be nice to include the running version on the activity screen so that we don't have to remember what version we started with.

**Comment by Jules-WinnfieldX** [comment]
This is by design, you can free up space after, then use the download failed option in the UI.

**Comment by bewbylover** [comment]
How do you get back to the menu?

**Comment by Jules-WinnfieldX** [comment]
Run the program again

**Comment by bewbylover** [comment]
it's hard to know that it stopped, would it be possible to indicate complete in the windows?

**Comment by Jules-WinnfieldX** [comment]
It clears screen and exits when it's complete

**Comment by bewbylover** [comment]
for me it just did the screenshot I shared above

**Comment by Jules-WinnfieldX** [comment]
Then there are probably still things it's doing in the background (like retrying certain downloads)

**Comment by Jules-WinnfieldX** [comment]
patience

**Comment by bewbylover** [comment]
Fair enough, in that instance it was ~10 minutes post last scrape.  Next time I will give it more time.  Shouldn't it have shown something in the status window if there were activities going on?  Also with the space limit reached, why retry any downloads?

**Comment by Jules-WinnfieldX** [comment]
Not necessarily, it's complicated.

**Comment by bewbylover** [comment]
Fair enough, thanks for the response
