### ISSUE TITLE
Skipping all files - stating Previously Downloaded files, after the recent update!!![BUG]

### ISSUE THREAD

**Issue by kabirnarain** [Jules-WinnfieldX/CyberDropDownloader#755]
**Describe the bug**
Make sure to read the FAQ here first: https://github.com/Jules-WinnfieldX/CyberDropDownloader/wiki

**To Help Reproduce**
Steps to help reproduce the behavior:
1. Describe the bug accurately. - Unable to download anything, from anysite - everytime I start the dowloader, its skipping all the files stating they have been previously downloaded. However, the links and artist are absolutely new. I am not sure how this started, as I was able to use the downloader pretty well. I have also updated the downloader to the latest.
2. Provide an example album that showcases it (if applicable) - https://bunkrr.su/a/Wxr3AHkl (Bunkrr Album)
3. Make sure you are updated to the latest version to see if it's already fixed. - Done

**Screenshots**

**Setup Information**
 - OS: WIndows 11
 - Cyberdrop Downloader Version # V5.1.26, updated PIP to latest as well

**Downloader.log file**
You need to include the downloader.log file after the issue occurs. Majority of the time it's the only way to diagnose issues. 

**Additional context**
![image](https://github.com/Jules-WinnfieldX/CyberDropDownloader/assets/118614270/38fa2288-2503-4898-8562-c303e9b5ebbc)

**Comment by Jules-WinnfieldX** [comment]
The album you linked is from over a year ago, it's something you had already downloaded.

**Comment by kabirnarain** [comment]
Another screenshot, I have tried playing aroung with configuration options. However, nothings seems to be working at the moment
![image](https://github.com/Jules-WinnfieldX/CyberDropDownloader/assets/118614270/8372bd20-7f20-473c-8e80-83b250eee4f8)

**Comment by kabirnarain** [comment]
These are all new for me, I checked my repository as well. Its the same behaviour for everylink
https://bunkrr.su/a/b6GVx55z
https://bunkrr.su/a/F4k6kyLR
https://bunkrr.su/a/BtcnrMGV
https://bunkrr.su/a/W8iTxVUh
https://bunkrr.su/a/b6upGU6u
https://bunkrr.su/a/JCAh2QWI
https://bunkrr.su/a/AgGnIVIv
https://bunkrr.su/a/738I6d9E
https://bunkrr.su/a/N9QSw9f8
https://bunkrr.su/a/UcT6aU7r
https://bunkrr.su/a/3G1Sw0e5
https://bunkrr.su/a/Xk0vCkCY
https://bunkrr.su/a/CtMBdo54
https://bunkrr.su/a/5bA71DRc
https://bunkrr.su/a/xe20ahoO

**Comment by Jules-WinnfieldX** [comment]
It's either you downloaded it, or ran with skip_download_mark_complete set to true. The program can't skip links otherwise.

**Comment by kabirnarain** [comment]
I even tried to change the configuration to - ignore the history but no success 
![image](https://github.com/Jules-WinnfieldX/CyberDropDownloader/assets/118614270/ad7b2c38-09ec-4e28-8ab6-28fa0f65edf9)

**Comment by Jules-WinnfieldX** [comment]
then I'll need to see a log file, as the issue template states.

**Comment by kabirnarain** [comment]
Ok, sharing it

**Comment by kabirnarain** [comment]
[Download_Error_URLs.csv](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/13773476/Download_Error_URLs.csv)
[Last_Scraped_Forum_Posts.txt](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/13773478/Last_Scraped_Forum_Posts.txt)
[Scrape_Error_URLs.csv](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/13773479/Scrape_Error_URLs.csv)
[Unsupported_URLs.txt](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/13773480/Unsupported_URLs.txt)
[downloader.log](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/13773481/downloader.log)

**Comment by Jules-WinnfieldX** [comment]
well for one, you don't have the above set to true. you need to go back to the main menu for it to save. 

Two, try downloading this: https://bunkrr.su/a/ZmR0WLUp

**Comment by kabirnarain** [comment]
[downloader.log](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/13773496/downloader.log)
See this log file, this will have the max history. I tried creating new configs so I guess the earlier log file may not have enough. Let me try downloading the link you shared.

**Comment by Jules-WinnfieldX** [comment]
the history is independent of configs, all configs use the same history.

**Comment by kabirnarain** [comment]
Same thing, 
![image](https://github.com/Jules-WinnfieldX/CyberDropDownloader/assets/118614270/3f017f67-b301-443a-9f18-75830a68cb3f)

**Comment by kabirnarain** [comment]
Should I re-install?

**Comment by Jules-WinnfieldX** [comment]
let me see your cyberdrop.db file in ./appdata/cache

**Comment by kabirnarain** [comment]
ok
[cyberdrop.zip](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/13773553/cyberdrop.zip)

**Comment by Jules-WinnfieldX** [comment]
This is user error somewhere on your end. The program is working as expected, it downloads files, then skips redownloading them in subsequent runs.

**Comment by kabirnarain** [comment]
What do you suggest, it was working fine till yesterday?

**Comment by ZeroRaven23** [comment]
I'm having the same problem
