### ISSUE TITLE
[FEATURE] Downloading files from Imsgbox based on the order from it.

### ISSUE THREAD

**Issue by D0n-A** [Jules-WinnfieldX/CyberDropDownloader#758]
Hello! The problem is the following: when downloading files from the Imgbox website, they are saved without a certain sorting.

**Description**:
01. Let's take this link as a random example: [https://imgbox.com/g/7S5aFwbuOd];
02. Add it as usual to the grabber on the standard settings;
03. It will be saved, but their order will definitely be broken (0Qhchuq2_o.jpg will be displayed first in Windows Explorer, the second one is 3u5kO1Hr_o.jpg, etc.);
04. Different settings of the grabber itself (including) its sorting does not work, the sorting options in Windows do not help.

**Solution**:
Unfortunately, there is no specific solution, but perhaps this fact will help you somehow: each image has its own title (for example, title="k001.jpg ", title="p155.jpg " etc.) - perhaps it is on the basis of these names that the site forms the order of their display.

**Additional context**:
01. It would be useful for a person to have a choice/toggle of exactly how files from this site were saved: someone may need to save them in the current version (0Qhchuq2_o.jpg ), to someone as in the "title" (k001.jpg );
02. And (or) a counter would be implemented in the names (or with `sort_downloads: true` or even without it, just when saving - so that the program could automatically number files, at least on some sites (01. k001.jpg , 02. k008.jpg or you could have set 001. k001.jpg , 002. k008.jpg ).

Perhaps all of the above does not make sense / is not feasible, but in any case, thank you and happy upcoming (and / or upcoming) holidays!!

**Comment by Jules-WinnfieldX** [comment]
I won't rename files outside of what they are on the actual website. On the website they appear and download as the `0Qhchuq2_o.jpg` files.
