### ISSUE TITLE
Ctrl-C doesn't stop the download

### ISSUE THREAD

**Issue by rdnkarchiver** [Jules-WinnfieldX/CyberDropDownloader#76]
If you kick off a big download, you cannot stop it (unless you find and kill the process I guess).

If I had to guess, the download threads/subprocesses are being "orphaned" or otherwise disconnected from the main process, so Ctrl-C doesn't have any effect. Just a guess though, I could be way off.

**Comment by Jules-WinnfieldX** [comment]
I believe this has to do with the use of nest_asyncio and it not currently handling interrupts correctly. I could also be wrong on that. 

The use of that library was brought in to bridge the loops between asyncio and scrapy, without it reactor errors were taking place. Not sure what to do about this.

**Comment by Jules-WinnfieldX** [comment]
This is fixed with the rewrite away from scrapy.
