### ISSUE TITLE
[BUG]  socialmediagirls links all fail login

### ISSUE THREAD

**Issue by bewbylover** [Jules-WinnfieldX/CyberDropDownloader#760]
**Describe the bug**
Login is correct, I validated it manually and browsed the forum, but the application is failing to be able to log in.  I also tried the xf user cookie, and that was unsuccessful too.  Is there anything you know that will allow those links to be scrapable again?

**To Help Reproduce**
Unsure how I got into this state, it was working in 4.x and for a little time in 5.X, I am not sure how long ago it stopped.

**Screenshots**
N/A

**Setup Information**
 - OS: Ubuntu 20.04.6 LTS
 - python 3.11.6
 - Cyberdrop Downloader V5.1.27

**Downloader.log file**
I can make one if it would help, not sure that it is an application issue.

**Additional context**

**Comment by Jules-WinnfieldX** [comment]
You need to use the xf cookie. Regular login won't work as there is a captcha on the login page.

**Comment by bewbylover** [comment]
The one I had was the URL decoded, and that didn't work.  Tried again with the non-decoded value and that worked.

**Comment by Quaso00** [comment]
Hey, how can I found the xf cookie. I dont understand (f95zone_xf_user_cookie: '' -- socialmediagirls_xf_user_cookie: '' ) Can someone help me?
