### ISSUE TITLE
[FEATURE] Show Number of "Remaining" Files

### ISSUE THREAD

**Issue by gashtal** [Jules-WinnfieldX/CyberDropDownloader#761]
**Is your feature request related to a problem? Please describe.**
Currently CDL only shows the status of files that it has tried to download so far (Completed, Previously Downloaded, etc.). It would be also helpful to show the number of total or remaining/pending files in the download screen which would give an idea of how many files are left to be downloaded.

**Describe the solution you'd like**
Please add a "Total" or "Remaining" file count to the download screen in the "Files" section.

**Comment by Jules-WinnfieldX** [comment]
Not possible as CDL scrapes as it downloads. There is no way for the program to know the remaining number.

**Comment by gashtal** [comment]
@Jules-WinnfieldX I understand that this might take more work than it is worth it to implement, but isn't it possible to get the total file count for albums from the album page's source for most sites? e.g., for bunkrr albums, the count of `class="grid-images_box rounded-lg` in the page source will give the total file count for that album. A quick starting scrape can count the files for each album and add them up to get the total file count. Remaining file count will be total minus the sum of "Completed", "Previously Downloaded", etc.

**Comment by Jules-WinnfieldX** [comment]
It's the quick starting scrape that isn't possible. The program follows linearly (basically) the links it finds. Any and every request counts towards ratelimiting, bunkr especially. Bunkr is already heavily restricted to try and get around ddos-guard.

**Comment by Jules-WinnfieldX** [comment]
You'd also need to parse through each and every link initially and prioritize them based on forum, then albums, then direct links, for every site supported.

**Comment by Jules-WinnfieldX** [comment]
And come up with a prioritization structure on what needs to be run first. 

So sure, it's technically possible, but it wouldn't be quick, and is way too much effort than it is worth. Especially when the program already says how many links remain.
