### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Harachai** [Jules-WinnfieldX/CyberDropDownloader#764]
I have installed 5.1, and it starts successfully, 

i put in the URL, and in a few seconds it came back as failed. 
looking at the log it seems there was an authentication failure
i am on windows 10 64 bit

[downloader.log](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/13803639/downloader.log)

**Comment by Jules-WinnfieldX** [comment]
This isn't an issue with the program. It's an issue with your computer trying to connect to Cyberdrop.

**Comment by Harachai** [comment]
So, what do i do? how do i find out the issue?

**Comment by Jules-WinnfieldX** [comment]
If you can't access the site without a VPN, then you need a system wide VPN, not a browser VPN.

**Comment by Harachai** [comment]
i can access the site, i can access the files, and download them individiually, but i can't seem to do it through the program
