### ISSUE TITLE
skipped by config (insufficient free space)

### ISSUE THREAD

**Issue by roweger** [Jules-WinnfieldX/CyberDropDownloader#765]
**Describe the bug**
I went through the [previous thread with this same title/issue](https://github.com/Jules-WinnfieldX/CyberDropDownloader/issues/651), and it doesn't appear it's the same thing.

In my case, it's a fresh install from Start Windows.bat, and the final readout does register all the files from the link and says they were skipped:

"Skipped By Config 31 files"

In the downloader.log file, each download says it was skipped "due to insufficient free space"...but these are just ~1MB images and the drive has hundreds of GB free. I haven't altered any of the installation files, aside from entering the link in the URL.txt.

**Setup Information**
 - OS: Windows 10
 - Cyberdrop Downloader Version # 5.1.28

Any ideas?

**Comment by Jules-WinnfieldX** [comment]
I'd need to see the log.

**Comment by roweger** [comment]
<details><summary>click for downloader.log:</summary>
<p>

INFO     : 2024-01-01 16:43:18,135 : utilities.py:98 : Starting Async Processes...
DEBUG    : 2024-01-01 16:43:18,135 : utilities.py:98 : Starting Cyberdrop-DL Process for Default Config
DEBUG    : 2024-01-01 16:43:18,135 : utilities.py:98 : Running version 5.1.28
DEBUG    : 2024-01-01 16:43:18,135 : utilities.py:98 : Using Config: Default
DEBUG    : 2024-01-01 16:43:18,135 : utilities.py:98 : Using Config File: AppData\Configs\Default\settings.yaml
DEBUG    : 2024-01-01 16:43:18,135 : utilities.py:98 : Using Input File: AppData\Configs\Default\URLs.txt
DEBUG    : 2024-01-01 16:43:18,135 : utilities.py:98 : Using Download Folder: Downloads\Cyberdrop-DL Downloads
DEBUG    : 2024-01-01 16:43:18,135 : utilities.py:98 : Using History File: AppData\Cache\cyberdrop.db
DEBUG    : 2024-01-01 16:43:18,135 : utilities.py:98 : Using Authentication: 
{
    "DDOS-Guard": {
        "Bunkrr Provided": false,
        "Coomer Provided": false,
        "Kemono Provided": false
    },
    "Forums Credentials": {
        "celebforum Credentials Provided": false,
        "f95zone Credentials Provided": false,
        "leakedmodels Credentials Provided": false,
        "nudostar Credentials Provided": false,
        "simpcity Credentials Provided": false,
        "socialmediagirls Credentials Provided": false,
        "xbunker Credentials Provided": false
    },
    "Forums XF Cookies": {
        "celebforum XF Cookie Provided": false,
        "f95zone XF Cookie Provided": false,
        "leakedmodels XF Cookie Provided": false,
        "nudostar XF Cookie Provided": false,
        "simpcity XF Cookie Provided": false,
        "socialmediagirls XF Cookie Provided": false,
        "xbunker XF Cookie Provided": false
    },
    "GoFile Provided": false,
    "Imgur Provided": false,
    "JDownloader Provided": false,
    "PixelDrain Provided": false,
    "Reddit Provided": false
}
DEBUG    : 2024-01-01 16:43:18,135 : utilities.py:98 : Using Settings: 
{
    "Download_Options": {
        "block_download_sub_folders": false,
        "disable_download_attempt_limit": false,
        "disable_file_timestamps": false,
        "include_album_id_in_folder_name": false,
        "include_thread_id_in_folder_name": false,
        "remove_domains_from_folder_names": false,
        "remove_generated_id_from_filenames": false,
        "scrape_single_forum_post": false,
        "separate_posts": false,
        "skip_download_mark_completed": false
    },
    "File_Size_Limits": {
        "maximum_image_size": 0,
        "maximum_other_size": 0,
        "maximum_video_size": 0,
        "minimum_image_size": 0,
        "minimum_other_size": 0,
        "minimum_video_size": 0
    },
    "Files": {
        "download_folder": "Downloads\\Cyberdrop-DL Downloads",
        "input_file": "AppData\\Configs\\Default\\URLs.txt"
    },
    "Ignore_Options": {
        "exclude_audio": false,
        "exclude_images": false,
        "exclude_other": false,
        "exclude_videos": false,
        "ignore_coomer_ads": false,
        "only_hosts": [],
        "skip_hosts": []
    },
    "Logs": {
        "download_error_urls_filename": "Download_Error_URLs.csv",
        "last_forum_post_filename": "Last_Scraped_Forum_Posts.txt",
        "log_folder": "AppData\\Configs\\Default\\Logs",
        "main_log_filename": "downloader.log",
        "scrape_error_urls_filename": "Scrape_Error_URLs.csv",
        "unsupported_urls_filename": "Unsupported_URLs.txt"
    },
    "Runtime_Options": {
        "delete_partial_files": false,
        "ignore_history": false,
        "log_level": 10,
        "send_unsupported_to_jdownloader": false,
        "skip_check_for_empty_folders": false,
        "skip_check_for_partial_files": false
    },
    "Sorting": {
        "sort_downloads": false,
        "sort_folder": "Downloads\\Cyberdrop-DL Sorted Downloads",
        "sort_incremementer_format": " ({i})",
        "sorted_audio": "{sort_dir}/{base_dir}/Audio/{filename}{ext}",
        "sorted_image": "{sort_dir}/{base_dir}/Images/{filename}{ext}",
        "sorted_other": "{sort_dir}/{base_dir}/Other/{filename}{ext}",
        "sorted_video": "{sort_dir}/{base_dir}/Videos/{filename}{ext}"
    }
}
DEBUG    : 2024-01-01 16:43:18,135 : utilities.py:98 : Using Global Settings: 
{
    "General": {
        "allow_insecure_connections": false,
        "max_file_name_length": 95,
        "max_folder_name_length": 60,
        "proxy": "",
        "required_free_space": 5,
        "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:120.0) Gecko/20100101 Firefox/120.0"
    },
    "Rate_Limiting_Options": {
        "connection_timeout": 15,
        "download_attempts": 10,
        "download_delay": 0,
        "max_simultaneous_downloads": 15,
        "max_simultaneous_downloads_per_domain": 5,
        "rate_limit": 50,
        "read_timeout": 300
    }
}
INFO     : 2024-01-01 16:43:18,145 : utilities.py:98 : Starting UI...
INFO     : 2024-01-01 16:43:18,245 : utilities.py:98 : Scrape Starting: https://bunkrr.su/a/2YiXLqhn
INFO     : 2024-01-01 16:43:18,959 : utilities.py:98 : Download Starting: https://i-milkshake.bunkr.ru/1-(1)-u7rMnJfN.jpg?download=true
DEBUG    : 2024-01-01 16:43:18,959 : utilities.py:98 : Download Skip https://i-milkshake.bunkr.ru/1-(1)-u7rMnJfN.jpg?download=true due to insufficient free space
INFO     : 2024-01-01 16:43:18,959 : utilities.py:98 : Download Finished: https://i-milkshake.bunkr.ru/1-(1)-u7rMnJfN.jpg?download=true
INFO     : 2024-01-01 16:43:18,975 : utilities.py:98 : Download Starting: https://i-milkshake.bunkr.ru/1-(2)-EowwPiIH.jpg?download=true
DEBUG    : 2024-01-01 16:43:18,975 : utilities.py:98 : Download Skip https://i-milkshake.bunkr.ru/1-(2)-EowwPiIH.jpg?download=true due to insufficient free space
INFO     : 2024-01-01 16:43:18,975 : utilities.py:98 : Download Finished: https://i-milkshake.bunkr.ru/1-(2)-EowwPiIH.jpg?download=true
INFO     : 2024-01-01 16:43:18,975 : utilities.py:98 : Download Starting: https://i-milkshake.bunkr.ru/1-(3)-zx7jQmi3.jpg?download=true
DEBUG    : 2024-01-01 16:43:18,975 : utilities.py:98 : Download Skip https://i-milkshake.bunkr.ru/1-(3)-zx7jQmi3.jpg?download=true due to insufficient free space
INFO     : 2024-01-01 16:43:18,975 : utilities.py:98 : Download Finished: https://i-milkshake.bunkr.ru/1-(3)-zx7jQmi3.jpg?download=true
INFO     : 2024-01-01 16:43:18,975 : utilities.py:98 : Download Starting: https://i-milkshake.bunkr.ru/1-(4)-fFp3czT8.jpg?download=true
DEBUG    : 2024-01-01 16:43:18,975 : utilities.py:98 : Download Skip https://i-milkshake.bunkr.ru/1-(4)-fFp3czT8.jpg?download=true due to insufficient free space
INFO     : 2024-01-01 16:43:18,975 : utilities.py:98 : Download Finished: https://i-milkshake.bunkr.ru/1-(4)-fFp3czT8.jpg?download=true
INFO     : 2024-01-01 16:43:18,975 : utilities.py:98 : Download Starting: https://i-milkshake.bunkr.ru/3-lvY1JC8w.jpg?download=true
DEBUG    : 2024-01-01 16:43:18,975 : utilities.py:98 : Download Skip https://i-milkshake.bunkr.ru/3-lvY1JC8w.jpg?download=true due to insufficient free space
INFO     : 2024-01-01 16:43:18,975 : utilities.py:98 : Download Finished: https://i-milkshake.bunkr.ru/3-lvY1JC8w.jpg?download=true
INFO     : 2024-01-01 16:43:18,975 : utilities.py:98 : Download Starting: https://i-milkshake.bunkr.ru/32131-H9PG7lhJ.jpg?download=true
DEBUG    : 2024-01-01 16:43:18,975 : utilities.py:98 : Download Skip https://i-milkshake.bunkr.ru/32131-H9PG7lhJ.jpg?download=true due to insufficient free space
INFO     : 2024-01-01 16:43:18,975 : utilities.py:98 : Download Finished: https://i-milkshake.bunkr.ru/32131-H9PG7lhJ.jpg?download=true
INFO     : 2024-01-01 16:43:18,975 : utilities.py:98 : Download Starting: https://i-milkshake.bunkr.ru/12312312-sE66ln2a.jpg?download=true
DEBUG    : 2024-01-01 16:43:18,975 : utilities.py:98 : Download Skip https://i-milkshake.bunkr.ru/12312312-sE66ln2a.jpg?download=true due to insufficient free space
INFO     : 2024-01-01 16:43:18,975 : utilities.py:98 : Download Finished: https://i-milkshake.bunkr.ru/12312312-sE66ln2a.jpg?download=true
INFO     : 2024-01-01 16:43:18,975 : utilities.py:98 : Download Starting: https://i-milkshake.bunkr.ru/PatreonTemporaryImage-3621b37d-7a3f-4c47-a029-d8153f010374-papi6b8c.jpg?download=true
DEBUG    : 2024-01-01 16:43:18,975 : utilities.py:98 : Download Skip https://i-milkshake.bunkr.ru/PatreonTemporaryImage-3621b37d-7a3f-4c47-a029-d8153f010374-papi6b8c.jpg?download=true due to insufficient free space
INFO     : 2024-01-01 16:43:18,975 : utilities.py:98 : Download Finished: https://i-milkshake.bunkr.ru/PatreonTemporaryImage-3621b37d-7a3f-4c47-a029-d8153f010374-papi6b8c.jpg?download=true
INFO     : 2024-01-01 16:43:18,975 : utilities.py:98 : Download Starting: https://i-milkshake.bunkr.ru/dani-bathroom-mCMluEGm.jpg?download=true
DEBUG    : 2024-01-01 16:43:18,975 : utilities.py:98 : Download Skip https://i-milkshake.bunkr.ru/dani-bathroom-mCMluEGm.jpg?download=true due to insufficient free space
INFO     : 2024-01-01 16:43:18,975 : utilities.py:98 : Download Finished: https://i-milkshake.bunkr.ru/dani-bathroom-mCMluEGm.jpg?download=true
INFO     : 2024-01-01 16:43:18,975 : utilities.py:98 : Download Starting: https://i-milkshake.bunkr.ru/PatreonTemporaryImage-1d5f9082-581b-49cf-b98e-a1fad5d42406-13DKXR9u.jpg?download=true
DEBUG    : 2024-01-01 16:43:18,975 : utilities.py:98 : Download Skip https://i-milkshake.bunkr.ru/PatreonTemporaryImage-1d5f9082-581b-49cf-b98e-a1fad5d42406-13DKXR9u.jpg?download=true due to insufficient free space
INFO     : 2024-01-01 16:43:18,975 : utilities.py:98 : Download Finished: https://i-milkshake.bunkr.ru/PatreonTemporaryImage-1d5f9082-581b-49cf-b98e-a1fad5d42406-13DKXR9u.jpg?download=true
INFO     : 2024-01-01 16:43:18,975 : utilities.py:98 : Download Starting: https://i-milkshake.bunkr.ru/PatreonTemporaryImage-81f75e77-adf5-4588-8d89-aa29189bad32-QfpDxDg9.jpg?download=true
DEBUG    : 2024-01-01 16:43:18,975 : utilities.py:98 : Download Skip https://i-milkshake.bunkr.ru/PatreonTemporaryImage-81f75e77-adf5-4588-8d89-aa29189bad32-QfpDxDg9.jpg?download=true due to insufficient free space
INFO     : 2024-01-01 16:43:18,975 : utilities.py:98 : Download Finished: https://i-milkshake.bunkr.ru/PatreonTemporaryImage-81f75e77-adf5-4588-8d89-aa29189bad32-QfpDxDg9.jpg?download=true
INFO     : 2024-01-01 16:43:18,975 : utilities.py:98 : Download Starting: https://i-milkshake.bunkr.ru/PatreonTemporaryImage-e0ed86b5-942e-47b1-b036-04bfb7f5b404-kWKC6zVN.jpg?download=true
DEBUG    : 2024-01-01 16:43:18,975 : utilities.py:98 : Download Skip https://i-milkshake.bunkr.ru/PatreonTemporaryImage-e0ed86b5-942e-47b1-b036-04bfb7f5b404-kWKC6zVN.jpg?download=true due to insufficient free space
INFO     : 2024-01-01 16:43:18,975 : utilities.py:98 : Download Finished: https://i-milkshake.bunkr.ru/PatreonTemporaryImage-e0ed86b5-942e-47b1-b036-04bfb7f5b404-kWKC6zVN.jpg?download=true
INFO     : 2024-01-01 16:43:18,975 : utilities.py:98 : Download Starting: https://i-milkshake.bunkr.ru/PatreonTemporaryImage-e9b063bc-59de-48f9-8cea-189931fdb2ec-8ueNv15x.jpg?download=true
DEBUG    : 2024-01-01 16:43:18,975 : utilities.py:98 : Download Skip https://i-milkshake.bunkr.ru/PatreonTemporaryImage-e9b063bc-59de-48f9-8cea-189931fdb2ec-8ueNv15x.jpg?download=true due to insufficient free space
INFO     : 2024-01-01 16:43:18,975 : utilities.py:98 : Download Finished: https://i-milkshake.bunkr.ru/PatreonTemporaryImage-e9b063bc-59de-48f9-8cea-189931fdb2ec-8ueNv15x.jpg?download=true
INFO     : 2024-01-01 16:43:18,975 : utilities.py:98 : Download Starting: https://i-milkshake.bunkr.ru/PatreonTemporaryImage-f6d08bf6-e1b9-404e-80c5-6b521309b6b1-VIZPaNYL.jpg?download=true
DEBUG    : 2024-01-01 16:43:18,975 : utilities.py:98 : Download Skip https://i-milkshake.bunkr.ru/PatreonTemporaryImage-f6d08bf6-e1b9-404e-80c5-6b521309b6b1-VIZPaNYL.jpg?download=true due to insufficient free space
INFO     : 2024-01-01 16:43:18,975 : utilities.py:98 : Download Finished: https://i-milkshake.bunkr.ru/PatreonTemporaryImage-f6d08bf6-e1b9-404e-80c5-6b521309b6b1-VIZPaNYL.jpg?download=true
INFO     : 2024-01-01 16:43:18,975 : utilities.py:98 : Download Starting: https://i-milkshake.bunkr.ru/PatreonTemporaryImage-fe31b5e0-6072-44dd-9624-a893cad53eef-U7MtTr3C.jpg?download=true
DEBUG    : 2024-01-01 16:43:18,975 : utilities.py:98 : Download Skip https://i-milkshake.bunkr.ru/PatreonTemporaryImage-fe31b5e0-6072-44dd-9624-a893cad53eef-U7MtTr3C.jpg?download=true due to insufficient free space
INFO     : 2024-01-01 16:43:18,975 : utilities.py:98 : Download Finished: https://i-milkshake.bunkr.ru/PatreonTemporaryImage-fe31b5e0-6072-44dd-9624-a893cad53eef-U7MtTr3C.jpg?download=true
INFO     : 2024-01-01 16:43:18,975 : utilities.py:98 : Download Starting: https://i-milkshake.bunkr.ru/PatreonTemporaryImage-fea3600f-ae75-47e0-b982-9e05f7fa3494-1ZKibsCi.jpg?download=true
DEBUG    : 2024-01-01 16:43:18,975 : utilities.py:98 : Download Skip https://i-milkshake.bunkr.ru/PatreonTemporaryImage-fea3600f-ae75-47e0-b982-9e05f7fa3494-1ZKibsCi.jpg?download=true due to insufficient free space
INFO     : 2024-01-01 16:43:18,975 : utilities.py:98 : Download Finished: https://i-milkshake.bunkr.ru/PatreonTemporaryImage-fea3600f-ae75-47e0-b982-9e05f7fa3494-1ZKibsCi.jpg?download=true
INFO     : 2024-01-01 16:43:18,975 : utilities.py:98 : Download Starting: https://i-milkshake.bunkr.ru/PatreonTemporaryImage-02df33aa-ee3c-4d66-82ec-e2aaf207087b-HHNDTlhj.jpg?download=true
DEBUG    : 2024-01-01 16:43:18,975 : utilities.py:98 : Download Skip https://i-milkshake.bunkr.ru/PatreonTemporaryImage-02df33aa-ee3c-4d66-82ec-e2aaf207087b-HHNDTlhj.jpg?download=true due to insufficient free space
INFO     : 2024-01-01 16:43:18,975 : utilities.py:98 : Download Finished: https://i-milkshake.bunkr.ru/PatreonTemporaryImage-02df33aa-ee3c-4d66-82ec-e2aaf207087b-HHNDTlhj.jpg?download=true
INFO     : 2024-01-01 16:43:18,975 : utilities.py:98 : Download Starting: https://i-milkshake.bunkr.ru/PatreonTemporaryImage-6cd5f716-627f-4936-9516-2727a44c6820-6h2TPDzB.jpg?download=true
DEBUG    : 2024-01-01 16:43:18,975 : utilities.py:98 : Download Skip https://i-milkshake.bunkr.ru/PatreonTemporaryImage-6cd5f716-627f-4936-9516-2727a44c6820-6h2TPDzB.jpg?download=true due to insufficient free space
INFO     : 2024-01-01 16:43:18,975 : utilities.py:98 : Download Finished: https://i-milkshake.bunkr.ru/PatreonTemporaryImage-6cd5f716-627f-4936-9516-2727a44c6820-6h2TPDzB.jpg?download=true
INFO     : 2024-01-01 16:43:18,990 : utilities.py:98 : Download Starting: https://i-milkshake.bunkr.ru/PatreonTemporaryImage-9dc32a8c-85e7-485b-90d2-0c448ce29d9c-3woNsECw.jpg?download=true
DEBUG    : 2024-01-01 16:43:18,990 : utilities.py:98 : Download Skip https://i-milkshake.bunkr.ru/PatreonTemporaryImage-9dc32a8c-85e7-485b-90d2-0c448ce29d9c-3woNsECw.jpg?download=true due to insufficient free space
INFO     : 2024-01-01 16:43:18,990 : utilities.py:98 : Download Finished: https://i-milkshake.bunkr.ru/PatreonTemporaryImage-9dc32a8c-85e7-485b-90d2-0c448ce29d9c-3woNsECw.jpg?download=true
INFO     : 2024-01-01 16:43:18,990 : utilities.py:98 : Download Starting: https://i-milkshake.bunkr.ru/PatreonTemporaryImage-248bb6c5-cd31-4a3b-816a-ec6b07c4fcf3.jpg.;-filename.=utf-8''PatreonTemporaryImage-248bb6c5-cd31-4a3b-816a-ec6b07c4fcf3.jp-k6l0s8H5.jpg?download=true
DEBUG    : 2024-01-01 16:43:18,990 : utilities.py:98 : Download Skip https://i-milkshake.bunkr.ru/PatreonTemporaryImage-248bb6c5-cd31-4a3b-816a-ec6b07c4fcf3.jpg.;-filename.=utf-8''PatreonTemporaryImage-248bb6c5-cd31-4a3b-816a-ec6b07c4fcf3.jp-k6l0s8H5.jpg?download=true due to insufficient free space
INFO     : 2024-01-01 16:43:18,990 : utilities.py:98 : Download Finished: https://i-milkshake.bunkr.ru/PatreonTemporaryImage-248bb6c5-cd31-4a3b-816a-ec6b07c4fcf3.jpg.;-filename.=utf-8''PatreonTemporaryImage-248bb6c5-cd31-4a3b-816a-ec6b07c4fcf3.jp-k6l0s8H5.jpg?download=true
INFO     : 2024-01-01 16:43:18,990 : utilities.py:98 : Download Starting: https://i-milkshake.bunkr.ru/PatreonTemporaryImage-9309f869-8e69-4479-9af5-2fc494fa1982-nhD9d6km.jpg?download=true
DEBUG    : 2024-01-01 16:43:18,990 : utilities.py:98 : Download Skip https://i-milkshake.bunkr.ru/PatreonTemporaryImage-9309f869-8e69-4479-9af5-2fc494fa1982-nhD9d6km.jpg?download=true due to insufficient free space
INFO     : 2024-01-01 16:43:18,990 : utilities.py:98 : Download Finished: https://i-milkshake.bunkr.ru/PatreonTemporaryImage-9309f869-8e69-4479-9af5-2fc494fa1982-nhD9d6km.jpg?download=true
INFO     : 2024-01-01 16:43:18,990 : utilities.py:98 : Download Starting: https://i-milkshake.bunkr.ru/PatreonTemporaryImage-086638bd-8799-48b5-8d88-ef827c4e5628.jpg.;-filename.=utf-8''PatreonTemporaryImage-086638bd-8799-48b5-8d88-ef827c4e5628.jp-gvkahGAo.jpg?download=true
DEBUG    : 2024-01-01 16:43:18,990 : utilities.py:98 : Download Skip https://i-milkshake.bunkr.ru/PatreonTemporaryImage-086638bd-8799-48b5-8d88-ef827c4e5628.jpg.;-filename.=utf-8''PatreonTemporaryImage-086638bd-8799-48b5-8d88-ef827c4e5628.jp-gvkahGAo.jpg?download=true due to insufficient free space
INFO     : 2024-01-01 16:43:18,990 : utilities.py:98 : Download Finished: https://i-milkshake.bunkr.ru/PatreonTemporaryImage-086638bd-8799-48b5-8d88-ef827c4e5628.jpg.;-filename.=utf-8''PatreonTemporaryImage-086638bd-8799-48b5-8d88-ef827c4e5628.jp-gvkahGAo.jpg?download=true
INFO     : 2024-01-01 16:43:18,990 : utilities.py:98 : Download Starting: https://i-milkshake.bunkr.ru/PatreonTemporaryImage-a0786e48-11c8-4a16-bc01-322aeefe18a0-H2JdJmFI.jpg?download=true
DEBUG    : 2024-01-01 16:43:18,990 : utilities.py:98 : Download Skip https://i-milkshake.bunkr.ru/PatreonTemporaryImage-a0786e48-11c8-4a16-bc01-322aeefe18a0-H2JdJmFI.jpg?download=true due to insufficient free space
INFO     : 2024-01-01 16:43:18,990 : utilities.py:98 : Download Finished: https://i-milkshake.bunkr.ru/PatreonTemporaryImage-a0786e48-11c8-4a16-bc01-322aeefe18a0-H2JdJmFI.jpg?download=true
INFO     : 2024-01-01 16:43:18,990 : utilities.py:98 : Download Starting: https://i-milkshake.bunkr.ru/PatreonTemporaryImage-b466bbc2-4fab-4538-80f5-f922a46e2ed2-pCeMoDbH.jpg?download=true
DEBUG    : 2024-01-01 16:43:18,990 : utilities.py:98 : Download Skip https://i-milkshake.bunkr.ru/PatreonTemporaryImage-b466bbc2-4fab-4538-80f5-f922a46e2ed2-pCeMoDbH.jpg?download=true due to insufficient free space
INFO     : 2024-01-01 16:43:18,990 : utilities.py:98 : Download Finished: https://i-milkshake.bunkr.ru/PatreonTemporaryImage-b466bbc2-4fab-4538-80f5-f922a46e2ed2-pCeMoDbH.jpg?download=true
INFO     : 2024-01-01 16:43:18,990 : utilities.py:98 : Download Starting: https://i-milkshake.bunkr.ru/PatreonTemporaryImage-f5257ae6-6b92-4892-8526-2ac59d5d7aec-BOCq13ce.jpg?download=true
DEBUG    : 2024-01-01 16:43:18,990 : utilities.py:98 : Download Skip https://i-milkshake.bunkr.ru/PatreonTemporaryImage-f5257ae6-6b92-4892-8526-2ac59d5d7aec-BOCq13ce.jpg?download=true due to insufficient free space
INFO     : 2024-01-01 16:43:18,990 : utilities.py:98 : Download Finished: https://i-milkshake.bunkr.ru/PatreonTemporaryImage-f5257ae6-6b92-4892-8526-2ac59d5d7aec-BOCq13ce.jpg?download=true
INFO     : 2024-01-01 16:43:18,990 : utilities.py:98 : Download Starting: https://i-milkshake.bunkr.ru/PatreonTemporaryImage-7792bd54-2052-41e1-be58-a04df3a163e2-foMt1SvU.jpg?download=true
DEBUG    : 2024-01-01 16:43:18,990 : utilities.py:98 : Download Skip https://i-milkshake.bunkr.ru/PatreonTemporaryImage-7792bd54-2052-41e1-be58-a04df3a163e2-foMt1SvU.jpg?download=true due to insufficient free space
INFO     : 2024-01-01 16:43:18,990 : utilities.py:98 : Download Finished: https://i-milkshake.bunkr.ru/PatreonTemporaryImage-7792bd54-2052-41e1-be58-a04df3a163e2-foMt1SvU.jpg?download=true
INFO     : 2024-01-01 16:43:18,990 : utilities.py:98 : Download Starting: https://i-milkshake.bunkr.ru/PatreonTemporaryImage-6244177a-aaed-4ed8-b72a-f6f423a090d6-YkU5MQPS.jpg?download=true
DEBUG    : 2024-01-01 16:43:18,990 : utilities.py:98 : Download Skip https://i-milkshake.bunkr.ru/PatreonTemporaryImage-6244177a-aaed-4ed8-b72a-f6f423a090d6-YkU5MQPS.jpg?download=true due to insufficient free space
INFO     : 2024-01-01 16:43:18,990 : utilities.py:98 : Download Finished: https://i-milkshake.bunkr.ru/PatreonTemporaryImage-6244177a-aaed-4ed8-b72a-f6f423a090d6-YkU5MQPS.jpg?download=true
INFO     : 2024-01-01 16:43:18,990 : utilities.py:98 : Download Starting: https://i-milkshake.bunkr.ru/21312312-hnXLpjom.jpg?download=true
DEBUG    : 2024-01-01 16:43:18,990 : utilities.py:98 : Download Skip https://i-milkshake.bunkr.ru/21312312-hnXLpjom.jpg?download=true due to insufficient free space
INFO     : 2024-01-01 16:43:18,990 : utilities.py:98 : Download Finished: https://i-milkshake.bunkr.ru/21312312-hnXLpjom.jpg?download=true
INFO     : 2024-01-01 16:43:18,990 : utilities.py:98 : Download Starting: https://i-milkshake.bunkr.ru/123123123-g9ZUryFC.jpg?download=true
DEBUG    : 2024-01-01 16:43:18,990 : utilities.py:98 : Download Skip https://i-milkshake.bunkr.ru/123123123-g9ZUryFC.jpg?download=true due to insufficient free space
INFO     : 2024-01-01 16:43:18,990 : utilities.py:98 : Download Finished: https://i-milkshake.bunkr.ru/123123123-g9ZUryFC.jpg?download=true
INFO     : 2024-01-01 16:43:18,990 : utilities.py:98 : Download Starting: https://milkshake.bunkr.ru/Merry-Christmas!!!-DYfaczoX.mp4?download=true
DEBUG    : 2024-01-01 16:43:18,990 : utilities.py:98 : Download Skip https://milkshake.bunkr.ru/Merry-Christmas!!!-DYfaczoX.mp4?download=true due to insufficient free space
INFO     : 2024-01-01 16:43:18,990 : utilities.py:98 : Download Finished: https://milkshake.bunkr.ru/Merry-Christmas!!!-DYfaczoX.mp4?download=true
INFO     : 2024-01-01 16:43:18,990 : utilities.py:98 : Download Starting: https://i-milkshake.bunkr.ru/7-X09Mn5DL.jpg?download=true
DEBUG    : 2024-01-01 16:43:18,990 : utilities.py:98 : Download Skip https://i-milkshake.bunkr.ru/7-X09Mn5DL.jpg?download=true due to insufficient free space
INFO     : 2024-01-01 16:43:18,990 : utilities.py:98 : Download Finished: https://i-milkshake.bunkr.ru/7-X09Mn5DL.jpg?download=true
INFO     : 2024-01-01 16:43:18,990 : utilities.py:98 : Scrape Finished: https://www.bunkrr.su/a/2YiXLqhn
INFO     : 2024-01-01 16:43:19,053 : utilities.py:98 : Running Post-Download Processes...
INFO     : 2024-01-01 16:43:19,053 : utilities.py:103 : Checking for partial downloads...
INFO     : 2024-01-01 16:43:19,053 : utilities.py:103 : Checking for empty folders...
INFO     : 2024-01-01 16:43:19,053 : utilities.py:98 : Printing Stats...
INFO     : 2024-01-01 16:43:19,053 : utilities.py:103 : 
Download Stats:
INFO     : 2024-01-01 16:43:19,053 : utilities.py:103 : Downloaded 0 files
INFO     : 2024-01-01 16:43:19,053 : utilities.py:103 : Previously Downloaded 0 files
INFO     : 2024-01-01 16:43:19,053 : utilities.py:103 : Skipped By Config 31 files
INFO     : 2024-01-01 16:43:19,053 : utilities.py:103 : Failed 0 files
INFO     : 2024-01-01 16:43:19,053 : utilities.py:103 : 
Scrape Failures:
INFO     : 2024-01-01 16:43:19,053 : utilities.py:103 : 
Download Failures:
INFO     : 2024-01-01 16:43:19,053 : utilities.py:98 : Checking for Program End...
INFO     : 2024-01-01 16:43:19,053 : utilities.py:98 : Checking for Updates...
INFO     : 2024-01-01 16:43:19,345 : utilities.py:98 : Closing Program...
INFO     : 2024-01-01 16:43:19,361 : utilities.py:103 : 
Finished downloading. Enjoy :)

</p>
</details>

**Comment by Jules-WinnfieldX** [comment]
Can I see a screenshot of your drives?

**Comment by roweger** [comment]
Got it working. It was a drive with only 3.59 GB of free space instead of the hundreds.

But wouldn't that still be enough for 66MB of files? Is there some kind of required minimum in the program before it will download anything?

**Comment by Jules-WinnfieldX** [comment]
the program by default has a limit of 5gb free, if it's less than that, no downloads will happen. You can change it in the config.
