### ISSUE TITLE
[FEATURE] Add website to Failure "Failed Login"

### ISSUE THREAD

**Issue by Dorentil** [Jules-WinnfieldX/CyberDropDownloader#768]
**Is your feature request related to a problem? Please describe.**
When downloading from a site, that itself is working well, but links to one (or more) websites, that would require login information, it can be difficult to identify which one is missing/required.

**Describe the solution you'd like**
Replace the generic "Failed Login" error with a "Failed Login <Website_name>".

**Additional context**
![2024-01-03_14-44](https://github.com/Jules-WinnfieldX/CyberDropDownloader/assets/99742937/747ee19e-d84e-4e86-886c-ffa4b991f59d)

**Comment by Jules-WinnfieldX** [comment]
You can see what site these are easily using the scrape_error_urls.csv file in the logs folder for that config. 

It's generic for a reason, reason being not to clutter and try to limit to amount of entries on the UI to keep it readable and not off screen.
