### ISSUE TITLE
[FEATURE] Support for mega.nz

### ISSUE THREAD

**Issue by gashtal** [Jules-WinnfieldX/CyberDropDownloader#770]
**Describe the solution you'd like**
Support for downloading direct links and folders from mega.nz in CDL

**Additional context**
Surprised to see this has not been requested before. I guess the biggest challenge would be handling Mega's daily download limit.

**Comment by Jules-WinnfieldX** [comment]
It's been somewhat requested before, and it's a can of worms I'd prefer to just not open. 

It's not a no forever, it's a no for now.
