### ISSUE TITLE
[BUG] Creating of a New Sorted Downloads Folder after rename of the Main Folder

### ISSUE THREAD

**Issue by V-i-K-M** [Jules-WinnfieldX/CyberDropDownloader#771]
**Describe the bug**

Hi,

i've changed the foldername of the main folder to my need to _Cyberdrop_DL. 
Also maintained the config so that the Downloads folder and logs folder point to the new foldername and path.
And it worked fine without a problem.

Now since recent release (i'm not sure wich) it creates always a new folder with a Downloads Subfolder with the old Name: \Cyberdrop_DL.V5\Downloads\Cyberdrop-DL Sorted Downloads. 

The "new" Downloads folder is empty and my downloads are put correctly at my defined path (_Cyberdrop_DL\Downloads)

The Sorting Downloads Option is disabled

**To Help Reproduce**

Rename the Main Folder and maintain the Download Path to the new Folder.
After that, start a new download

**Screenshot**
![image](https://github.com/Jules-WinnfieldX/CyberDropDownloader/assets/152895279/1d5576fb-ad28-407c-a84c-e3396b3e982a)
![image](https://github.com/Jules-WinnfieldX/CyberDropDownloader/assets/152895279/88b6194b-ddee-4a23-b72f-08d36d95488d)

**Setup Information**
 - OS: Windows 11
 - Cyberdrop Downloader Version 5.1.34

Could you please check?

Regards

**Comment by V-i-K-M** [comment]
Is the downloader log file enough?

**Comment by V-i-K-M** [comment]
[downloader.log](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/13833168/downloader.log)

**Comment by Jules-WinnfieldX** [comment]
5.1.36 going up now to fix.
