### ISSUE TITLE
[BUG] Redgifs scraper url fault

### ISSUE THREAD

**Issue by MachiavelliSeraphim** [Jules-WinnfieldX/CyberDropDownloader#772]
**Describe the bug**
Redgifs links fail with a fault
ERROR    : 2024-01-04 12:06:06,010 : utilities.py:98 : Scrape Failed: https://api.redgifs.com/v2/auth/temporary (ScraperClient.get_json() missing 1 required positional argument: 'url')

**Setup Information**
 - OS: W10
 - Cyberdrop Downloader Version #V5.1.34

**Downloader.log file**
INFO     : 2024-01-04 12:06:05,549 : utilities.py:98 : Starting Async Processes...
DEBUG    : 2024-01-04 12:06:05,549 : utilities.py:98 : Starting Cyberdrop-DL Process for Default Config
DEBUG    : 2024-01-04 12:06:05,549 : utilities.py:98 : Running version 5.1.34
DEBUG    : 2024-01-04 12:06:05,549 : utilities.py:98 : Using Config: Default
DEBUG    : 2024-01-04 12:06:05,549 : utilities.py:98 : Using Config File: AppData\Configs\Default\settings.yaml
DEBUG    : 2024-01-04 12:06:05,549 : utilities.py:98 : Using Input File: AppData\Configs\Default\URLs.txt
DEBUG    : 2024-01-04 12:06:05,550 : utilities.py:98 : Using Download Folder: Downloads\Cyberdrop-DL Downloads
DEBUG    : 2024-01-04 12:06:05,550 : utilities.py:98 : Using History File: AppData\Cache\cyberdrop.db
DEBUG    : 2024-01-04 12:06:05,550 : utilities.py:98 : Using Authentication: 
{
    "DDOS-Guard": {
        "Bunkrr Provided": false,
        "Coomer Provided": false,
        "Kemono Provided": false
    },
    "Forums Credentials": {
        "celebforum Credentials Provided": false,
        "f95zone Credentials Provided": false,
        "leakedmodels Credentials Provided": false,
        "nudostar Credentials Provided": false,
        "simpcity Credentials Provided": false,
        "socialmediagirls Credentials Provided": false,
        "xbunker Credentials Provided": false
    },
    "Forums XF Cookies": {
        "celebforum XF Cookie Provided": false,
        "f95zone XF Cookie Provided": false,
        "leakedmodels XF Cookie Provided": false,
        "nudostar XF Cookie Provided": false,
        "simpcity XF Cookie Provided": false,
        "socialmediagirls XF Cookie Provided": false,
        "xbunker XF Cookie Provided": false
    },
    "GoFile Provided": false,
    "Imgur Provided": false,
    "JDownloader Provided": false,
    "PixelDrain Provided": false,
    "Reddit Provided": false
}
DEBUG    : 2024-01-04 12:06:05,550 : utilities.py:98 : Using Settings: 
{
    "Download_Options": {
        "block_download_sub_folders": false,
        "disable_download_attempt_limit": false,
        "disable_file_timestamps": false,
        "include_album_id_in_folder_name": false,
        "include_thread_id_in_folder_name": false,
        "remove_domains_from_folder_names": false,
        "remove_generated_id_from_filenames": false,
        "scrape_single_forum_post": false,
        "separate_posts": false,
        "skip_download_mark_completed": false
    },
    "File_Size_Limits": {
        "maximum_image_size": 0,
        "maximum_other_size": 0,
        "maximum_video_size": 0,
        "minimum_image_size": 0,
        "minimum_other_size": 0,
        "minimum_video_size": 0
    },
    "Files": {
        "download_folder": "Downloads\\Cyberdrop-DL Downloads",
        "input_file": "AppData\\Configs\\Default\\URLs.txt"
    },
    "Ignore_Options": {
        "exclude_audio": false,
        "exclude_images": false,
        "exclude_other": false,
        "exclude_videos": false,
        "ignore_coomer_ads": false,
        "only_hosts": [],
        "skip_hosts": []
    },
    "Logs": {
        "download_error_urls_filename": "Download_Error_URLs.csv",
        "last_forum_post_filename": "Last_Scraped_Forum_Posts.txt",
        "log_folder": "AppData\\Configs\\Default\\Logs",
        "main_log_filename": "downloader.log",
        "scrape_error_urls_filename": "Scrape_Error_URLs.csv",
        "unsupported_urls_filename": "Unsupported_URLs.txt"
    },
    "Runtime_Options": {
        "delete_partial_files": false,
        "ignore_history": false,
        "log_level": 10,
        "send_unsupported_to_jdownloader": false,
        "skip_check_for_empty_folders": false,
        "skip_check_for_partial_files": false
    },
    "Sorting": {
        "sort_downloads": false,
        "sort_folder": "Downloads\\Cyberdrop-DL Sorted Downloads",
        "sort_incremementer_format": " ({i})",
        "sorted_audio": "{sort_dir}/{base_dir}/Audio/{filename}{ext}",
        "sorted_image": "{sort_dir}/{base_dir}/Images/{filename}{ext}",
        "sorted_other": "{sort_dir}/{base_dir}/Other/{filename}{ext}",
        "sorted_video": "{sort_dir}/{base_dir}/Videos/{filename}{ext}"
    }
}
DEBUG    : 2024-01-04 12:06:05,550 : utilities.py:98 : Using Global Settings: 
{
    "General": {
        "allow_insecure_connections": false,
        "max_file_name_length": 95,
        "max_folder_name_length": 60,
        "proxy": "",
        "required_free_space": 5,
        "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:120.0) Gecko/20100101 Firefox/120.0"
    },
    "Rate_Limiting_Options": {
        "connection_timeout": 15,
        "download_attempts": 10,
        "download_delay": 0,
        "max_simultaneous_downloads": 15,
        "max_simultaneous_downloads_per_domain": 5,
        "rate_limit": 50,
        "read_timeout": 300
    }
}
INFO     : 2024-01-04 12:06:05,575 : utilities.py:98 : Starting UI...
INFO     : 2024-01-04 12:06:05,866 : utilities.py:98 : Scrape Starting: https://www.redgifs.com/watch/slategreynavyflyingfish
ERROR    : 2024-01-04 12:06:05,867 : utilities.py:98 : Scrape Failed: https://api.redgifs.com/v2/auth/temporary (ScraperClient.get_json() missing 1 required positional argument: 'url')
ERROR    : 2024-01-04 12:06:05,868 : utilities.py:98 : Traceback (most recent call last):
  File "C:\Python311\Lib\site-packages\cyberdrop_dl\utils\utilities.py", line 62, in wrapper
    return await func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\cyberdrop_dl\scraper\crawlers\redgifs_crawler.py", line 97, in manage_token
    json_obj = await self.client.get_json(self.domain, )
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\cyberdrop_dl\clients\scraper_client.py", line 32, in wrapper
    return await func(self, *args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ScraperClient.get_json() missing 1 required positional argument: 'url'

INFO     : 2024-01-04 12:06:05,869 : utilities.py:98 : Scrape Finished: https://www.redgifs.com/watch/slategreynavyflyingfish
INFO     : 2024-01-04 12:06:05,869 : utilities.py:98 : Scrape Starting: https://www.redgifs.com/watch/corruptinbornwaterbuck
ERROR    : 2024-01-04 12:06:05,870 : utilities.py:98 : Scrape Failed: https://api.redgifs.com/v2/auth/temporary (ScraperClient.get_json() missing 1 required positional argument: 'url')
ERROR    : 2024-01-04 12:06:05,870 : utilities.py:98 : Traceback (most recent call last):
  File "C:\Python311\Lib\site-packages\cyberdrop_dl\utils\utilities.py", line 62, in wrapper
    return await func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\cyberdrop_dl\scraper\crawlers\redgifs_crawler.py", line 97, in manage_token
    json_obj = await self.client.get_json(self.domain, )
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\cyberdrop_dl\clients\scraper_client.py", line 32, in wrapper
    return await func(self, *args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ScraperClient.get_json() missing 1 required positional argument: 'url'

INFO     : 2024-01-04 12:06:05,872 : utilities.py:98 : Scrape Finished: https://www.redgifs.com/watch/corruptinbornwaterbuck
INFO     : 2024-01-04 12:06:05,872 : utilities.py:98 : Scrape Starting: https://www.redgifs.com/users/mollatare
ERROR    : 2024-01-04 12:06:05,872 : utilities.py:98 : Scrape Failed: https://api.redgifs.com/v2/auth/temporary (ScraperClient.get_json() missing 1 required positional argument: 'url')
ERROR    : 2024-01-04 12:06:05,873 : utilities.py:98 : Traceback (most recent call last):
  File "C:\Python311\Lib\site-packages\cyberdrop_dl\utils\utilities.py", line 62, in wrapper
    return await func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\cyberdrop_dl\scraper\crawlers\redgifs_crawler.py", line 97, in manage_token
    json_obj = await self.client.get_json(self.domain, )
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\cyberdrop_dl\clients\scraper_client.py", line 32, in wrapper
    return await func(self, *args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ScraperClient.get_json() missing 1 required positional argument: 'url'

INFO     : 2024-01-04 12:06:05,874 : utilities.py:98 : Scrape Finished: https://www.redgifs.com/users/mollatare
INFO     : 2024-01-04 12:06:05,875 : utilities.py:98 : Scrape Starting: https://www.redgifs.com/watch/carelessmulticoloredstinkpot
ERROR    : 2024-01-04 12:06:05,875 : utilities.py:98 : Scrape Failed: https://api.redgifs.com/v2/auth/temporary (ScraperClient.get_json() missing 1 required positional argument: 'url')
ERROR    : 2024-01-04 12:06:05,875 : utilities.py:98 : Traceback (most recent call last):
  File "C:\Python311\Lib\site-packages\cyberdrop_dl\utils\utilities.py", line 62, in wrapper
    return await func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\cyberdrop_dl\scraper\crawlers\redgifs_crawler.py", line 97, in manage_token
    json_obj = await self.client.get_json(self.domain, )
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\cyberdrop_dl\clients\scraper_client.py", line 32, in wrapper
    return await func(self, *args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ScraperClient.get_json() missing 1 required positional argument: 'url'

INFO     : 2024-01-04 12:06:05,877 : utilities.py:98 : Scrape Finished: https://www.redgifs.com/watch/carelessmulticoloredstinkpot
INFO     : 2024-01-04 12:06:05,877 : utilities.py:98 : Scrape Starting: https://www.redgifs.com/users/rubyonyx20
ERROR    : 2024-01-04 12:06:05,877 : utilities.py:98 : Scrape Failed: https://api.redgifs.com/v2/auth/temporary (ScraperClient.get_json() missing 1 required positional argument: 'url')
ERROR    : 2024-01-04 12:06:05,878 : utilities.py:98 : Traceback (most recent call last):
  File "C:\Python311\Lib\site-packages\cyberdrop_dl\utils\utilities.py", line 62, in wrapper
    return await func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\cyberdrop_dl\scraper\crawlers\redgifs_crawler.py", line 97, in manage_token
    json_obj = await self.client.get_json(self.domain, )
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\cyberdrop_dl\clients\scraper_client.py", line 32, in wrapper
    return await func(self, *args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ScraperClient.get_json() missing 1 required positional argument: 'url'

INFO     : 2024-01-04 12:06:05,879 : utilities.py:98 : Scrape Finished: https://www.redgifs.com/users/rubyonyx20
INFO     : 2024-01-04 12:06:05,880 : utilities.py:98 : Scrape Starting: https://www.redgifs.com/users/inkyminky
ERROR    : 2024-01-04 12:06:05,880 : utilities.py:98 : Scrape Failed: https://api.redgifs.com/v2/auth/temporary (ScraperClient.get_json() missing 1 required positional argument: 'url')
ERROR    : 2024-01-04 12:06:05,880 : utilities.py:98 : Traceback (most recent call last):
  File "C:\Python311\Lib\site-packages\cyberdrop_dl\utils\utilities.py", line 62, in wrapper
    return await func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\cyberdrop_dl\scraper\crawlers\redgifs_crawler.py", line 97, in manage_token
    json_obj = await self.client.get_json(self.domain, )
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\cyberdrop_dl\clients\scraper_client.py", line 32, in wrapper
    return await func(self, *args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ScraperClient.get_json() missing 1 required positional argument: 'url'

INFO     : 2024-01-04 12:06:05,882 : utilities.py:98 : Scrape Finished: https://www.redgifs.com/users/inkyminky
INFO     : 2024-01-04 12:06:05,882 : utilities.py:98 : Scrape Starting: https://www.redgifs.com/users/that1iggirl
ERROR    : 2024-01-04 12:06:05,882 : utilities.py:98 : Scrape Failed: https://api.redgifs.com/v2/auth/temporary (ScraperClient.get_json() missing 1 required positional argument: 'url')
ERROR    : 2024-01-04 12:06:05,883 : utilities.py:98 : Traceback (most recent call last):
  File "C:\Python311\Lib\site-packages\cyberdrop_dl\utils\utilities.py", line 62, in wrapper
    return await func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\cyberdrop_dl\scraper\crawlers\redgifs_crawler.py", line 97, in manage_token
    json_obj = await self.client.get_json(self.domain, )
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\cyberdrop_dl\clients\scraper_client.py", line 32, in wrapper
    return await func(self, *args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ScraperClient.get_json() missing 1 required positional argument: 'url'

INFO     : 2024-01-04 12:06:05,884 : utilities.py:98 : Scrape Finished: https://www.redgifs.com/users/that1iggirl
INFO     : 2024-01-04 12:06:05,884 : utilities.py:98 : Scrape Starting: https://www.redgifs.com/watch/parallelunfortunatemolly
ERROR    : 2024-01-04 12:06:05,885 : utilities.py:98 : Scrape Failed: https://api.redgifs.com/v2/auth/temporary (ScraperClient.get_json() missing 1 required positional argument: 'url')
ERROR    : 2024-01-04 12:06:05,887 : utilities.py:98 : Traceback (most recent call last):
  File "C:\Python311\Lib\site-packages\cyberdrop_dl\utils\utilities.py", line 62, in wrapper
    return await func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\cyberdrop_dl\scraper\crawlers\redgifs_crawler.py", line 97, in manage_token
    json_obj = await self.client.get_json(self.domain, )
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\cyberdrop_dl\clients\scraper_client.py", line 32, in wrapper
    return await func(self, *args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ScraperClient.get_json() missing 1 required positional argument: 'url'

INFO     : 2024-01-04 12:06:05,888 : utilities.py:98 : Scrape Finished: https://www.redgifs.com/watch/parallelunfortunatemolly
INFO     : 2024-01-04 12:06:05,888 : utilities.py:98 : Scrape Starting: https://www.redgifs.com/users/naomi_soraya
ERROR    : 2024-01-04 12:06:05,889 : utilities.py:98 : Scrape Failed: https://api.redgifs.com/v2/auth/temporary (ScraperClient.get_json() missing 1 required positional argument: 'url')
ERROR    : 2024-01-04 12:06:05,891 : utilities.py:98 : Traceback (most recent call last):
  File "C:\Python311\Lib\site-packages\cyberdrop_dl\utils\utilities.py", line 62, in wrapper
    return await func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\cyberdrop_dl\scraper\crawlers\redgifs_crawler.py", line 97, in manage_token
    json_obj = await self.client.get_json(self.domain, )
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\cyberdrop_dl\clients\scraper_client.py", line 32, in wrapper
    return await func(self, *args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ScraperClient.get_json() missing 1 required positional argument: 'url'

INFO     : 2024-01-04 12:06:05,892 : utilities.py:98 : Scrape Finished: https://www.redgifs.com/users/naomi_soraya
INFO     : 2024-01-04 12:06:05,892 : utilities.py:98 : Scrape Starting: https://www.redgifs.com/watch/lightsalmonanxiousafricanaugurbuzzard#rel=tag:creampie,a;order=trending
ERROR    : 2024-01-04 12:06:05,893 : utilities.py:98 : Scrape Failed: https://api.redgifs.com/v2/auth/temporary (ScraperClient.get_json() missing 1 required positional argument: 'url')
ERROR    : 2024-01-04 12:06:05,894 : utilities.py:98 : Traceback (most recent call last):
  File "C:\Python311\Lib\site-packages\cyberdrop_dl\utils\utilities.py", line 62, in wrapper
    return await func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\cyberdrop_dl\scraper\crawlers\redgifs_crawler.py", line 97, in manage_token
    json_obj = await self.client.get_json(self.domain, )
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\cyberdrop_dl\clients\scraper_client.py", line 32, in wrapper
    return await func(self, *args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ScraperClient.get_json() missing 1 required positional argument: 'url'

INFO     : 2024-01-04 12:06:05,896 : utilities.py:98 : Scrape Finished: https://www.redgifs.com/watch/lightsalmonanxiousafricanaugurbuzzard#rel=tag:creampie,a;order=trending
INFO     : 2024-01-04 12:06:05,896 : utilities.py:98 : Scrape Starting: https://www.redgifs.com/users/floridajuicy
ERROR    : 2024-01-04 12:06:06,010 : utilities.py:98 : Scrape Failed: https://api.redgifs.com/v2/auth/temporary (ScraperClient.get_json() missing 1 required positional argument: 'url')
ERROR    : 2024-01-04 12:06:06,012 : utilities.py:98 : Traceback (most recent call last):
  File "C:\Python311\Lib\site-packages\cyberdrop_dl\utils\utilities.py", line 62, in wrapper
    return await func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\cyberdrop_dl\scraper\crawlers\redgifs_crawler.py", line 97, in manage_token
    json_obj = await self.client.get_json(self.domain, )
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\cyberdrop_dl\clients\scraper_client.py", line 32, in wrapper
    return await func(self, *args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ScraperClient.get_json() missing 1 required positional argument: 'url'

INFO     : 2024-01-04 12:06:06,015 : utilities.py:98 : Scrape Finished: https://www.redgifs.com/users/floridajuicy
INFO     : 2024-01-04 12:06:06,015 : utilities.py:98 : Scrape Starting: https://www.redgifs.com/watch/colossalslatebluejuliabutterfly#rel=tag:creampie,a;order=trending
ERROR    : 2024-01-04 12:06:06,121 : utilities.py:98 : Scrape Failed: https://api.redgifs.com/v2/auth/temporary (ScraperClient.get_json() missing 1 required positional argument: 'url')
ERROR    : 2024-01-04 12:06:06,122 : utilities.py:98 : Traceback (most recent call last):
  File "C:\Python311\Lib\site-packages\cyberdrop_dl\utils\utilities.py", line 62, in wrapper
    return await func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\cyberdrop_dl\scraper\crawlers\redgifs_crawler.py", line 97, in manage_token
    json_obj = await self.client.get_json(self.domain, )
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\cyberdrop_dl\clients\scraper_client.py", line 32, in wrapper
    return await func(self, *args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ScraperClient.get_json() missing 1 required positional argument: 'url'

INFO     : 2024-01-04 12:06:06,124 : utilities.py:98 : Scrape Finished: https://www.redgifs.com/watch/colossalslatebluejuliabutterfly#rel=tag:creampie,a;order=trending
INFO     : 2024-01-04 12:06:06,124 : utilities.py:98 : Scrape Starting: https://www.redgifs.com/users/chbpt69
ERROR    : 2024-01-04 12:06:06,248 : utilities.py:98 : Scrape Failed: https://api.redgifs.com/v2/auth/temporary (ScraperClient.get_json() missing 1 required positional argument: 'url')
ERROR    : 2024-01-04 12:06:06,261 : utilities.py:98 : Traceback (most recent call last):
  File "C:\Python311\Lib\site-packages\cyberdrop_dl\utils\utilities.py", line 62, in wrapper
    return await func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\cyberdrop_dl\scraper\crawlers\redgifs_crawler.py", line 97, in manage_token
    json_obj = await self.client.get_json(self.domain, )
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\cyberdrop_dl\clients\scraper_client.py", line 32, in wrapper
    return await func(self, *args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ScraperClient.get_json() missing 1 required positional argument: 'url'

INFO     : 2024-01-04 12:06:06,264 : utilities.py:98 : Scrape Finished: https://www.redgifs.com/users/chbpt69
INFO     : 2024-01-04 12:06:06,265 : utilities.py:98 : Scrape Starting: https://www.redgifs.com/watch/richstarchywaxwing#rel=tag:creampie,a;order=trending
ERROR    : 2024-01-04 12:06:06,265 : utilities.py:98 : Scrape Failed: https://api.redgifs.com/v2/auth/temporary (ScraperClient.get_json() missing 1 required positional argument: 'url')
ERROR    : 2024-01-04 12:06:06,267 : utilities.py:98 : Traceback (most recent call last):
  File "C:\Python311\Lib\site-packages\cyberdrop_dl\utils\utilities.py", line 62, in wrapper
    return await func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\cyberdrop_dl\scraper\crawlers\redgifs_crawler.py", line 97, in manage_token
    json_obj = await self.client.get_json(self.domain, )
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\cyberdrop_dl\clients\scraper_client.py", line 32, in wrapper
    return await func(self, *args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ScraperClient.get_json() missing 1 required positional argument: 'url'

INFO     : 2024-01-04 12:06:06,271 : utilities.py:98 : Scrape Finished: https://www.redgifs.com/watch/richstarchywaxwing#rel=tag:creampie,a;order=trending
INFO     : 2024-01-04 12:06:06,271 : utilities.py:98 : Scrape Starting: https://www.redgifs.com/users/shygothexhib
ERROR    : 2024-01-04 12:06:06,374 : utilities.py:98 : Scrape Failed: https://api.redgifs.com/v2/auth/temporary (ScraperClient.get_json() missing 1 required positional argument: 'url')
ERROR    : 2024-01-04 12:06:06,376 : utilities.py:98 : Traceback (most recent call last):
  File "C:\Python311\Lib\site-packages\cyberdrop_dl\utils\utilities.py", line 62, in wrapper
    return await func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\cyberdrop_dl\scraper\crawlers\redgifs_crawler.py", line 97, in manage_token
    json_obj = await self.client.get_json(self.domain, )
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\cyberdrop_dl\clients\scraper_client.py", line 32, in wrapper
    return await func(self, *args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ScraperClient.get_json() missing 1 required positional argument: 'url'

INFO     : 2024-01-04 12:06:06,379 : utilities.py:98 : Scrape Finished: https://www.redgifs.com/users/shygothexhib
INFO     : 2024-01-04 12:06:06,379 : utilities.py:98 : Scrape Starting: https://www.redgifs.com/watch/littleoutgoingserpent
ERROR    : 2024-01-04 12:06:06,485 : utilities.py:98 : Scrape Failed: https://api.redgifs.com/v2/auth/temporary (ScraperClient.get_json() missing 1 required positional argument: 'url')
ERROR    : 2024-01-04 12:06:06,486 : utilities.py:98 : Traceback (most recent call last):
  File "C:\Python311\Lib\site-packages\cyberdrop_dl\utils\utilities.py", line 62, in wrapper
    return await func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\cyberdrop_dl\scraper\crawlers\redgifs_crawler.py", line 97, in manage_token
    json_obj = await self.client.get_json(self.domain, )
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\cyberdrop_dl\clients\scraper_client.py", line 32, in wrapper
    return await func(self, *args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ScraperClient.get_json() missing 1 required positional argument: 'url'

INFO     : 2024-01-04 12:06:06,488 : utilities.py:98 : Scrape Finished: https://www.redgifs.com/watch/littleoutgoingserpent
INFO     : 2024-01-04 12:06:06,488 : utilities.py:98 : Scrape Starting: https://www.redgifs.com/watch/bonycluelessmantid
ERROR    : 2024-01-04 12:06:06,595 : utilities.py:98 : Scrape Failed: https://api.redgifs.com/v2/auth/temporary (ScraperClient.get_json() missing 1 required positional argument: 'url')
ERROR    : 2024-01-04 12:06:06,597 : utilities.py:98 : Traceback (most recent call last):
  File "C:\Python311\Lib\site-packages\cyberdrop_dl\utils\utilities.py", line 62, in wrapper
    return await func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\cyberdrop_dl\scraper\crawlers\redgifs_crawler.py", line 97, in manage_token
    json_obj = await self.client.get_json(self.domain, )
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\cyberdrop_dl\clients\scraper_client.py", line 32, in wrapper
    return await func(self, *args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ScraperClient.get_json() missing 1 required positional argument: 'url'

INFO     : 2024-01-04 12:06:06,600 : utilities.py:98 : Scrape Finished: https://www.redgifs.com/watch/bonycluelessmantid
INFO     : 2024-01-04 12:06:06,600 : utilities.py:98 : Scrape Starting: https://www.redgifs.com/users/lamsinka89
ERROR    : 2024-01-04 12:06:06,705 : utilities.py:98 : Scrape Failed: https://api.redgifs.com/v2/auth/temporary (ScraperClient.get_json() missing 1 required positional argument: 'url')
ERROR    : 2024-01-04 12:06:06,706 : utilities.py:98 : Traceback (most recent call last):
  File "C:\Python311\Lib\site-packages\cyberdrop_dl\utils\utilities.py", line 62, in wrapper
    return await func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\cyberdrop_dl\scraper\crawlers\redgifs_crawler.py", line 97, in manage_token
    json_obj = await self.client.get_json(self.domain, )
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\cyberdrop_dl\clients\scraper_client.py", line 32, in wrapper
    return await func(self, *args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ScraperClient.get_json() missing 1 required positional argument: 'url'

INFO     : 2024-01-04 12:06:06,707 : utilities.py:98 : Scrape Finished: https://www.redgifs.com/users/lamsinka89
INFO     : 2024-01-04 12:06:06,812 : utilities.py:98 : Running Post-Download Processes...
INFO     : 2024-01-04 12:06:06,812 : utilities.py:103 : Checking for partial downloads...
INFO     : 2024-01-04 12:06:06,814 : utilities.py:103 : Checking for empty folders...
INFO     : 2024-01-04 12:06:06,817 : utilities.py:98 : Printing Stats...
INFO     : 2024-01-04 12:06:06,817 : utilities.py:103 : 
Download Stats:
INFO     : 2024-01-04 12:06:06,819 : utilities.py:103 : Downloaded 0 files
INFO     : 2024-01-04 12:06:06,821 : utilities.py:103 : Previously Downloaded 0 files
INFO     : 2024-01-04 12:06:06,823 : utilities.py:103 : Skipped By Config 0 files
INFO     : 2024-01-04 12:06:06,825 : utilities.py:103 : Failed 0 files
INFO     : 2024-01-04 12:06:06,827 : utilities.py:103 : 
Scrape Failures:
INFO     : 2024-01-04 12:06:06,828 : utilities.py:103 : Scrape Failures (Unknown): 18
INFO     : 2024-01-04 12:06:06,831 : utilities.py:103 : 
Download Failures:
INFO     : 2024-01-04 12:06:06,834 : utilities.py:98 : Checking for Program End...
INFO     : 2024-01-04 12:06:06,834 : utilities.py:98 : Checking for Updates...
INFO     : 2024-01-04 12:06:07,067 : utilities.py:98 : Closing Program...
INFO     : 2024-01-04 12:06:07,068 : utilities.py:103 : 
Finished downloading. Enjoy :)

**Comment by Jules-WinnfieldX** [comment]
5.1.35 going up now will fix this.

**Comment by MachiavelliSeraphim** [comment]
That was quick.  Thanks.
