### ISSUE TITLE
[BUG] Rule34.xyz Playlist Download HTTP Error

### ISSUE THREAD

**Issue by Quaso00** [Jules-WinnfieldX/CyberDropDownloader#773]
1-)
Hello, I receive a 404 HTTP error for over 90% of the content in the playlist when trying to download from the site, preventing the download process. Additionally, it only downloads the first page and does not download the remaining pages.
2-)
Another issue is that, as far as I understand, to download content from f95.zone and socialmediagirls, we need to enter a username, password, and xf cookie data. However, I don't know what xf cookie is and where to find it. Can you help? (f95zone_xf_user_cookie: '' -- socialmediagirls_xf_user_cookie: '')

**Comment by Jules-WinnfieldX** [comment]
https://jules-winnfieldx.gitbook.io/cyberdrop-dl/reference/supported-websites

Playlists aren't officially supported with that site. 

2. Use the cookie extractor in the ui. (edit configs -> edit auth -> cookies)

**Comment by Quaso00** [comment]
![Ekran görüntüsü 2024-01-06 221349](https://github.com/Jules-WinnfieldX/CyberDropDownloader/assets/51510166/f815ee41-82bf-46df-94e5-20db692c4792)
Isn't this the right place?

**Comment by Jules-WinnfieldX** [comment]
You can try it. But I’m not going to walk anyone through how to do it manually.
