### ISSUE TITLE
[BUG] bunkr DDOS guard has new, additional cookies

### ISSUE THREAD

**Issue by pdobrien** [Jules-WinnfieldX/CyberDropDownloader#774]
**Describe the bug**
bunkr's DDOS guard appears to have a couple new cookies: __ddg5_ and __ddgmark_.  I am constantly triggering DDOS guard even if I put in the correct ddg1, ddg2, and ddgid  cookies

**To Help Reproduce**
Try to download something from bunkr

**Setup Information**
 v 5.0.124 (latest I can get via pip)

**Downloader.log file**
relevant lines:
2023-12-26 01:29:23,209:DEBUG:downloaders:downloaders.py:287:
https://burger.bunkr.ru/xxxx.xxx (DDoS-Guard detected, unable to download)
2023-12-26 01:29:23,209:DEBUG:downloaders:downloaders.py:291:We ran into a 400 level error: CustomHTTPStatus.IM_A_TEAPOT

**Comment by Jules-WinnfieldX** [comment]
Here's the thing. I've done the work to put these additional cookies in. They don't make an ounce of difference, nor do the cookies already there as an option for input. Simply put, that feature doesn't work in preventing ddos-guard. The only thing that can really help, is a vpn, or stopping vpn use, or simply put, just waiting an extended period of time without accessing (> 24 hrs, 48 hrs, etc.)

**Comment by chatoooo** [comment]
My observations are different. It seems that all ddg cookies are enough to access an album. But when you open a file a new DDOS-Guard will appear. It seems that new cookies are not generated the site just wants to verify you again. It seems to be also related to the rate limit. 50 will trigger DDOS-Guard and even block your IP for connection.

**Comment by Jules-WinnfieldX** [comment]
> related to the rate limit. 50 will trigger DDOS-Guard and even block your IP for connection.

The rate limit in the settings is the global rate limit. In reality, Bunkr is a 10. Some go lower (5 for example). Though in reality is probably quite a bit lower with program overhead.

But this is exactly what I was attempting to say, as even with ddg cookies, ddos guard still appears. It doesn't matter.

**Comment by chatoooo** [comment]
When you pass through the DDOS-Guard in your browser, the files are accessible with the already existing cookies. So you just need to open an album (1st DDOS-Guard) and then some file (2nd DDOS-Guard). That should activate file access for the cookies. Yes, it requires some manual steps but still better than nothing.

**Comment by chatoooo** [comment]
I would be interested if this could be handled by opening a headless browser, letting the JS Cookie check do its magic, and then getting the cookies from the browser.

**Comment by Jules-WinnfieldX** [comment]
Selenium, while a great tool, is a absolute nightmare to support, especially on a program of this scale. Long long ago, CDL did have a selenium component, but trying to enforce a browser, and trying to troubleshoot all the various issues that go along with it, made me ditch it and go entirely request based. 

I have no intention of adding anything like that back into any project that's released to the public.

**Comment by chatoooo** [comment]
Well, doing nothing makes bunkr unscrapable by the tool. The DDOS-Guard on files will appear no matter what. I tried a new IP from AWS and I didn't get DDOS-Guard on the album, but there was one on the file. So the support for the new cookies will at least allow scraping with some manual steps.

**Comment by chatoooo** [comment]
I tried to dig deep into your code and cookies might be the source of the issue. Seems like cookies from config are not send (a bit harder to debug with aiohttp) and new ddg cookies start to appear in the CookieJar with expire times.

I created simple test script to test if really the cookies are the issue. (need to fill your values)
```
import urllib3

ALBUM_URL = ""
FILE_URL = ""

cookie = ""

http = urllib3.PoolManager()
r = http.request('GET', ALBUM_URL, headers={"Cookie": cookie})
print (r.status)
r = http.request('GET', FILE_URL, headers={"Cookie": cookie})
print (r.status) 
```

When I run it without cookies I get
```
200
403
```
With cookies
```
200
200
```
So really the cookies are the only thing needed

**Comment by Jules-WinnfieldX** [comment]
Just checked, they are in fact being sent. The issue here likely stems from the download servers using different ddg cookies than the main site does. In fact multiple components of bunkr uses different ddg cookies. *.bunkrr.su is what is being loaded, and that doesn't apply to everything.

**Comment by puc9** [comment]
Leaving this here in case someone has time to experiment:
I think that the cookies are dependent also on the http protocol version used by the browser but I am not 100% sure or it may not apply to all sites. If the browser created the cookies using http3 for example, then whatever will use them will have to use the same http protocol.
There are some Python projects trying to solve this problem: https://github.com/topics/cloudflare?l=python (sort by number of stars).
The ones that looked interesting to me:

- FlareSolverr
- cloudscraper
- cloudflare-scrape
- CloudFlair

but I didn't manage to test any of them.

**Comment by chatoooo** [comment]
@puc9 The HTTP version does not matter in this case. I get all my cookies from the browser, which used HTTP/2, but urllib3 will not use HTTP/2 and it still works. For my IP, download servers work even without any cookies, but they use only ddg1, which is different.

So
1. Loading the album works even without cookies
2. Loading the file page ends up in DDos-Guard - but works when you try it with a simple script and cookies
3. Downloading works even without cookies

**Comment by chatoooo** [comment]
OK, I found the issue. It was a cookie domain 😄 
https://github.com/Jules-WinnfieldX/CyberDropDownloader/blob/73a423ddaca72d453ca90d47eaeb33c507df7d8e/cyberdrop_dl/scraper/crawlers/bunkrr_crawler.py#L24
When you change it to `https://bunkrr.su` it starts working
