### ISSUE TITLE
[FEATURE] Add recu.me

### ISSUE THREAD

**Issue by Gaetann18** [Jules-WinnfieldX/CyberDropDownloader#776]
hello, I would like to ask if you had the possibility of adding the site to the list of compatible sites. I thank you in advance !

Website : https://recu.me/

Thx

**Comment by Kakashi-Hatake-123** [comment]
My 2cents. Even though I would love this to be added. I don't think it's possible due to the content from recu.me is behind a paywall.

**Comment by Jules-WinnfieldX** [comment]
Expanding on the above, doesn't seem like it'd fit with the rest of what is supported currently. Not something I want to offer ongoing support for.
