### ISSUE TITLE
[BUG] Only downloading thumbnails on simpcity.su

### ISSUE THREAD

**Issue by Grimsanta** [Jules-WinnfieldX/CyberDropDownloader#777]
**Describe the bug**
I was noticing that here lately Cyberdrop-DL was only downloading the thumbnails of the images on the forums, [SimpCity](https://simpcity.su/) is the one noticed on may be others. I have only started noticing the past few days and it may have been longer than that.

A good example is this particular post here [SimpCity - Alinity Post 14141](https://simpcity.su/threads/alinity.29/#post-14141) and it is a 150 x 249 res image. The real image that is in that post is a im of 1552 x 2572 . The image with the name 464-021244d45c80e6605b68883e5d02a81b.jpg

I am unsure if it is something on my end as I have changed nothing in setting since it started doing that or something has changed program or site wise.

**To Help Reproduce**
Here is how I have been able to reproduce it.

This is a forum post I first noticed it on after checking all my settings.
[SimpCity - Alinity Post 14141](https://simpcity.su/threads/alinity.29/#post-14141) and the image 464-021244d45c80e6605b68883e5d02a81b.jpg was supposed to be 1552 x 2572 but downloaded as the 150 x 249 res thumbnail. There were others I noticed and can try to figure out all if they are needed. 

**Setup Information**
 - OS: [e.g. Windows 11
 - Cyberdrop Downloader Version v5.1.41
 - 
[downloader - Copy.log](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/13930576/downloader.-.Copy.log)

**Comment by Jules-WinnfieldX** [comment]
Fixed in 5.1.58

**Comment by Grimsanta** [comment]
Ive noticed this happening again. I am on the most current version as of 2/7/2024 and it seems to be on the same loose files as stated above. Noticed it on several forums on SimpCity.

**Comment by Grimsanta** [comment]
![MEBXSJY_t](https://github.com/Jules-WinnfieldX/CyberDropDownloader/assets/81027827/5d4cc433-a751-456a-8794-4b1ac5a601d5)

Here is an example for instance
