### ISSUE TITLE
python 3.11 in ubuntu 22 lts breaks a lot of things

### ISSUE THREAD

**Issue by digby5** [Jules-WinnfieldX/CyberDropDownloader#778]
the requirement of python 3.11 breaks a lot of things in ubuntu 22 arm lts. 3.11 is apparently not backwards compatible with the default 3.10 and many apps require 3.10 to operate properly, including apt, gnome-tweaks, gnome-terminal, etc. i did update-alteernatives to 3.11 and quite a few things broke as result.

**Comment by Jules-WinnfieldX** [comment]
The requirement is a requirement for a reason, it's not possible to run V5 on 3.10. 

You should look into creating a 3.11 virtual environment for CDL, and leaving 3.10 as the main installation if that is the case. But I can't help beyond that. That's up to you to figure out.
