### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by greyhat94** [Jules-WinnfieldX/CyberDropDownloader#780]
**Is your feature request related to a problem? Please describe.**
When I try to download content from the same website a second time, the software no longer downloads the target type of files. I have to clear the cache each time. This happens especially after you have changed the configuration to ignore some files. 

**Describe the solution you'd like**
I'd like a feature that allows me to clear the cache from the command line.. 

**Additional context**
Let's say you edit the configuration to tell the software to ignore image files. You run the program for the first time and retrieve only video files from a URL, excluding the ignored files, i.e. the images. Everything is fine. However, if you delete the downloaded file and run the same process again, the software will skip the ignored files and not download the target files. So far, I've been forced to clear the cache each time to fix this problem. I'd like to know if it's possible to add a feature that allows me to clear the cache from the command line, or if it's possible to solve this problem in some other way.

**Comment by Jules-WinnfieldX** [comment]
That's by design, and you use ignore history in the config to do what you are trying to achieve.

**Comment by greyhat94** [comment]
Thanks for your answer. I don't understand how to do this. Should I perform this operation once the downloaded is ended, or I find this option in configuration settings? I rely on your help and look forward to hearing from you soon.

**Comment by Jules-WinnfieldX** [comment]
Configuration settings

**Comment by Jules-WinnfieldX** [comment]
https://jules-winnfieldx.gitbook.io/cyberdrop-dl/reference/configuration-options/settings#runtime-options

you can from command line

**Comment by greyhat94** [comment]
> https://jules-winnfieldx.gitbook.io/cyberdrop-dl/reference/configuration-options/settings#runtime-options
> 
> you can from command line

Ok. Thank you for your prompt response. As for "Log Level", should I insert "10" as value, or should I press "Enter"?

**Comment by Jules-WinnfieldX** [comment]
You can just press enter and it'll leave it as default.

**Comment by greyhat94** [comment]
Thank you very much for your precious help. I appreciate it.
