### ISSUE TITLE
[BUG] 429 Too Many requests

### ISSUE THREAD

**Issue by Ahmet59692** [Jules-WinnfieldX/CyberDropDownloader#783]
Bunkrr.ru downloads have this 429 too many requests error how can i fix this?

**Comment by Rust1v1** [comment]
I don't want to speak for a maintainer who knows the code better, but this is almost certainly just rate-limiting on Bunkrr's side. I've hit this error a number of times just trying to view my own uploads on there. I just used cyberdrop-dl at version 5.1.42 to download from Bunkrr the same day you posted this. Maybe give it another try now that the files have been able to sit for awhile. Or try some way to change your IP (especially if you're using a free VPN, could be getting too much traffic from the same IP).
