### ISSUE TITLE
[BUG] Failed login, but no log where

### ISSUE THREAD

**Issue by bewbylover** [Jules-WinnfieldX/CyberDropDownloader#784]
**Describe the bug**
I can't see where I am failing to log in.  I checked the logs for failed, or login and there wasn't anything.  Also checked some of the other error logs.   I use the xf_user cookie for nudo, simp, socail, and xbunker (only forums in URL.txt).  I validated the cookie works with a small file with each of the 4 and all loaded.  Included a screenshot, URL.txt, and log.

**To Help Reproduce**
Steps to help reproduce the behavior:
1. Open the app and load my URL list.
2. Wait

**Screenshots**
Just showing the errors.
![Screenshot from 2024-01-17 16-51-40](https://github.com/Jules-WinnfieldX/CyberDropDownloader/assets/152096820/bcc36946-81e0-48eb-8abe-4207570e0e00)

**Setup Information**
 - OS: Ubuntu 20.04.6 LTS
 - python 3.11.6
 - Cyberdrop Downloader V5.1.42

**Downloader.log file**
[URLs.txt](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/13970660/URLs.txt)
[downloader.zip](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/13970662/downloader.zip)

**Additional context**
N/A

**Comment by Jules-WinnfieldX** [comment]
It's Imgur / Reddit

**Comment by bewbylover** [comment]
Thanks.  Do I need to get a log in for those?  What do I need for that another cookie?

**Comment by Jules-WinnfieldX** [comment]
https://jules-winnfieldx.gitbook.io/cyberdrop-dl/reference/configuration-options/authentication

No cookies, you need to register the app on your respective accounts and give values to CDL from the website.

**Comment by bewbylover** [comment]
Thanks!
