### ISSUE TITLE
[BUG] Downloading the bunkrr "Media not available" vid

### ISSUE THREAD

**Issue by bewbylover** [Jules-WinnfieldX/CyberDropDownloader#785]
**Describe the bug**
Downloaded the holder video and likely marked the download as completed.  Stumbled on it as I was checking small video files as it has happened before, but hasn't happened in like a month.  Included what information I could gather.

I believe it should be in https://simpcity.su/threads/tessa-fowler.9928/, this post https://simpcity.su/threads/tessa-fowler.9928/post-10651

Likely this collection link: https://bunkrr.ru/a/IDzodSCD

And this file: https://bunkrr.ru/v/LqjWFRgLLdWdo

Log entries:
INFO     : 2024-01-17 15:26:45,372 : utilities.py:98 : Download Starting: https://milkshake.bunkr.ru/2021-01-15_8_0gmof8n3wi2jdnyyuboaw_source-KBXowipC.mp4?download=true
INFO     : 2024-01-17 15:26:50,327 : utilities.py:98 : Download Finished: https://milkshake.bunkr.ru/2021-01-15_8_0gmof8n3wi2jdnyyuboaw_source-KBXowipC.mp4?download=true

**To Help Reproduce**
Steps to help reproduce the behavior:
1. Just loaded the app and URL.txt like normal.

**Screenshots**
N/A

**Setup Information**
 - OS: Ubuntu 20.04.6 LTS
 - python 3.11.6
 - Cyberdrop Downloader V5.1.42

**Downloader.log file**
[downloader.zip](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/13970716/downloader.zip)

**Additional context**
Failed video.
https://github.com/Jules-WinnfieldX/CyberDropDownloader/assets/152096820/815647e7-b5b8-47fc-921e-d79f635393bd

Is there anyway to edit the database to cause these files to reattempt after a fix is made?

**Comment by Jules-WinnfieldX** [comment]
5.1.43 Going up now to fix it.

**Comment by Jules-WinnfieldX** [comment]
As for your question, You can do it manually with an SQLite viewer, or you can just use ignore history in the config.

**Comment by bewbylover** [comment]
Thanks, I would prefer not to have to re-download everything again.  I'll try a viewer, thanks again.
