### ISSUE TITLE
[FEATURE] detect bunkr "server unavailable" video

### ISSUE THREAD

**Issue by pdobrien** [Jules-WinnfieldX/CyberDropDownloader#787]
**Is your feature request related to a problem? Please describe.**
When a bunker server is offline for maintenance/migration, rather than issue an HTTP error, it serves up a small video file (attached) that explains what is happening.

**Describe the solution you'd like**
cyberdrop-dl should detect this video and rather than download it, fail the download for future retry.

**Additional context**
Here's the video file.

https://github.com/Jules-WinnfieldX/CyberDropDownloader/assets/4895437/3cbbbeca-a182-4fad-bbb6-e9c864f61a9a

**Comment by Jules-WinnfieldX** [comment]
I'd need a link where this is currently happening to deal with it.

**Comment by Jules-WinnfieldX** [comment]
This maintenance video was filtered in 5.1.43, and should no longer be an issue on the current version
