### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by vibhav25** [Jules-WinnfieldX/CyberDropDownloader#789]
**Describe the bug**
Unable to download from Bunkr albums. Getting this DDOS-Guard issue. I'm from India and DDOS Guard is something that appears to be blocked here. However, using a VPN I'm able to bypass this and download individual files. The album downloads were working fine earlier as well.

**Checking for partial downloads...
Checking for empty folders...

Download Stats:
Downloaded 0 files
Previously Downloaded 0 files
Skipped By Config 0 files
Failed 0 files

Scrape Failures:
Scrape Failures (DDOS-Guard): 1

Download Failures:

Finished downloading. Enjoy :)

C:\Users\vibha\Desktop\Cyberdrop_DL.V3>pause
Press any key to continue . . .**

**Setup Information**
 - OS: **Windows 11**
 - Cyberdrop Downloader Version **5.1.44**

**Comment by Jules-WinnfieldX** [comment]
This isn't a bug, or something the program can bypass.

**Comment by vibhav25** [comment]
If the browser is able to download the individual file, how come the program isn't able to download the album when it was able to earlier. Any ideas?

**Comment by Jules-WinnfieldX** [comment]
Because the program doesn't use a browser. It can't pass the ddos-guard check.

**Comment by vibhav25** [comment]
This check was available earlier as well. Looks like Bunkr has added some additional config from its end. That's a bummer.

**Comment by vibhav25** [comment]
An update to this case, in case anyone else was facing this issue. Looks like it is back to working with a VPN now.

**Comment by chatoooo** [comment]
@vibhav25 You can try this workaround https://github.com/Jules-WinnfieldX/CyberDropDownloader/issues/774#issuecomment-1888088393
@Jules-WinnfieldX completely neglects the solution

**Comment by Jules-WinnfieldX** [comment]
https://github.com/Jules-WinnfieldX/CyberDropDownloader/commit/33e7522ca82f6354b861703a8a8c1c004c9dcfa0#

Is that so? @chatoooo

**Comment by chatoooo** [comment]
I apologize, I have had that feeling for the last two weeks. I'm happy that will be fixed. 😄
