### ISSUE TITLE
[BUG] Remove executable bit from downloaded files

### ISSUE THREAD

**Issue by qarkai** [Jules-WinnfieldX/CyberDropDownloader#790]
**Describe the bug**
Downloaded files have executable bit on Linux, more precisely file permissions is `-rwxrwxrwx` or `777` in [numeric notation](https://en.wikipedia.org/wiki/File-system_permissions#Numeric_notation). Regular data files don't need to be executed.
Expected file permissions is at least `-rw-rw-rw-` or `666`. Normally regular files have `-rw-r--r--` or `644` permissions.

**To Help Reproduce**
Steps to help reproduce the behavior:
1. Download any media file on Linux. Probably macOS is affected too.
2. Check file permissions using `ls -l`

**Setup Information**
 - OS: Arch Linux
 - Cyberdrop Downloader Version 5.1.44

**Comment by Jules-WinnfieldX** [comment]
5.1.82 should set to 666
