### ISSUE TITLE
GoFile 401 Unauthorized

### ISSUE THREAD

**Issue by rdsxfn2004** [Jules-WinnfieldX/CyberDropDownloader#792]
**Describe the bug**
GoFile downloads are getting 401 unauthorized errors when the folder is public on the site

**To Help Reproduce**
Attempted different GoFile sites with same result

**Screenshots**

**Setup Information**
 - OS: [e.g. Windows 10, Mac OS X Sierra, etc]
 - Cyberdrop Downloader Version # 5.1.52

**Downloader.log file**
[downloader.log](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/14066579/downloader.log)

**Additional context**

**Comment by Jules-WinnfieldX** [comment]
Should be fixed in 5.1.53
