### ISSUE TITLE
Define Directory Paths in URL.txt file

### ISSUE THREAD

**Issue by BosonHair** [Jules-WinnfieldX/CyberDropDownloader#793]
**Is your feature request related to a problem? Please describe.**
It'd be great to use just one url file with the ability to define download paths versus using multiple configs

**Comment by Jules-WinnfieldX** [comment]
It's easier to enforce structuring with different url files.

This isn't something that is going to happen for ya, sorry

**Comment by BosonHair** [comment]
All good, thanks for your hard work
