### ISSUE TITLE
[FEATURE] Average Download Rate Minimums 

### ISSUE THREAD

**Issue by davelm42** [Jules-WinnfieldX/CyberDropDownloader#796]
Some domains have better download rates than others. Sometimes a specific file will get hung up at a very low download rate. 

There should be a config option (either for all domains or specific domains) where you can specify if the download rate over 1 min (or some other frequency) goes below some average X, then skip that file or that domain. On the next run of the program, the file/partials could be picked up and re-tried.

**Comment by Jules-WinnfieldX** [comment]
This would be quite complex to actually implement, so I'm going to decline this for now.
