### ISSUE TITLE
[BUG] 401 from Gofile

### ISSUE THREAD

**Issue by Aaeeschylus** [Jules-WinnfieldX/CyberDropDownloader#797]
**Describe the bug**
Similarly to #792 (which stated fixed in 5.1.53) GoFile.io downloads are getting 401 unauthorized when scraping

**To Help Reproduce**
Attempt to download from a public GoFile.io folder

**Setup Information**
 - OS: Windows 11
 - Cyberdrop Downloader Version #5.1.57

**Downloader.log file**
[downloader.log](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/14084113/downloader.log)

**Additional context**
Exact same issue as #792. Logs look identical apart from paths.

**Comment by rdsxfn2004** [comment]
I am having the same issues for the following 12 sites.  Below are the sites and my log when attempted to run the downloader.

https://gofile.io/d/zjigob
https://gofile.io/d/I5ttEQ
https://gofile.io/d/mLpIKl
https://gofile.io/d/c5KVVK
https://gofile.io/d/CqaWTa
https://gofile.io/d/TyY66e
https://gofile.io/d/y4bvRW
https://gofile.io/d/vgNuCA
https://gofile.io/d/EgQveW
https://gofile.io/d/42WWNY
https://gofile.io/d/whRmhO
https://gofile.io/d/8i6QRk

[downloader.log](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/14089100/downloader.log)

**Comment by Jules-WinnfieldX** [comment]
This doesn't seem to be an issue with the program. I can't recreate it under any scenario, and others are seemingly seeing 401 status' in the browser from the API endpoint. 

So current ruling is this is a gofile issue.
