### ISSUE TITLE
[BUG]Unknown Scrape Failure

### ISSUE THREAD

**Issue by fzzhd123** [Jules-WinnfieldX/CyberDropDownloader#798]
I am trying to download off of bunkr, and I keep getting failure (unknown)
I am using version 5.1.58

[downloader.log](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/14090925/downloader.log)

**Comment by Jules-WinnfieldX** [comment]
It's an SSL connection issue on your PC. Can't really tell you more than that. Try using a VPN, or a different VPN
