### ISSUE TITLE
[FEATURE] View failed URLs

### ISSUE THREAD

**Issue by SharingSpoon** [Jules-WinnfieldX/CyberDropDownloader#801]
I'd like to be able to see the failed URLs so that I can manually check them to see if it's a temporary access issue or the file is no longer there at all.

**Comment by Jules-WinnfieldX** [comment]
You can do this already using the failed files lists in the Logs folder.

**Comment by SharingSpoon** [comment]
i had a look for any logs and couldn't see them. Where is the default location for logs folder? I can't see it in the install location

**Comment by Jules-WinnfieldX** [comment]
From wherever you are running CDL > ./appdata/configs/<config>/logs

**Comment by SharingSpoon** [comment]
ah perfect thank you. I didn't look deep enough
