### ISSUE TITLE
[BUG] Simpcity now has DDOSguard

### ISSUE THREAD

**Issue by minicoz** [Jules-WinnfieldX/CyberDropDownloader#804]
**Describe the bug**
Seems like simpcity has enabled DDOSguard for their site.
I have extracted the user cookie and tried using it but I still run into the DDOS guard error.

**To Help Reproduce**
Steps to help reproduce the behavior:
Try any site for simpcity.

**Screenshots**

**Setup Information**
Windows

**Downloader.log file**
You need to include the downloader.log file after the issue occurs. Majority of the time it's the only way to diagnose issues. 
[downloader.log](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/14130555/downloader.log)

**Comment by Jules-WinnfieldX** [comment]
Nothing to do about it. Just wait a few days and try again.

**Comment by github-userx** [comment]
> Nothing to do about it. Just wait a few days and try again.

I guess they hate scraping now.

**Comment by Jules-WinnfieldX** [comment]
@github-userx Most of these sites have had DDOS-Guard for years. Bunkr & SC especially. It really only becomes a problem when they are having a problem dealing with unprecedented traffic and DDOS attacks.
