### ISSUE TITLE
[BUG] Problems Updating from v4 to v5

### ISSUE THREAD

**Issue by RazeBerry** [Jules-WinnfieldX/CyberDropDownloader#806]
**Describe the bug**
I have ran the command per wiki: "pip install cyberdrop-dl --upgrade" 

However it reads: 

"user@Sihaos-MacBook-Pro-2 documents % pip install cyberdrop-dl --upgrade
Requirement already satisfied: cyberdrop-dl in /Users/sihao/.pyenv/versions/3.9.10/lib/python3.9/site-packages (4.2.231)"

So it seems like that pypi isnt distrbuting the 5.1 something package correctly.

<img width="565" alt="Screenshot 2024-02-01 at 22 49 54" src="https://github.com/Jules-WinnfieldX/CyberDropDownloader/assets/28079152/82925ae7-4bc4-465e-a199-fe26edd8dcbf">

Furthermore, I have tried to install it locally, but it seems like the local installer .command file cannot mysteriously overwrite existing v4 installation. Any help would be appreciated. 

<img width="568" alt="Screenshot 2024-02-01 at 22 51 08" src="https://github.com/Jules-WinnfieldX/CyberDropDownloader/assets/28079152/46d9fff1-eb6d-4e32-932c-69526791bf15">

After running the .command file, the version is still stuck at purging empty directors command.

**Setup Information**
 - OS: MacOs
 - Cyberdrop Downloader Version # 4.2.231

I have not provided a downloader.log file due to the nature of the issue.

**Comment by Jules-WinnfieldX** [comment]
https://jules-winnfieldx.gitbook.io/cyberdrop-dl/

you need python 3.11
