### ISSUE TITLE
[FEATURE] Use linter

### ISSUE THREAD

**Issue by qarkai** [Jules-WinnfieldX/CyberDropDownloader#807]
**Is your feature request related to a problem? Please describe.**
Linters help fixing common issues, make code more "pythonic", simple and cleaner, etc, etc.

**Describe the solution you'd like**
1. Select linter: flake8, pylint, ruff (recommended, it's fast and tries to combine rules from other known tools), etc.
2. Start with few rules.
3. Fix warnings.
4. Add pre-commit hook and/or GitHub Action to avoid them in new code.
5. Expand rules set.
6. Go to 3.

**Comment by Jules-WinnfieldX** [comment]
Silly me. I've had ruff installed but never gave it a executable to run with. Fixed going forward
