### ISSUE TITLE
[BUG] Unknown scrape failure. Missing extension in log

### ISSUE THREAD

**Issue by dino1123123** [Jules-WinnfieldX/CyberDropDownloader#810]
I'm trying to download an album from bunkr but I keep getting unknown scrape failures.

Checking the log, it reports that the extension is missing for the file. Not quite sure what that means or how to go about fixing it.

Thanks!

[downloader.log](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/14217075/downloader.log)

**Comment by Jules-WinnfieldX** [comment]
Not a bug, you aren't up to date. You need to use python 3.11

**Comment by dino1123123** [comment]
Thanks! I realized that I didn't update the python path to use the newer version even though I had it installed. My bad.
