### ISSUE TITLE
[FEATURE] Support for imglike.com

### ISSUE THREAD

**Issue by Barbarella6666666** [Jules-WinnfieldX/CyberDropDownloader#812]
I would like to ask support for imglike.com, if possible.
My best regards

Single picture
https://imglike.com/image/denise-milany-busty-cop-%281%29.Jw3yk

Gallery
https://imglike.com/category/Bursting-boobs

**Comment by Jules-WinnfieldX** [comment]
The site is doing really fishy things with redirects for me. So I'm gonna go with a no go.
