### ISSUE TITLE
[FEATURE] Improvement on the "UI" download progress

### ISSUE THREAD

**Issue by eskaviam** [Jules-WinnfieldX/CyberDropDownloader#813]
**Describe the solution you'd like**
Introduce a '--no-ui' mode with periodic download progress updates instead of none at all. The current progress display consumes too much CPU, particularly for cloud service users. Alternatively, provide a refresh rate option for the existing download progress feature.

**Comment by Jules-WinnfieldX** [comment]
I have no interest in maintaining two different download progress styles anymore. I've done it once, never again. 

That being said, I'll add a refresh rate option, it'll be in the next update.
