### ISSUE TITLE
[BUG] Failed Login to simpcity.su

### ISSUE THREAD

**Issue by pcarrero** [Jules-WinnfieldX/CyberDropDownloader#817]
downloader no longer successfully logging in to simpcity.su. I see the issue with both 1) providing username and password or 2) providing a cookie after logging in via browser

**Comment by Jules-WinnfieldX** [comment]
I'd need to see the downloader.log

**Comment by pcarrero** [comment]
"Forums Credentials": {
        "celebforum Credentials Provided": true,
        "f95zone Credentials Provided": true,
        "leakedmodels Credentials Provided": true,
        "nudostar Credentials Provided": true,
        "simpcity Credentials Provided": true,
        "socialmediagirls Credentials Provided": false,
        "xbunker Credentials Provided": true
    },
    "Forums XF Cookies": {
        "celebforum XF Cookie Provided": false,
        "f95zone XF Cookie Provided": false,
        "leakedmodels XF Cookie Provided": false,
        "nudostar XF Cookie Provided": false,
        "simpcity XF Cookie Provided": false,
        "socialmediagirls XF Cookie Provided": false,
        "xbunker XF Cookie Provided": false
    },


DEBUG    : 2024-02-15 13:06:42,928 : utilities.py:95 : Using Global Settings: 
{
    "General": {
        "allow_insecure_connections": true,
        "max_file_name_length": 95,
        "max_folder_name_length": 60,
        "proxy": "",
        "required_free_space": 5,
        "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/112.0"
    },
    "Rate_Limiting_Options": {
        "connection_timeout": 15,
        "download_attempts": 10,
        "download_delay": 0,
        "max_simultaneous_downloads": 15,
        "max_simultaneous_downloads_per_domain": 4,
        "rate_limit": 50,
        "read_timeout": 300
    }
}
INFO     : 2024-02-15 13:06:42,933 : utilities.py:95 : Starting UI...
INFO     : 2024-02-15 13:06:43,045 : utilities.py:95 : Scrape Starting: https://simpcity.su/threads/marina-mui-marinamuimui.10385
ERROR    : 2024-02-15 13:07:29,127 : utilities.py:95 : Scrape Failed: https://simpcity.su/login (Failed Login)
ERROR    : 2024-02-15 13:07:29,129 : utilities.py:95 : SimpCity login failed. Skipping.
INFO     : 2024-02-15 13:07:29,129 : utilities.py:95 : Scrape Finished: https://simpcity.su/threads/marina-mui-marinamuimui.10385
INFO     : 2024-02-15 13:07:29,154 : utilities.py:95 : Running Post-Download Processes...
INFO     : 2024-02-15 13:07:29,154 : utilities.py:100 : Checking for partial downloads...
INFO     : 2024-02-15 13:07:56,600 : utilities.py:100 : Checking for empty folders...
INFO     : 2024-02-15 13:07:56,856 : utilities.py:95 : Printing Stats...
INFO     : 2024-02-15 13:07:56,856 : utilities.py:100 : 
Download Stats:
INFO     : 2024-02-15 13:07:56,857 : utilities.py:100 : Downloaded 0 files
INFO     : 2024-02-15 13:07:56,857 : utilities.py:100 : Previously Downloaded 0 files
INFO     : 2024-02-15 13:07:56,857 : utilities.py:100 : Skipped By Config 0 files
INFO     : 2024-02-15 13:07:56,858 : utilities.py:100 : Failed 0 files
INFO     : 2024-02-15 13:07:56,858 : utilities.py:100 : 
Scrape Failures:
INFO     : 2024-02-15 13:07:56,858 : utilities.py:100 : Scrape Failures (Failed Login): 1
INFO     : 2024-02-15 13:07:56,859 : utilities.py:100 : 
Download Failures:
INFO     : 2024-02-15 13:07:56,859 : utilities.py:95 : Checking for Program End...
INFO     : 2024-02-15 13:07:56,859 : utilities.py:95 : Checking for Updates...
INFO     : 2024-02-15 13:07:56,902 : utilities.py:95 : Closing Program...
INFO     : 2024-02-15 13:07:56,902 : utilities.py:100 : 
Finished downloading. Enjoy :)

**Comment by Jules-WinnfieldX** [comment]
you don't have any cookies provided. But if you are putting the credentials in the auth config yourself, make sure they aren't backwards.

**Comment by pcarrero** [comment]
Strange. it was backwards. but this was working previously and i had not changed the creds. Apologies i submitted a bug report for something so simple.

**Comment by pcarrero** [comment]
Thank you
