### ISSUE TITLE
[BUG] unhandled errors in a TaskGroup (1 sub-exception)

### ISSUE THREAD

**Issue by vajdao** [Jules-WinnfieldX/CyberDropDownloader#819]
**Describe the bug**
Traceback error within the bunkrr crawler(? I guess) (note that this bug happened before the today's 5.1.69 update also)

**To Help Reproduce**
Steps to help reproduce the behavior:
1. Describe the bug accurately: 
Try to download anything from bunkrr

2. Provide an example album that showcases it (if applicable)
There's just too many (Ooopsie.. :'D ), please see the log file

3. Make sure you are updated to the latest version to see if it's already fixed.
Yes it is up to date.

**Screenshots**
![image](https://github.com/Jules-WinnfieldX/CyberDropDownloader/assets/123484746/81a625ae-1164-4688-a079-b8de318427fa)

**Setup Information**
 - OS: Linux Mint 21.3 (Virginia)
 - Cyberdrop Downloader Version # 5.1.69

**Downloader.log file**
[downloader.log](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/14313589/downloader.log)

**Additional context**
[traceback.log](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/14313592/traceback.log)

**Comment by Jules-WinnfieldX** [comment]
5.1.71 should probably fix it.

**Comment by vajdao** [comment]
That was quick :) Thanks @Jules-WinnfieldX 
Something definitely changed, because it no longer throws back an exception-traceback error, but it still throws back some error:

```

An error occurred, please report this to the developer
unhandled errors in a TaskGroup (1 sub-exception)
  + Exception Group Traceback (most recent call last):
  |   File "/home/vajdao/venv311/lib/python3.11/site-packages/cyberdrop_dl/main.py", line 85, in director
  |     await runtime(manager)
  |   File "/home/vajdao/venv311/lib/python3.11/site-packages/cyberdrop_dl/main.py", line 43, in runtime
  |     async with asyncio.TaskGroup() as task_group:
  |   File "/usr/lib/python3.11/asyncio/taskgroups.py", line 135, in __aexit__
  |     raise me from None
  | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "/home/vajdao/venv311/lib/python3.11/site-packages/cyberdrop_dl/scraper/crawler.py", line 55, in run
    |     await self.fetch(item)
    |   File "/home/vajdao/venv311/lib/python3.11/site-packages/cyberdrop_dl/scraper/crawlers/bunkrr_crawler.py", line 40, in fetch
    |     scrape_item.url = await self.get_stream_link(scrape_item.url)
    |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/vajdao/venv311/lib/python3.11/site-packages/cyberdrop_dl/scraper/crawlers/bunkrr_crawler.py", line 172, in get_stream_link
    |     if not re.match(cdn_possibilities, url.host):
    |                                        ^^^^^^^^
    | AttributeError: 'NoneType' object has no attribute 'host'
    +------------------------------------
```

**Comment by Jules-WinnfieldX** [comment]
If you could narrow down to the album (probably) it's coming from, that'd help a lot

**Comment by Jules-WinnfieldX** [comment]
5.1.72

Got it. But I'll do you one better, it'll actually download the file.

**Comment by vajdao** [comment]
Man you rock! :D Thank you, it works like a dream!! <3 My greatest respect to you
