### ISSUE TITLE
[FEATURE] please update simpcity

### ISSUE THREAD

**Issue by BigManTT** [Jules-WinnfieldX/CyberDropDownloader#821]
hello theres fix update for simpcity ?

**Comment by Jules-WinnfieldX** [comment]
SC is working fine

**Comment by BigManTT** [comment]
still get error message 
Scrape Failed: https://simpcity.su/login (Cannot connect to host simpcity.su:443 ssl:True [SSLCertVerificationError: (1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'simpcity.su'. (_ssl.c:992)")])

**Comment by Jules-WinnfieldX** [comment]
That would indicate an issue with SC. Though I'd recommend you try a VPN and turn off any antivirus you have.
