### ISSUE TITLE
Question: Is it possible to have sort files into separate creator subfolders?

### ISSUE THREAD

**Issue by stateofdenialist** [Jules-WinnfieldX/CyberDropDownloader#825]
Basically the title: Is it possible to have sort separate files into creator subfolders, rather than just into three big audio/images/videos directories?

Right now it's sorting everything into /sorted/images and /sorted/video, for example... would like it to sort into /sorted/creator_username/images and /sorted/creator_username/video

**Comment by Jules-WinnfieldX** [comment]
The default settings are as you describe.
