### ISSUE TITLE
[BUG] Simpcity DDOS-Guard. Please Fast. Error isn't significant!

### ISSUE THREAD

**Issue by kaynshae** [Jules-WinnfieldX/CyberDropDownloader#827]
When requesting to https://simpcity.su/login Throws out a DDOS Guard. Despite the fact that it just loads. Wait 5-10 seconds and the site opens. Fix this point.

connection_timeout - does not help
as well as increasing the wait_time before calling forum_login() in simpcity_crawler.py

**Comment by ductai199x** [comment]
@kaynshae You may need to go to the source code of simpcity crawler: <root dir of cyberdrop_dl>/scraper/crawlers/simpcity_crawler.py. Since the SimpCityCrawler class is inheriting the base Crawler class, you will need to override the "forum_login" method, basically copy the exact method in the base class over and change the line where it says `self.client.client_manager.cookies.update_cookies( <cookie>, ...`. You need to update cookie such that it takes your cookie when you login to simpcity like this (I have used black formatting to make code nicer to read):
![Screenshot 2024-02-22 060902](https://github.com/Jules-WinnfieldX/CyberDropDownloader/assets/29772899/dd8fa61b-d7bc-4455-87d7-7ae59329a577)

@Jules-WinnfieldX Could we add these field to simpcity login to resolve the DDoS issue? Thanks and I appreciate your work!

**Comment by kaynshae** [comment]
> @kaynshae You may need to go to the source code of simpcity crawler: /scraper/crawlers/simpcity_crawler.py. Since the SimpCityCrawler class is inheriting the base Crawler class, you will need to override the "forum_login" method, basically copy the exact method in the base class over and change the line where it says `self.client.client_manager.cookies.update_cookies( <cookie>, ...`. You need to update cookie such that it takes your cookie when you login to simpcity like this (I have used black formatting to make code nicer to read): ![Screenshot 2024-02-22 060902](https://private-user-images.githubusercontent.com/29772899/306973795-dd8fa61b-d7bc-4455-87d7-7ae59329a577.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2MDY0MDUsIm5iZiI6MTcwODYwNjEwNSwicGF0aCI6Ii8yOTc3Mjg5OS8zMDY5NzM3OTUtZGQ4ZmE2MWItZDdiYy00NDU1LTg3ZDctN2FlNTkzMjlhNTc3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIyVDEyNDgyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBmYjVkNzQ5MzJjMDdhNmI4YzQwNzc4OGY2NTA0MjZmMWQ2YjFkZjU4NmVhMDc0NWMxYTE5ODljZGIyZDZhYzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aV8zLk00Yr9PBlke_PZCu141k1wwD_V1WfTEzkQw8Ok)
> 
> @Jules-WinnfieldX Could we add these field to simpcity login's authentication yaml to resolve the DDoS issue? Thanks and I appreciate your work!

 "Add these field to simpcity login's authentication yaml to resolve the DDoS issue" is a good idea, I would like it to be implemented. 
 
 But before that, can you explain or give links where to find information, how and where to get these cookies? I don't understand what to write here: "DDOS-Guard: bunker_ddg1: " bunker_dg2: '' bunker_lodger: ''cooper_dg1: '' kemono_ddg1: " " The address to the cookie file or what? You have also sent a solution to the problem now, but I do not understand where to get the data from: ""xf_user": "xf_session": "xf_csrf": ＿ddg1_" ＿ddg2_": ＿ddg5_" ＿ddgid_":＿ddgmark_"" I exported cookies from DolphinAnty, I didn't find them in .txt of the necessary data, I try using cyberdrop-dl, select the Chrome browser, nothing is exported. Help me, how do I fill in cookies and where do I get them from?

**Comment by Kozi801** [comment]
I have the same issue as OP when I attempt to download I get a failed scraped : ddos guard : 1.
I will look at the current fix proposed

**Comment by kaynshae** [comment]
> @kaynshae You may need to go to the source code of simpcity crawler: /scraper/crawlers/simpcity_crawler.py. Since the SimpCityCrawler class is inheriting the base Crawler class, you will need to override the "forum_login" method, basically copy the exact method in the base class over and change the line where it says `self.client.client_manager.cookies.update_cookies( <cookie>, ...`. You need to update cookie such that it takes your cookie when you login to simpcity like this (I have used black formatting to make code nicer to read): ![Screenshot 2024-02-22 060902](https://private-user-images.githubusercontent.com/29772899/306973795-dd8fa61b-d7bc-4455-87d7-7ae59329a577.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2MTczNjQsIm5iZiI6MTcwODYxNzA2NCwicGF0aCI6Ii8yOTc3Mjg5OS8zMDY5NzM3OTUtZGQ4ZmE2MWItZDdiYy00NDU1LTg3ZDctN2FlNTkzMjlhNTc3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIyVDE1NTEwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJhYWQxMTI3ZmVlZGZmMDVlMzUyMzdiZWYwODQ2MDNhZTI4MGI0MDQ2ZTM3NDY2ODcxNTE5Yzc5MGYzNjBkY2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eblktKXucX5V8fX7-6zdXAMdkeMJt8yJ5APzWJgdyxA)
> 
> @Jules-WinnfieldX Could we add these field to simpcity login's authentication yaml to resolve the DDoS issue? Thanks and I appreciate your work!

I managed to find the cookie, but the method you suggested didn't work. Even just refreshing the page in the browser, first there is a DDOS check. That is, it's not about cookies, but we need to wait for the end of the DDOS check

**Comment by Jules-WinnfieldX** [comment]
and as @kaynshae discovered, cookies are a bandaid on a gaping sore. They may work *periodically* for some, or won't at all for others. That is exactly why I haven't bothered expanding on the DDOS-Guard cookies inside of CDL. 

DDOS-Guard will calm down in likely a few days. Until then, you can attempt the patch fix above, or wait it out. I'm going to leave this thread open, but lock it so I hopefully don't get a barrage of repeat issue requests.
