### ISSUE TITLE
[FEATURE] Ignore known useless files by default

### ISSUE THREAD

**Issue by baccccccc** [Jules-WinnfieldX/CyberDropDownloader#829]
Note: this of course has lower priority than everything else going on right now.

Even if you start downloading a new thread that you never downloaded before, you'll have this in the output: `Previously Downloaded 1 files`. This happens even if the thread has no visible links whatsoever and nothing should be downloaded.

The reason is probably this:
```
DEBUG    : 2024-02-24 10:54:53,293 : utilities.py:95 : Skipping https://simp4.host.church/2024/0fya082315al84db03fa9bf467e3.png as it has already been downloaded
```

I'm not sure how exactly the forum injects this link, but I can understand *why* they're doing this. However, it's useless, especially when this file does *not* get into download folder.

So, maybe it should be excluded by default? Otherwise, the results are slightly confusing.

**Comment by Jules-WinnfieldX** [comment]
I have a system setup to ignore other similar files. It'll throw a 404 in the next update.

**Comment by baccccccc** [comment]
why 404? This is perhaps where a 418 would be applicable.

**Comment by Jules-WinnfieldX** [comment]
Arguably true. I reserve that though for the specific instances it's already in use for in CDL. 

It's also a file that just doesn't matter, so 404 seems fine.
