### ISSUE TITLE
[FEATURE] Add support for shorts.sex.com

### ISSUE THREAD

**Issue by errx404** [Jules-WinnfieldX/CyberDropDownloader#831]
Hi, I'll start by saying that I really appreciate you and your work, keep it up :D.
Wanted to ask if it would be possible to add support for shorts.sex.com profiles ? 

https://shorts.sex.com/api/feed/listUserItems?pageNumber=1&pageSize=300&sortBy=position&username={username}&mediaType=video&visibility=public&visibility=subscribers

This is the api call made for each profile but i've changed the pageSize from 12 to 300 as it's the maximum allowed. You only need the to change the username in this request and increase pageNumber until the count given from a request is 0.

To parse the response into a list of downloadable links you can use something like this :

for item in data['page']['items']:
path = item['media']['sources'][0]['fullPath']
if(not path.endswith("__blurred.mp4")):
path should be put in the download list

Thank you in advance. :D

**Comment by Jules-WinnfieldX** [comment]
As I can't seem to find links to just straight up profiles on that site for shorts creators, I'm gonna have to say no.
