### ISSUE TITLE
bunkr DDoS-guard strikes back

### ISSUE THREAD

**Issue by baccccccc** [Jules-WinnfieldX/CyberDropDownloader#832]
there's been numerous topics on this issue in the past months, but I just feel like it's become worse again the last week or so.

maybe it has something to do with domains used in cookies. Most of the links found at forums still use `bunkrr.su` and this is the URL you typically get recorded in `Scrape_Error_URLs.csv`. However, after looking through some script source files, it looks like they've been updated to use `bunkr.sk`. I'm certainly not an expert here, and my understanding of Python is very limited. But maybe the increased cases of DDoS-guard have something to do with this mismatch. (I.e., script only expects to handle DDoS-guard at `.sk` URLs while we're still hitting them at `.su` domains.)

happy to be corrected, it's very much possible that the issue is something completely irrelevant. Just wanted to bring it up again.

**Comment by Jules-WinnfieldX** [comment]
You raise actually a good point, I'm only changing the base domain for albums, not other links. I'll look into this likely tomorrow.

**Comment by Jules-WinnfieldX** [comment]
Next version will point all at .sk.
