### ISSUE TITLE
[FEATURE] Integratee ability with FlareSolverr

### ISSUE THREAD

**Issue by minicoz** [Jules-WinnfieldX/CyberDropDownloader#837]
**Is your feature request related to a problem? Please describe.**
DDosGuard blocks some Bunkerr sites.
[FlareSolverr](https://github.com/FlareSolverr/FlareSolverr) can be used to solve some of the cloudflare captchaes and bypass these blocks.

**Describe the solution you'd like**
Maybe an integration somehow whenever a challenge appears. Have flaresolverr running in a docker container and then forward the challenge to the service. 

**Additional context**
It works for prowlarr.

Edit:
I just found that you have previously addressed integrations FlareSolverr

**Comment by Jules-WinnfieldX** [comment]
I wasn't aware FlareSolverr worked for DDoS-Guard. I'll add integration.

**Comment by Jules-WinnfieldX** [comment]
So. I've attempted to add integration in 5.1.86. 

However, I have no idea if it works. I don't have a link that I can test for ddos-guard with.

**Comment by Jules-WinnfieldX** [comment]
Oh. 5.1.86 won't work. 1 sec

**Comment by Jules-WinnfieldX** [comment]
5.1.87 has the proper flaresolverr address. Try it, let me know if it works.

**Comment by Jules-WinnfieldX** [comment]
make sure you are on .91... is all I'll say.

**Comment by Jules-WinnfieldX** [comment]
Scratch. .92 should actually communicate with flaresolverr properly.
