### ISSUE TITLE
[BUG] sanitize-filename

### ISSUE THREAD

**Issue by spiritkingdom** [Jules-WinnfieldX/CyberDropDownloader#84]
not work to me , every time i try it show this message

error: could not find a version that satisfies the requirement sanitize-filename ~=1.2.0 (from versions: none) error: no matching distribution found for sanitize-filename~=1.2.0

**Comment by Jules-WinnfieldX** [comment]
Which version of python are you running?

**Comment by spiritkingdom** [comment]
that right i use version 3.6 
i remove it and install version 3.8

still not work it show like this

![screen](https://user-images.githubusercontent.com/102337940/160050827-f4aab1b5-d75b-455f-8e9e-bd494c61a971.jpg)

**Comment by Jules-WinnfieldX** [comment]
Open a command prompt window and run this command `py -m ensurepip --upgrade`

**Comment by spiritkingdom** [comment]
i try it , it look like pip problem and not upgrade well


C:\Users\spirit\AppData\Local\Programs\Python\Python38\Scripts>py -m ensurepip -
-upgrade
WARNING: Ignoring invalid distribution -ip (c:\users\spirit\appdata\local\progra
ms\python\python38\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\users\spirit\appdata\local\programs
\python\python38\lib\site-packages)
WARNING: Ignoring invalid distribution -ip (c:\users\spirit\appdata\local\progra
ms\python\python38\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\users\spirit\appdata\local\programs
\python\python38\lib\site-packages)
Looking in links: c:\Users\spirit\AppData\Local\Temp\tmpym6bga7l
Requirement already satisfied: setuptools in c:\users\spirit\appdata\local\progr
ams\python\python38\lib\site-packages (56.0.0)
Processing c:\users\spirit\appdata\local\temp\tmpym6bga7l\pip-21.1.1-py3-none-an
y.whl
WARNING: Ignoring invalid distribution -ip (c:\users\spirit\appdata\local\progra
ms\python\python38\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\users\spirit\appdata\local\programs
\python\python38\lib\site-packages)
Installing collected packages: pip
  WARNING: The scripts pip3.8.exe and pip3.exe are installed in 'C:\Users\spirit
\AppData\Local\Programs\Python\Python38\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warn
ing, use --no-warn-script-location.
WARNING: Ignoring invalid distribution -ip (c:\users\spirit\appdata\local\progra
ms\python\python38\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\users\spirit\appdata\local\programs
\python\python38\lib\site-packages)
Successfully installed pip-21.1.1

C:\Users\spirit\AppData\Local\Programs\Python\Python38\Scripts>pip install --upg
rade pip
WARNING: Ignoring invalid distribution -ip (c:\users\spirit\appdata\local\progra
ms\python\python38\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\users\spirit\appdata\local\programs
\python\python38\lib\site-packages)
WARNING: Ignoring invalid distribution -ip (c:\users\spirit\appdata\local\progra
ms\python\python38\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\users\spirit\appdata\local\programs
\python\python38\lib\site-packages)
Requirement already satisfied: pip in c:\users\spirit\appdata\local\programs\pyt
hon\python38\lib\site-packages (21.1.1)
Collecting pip
  Using cached pip-22.0.4-py3-none-any.whl (2.1 MB)
WARNING: Ignoring invalid distribution -ip (c:\users\spirit\appdata\local\progra
ms\python\python38\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\users\spirit\appdata\local\programs
\python\python38\lib\site-packages)
Installing collected packages: pip
  Attempting uninstall: pip
    WARNING: Ignoring invalid distribution -ip (c:\users\spirit\appdata\local\pr
ograms\python\python38\lib\site-packages)
    WARNING: Ignoring invalid distribution - (c:\users\spirit\appdata\local\prog
rams\python\python38\lib\site-packages)
    Found existing installation: pip 21.1.1
    Uninstalling pip-21.1.1:
ERROR: Could not install packages due to an OSError: [WinError 5] Access is deni
ed: 'c:\\users\\spirit\\appdata\\local\\programs\\python\\python38\\scripts\\pip
.exe'
Consider using the `--user` option or check the permissions.

WARNING: Ignoring invalid distribution -ip (c:\users\spirit\appdata\local\progra
ms\python\python38\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\users\spirit\appdata\local\programs
\python\python38\lib\site-packages)
WARNING: Ignoring invalid distribution -ip (c:\users\spirit\appdata\local\progra
ms\python\python38\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\users\spirit\appdata\local\programs
\python\python38\lib\site-packages)

C:\Users\spirit\AppData\Local\Programs\Python\Python38\Scripts>

**Comment by Jules-WinnfieldX** [comment]
Run the start.bat now.

**Comment by spiritkingdom** [comment]
C:\CyberDropDownloader-2.6.1>py -m pip install -r requirements.txt  --user
WARNING: Ignoring invalid distribution -p (c:\users\spirit\appdata\local\program
s\python\python38\lib\site-packages)
WARNING: Ignoring invalid distribution -ip (c:\users\spirit\appdata\local\progra
ms\python\python38\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\users\spirit\appdata\local\programs
\python\python38\lib\site-packages)
WARNING: Ignoring invalid distribution -p (c:\users\spirit\appdata\local\program
s\python\python38\lib\site-packages)
WARNING: Ignoring invalid distribution -ip (c:\users\spirit\appdata\local\progra
ms\python\python38\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\users\spirit\appdata\local\programs
\python\python38\lib\site-packages)
Requirement already satisfied: aiofiles~=0.8.0 in c:\users\spirit\appdata\roamin
g\python\python38\site-packages (from -r requirements.txt (line 1)) (0.8.0)
Requirement already satisfied: aiohttp~=3.8.1 in c:\users\spirit\appdata\roaming
\python\python38\site-packages (from -r requirements.txt (line 2)) (3.8.1)
Requirement already satisfied: certifi~=2021.10.8 in c:\users\spirit\appdata\roa
ming\python\python38\site-packages (from -r requirements.txt (line 3)) (2021.10.
8)
Requirement already satisfied: colorama~=0.4.4 in c:\users\spirit\appdata\roamin
g\python\python38\site-packages (from -r requirements.txt (line 4)) (0.4.4)
Requirement already satisfied: gofile-client~=1.0.0 in c:\users\spirit\appdata\r
oaming\python\python38\site-packages (from -r requirements.txt (line 5)) (1.0.0)

Requirement already satisfied: nest-asyncio~=1.5.4 in c:\users\spirit\appdata\ro
aming\python\python38\site-packages (from -r requirements.txt (line 6)) (1.5.4)
Requirement already satisfied: readchar~=3.0.4 in c:\users\spirit\appdata\roamin
g\python\python38\site-packages (from -r requirements.txt (line 7)) (3.0.5)
Requirement already satisfied: requests==2.27.1 in c:\users\spirit\appdata\roami
ng\python\python38\site-packages (from -r requirements.txt (line 8)) (2.27.1)
Requirement already satisfied: sanitize-filename~=1.2.0 in c:\users\spirit\appda
ta\roaming\python\python38\site-packages (from -r requirements.txt (line 9)) (1.
2.0)
Requirement already satisfied: Scrapy~=2.6.0 in c:\users\spirit\appdata\roaming\
python\python38\site-packages (from -r requirements.txt (line 10)) (2.6.1)
Requirement already satisfied: tqdm==4.63.0 in c:\users\spirit\appdata\roaming\p
ython\python38\site-packages (from -r requirements.txt (line 11)) (4.63.0)
Requirement already satisfied: yarl~=1.7.2 in c:\users\spirit\appdata\roaming\py
thon\python38\site-packages (from -r requirements.txt (line 12)) (1.7.2)
Requirement already satisfied: charset-normalizer~=2.0.0 in c:\users\spirit\appd
ata\roaming\python\python38\site-packages (from requests==2.27.1->-r requirement
s.txt (line 8)) (2.0.12)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\spirit\appdata\
roaming\python\python38\site-packages (from requests==2.27.1->-r requirements.tx
t (line 8)) (1.26.9)
Requirement already satisfied: idna<4,>=2.5 in c:\users\spirit\appdata\roaming\p
ython\python38\site-packages (from requests==2.27.1->-r requirements.txt (line 8
)) (3.3)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\users\spirit\appdata\ro
aming\python\python38\site-packages (from aiohttp~=3.8.1->-r requirements.txt (l
ine 2)) (6.0.2)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in c:\users\spirit\ap
pdata\roaming\python\python38\site-packages (from aiohttp~=3.8.1->-r requirement
s.txt (line 2)) (4.0.2)
Requirement already satisfied: frozenlist>=1.1.1 in c:\users\spirit\appdata\roam
ing\python\python38\site-packages (from aiohttp~=3.8.1->-r requirements.txt (lin
e 2)) (1.3.0)
Requirement already satisfied: attrs>=17.3.0 in c:\users\spirit\appdata\roaming\
python\python38\site-packages (from aiohttp~=3.8.1->-r requirements.txt (line 2)
) (21.4.0)
Requirement already satisfied: aiosignal>=1.1.2 in c:\users\spirit\appdata\roami
ng\python\python38\site-packages (from aiohttp~=3.8.1->-r requirements.txt (line
 2)) (1.2.0)
Requirement already satisfied: w3lib>=1.17.0 in c:\users\spirit\appdata\roaming\
python\python38\site-packages (from Scrapy~=2.6.0->-r requirements.txt (line 10)
) (1.22.0)
Requirement already satisfied: protego>=0.1.15 in c:\users\spirit\appdata\roamin
g\python\python38\site-packages (from Scrapy~=2.6.0->-r requirements.txt (line 1
0)) (0.2.1)
Requirement already satisfied: setuptools in c:\users\spirit\appdata\local\progr
ams\python\python38\lib\site-packages (from Scrapy~=2.6.0->-r requirements.txt (
line 10)) (56.0.0)
Requirement already satisfied: PyDispatcher>=2.0.5 in c:\users\spirit\appdata\ro
aming\python\python38\site-packages (from Scrapy~=2.6.0->-r requirements.txt (li
ne 10)) (2.0.5)
Requirement already satisfied: Twisted>=17.9.0 in c:\users\spirit\appdata\roamin
g\python\python38\site-packages (from Scrapy~=2.6.0->-r requirements.txt (line 1
0)) (22.2.0)
Requirement already satisfied: zope.interface>=4.1.3 in c:\users\spirit\appdata\
roaming\python\python38\site-packages (from Scrapy~=2.6.0->-r requirements.txt (
line 10)) (5.4.0)
Requirement already satisfied: cryptography>=2.0 in c:\users\spirit\appdata\roam
ing\python\python38\site-packages (from Scrapy~=2.6.0->-r requirements.txt (line
 10)) (36.0.2)
Requirement already satisfied: service-identity>=16.0.0 in c:\users\spirit\appda
ta\roaming\python\python38\site-packages (from Scrapy~=2.6.0->-r requirements.tx
t (line 10)) (21.1.0)
Requirement already satisfied: tldextract in c:\users\spirit\appdata\roaming\pyt
hon\python38\site-packages (from Scrapy~=2.6.0->-r requirements.txt (line 10)) (
3.2.0)
Requirement already satisfied: itemloaders>=1.0.1 in c:\users\spirit\appdata\roa
ming\python\python38\site-packages (from Scrapy~=2.6.0->-r requirements.txt (lin
e 10)) (1.0.4)
Requirement already satisfied: cssselect>=0.9.1 in c:\users\spirit\appdata\roami
ng\python\python38\site-packages (from Scrapy~=2.6.0->-r requirements.txt (line
10)) (1.1.0)
Requirement already satisfied: parsel>=1.5.0 in c:\users\spirit\appdata\roaming\
python\python38\site-packages (from Scrapy~=2.6.0->-r requirements.txt (line 10)
) (1.6.0)
Requirement already satisfied: queuelib>=1.4.2 in c:\users\spirit\appdata\roamin
g\python\python38\site-packages (from Scrapy~=2.6.0->-r requirements.txt (line 1
0)) (1.6.2)
Requirement already satisfied: lxml>=3.5.0 in c:\users\spirit\appdata\roaming\py
thon\python38\site-packages (from Scrapy~=2.6.0->-r requirements.txt (line 10))
(4.8.0)
Requirement already satisfied: pyOpenSSL>=16.2.0 in c:\users\spirit\appdata\roam
ing\python\python38\site-packages (from Scrapy~=2.6.0->-r requirements.txt (line
 10)) (22.0.0)
Requirement already satisfied: itemadapter>=0.1.0 in c:\users\spirit\appdata\roa
ming\python\python38\site-packages (from Scrapy~=2.6.0->-r requirements.txt (lin
e 10)) (0.5.0)
Requirement already satisfied: cffi>=1.12 in c:\users\spirit\appdata\roaming\pyt
hon\python38\site-packages (from cryptography>=2.0->Scrapy~=2.6.0->-r requiremen
ts.txt (line 10)) (1.15.0)
Requirement already satisfied: pycparser in c:\users\spirit\appdata\roaming\pyth
on\python38\site-packages (from cffi>=1.12->cryptography>=2.0->Scrapy~=2.6.0->-r
 requirements.txt (line 10)) (2.21)
Requirement already satisfied: jmespath>=0.9.5 in c:\users\spirit\appdata\roamin
g\python\python38\site-packages (from itemloaders>=1.0.1->Scrapy~=2.6.0->-r requ
irements.txt (line 10)) (1.0.0)
Requirement already satisfied: six>=1.6.0 in c:\users\spirit\appdata\roaming\pyt
hon\python38\site-packages (from parsel>=1.5.0->Scrapy~=2.6.0->-r requirements.t
xt (line 10)) (1.16.0)
Requirement already satisfied: pyasn1-modules in c:\users\spirit\appdata\roaming
\python\python38\site-packages (from service-identity>=16.0.0->Scrapy~=2.6.0->-r
 requirements.txt (line 10)) (0.2.8)
Requirement already satisfied: pyasn1 in c:\users\spirit\appdata\roaming\python\
python38\site-packages (from service-identity>=16.0.0->Scrapy~=2.6.0->-r require
ments.txt (line 10)) (0.4.8)
Requirement already satisfied: Automat>=0.8.0 in c:\users\spirit\appdata\roaming
\python\python38\site-packages (from Twisted>=17.9.0->Scrapy~=2.6.0->-r requirem
ents.txt (line 10)) (20.2.0)
Requirement already satisfied: typing-extensions>=3.6.5 in c:\users\spirit\appda
ta\roaming\python\python38\site-packages (from Twisted>=17.9.0->Scrapy~=2.6.0->-
r requirements.txt (line 10)) (4.1.1)
Requirement already satisfied: hyperlink>=17.1.1 in c:\users\spirit\appdata\roam
ing\python\python38\site-packages (from Twisted>=17.9.0->Scrapy~=2.6.0->-r requi
rements.txt (line 10)) (21.0.0)
Requirement already satisfied: twisted-iocpsupport<2,>=1.0.2 in c:\users\spirit\
appdata\roaming\python\python38\site-packages (from Twisted>=17.9.0->Scrapy~=2.6
.0->-r requirements.txt (line 10)) (1.0.2)
Requirement already satisfied: incremental>=21.3.0 in c:\users\spirit\appdata\ro
aming\python\python38\site-packages (from Twisted>=17.9.0->Scrapy~=2.6.0->-r req
uirements.txt (line 10)) (21.3.0)
Requirement already satisfied: constantly>=15.1 in c:\users\spirit\appdata\roami
ng\python\python38\site-packages (from Twisted>=17.9.0->Scrapy~=2.6.0->-r requir
ements.txt (line 10)) (15.1.0)
Requirement already satisfied: requests-file>=1.4 in c:\users\spirit\appdata\roa
ming\python\python38\site-packages (from tldextract->Scrapy~=2.6.0->-r requireme
nts.txt (line 10)) (1.5.1)
Requirement already satisfied: filelock>=3.0.8 in c:\users\spirit\appdata\roamin
g\python\python38\site-packages (from tldextract->Scrapy~=2.6.0->-r requirements
.txt (line 10)) (3.6.0)
WARNING: Ignoring invalid distribution -p (c:\users\spirit\appdata\local\program
s\python\python38\lib\site-packages)
WARNING: Ignoring invalid distribution -ip (c:\users\spirit\appdata\local\progra
ms\python\python38\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\users\spirit\appdata\local\programs
\python\python38\lib\site-packages)
WARNING: Ignoring invalid distribution -p (c:\users\spirit\appdata\local\program
s\python\python38\lib\site-packages)
WARNING: Ignoring invalid distribution -ip (c:\users\spirit\appdata\local\progra
ms\python\python38\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\users\spirit\appdata\local\programs
\python\python38\lib\site-packages)
WARNING: Ignoring invalid distribution -p (c:\users\spirit\appdata\local\program
s\python\python38\lib\site-packages)
WARNING: Ignoring invalid distribution -ip (c:\users\spirit\appdata\local\progra
ms\python\python38\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\users\spirit\appdata\local\programs
\python\python38\lib\site-packages)
WARNING: Ignoring invalid distribution -p (c:\users\spirit\appdata\local\program
s\python\python38\lib\site-packages)
WARNING: Ignoring invalid distribution -ip (c:\users\spirit\appdata\local\progra
ms\python\python38\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\users\spirit\appdata\local\programs
\python\python38\lib\site-packages)
WARNING: You are using pip version 21.1.1; however, version 22.0.4 is available.

You should consider upgrading via the 'C:\Users\spirit\AppData\Local\Programs\Py
thon\Python38\python.exe -m pip install --upgrade pip' command.

C:\CyberDropDownloader-2.6.1>pause
Press any key to continue . . .

**Comment by Jules-WinnfieldX** [comment]
Yea, it's working. Just press a key after that and the program will do it's thing.
