### ISSUE TITLE
Wrong file extension

### ISSUE THREAD

**Issue by imufo** [Jules-WinnfieldX/CyberDropDownloader#841]
**Describe the bug**
Media files gets saved with wrong file extension!
For example some .jpeg files gets stored with .png

**To Help Reproduce**
While I was scraping This link: https://coomer.su/fansly/user/285237922733502464
I found out that files are not stored in the correct file extensions. Most of jpeg image files were stored with png file extensions.
This causes file opening failures!
However, when I manually change file extension to correct form for example jpg, I can open image file!

**Screenshots**
![Screenshot at 2024-03-10 13-12-31](https://github.com/Jules-WinnfieldX/CyberDropDownloader/assets/60540316/e45b82c7-1a11-4798-9b6a-e8efc827f2ba)

**Setup Information**
 - OS: Linux Parrot OS
 - Cyberdrop Downloader Version 4.2.197 

**Downloader.log file**
 
[downloader.log](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/14549717/downloader.log)

**Additional context**
 I have installed cypberdrop with esay installer Cyberdrop_DL.V5.1 but I don't know why mine is ruining with version 4.2.

**Comment by Jules-WinnfieldX** [comment]
You need python 3.11 for V5 of CDL. 

As for the file extensions, CDL is working as intended. Coomer is saying the file extension is .png, so it downloads as .png.
