### ISSUE TITLE
[BUG]Tool does not scrape Rule34.xyz properly

### ISSUE THREAD

**Issue by Kafajesty** [Jules-WinnfieldX/CyberDropDownloader#842]
The tool is not scraping content from the Rule34.xyz website correctly.
A page with 1000 posts, it only scrapes half the page and ignores all other content on the page, presenting (404 HTTP failure), but when I download it manually, I can do it without any problems

**Comment by Jules-WinnfieldX** [comment]
Please fill out the bug report properly, with a downloader.log file attached showing the issue.

**Comment by Kafajesty** [comment]
edited

**Comment by Jules-WinnfieldX** [comment]
Fixed in 5.2.3
