### ISSUE TITLE
[BUG] ReaderError after new update

### ISSUE THREAD

**Issue by ClearWing** [Jules-WinnfieldX/CyberDropDownloader#845]
![Captura de tela 2024-03-11 192851](https://github.com/Jules-WinnfieldX/CyberDropDownloader/assets/12037497/ba42a63a-3b74-420c-b89b-aa3a1fb68a69)

**Comment by Jules-WinnfieldX** [comment]
Need more info than that. Show me the full text

**Comment by ClearWing** [comment]
Installing / Updating Cyberdrop-DL
Requirement already satisfied: cyberdrop-dl in e:\downloads\cyberdrop_dl.v5.1\venv\lib\site-packages (5.2.4)
Requirement already satisfied: aiofiles==0.8.0 in e:\downloads\cyberdrop_dl.v5.1\venv\lib\site-packages (from cyberdrop-dl) (0.8.0)
Requirement already satisfied: aiohttp<4.0.0,>=3.9.1 in e:\downloads\cyberdrop_dl.v5.1\venv\lib\site-packages (from cyberdrop-dl) (3.9.3)
Requirement already satisfied: aiolimiter<2.0.0,>=1.1.0 in e:\downloads\cyberdrop_dl.v5.1\venv\lib\site-packages (from cyberdrop-dl) (1.1.0)
Requirement already satisfied: aiosqlite==0.17.0 in e:\downloads\cyberdrop_dl.v5.1\venv\lib\site-packages (from cyberdrop-dl) (0.17.0)
Requirement already satisfied: asyncpraw<8.0.0,>=7.7.1 in e:\downloads\cyberdrop_dl.v5.1\venv\lib\site-packages (from cyberdrop-dl) (7.7.1)
Requirement already satisfied: beautifulsoup4<5.0.0,>=4.12.2 in e:\downloads\cyberdrop_dl.v5.1\venv\lib\site-packages (from cyberdrop-dl) (4.12.3)
Requirement already satisfied: browser-cookie3<0.20.0,>=0.19.1 in e:\downloads\cyberdrop_dl.v5.1\venv\lib\site-packages (from cyberdrop-dl) (0.19.1)
Requirement already satisfied: certifi<2025.0.0,>=2024.2.2 in e:\downloads\cyberdrop_dl.v5.1\venv\lib\site-packages (from cyberdrop-dl) (2024.2.2)
Requirement already satisfied: filedate<4.0,>=3.0 in e:\downloads\cyberdrop_dl.v5.1\venv\lib\site-packages (from cyberdrop-dl) (3.0)
Requirement already satisfied: get-video-properties<0.2.0,>=0.1.1 in e:\downloads\cyberdrop_dl.v5.1\venv\lib\site-packages (from cyberdrop-dl) (0.1.1)
Requirement already satisfied: inquirerpy<0.4.0,>=0.3.4 in e:\downloads\cyberdrop_dl.v5.1\venv\lib\site-packages (from cyberdrop-dl) (0.3.4)
Requirement already satisfied: mediafire<0.7.0,>=0.6.1 in e:\downloads\cyberdrop_dl.v5.1\venv\lib\site-packages (from cyberdrop-dl) (0.6.1)
Requirement already satisfied: mutagen<2.0.0,>=1.47.0 in e:\downloads\cyberdrop_dl.v5.1\venv\lib\site-packages (from cyberdrop-dl) (1.47.0)
Requirement already satisfied: myjdapi<2.0.0,>=1.1.7 in e:\downloads\cyberdrop_dl.v5.1\venv\lib\site-packages (from cyberdrop-dl) (1.1.7)
Requirement already satisfied: pillow<11.0.0,>=10.2.0 in e:\downloads\cyberdrop_dl.v5.1\venv\lib\site-packages (from cyberdrop-dl) (10.2.0)
Requirement already satisfied: platformdirs<5.0.0,>=4.2.0 in e:\downloads\cyberdrop_dl.v5.1\venv\lib\site-packages (from cyberdrop-dl) (4.2.0)
Requirement already satisfied: pyyaml<7.0.0,>=6.0.1 in e:\downloads\cyberdrop_dl.v5.1\venv\lib\site-packages (from cyberdrop-dl) (6.0.1)
Requirement already satisfied: rich<14.0.0,>=13.7.0 in e:\downloads\cyberdrop_dl.v5.1\venv\lib\site-packages (from cyberdrop-dl) (13.7.1)
Requirement already satisfied: typing_extensions>=3.7.2 in e:\downloads\cyberdrop_dl.v5.1\venv\lib\site-packages (from aiosqlite==0.17.0->cyberdrop-dl) (4.10.0)
Requirement already satisfied: aiosignal>=1.1.2 in e:\downloads\cyberdrop_dl.v5.1\venv\lib\site-packages (from aiohttp<4.0.0,>=3.9.1->cyberdrop-dl) (1.3.1)
Requirement already satisfied: attrs>=17.3.0 in e:\downloads\cyberdrop_dl.v5.1\venv\lib\site-packages (from aiohttp<4.0.0,>=3.9.1->cyberdrop-dl) (23.2.0)
Requirement already satisfied: frozenlist>=1.1.1 in e:\downloads\cyberdrop_dl.v5.1\venv\lib\site-packages (from aiohttp<4.0.0,>=3.9.1->cyberdrop-dl) (1.4.1)
Requirement already satisfied: multidict<7.0,>=4.5 in e:\downloads\cyberdrop_dl.v5.1\venv\lib\site-packages (from aiohttp<4.0.0,>=3.9.1->cyberdrop-dl) (6.0.5)
Requirement already satisfied: yarl<2.0,>=1.0 in e:\downloads\cyberdrop_dl.v5.1\venv\lib\site-packages (from aiohttp<4.0.0,>=3.9.1->cyberdrop-dl) (1.9.4)
Requirement already satisfied: asyncprawcore<3,>=2.1 in e:\downloads\cyberdrop_dl.v5.1\venv\lib\site-packages (from asyncpraw<8.0.0,>=7.7.1->cyberdrop-dl) (2.4.0)
Requirement already satisfied: update-checker>=0.18 in e:\downloads\cyberdrop_dl.v5.1\venv\lib\site-packages (from asyncpraw<8.0.0,>=7.7.1->cyberdrop-dl) (0.18.0)
Requirement already satisfied: soupsieve>1.2 in e:\downloads\cyberdrop_dl.v5.1\venv\lib\site-packages (from beautifulsoup4<5.0.0,>=4.12.2->cyberdrop-dl) (2.5)
Requirement already satisfied: lz4 in e:\downloads\cyberdrop_dl.v5.1\venv\lib\site-packages (from browser-cookie3<0.20.0,>=0.19.1->cyberdrop-dl) (4.3.3)
Requirement already satisfied: pycryptodomex in e:\downloads\cyberdrop_dl.v5.1\venv\lib\site-packages (from browser-cookie3<0.20.0,>=0.19.1->cyberdrop-dl) (3.20.0)
Requirement already satisfied: python-dateutil in e:\downloads\cyberdrop_dl.v5.1\venv\lib\site-packages (from filedate<4.0,>=3.0->cyberdrop-dl) (2.9.0)
Requirement already satisfied: pfzy<0.4.0,>=0.3.1 in e:\downloads\cyberdrop_dl.v5.1\venv\lib\site-packages (from inquirerpy<0.4.0,>=0.3.4->cyberdrop-dl) (0.3.4)
Requirement already satisfied: prompt-toolkit<4.0.0,>=3.0.1 in e:\downloads\cyberdrop_dl.v5.1\venv\lib\site-packages (from inquirerpy<0.4.0,>=0.3.4->cyberdrop-dl) (3.0.43)
Requirement already satisfied: requests in e:\downloads\cyberdrop_dl.v5.1\venv\lib\site-packages (from mediafire<0.7.0,>=0.6.1->cyberdrop-dl) (2.31.0)
Requirement already satisfied: requests-toolbelt in e:\downloads\cyberdrop_dl.v5.1\venv\lib\site-packages (from mediafire<0.7.0,>=0.6.1->cyberdrop-dl) (1.0.0)
Requirement already satisfied: six in e:\downloads\cyberdrop_dl.v5.1\venv\lib\site-packages (from mediafire<0.7.0,>=0.6.1->cyberdrop-dl) (1.16.0)
Requirement already satisfied: pycryptodome in e:\downloads\cyberdrop_dl.v5.1\venv\lib\site-packages (from myjdapi<2.0.0,>=1.1.7->cyberdrop-dl) (3.20.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in e:\downloads\cyberdrop_dl.v5.1\venv\lib\site-packages (from rich<14.0.0,>=13.7.0->cyberdrop-dl) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in e:\downloads\cyberdrop_dl.v5.1\venv\lib\site-packages (from rich<14.0.0,>=13.7.0->cyberdrop-dl) (2.17.2)
Requirement already satisfied: mdurl~=0.1 in e:\downloads\cyberdrop_dl.v5.1\venv\lib\site-packages (from markdown-it-py>=2.2.0->rich<14.0.0,>=13.7.0->cyberdrop-dl) (0.1.2)
Requirement already satisfied: wcwidth in e:\downloads\cyberdrop_dl.v5.1\venv\lib\site-packages (from prompt-toolkit<4.0.0,>=3.0.1->inquirerpy<0.4.0,>=0.3.4->cyberdrop-dl) (0.2.13)
Requirement already satisfied: charset-normalizer<4,>=2 in e:\downloads\cyberdrop_dl.v5.1\venv\lib\site-packages (from requests->mediafire<0.7.0,>=0.6.1->cyberdrop-dl) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in e:\downloads\cyberdrop_dl.v5.1\venv\lib\site-packages (from requests->mediafire<0.7.0,>=0.6.1->cyberdrop-dl) (3.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in e:\downloads\cyberdrop_dl.v5.1\venv\lib\site-packages (from requests->mediafire<0.7.0,>=0.6.1->cyberdrop-dl) (2.2.1)

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "E:\Downloads\Cyberdrop_DL.V5.1\venv\Scripts\cyberdrop-dl.exe\__main__.py", line 7, in <module>
  File "E:\Downloads\Cyberdrop_DL.V5.1\venv\Lib\site-packages\cyberdrop_dl\main.py", line 145, in main
    manager = startup()
              ^^^^^^^^^
  File "E:\Downloads\Cyberdrop_DL.V5.1\venv\Lib\site-packages\cyberdrop_dl\main.py", line 26, in startup
    manager.startup()
  File "E:\Downloads\Cyberdrop_DL.V5.1\venv\Lib\site-packages\cyberdrop_dl\managers\manager.py", line 56, in startup
    self.config_manager.startup()
  File "E:\Downloads\Cyberdrop_DL.V5.1\venv\Lib\site-packages\cyberdrop_dl\managers\config_manager.py", line 66, in startup
    self.load_configs()
  File "E:\Downloads\Cyberdrop_DL.V5.1\venv\Lib\site-packages\cyberdrop_dl\managers\config_manager.py", line 77, in load_configs
    self._verify_global_settings_config()
  File "E:\Downloads\Cyberdrop_DL.V5.1\venv\Lib\site-packages\cyberdrop_dl\managers\config_manager.py", line 142, in _verify_global_settings_config
    existing_global_settings_data = _load_yaml(self.global_settings)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Downloads\Cyberdrop_DL.V5.1\venv\Lib\site-packages\cyberdrop_dl\managers\config_manager.py", line 36, in _load_yaml
    return yaml.load(yaml_file.read(), Loader=yaml.FullLoader)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Downloads\Cyberdrop_DL.V5.1\venv\Lib\site-packages\yaml\__init__.py", line 79, in load
    loader = Loader(stream)
             ^^^^^^^^^^^^^^
  File "E:\Downloads\Cyberdrop_DL.V5.1\venv\Lib\site-packages\yaml\loader.py", line 24, in __init__
    Reader.__init__(self, stream)
  File "E:\Downloads\Cyberdrop_DL.V5.1\venv\Lib\site-packages\yaml\reader.py", line 74, in __init__
    self.check_printable(stream)
  File "E:\Downloads\Cyberdrop_DL.V5.1\venv\Lib\site-packages\yaml\reader.py", line 143, in check_printable
    raise ReaderError(self.name, position, ord(character),
yaml.reader.ReaderError: unacceptable character #x0000: special characters are not allowed
  in "<unicode string>", position 0

**Comment by Jules-WinnfieldX** [comment]
delete the global settings file in ./appdata/configs and try again.

**Comment by ClearWing** [comment]
worked, thanks
