### ISSUE TITLE
[BUG] omegascans.org support broken

### ISSUE THREAD

**Issue by hrm-princess-fluffybutt** [Jules-WinnfieldX/CyberDropDownloader#849]
**Describe the bug**
omegascans.org no longer scrapes and downloads

**To Help Reproduce**
do any supported omegscans.org link

e.g. https://omegascans.org/series/how-to-conquer-women-with-hypnosis

**Additional context**
site got an aesthetic update, broke the spider

**Comment by Jules-WinnfieldX** [comment]
5.2.36

Fixed
