### ISSUE TITLE
[BUG] Error trying to download no matter what URL is tried

### ISSUE THREAD

**Issue by dynbabaul** [Jules-WinnfieldX/CyberDropDownloader#85]
Moving to version 2.6.1 I get this output no matter the URL I try to use.

Traceback (most recent call last):
  File "./main.py", line 15, in <module>
    from utils.downloaders import get_downloaders
  File "/Downloads/CyberDropDownloader-2.6.1/utils/downloaders.py", line 111, in <module>
    class Downloader:
  File "/Downloads/CyberDropDownloader-2.6.1/utils/downloaders.py", line 112, in Downloader
    def __init__(self, links: list[list[str]], morsels, folder: Path, title: str, max_workers: int):
TypeError: 'type' object is not subscriptable

**Setup Information**
 - OS: debian linux 
 - Cyberdrop Downloader Version # 2.6.1

**Comment by Jules-WinnfieldX** [comment]
I believe this is due to you not being on a high enough python version, what version are you using?

**Comment by dynbabaul** [comment]
Python 2.7.16

**Comment by Jules-WinnfieldX** [comment]
I don't have a copy of the old 2.6.1 start.sh file. I'd recommend you update either way to 2.7.2 (release, in the release pages). See if that version works for you.

**Comment by dynbabaul** [comment]
Installing 2.7.2 is missing the Start.sh file. If I get it from Cyberdrop-DL.zip then it runs the cyberdrop-dl that it downloads from pip and gives the same error.

**Comment by Jules-WinnfieldX** [comment]
Can you add a line above cyberdrop-dl in the start.sh file that says `python --version`? Just for my sanity.

**Comment by dynbabaul** [comment]
python --version
Python 2.7.16
python3 --version
Python 3.7.3

**Comment by Jules-WinnfieldX** [comment]
That's not what I asked, I was trying to see which environment is being used to call cyberdrop-dl. Because I'm fairly certain that it's the 2.7.16 environment.

**Comment by dynbabaul** [comment]
If I put "python --version" in that file I get "Python 2.7.16" in the output. 

That doesn't tell what version is calling cyberdrop-dl, because if you put "python3 --version" in start.sh you'll get "Python 3.7.3" in the output.

**Comment by Jules-WinnfieldX** [comment]
Yes, but that SH script is installing using pip, not pip3. So I'm not incredibly familiar with linux in general. But I do know that error. I've seen that error (or something extremely similar) from people who were using versions of python that do not support type hinting. I'm pushing 2.7.3 for you to try.

**Comment by Jules-WinnfieldX** [comment]
Scratch, it's 2.8.0

**Comment by dynbabaul** [comment]
Looking on https://www.python.org/downloads/source/ the latest release of python 2 is Python 2.7.18, there is no 2.8.0 release.

**Comment by dynbabaul** [comment]
I also noticed this, when you look at cyberdrop-dl the first line is calling python3.

#!/usr/bin/python3

**Comment by Jules-WinnfieldX** [comment]
> Looking on https://www.python.org/downloads/source/ the latest release of python 2 is Python 2.7.18, there is no 2.8.0 release.

I meant I'm pushing version 2.8.0 of Cyberdrop-dl

**Comment by dynbabaul** [comment]
Ok, I was trying to upgrade python and thought that's what you meant.
