### ISSUE TITLE
[BUG] can't download posts without a "full date"

### ISSUE THREAD

**Issue by andorewasu** [Jules-WinnfieldX/CyberDropDownloader#851]
**Describe the bug**
Since said post's date is just month/year, essentially **_not like_** every other post on Coomer/Kemono is, it results in a failed scrap.

**To Help Reproduce**
Steps to help reproduce the behavior:
1. set "https://kemono.su/gumroad/user/6999878318079/post/pHkFR" as target URL
2. start download
3. failed scrap

**Setup Information**
 - OS: Windows 10
 - Cyberdrop Downloader V5

**Downloader.log file**
[downloader.log](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/14654057/downloader.log)

**Comment by Jules-WinnfieldX** [comment]
As this post has been updated to include the full date, I'm just going to close this for now.
