### ISSUE TITLE
[BUG] Cyberdrop-DL downloading from Coomer Fansly profiles fails when the files are in a previous revision.

### ISSUE THREAD

**Issue by actualdisaster** [Jules-WinnfieldX/CyberDropDownloader#855]
It won't download https://coomer.su/fansly/user/568147843500486656/post/627256837493764096 even though the file is available at https://coomer.su/fansly/user/568147843500486656/post/627256837493764096/revision/6075523

**Comment by marioaugustorama** [comment]
I just tested it, I downloaded it normally. I already have the latest version.

**Comment by Jules-WinnfieldX** [comment]
Can confirm the reply above, closing.
