### ISSUE TITLE
OSError: [Error 36] File name too long: [BUG]

### ISSUE THREAD

**Issue by scroguard** [Jules-WinnfieldX/CyberDropDownloader#856]
I seem to be bumping into an issue with downloading that will eventually cause cyberdrop-dl to hang. The error in the log file states that the filename is too long. When this occurs cyberdrop-dl will attempt to re-download the file, only to throw the error again. In the UI the file is no longer downloading and a "?" is displayed in the transfer rate for the file. 

I have left it running for multiple days to see if the file is eventually dropped so that the script can move on, but that never happens. In fact, this will sometimes occur with multiple files and eventually cyberdrop-dl will get stuck in a never-ending loop.

OS: Debian 12 w Linux Kernel 6.1.64 LXC Container
Filesystem: EXT4 for LXC container with download directory on an NFS share mounted into the container
cyberdrop-dl version: 5.2.9
Python version: 3.11.2

I've attached the full downloader.log file for reference.

![download-stalled](https://github.com/Jules-WinnfieldX/CyberDropDownloader/assets/74786005/88df32f2-aefb-481d-8a62-b7f0759a9a77)

[downloader.log](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/14747032/downloader.log)

**Comment by Jules-WinnfieldX** [comment]
It shouldn't continuously retry, I'll get to that. As an intermediary solution. You can reduce the max filename size in the configs (default is 95 characters).
