### ISSUE TITLE
[BUG] CDDL fails to scrape images from SMG Forum Threads

### ISSUE THREAD

**Issue by resnovox12** [Jules-WinnfieldX/CyberDropDownloader#857]
**Description**
Attempting to scrape thread posts results in the process completing without actually doing anything. I had attempted this a few days prior, and on one occasion it managed to grab 3 video files, but no attempt was made to scrape images (from ibb.co and jpg4.su in particular).

**Steps & Additional Testing**
1. Initiate a scrape on a thread from SMG - the one I have been trying is this one (https://forums.socialmediagirls.com/threads/4x4-offroad-car-girls-truck-girls.340830/)
2. Downloader log shows no related errors or attempts to scrape any images (it did grab 3 videos from Redgifs at one point, but that was all it tried to get)
3. I have tested another forum (SC) and image scraping works just fine there.
4. Settings YAML file is set correctly, "exclude_images" is set to false, "coomer" is set as a skipped host, etc.

**Setup Information**
 - OS: Windows 10 22H2 (19045)
 - Cyberdrop Downloader Version 5.2.11 (latest version as of this issue)
 - Using Python 3.11.4

**Downloader.log file**
[downloader.log](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/14754470/downloader.log)

**Comment by Jules-WinnfieldX** [comment]
5.1.12 going up should fix it

**Comment by resnovox12** [comment]
> 5.1.12 going up should fix it

Scraping works fine, it's seeing the images. But now an odd thing occurs, particularly with IBB - not sure if this is a CDDL issue or something on IBB's end, basically what happens is IBB tells me the requested page doesn't exist, but if I turn on my VPN, the page comes up and the image loads, but when I start a scrape, it throws 404 errors and goes back to saying the page doesn't exist.

**Comment by Jules-WinnfieldX** [comment]
shoot over another log showcasing that

**Comment by resnovox12** [comment]
> shoot over another log showcasing that

Here you go - 
[downloader.log](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/14799373/downloader.log)

jpg4 images scrape and download just fine, but IBB refuses to scrape and just throws 404's.

**Comment by Jules-WinnfieldX** [comment]
This actually appears to be an issue with ibb.co itself. 

Every image url like `https://i.ibb.co/wK7SGvp/The-Old-Man-S01-E01-I-720p-WEB-HD-x264-450-MB-Pahe-in.jpg` should be accessible at `https://ibb.co/wK7SGvp`

CDL reverses direct links to post links in order to get the information it looks for. But for some reason, none of the post links on ibb.co work, even on images I've uploaded myself in the past.

**Comment by resnovox12** [comment]
Interesting... I know that IBB used to work fine (not that long ago), so I guess they changed something. Could be some sort of protection, perhaps?

**Comment by Jules-WinnfieldX** [comment]
It's not protection, just broken website. Only reason the direct link loads is because it's cached in nginx.

**Comment by resnovox12** [comment]
Gotcha. I'd assume a fix for that isn't really possible then, since it's on IBB's end and not CDL.
