### ISSUE TITLE
[FEATURE] Add the ability to load a single page with simpcity

### ISSUE THREAD

**Issue by kaynshae** [Jules-WinnfieldX/CyberDropDownloader#859]
If you insert a link now https://simpcity.su/threads/.../page-8 then it will start loading the full theme from page 1 to the end. But very often this is unnecessary, you only need a specific page, but you can't do it

**Comment by Jules-WinnfieldX** [comment]
Page linking is supported. As in your format. However it's not single page, it uses that page as the starting point. Same as if you linked a post number. 

This feature request is in conflict with that, so I'm gonna have to deny it.
