### ISSUE TITLE
[BUG] Cannot start the script

### ISSUE THREAD

**Issue by wooferfluff** [Jules-WinnfieldX/CyberDropDownloader#86]
C:\Users\RD\Desktop\Cyberdrop_DL>pip install --user --upgrade cyberdrop-dl
'pip' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\RD\Desktop\Cyberdrop_DL>FOR /F %p in ('where pip') do (
set part2=%p
 set part3=!part2:pip.exe=!
 set part4=!part3:Local\Programs=Roaming!
 path !Part4!;!part3!;!path!
)
INFO: Could not find files for the given pattern(s).

**Comment by Jules-WinnfieldX** [comment]
python -m ensurepip

Run that command in command prompt

**Comment by wallysly** [comment]
i have same issue this did not resolve cmd:
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.

**Comment by Jules-WinnfieldX** [comment]
Well, you need to have python installed. https://www.python.org/downloads/release/python-3103/
install it, make sure you click the add to path option.

**Comment by Jules-WinnfieldX** [comment]
If you already have an installation, it isn't working properly. I'd recommend uninstalling all versions of python you have installed and reinstalling through the link above. With the option clicked.

**Comment by wallysly** [comment]
I have uninstalled and reinstalled and have seem to got it working. Something as simple and an option to ticked in installation, I feel like an idiot now ,Thankyou very much for you help.
