### ISSUE TITLE
[BUG]Keep asking for the update 

### ISSUE THREAD

**Issue by vduong421** [Jules-WinnfieldX/CyberDropDownloader#861]
![Screenshot 2024-03-28 002524](https://github.com/Jules-WinnfieldX/CyberDropDownloader/assets/125083960/21cedc2a-91cd-473f-b5fb-0cb6f25b11bb)
How to fix this issue?

**Comment by Jules-WinnfieldX** [comment]
uninstall python and install python 3.11
