### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by eldawoody** [Jules-WinnfieldX/CyberDropDownloader#865]
**Describe the bug**
when ever i try to download something i get the following error

Download Stats:
Downloaded 0 files
Previously Downloaded 0 files
Skipped By Config 0 files
Failed 25 files

Scrape Failures:

Download Failures:
Download Failures (CustomHTTPStatus.IM_A_TEAPOT HTTP Status): 25

**Screenshots**
![image](https://github.com/Jules-WinnfieldX/CyberDropDownloader/assets/67889943/9736de8f-5794-4a9b-a5c0-cf7e125e1057).

**Setup Information**
 - OS: windows 11
 - Cyberdrop Downloader 5.1

**Comment by Jules-WinnfieldX** [comment]
It's because you're on an old version of CDL. Read the message at the bottom of your screenshot.

**Comment by Jules-WinnfieldX** [comment]
uninstall the python you have and install at least 3.11
