### ISSUE TITLE
[FEATURE] Add sort-downloads  and sort-folder to cmdline

### ISSUE THREAD

**Issue by marioaugustorama** [Jules-WinnfieldX/CyberDropDownloader#866]
Please add sort-downloads directly to the command line.

--sort-downloads
--sort-folder

To overwrite configuration file parameters at runtime.

sorting:
   sort_downloads: true
   sort_folder: /app/Downloads/new_directory

**Comment by Jules-WinnfieldX** [comment]
Will be in next update
