### ISSUE TITLE
[BUG]'cyberdrop-dl' is not recognized 

### ISSUE THREAD

**Issue by Irishdab** [Jules-WinnfieldX/CyberDropDownloader#868]
I have been using cyberdrop for months with no issue till today I get the error: 

'cyberdrop-dl' is not recognized as an internal or external command,
operable program or batch file.

And will no longer run.

**Comment by Jules-WinnfieldX** [comment]
Uninstall and then reinstall python. Delete the venv folder if one exists.

**Comment by Jules-WinnfieldX** [comment]
Make sure Python is added to path when reinstalling it.
