### ISSUE TITLE
[BUG] Cyberdrop-dl is installed via pip but cyberdrop-dl is not recognized.

### ISSUE THREAD

**Issue by wdos3** [Jules-WinnfieldX/CyberDropDownloader#87]
Both the manual version (the batch file) and the pip-installed version cannot be recognized, even though:
1. It shows up in pip list.
2. "Requirement already satisfied" when trying to upgrade/install it.
3. It's in the site-packages folder.

Not sure how to fix this. Please help.

**Comment by Jules-WinnfieldX** [comment]
I silently updated the batch file zip in releases yesterday. Download that again and try the new one if you aren't already using it.

**Comment by wdos3** [comment]
Annoyingly, 'cyberdrop-dl' is not recognized as an internal or external command, operable program or batch file.
I am using Python 3.9.12, not sure whether there's some sort of special whell for that version alone.

**Comment by Jules-WinnfieldX** [comment]
Two options. You can either uninstall all versions of python you have currently and reinstall 3.9.12 or 3.10. When you do, make sure to click the "add python to path checkbox" in the installer. Can't guarantee that will work, but it has for others.

The other option is to edit your environmental variables and add the following to PATH `C:\Users\<your name> \AppData\Local\Programs\Python\<the python folder>\Scripts` 
inside that folder will be a cyberdrop-dl file that command prompt is looking for. You'll have to fill in the <>'s with the info from your system

**Comment by wdos3** [comment]
Python is already added to PATH, and annoyingly, I can freely use any other commands from any other libraries in the same place. Not sure what's going on really.

I will try deleting python if I can guarantee it doesn't poof all my libraries away tbf
![image_2022-03-27_024935](https://user-images.githubusercontent.com/86643177/160254967-f37a9cef-6f0b-4903-adc1-3d967cd1d94b.png)

**Comment by Jules-WinnfieldX** [comment]
Sorry, it's this one that needs to be added to PATH

C:\Users\<user>\AppData\Roaming\Python\<python folder>\Scripts

Python only adds one by default.

**Comment by Jules-WinnfieldX** [comment]
Can never remember which one is already there for people.

**Comment by wdos3** [comment]
![image_2022-03-27_025853](https://user-images.githubusercontent.com/86643177/160255218-3aa6f355-caf5-4577-9245-e6a16133151c.png)
Annoyingly, still there already.
Added the site-packages path to PATH though, crossing my fingers that it works.

**Comment by wdos3** [comment]
Doesn't work.

**Comment by Jules-WinnfieldX** [comment]
Well that's extremely annoying. Can you confirm that you see cyberdrop-dl in those python script folders?

**Comment by wdos3** [comment]
![image_2022-03-27_030317](https://user-images.githubusercontent.com/86643177/160255341-83b6bfb7-73e0-4a6f-8e51-03827e101bcd.png)
Yeah, it's there. I;m gonna restart my laptop to see if the changes to PATH needs a reset or not.

**Comment by Jules-WinnfieldX** [comment]
Not in site packages, you should see an application file in python39/Scripts.

**Comment by wdos3** [comment]
![image](https://user-images.githubusercontent.com/86643177/160255380-bed157ef-2a04-435f-8023-6ec2062d9fbc.png)
Oh yeah, it's also there.

**Comment by Jules-WinnfieldX** [comment]
I'm puzzled. And to just double check, those paths are on your user variables, not in system variables right?

**Comment by wdos3** [comment]
I believe they are on both paths. At least the Roaming-Python-Script/site-packages are on both paths.

**Comment by wdos3** [comment]
What's puzzling me is that it's very clearly working with other libraries, just refusing to work with this one.

**Comment by Jules-WinnfieldX** [comment]
Yea, I'm new to maintaining a library in all honesty, I had help setting this up for the pip install. I believe everything should be how it's supposed to be. But I'm not sure I can be of much help for you right now.

**Comment by wdos3** [comment]
Yeah, fair point, I might try writing my own data scraper based on existing designs, or just have a good sleep and hopefully wake up to a lot of answers. Have a good night/day/afternoon/noon at your end.

**Comment by ShavedLearner89** [comment]
i think i found a solution / workaround for now, 

So, after messing with the files a bit, i found out this

![PATH](https://user-images.githubusercontent.com/32031898/160500004-21ee7a3f-28a6-4062-a35e-9a6bec15b82a.png)

so, i went to check the PATH variables in my system, and well, look what i found
the variables / scripts folder that the installer adds are the \local\programs\ and not the \Roaming\

![Path 2](https://user-images.githubusercontent.com/32031898/160500345-42d16264-4ff3-4b8b-9cb9-7ce21f84b89c.png)

so, after adding the \Roaming\Python\Python310\Scripts folder manually with the Environment Variables editor, now the app works properly 

![stuck 1](https://user-images.githubusercontent.com/32031898/160500683-b684e52e-15c3-4a7d-969c-bdeae8b9e65c.png)


(you might have to run the windows.bat a couple of times for some reason, but that works)

**Comment by Jules-WinnfieldX** [comment]
Can you try this? https://github.com/Jules-WinnfieldX/CyberDropDownloader/releases/download/Release/Cyberdrop_DL.V2.zip

**Comment by wdos3** [comment]
Yeah, it still doesn't work, thanks for getting back to this though.

**Comment by Jules-WinnfieldX** [comment]
Yea besides a reinstall I got nothin. It doesn't seem like cmd prompt is seeing your path variables properly.

**Comment by wdos3** [comment]
I think I solved the problem?
My PATH has 2 site-packages, Program Files/Python39/site-packages and AppData/.../Python39/site-packages.
All the libraries were downloaded to the AppData one, and none to the Program Files one. All works well, except for CyberDrop, so I have to move Cyberdrop to the Program Files, where it works.

And now I have another problem. I think the .bat file isn't taking the request from the URL file.

**Comment by Jules-WinnfieldX** [comment]
Moving the files will break auto-updating. As a fair warning. Not sure what you mean by that last line.

**Comment by wdos3** [comment]
[downloader.log](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/8376599/downloader.log)
I think the download log shows the problem. There's nothing in the link array, but I have already put a link in the URLs file, which makes me think cyberdrop is not taking in the URL file (I both used CMD and the bat file in the same directory just to be sure).

**Comment by Jules-WinnfieldX** [comment]
No that links array is for a command line option that isn't explicitly mentioned in the readme.  Unless the program outputs an error and says the URLs.txt file is empty (or equivalent) then it's still working.

**Comment by wdos3** [comment]
Then how have I exhausted all my downloading attempts? Bad wifi connection?

**Comment by Jules-WinnfieldX** [comment]
The downloader.log you provided didn't show that, I'd need a full log to see what's happening.

**Comment by wdos3** [comment]
Where can I find the full log? The Cyberdrop program auto-wipes the terminal.

**Comment by Jules-WinnfieldX** [comment]
After the program finishes upload the downloader.log. You uploaded it right after a run started, it hadn't had a chance to do anything yet.

**Comment by wdos3** [comment]
![image_2022-03-30_095742](https://user-images.githubusercontent.com/86643177/160742104-f54b7d52-5eae-4c63-abff-728182a60433.png)
Oh, the program automatically ended so I don't know what to do there.

**Comment by Jules-WinnfieldX** [comment]
Ha, well I just realized that my checking for no links broke with my recent changes. What links are you using in your URLs.txt? While I fix it.

**Comment by wdos3** [comment]
not boutta expose myself here lol

**Comment by Jules-WinnfieldX** [comment]
Understandable, if they are password protected they won't work. If you are on TB you can PM me them there.

**Comment by wdos3** [comment]
1. What's TB?
2. My links should still be working and not password-protected, but I'll try another one and get back to you later.

**Comment by Jules-WinnfieldX** [comment]
ThotsBay. Without having the links, I can't test them myself and fix issues, which is the only reason I ask for them.

**Comment by wdos3** [comment]
Oh okie, my name on there is opcleaver0, shoot me a msg.

**Comment by Jules-WinnfieldX** [comment]
I've pushed up 2.10.1, as I said your auto update won't work. Will PM
