### ISSUE TITLE
[FEATURE] Bunkr - Keep original file name

### ISSUE THREAD

**Issue by Christus92** [Jules-WinnfieldX/CyberDropDownloader#871]
The file name the uploader original used stands in file tile in each gallery:
File preview
original filename
Size
Upload Date

Please add the option to change the filename after the download to the former one. Its way more easy to find duplicates after the download, when we dont have to use the generated ones by bunkr. I know, that i can remove the id from the filename, buts not what i am looking for.
Thanks

**Comment by Jules-WinnfieldX** [comment]
> I know, that i can remove the id from the filename, buts not what i am looking for

You'll need to clarify here what you are looking for then

**Comment by Christus92** [comment]
Thanks for your reply. 
Ok, the filename after regular download is e.g. Video-from-holliday-1080p-rAnd0m.mp4
If i enable remove_generated_id_from_filenames its: Video-from-holliday-1080p.mp4

In the gallery tile/preview between thumbnail and size stands the real filename the uploader used before: Video.from.Holliday.1080p.mp4

I wish the download script automatically reverts the filename to the one the uploader used.

**Comment by Jules-WinnfieldX** [comment]
Not going to be possible as the filenames you are describing don't exist on the /i/ /d/ or /v/ pages.
