### ISSUE TITLE
[FEATURE] Add Support for Twitter.com

### ISSUE THREAD

**Issue by jerrywoo96** [Jules-WinnfieldX/CyberDropDownloader#877]
**Is your feature request related to a problem? Please describe.**
Not related to a problem.

**Describe the solution you'd like**
As stated in the title.

**Additional context**
Able to download videos and pictures posted by OP only. No need to download retweets from other people.

**Comment by Jules-WinnfieldX** [comment]
Yea, any big social media I'm not going to support. You are better off looking elsewhere for that.
