### ISSUE TITLE
downloader hangs and does not skip past file(s) with issues

### ISSUE THREAD

**Issue by scroguard** [Jules-WinnfieldX/CyberDropDownloader#878]
**Describe the bug**
Recently I've run into an issue where a file will not download. Eventually the script will run into 2 files like this and then it gets stuck in a permanent loop. I have tried adjusting the timeout settings, etc. and have been unable to find a way around this issue. It's occured on the last 3 versions of Cyberdrop-DL.

**To Help Reproduce**
Steps to help reproduce the behavior:
1. Start the script and have it start downloading files.
2. Eventually a file will get hung up. When this occurs the script just sits and continuously retries the same file over and over. Eventually another one will occur and once you reach your number of max simultaneous downloads, the entire thing grinds to a halt. I've tried letting it sit for 24 hours or more to see if it would eventually move on. Unfortunately this doesn't work either.

I'm attaching a log file from when this occured in 5.2.25. I updated to 5.2.26 and it's still occuring.

Debian Linux 12 with all latest updates applied
Cyberdrop 5.2.26, but has occured on multiple previous versions.

[downloader.log](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/14949525/downloader.log)

![image](https://github.com/Jules-WinnfieldX/CyberDropDownloader/assets/74786005/feacbdb3-7784-487e-b913-ef136b5f83ee)

**Comment by Jules-WinnfieldX** [comment]
Coomer has been like this lately. 

CDL is programmed to skip on failure, and after 10 retries _when no new data has been downloaded._

What's happening is that some data is being downloaded every attempt, and hence, the retry count is never increasing. The files are downloading, just very very slowly. 

I don't know what a good solution for you would be.

**Comment by scroguard** [comment]
thank you for the explanation, it makes sense. it's frustrating that coomer doesn't just kill the download vs. being unbearably slow.
