### ISSUE TITLE
[BUG] Unsupported links not being sent to Jdownloader

### ISSUE THREAD

**Issue by Sur3nix** [Jules-WinnfieldX/CyberDropDownloader#879]
Unsupported links are not being sent to JDownloader. Program either skips them in general and goes straight to downloading each thing on each posts(Kemono) or it detects it but labels it as a non file extension  link and causes it to be labeled as a scrap failures.
Settings.yaml config   send_unsupported_to_jdownloader: true and authentication information for jdownloader is set within the config file also.
 
**Screenshots**
![Screenshot 2024-04-12 102607](https://github.com/Jules-WinnfieldX/CyberDropDownloader/assets/154576864/04a5322c-f74f-415e-8333-6d8ade0b96e3)

**Setup Information**
 - OS: [Windows 10]
 - Cyberdrop Downloader Version # Latest

**Downloader.log file**
[downloader.log](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/14961608/downloader.log)

**Comment by Jules-WinnfieldX** [comment]
5.2.28 fixes this.
