### ISSUE TITLE
[BUG]Download failed

### ISSUE THREAD

**Issue by DDOOKBAEKI** [Jules-WinnfieldX/CyberDropDownloader#88]
I put links in URLs.txt and launched Start Windows.bat, but download failed. 
Sorry I don't know about programming, so I only can attach cmd messages when it failed. 

C:\Windows\system32>setlocal EnableDelayedExpansion

C:\Windows\system32>pip install --user --upgrade cyberdrop-dl
Requirement already satisfied: cyberdrop-dl in c:\users\ljj\appdata\roaming\python\python310\site-packages (2.8.1)
Requirement already satisfied: colorama in c:\users\ljj\appdata\roaming\python\python310\site-packages (from cyberdrop-dl) (0.4.4)
Requirement already satisfied: requests in c:\users\ljj\appdata\roaming\python\python310\site-packages (from cyberdrop-dl) (2.27.1)
Requirement already satisfied: aiofiles in c:\users\ljj\appdata\roaming\python\python310\site-packages (from cyberdrop-dl) (0.8.0)
Requirement already satisfied: nest-asyncio in c:\users\ljj\appdata\roaming\python\python310\site-packages (from cyberdrop-dl) (1.5.4)
Requirement already satisfied: aiohttp in c:\users\ljj\appdata\roaming\python\python310\site-packages (from cyberdrop-dl) (3.8.1)
Requirement already satisfied: gofile-client in c:\users\ljj\appdata\roaming\python\python310\site-packages (from cyberdrop-dl) (1.0.0)
Requirement already satisfied: yarl in c:\users\ljj\appdata\roaming\python\python310\site-packages (from cyberdrop-dl) (1.7.2)
Requirement already satisfied: certifi in c:\users\ljj\appdata\roaming\python\python310\site-packages (from cyberdrop-dl) (2021.10.8)
Requirement already satisfied: tqdm in c:\users\ljj\appdata\roaming\python\python310\site-packages (from cyberdrop-dl) (4.63.1)
Requirement already satisfied: Scrapy in c:\users\ljj\appdata\roaming\python\python310\site-packages (from cyberdrop-dl) (2.6.1)
Requirement already satisfied: sanitize-filename in c:\users\ljj\appdata\roaming\python\python310\site-packages (from cyberdrop-dl) (1.2.0)
Requirement already satisfied: aiosignal>=1.1.2 in c:\users\ljj\appdata\roaming\python\python310\site-packages (from aiohttp->cyberdrop-dl) (1.2.0)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\users\ljj\appdata\roaming\python\python310\site-packages (from aiohttp->cyberdrop-dl) (6.0.2)
Requirement already satisfied: frozenlist>=1.1.1 in c:\users\ljj\appdata\roaming\python\python310\site-packages (from aiohttp->cyberdrop-dl) (1.3.0)
Requirement already satisfied: charset-normalizer<3.0,>=2.0 in c:\users\ljj\appdata\roaming\python\python310\site-packages (from aiohttp->cyberdrop-dl) (2.0.12)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in c:\users\ljj\appdata\roaming\python\python310\site-packages (from aiohttp->cyberdrop-dl) (4.0.2)
Requirement already satisfied: attrs>=17.3.0 in c:\users\ljj\appdata\roaming\python\python310\site-packages (from aiohttp->cyberdrop-dl) (21.4.0)
Requirement already satisfied: idna>=2.0 in c:\users\ljj\appdata\roaming\python\python310\site-packages (from yarl->cyberdrop-dl) (3.3)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\ljj\appdata\roaming\python\python310\site-packages (from requests->cyberdrop-dl) (1.26.9)
Requirement already satisfied: zope.interface>=4.1.3 in c:\users\ljj\appdata\roaming\python\python310\site-packages (from Scrapy->cyberdrop-dl) (5.4.0)
Requirement already satisfied: itemloaders>=1.0.1 in c:\users\ljj\appdata\roaming\python\python310\site-packages (from Scrapy->cyberdrop-dl) (1.0.4)
Requirement already satisfied: lxml>=3.5.0 in c:\users\ljj\appdata\roaming\python\python310\site-packages (from Scrapy->cyberdrop-dl) (4.8.0)
Requirement already satisfied: PyDispatcher>=2.0.5 in c:\users\ljj\appdata\roaming\python\python310\site-packages (from Scrapy->cyberdrop-dl) (2.0.5)
Requirement already satisfied: tldextract in c:\users\ljj\appdata\roaming\python\python310\site-packages (from Scrapy->cyberdrop-dl) (3.2.0)
Requirement already satisfied: itemadapter>=0.1.0 in c:\users\ljj\appdata\roaming\python\python310\site-packages (from Scrapy->cyberdrop-dl) (0.5.0)
Requirement already satisfied: pyOpenSSL>=16.2.0 in c:\users\ljj\appdata\roaming\python\python310\site-packages (from Scrapy->cyberdrop-dl) (22.0.0)
Requirement already satisfied: queuelib>=1.4.2 in c:\users\ljj\appdata\roaming\python\python310\site-packages (from Scrapy->cyberdrop-dl) (1.6.2)
Requirement already satisfied: parsel>=1.5.0 in c:\users\ljj\appdata\roaming\python\python310\site-packages (from Scrapy->cyberdrop-dl) (1.6.0)
Requirement already satisfied: cssselect>=0.9.1 in c:\users\ljj\appdata\roaming\python\python310\site-packages (from Scrapy->cyberdrop-dl) (1.1.0)
Requirement already satisfied: setuptools in c:\python310\lib\site-packages (from Scrapy->cyberdrop-dl) (58.1.0)
Requirement already satisfied: service-identity>=16.0.0 in c:\users\ljj\appdata\roaming\python\python310\site-packages (from Scrapy->cyberdrop-dl) (21.1.0)
Requirement already satisfied: w3lib>=1.17.0 in c:\users\ljj\appdata\roaming\python\python310\site-packages (from Scrapy->cyberdrop-dl) (1.22.0)
Requirement already satisfied: Twisted>=17.9.0 in c:\users\ljj\appdata\roaming\python\python310\site-packages (from Scrapy->cyberdrop-dl) (22.2.0)
Requirement already satisfied: protego>=0.1.15 in c:\users\ljj\appdata\roaming\python\python310\site-packages (from Scrapy->cyberdrop-dl) (0.2.1)
Requirement already satisfied: cryptography>=2.0 in c:\users\ljj\appdata\roaming\python\python310\site-packages (from Scrapy->cyberdrop-dl) (36.0.2)
Requirement already satisfied: cffi>=1.12 in c:\users\ljj\appdata\roaming\python\python310\site-packages (from cryptography>=2.0->Scrapy->cyberdrop-dl) (1.15.0)
Requirement already satisfied: jmespath>=0.9.5 in c:\users\ljj\appdata\roaming\python\python310\site-packages (from itemloaders>=1.0.1->Scrapy->cyberdrop-dl) (1.0.0)
Requirement already satisfied: six>=1.6.0 in c:\users\ljj\appdata\roaming\python\python310\site-packages (from parsel>=1.5.0->Scrapy->cyberdrop-dl) (1.16.0)
Requirement already satisfied: pyasn1-modules in c:\users\ljj\appdata\roaming\python\python310\site-packages (from service-identity>=16.0.0->Scrapy->cyberdrop-dl) (0.2.8)
Requirement already satisfied: pyasn1 in c:\users\ljj\appdata\roaming\python\python310\site-packages (from service-identity>=16.0.0->Scrapy->cyberdrop-dl) (0.4.8)
Requirement already satisfied: twisted-iocpsupport<2,>=1.0.2 in c:\users\ljj\appdata\roaming\python\python310\site-packages (from Twisted>=17.9.0->Scrapy->cyberdrop-dl) (1.0.2)
Requirement already satisfied: incremental>=21.3.0 in c:\users\ljj\appdata\roaming\python\python310\site-packages (from Twisted>=17.9.0->Scrapy->cyberdrop-dl) (21.3.0)
Requirement already satisfied: typing-extensions>=3.6.5 in c:\users\ljj\appdata\roaming\python\python310\site-packages (from Twisted>=17.9.0->Scrapy->cyberdrop-dl) (4.1.1)
Requirement already satisfied: constantly>=15.1 in c:\users\ljj\appdata\roaming\python\python310\site-packages (from Twisted>=17.9.0->Scrapy->cyberdrop-dl) (15.1.0)
Requirement already satisfied: hyperlink>=17.1.1 in c:\users\ljj\appdata\roaming\python\python310\site-packages (from Twisted>=17.9.0->Scrapy->cyberdrop-dl) (21.0.0)
Requirement already satisfied: Automat>=0.8.0 in c:\users\ljj\appdata\roaming\python\python310\site-packages (from Twisted>=17.9.0->Scrapy->cyberdrop-dl) (20.2.0)
Requirement already satisfied: requests-file>=1.4 in c:\users\ljj\appdata\roaming\python\python310\site-packages (from tldextract->Scrapy->cyberdrop-dl) (1.5.1)
Requirement already satisfied: filelock>=3.0.8 in c:\users\ljj\appdata\roaming\python\python310\site-packages (from tldextract->Scrapy->cyberdrop-dl) (3.6.0)
Requirement already satisfied: pycparser in c:\users\ljj\appdata\roaming\python\python310\site-packages (from cffi>=1.12->cryptography>=2.0->Scrapy->cyberdrop-dl) (2.21)

C:\Windows\system32>FOR /F %p in ('where pip') do (
set part2=%p
 set part3=!part2:pip.exe=!
 set part4=!part3:Local\Programs=Roaming!
 path !Part4!;!part3!;!path!
)

C:\Windows\system32>(
set part2=C:\Python310\Scripts\pip.exe
 set part3=!part2:pip.exe=!
 set part4=!part3:Local\Programs=Roaming!
 path !Part4!;!part3!;!path!
)

C:\Windows\system32>echo C:\Python310\Scripts\;C:\Python310\Scripts\;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\Bandizip\;C:\Program Files\dotnet\;C:\Python310;C:\Python310\Scripts;C:\Users\ljj\AppData\Local\Microsoft\WindowsApps;C:\Users\ljj\AppData\Local\atom\bin
C:\Python310\Scripts\;C:\Python310\Scripts\;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\Bandizip\;C:\Program Files\dotnet\;C:\Python310;C:\Python310\Scripts;C:\Users\ljj\AppData\Local\Microsoft\WindowsApps;C:\Users\ljj\AppData\Local\atom\bin

**Comment by Jules-WinnfieldX** [comment]
This isn't a failure message, there's most likely a message that was directly underneath that that was "press any key to continue", if I'm right, press any key.

**Comment by DDOOKBAEKI** [comment]
Then "'cyberdrop-dl' is not recognized as an internal or external command" message is occurred..

**Comment by Jules-WinnfieldX** [comment]
I'd recommend uninstalling python, and reinstalling, make sure to select the "add python to path" checkbox during installation.
