### ISSUE TITLE
[BUG] - Size Reporting On Large Drives

### ISSUE THREAD

**Issue by trikki69** [Jules-WinnfieldX/CyberDropDownloader#881]
When I make an attempt to download, the URLs file is checked then Cyberdrop Downloader returns "skipped by config 5839 files" and exits.
I have checked the logs and it's reporting insufficient space... I have nearly 6TB (terabytes) of space available on the target drive.

If I go into "Edit Global Values" then "Edit General Settings" and then change the 5GB (gigabyte) "Required Free Space" limit to 1GB (gigabyte) the downloads work fine. Looks like something is going on with the TB/GB size reporting in the "Required Free Space" field.

Using Ubuntu 22.04 headless on proxmox saving to external truenas array.
Using version 5.2.26 of Cyberdrop Downloader
I have attached a screenshot of my disks to show 5.7TB free.

Thanks for all the effort you put in to this app - it's greatly appreciated!

![scrp01](https://github.com/Jules-WinnfieldX/CyberDropDownloader/assets/77904636/38b73f3d-c2ec-4f63-87bc-e7a2cf0e2109)

Is 5GB of space required on all drives? I just noticed my LVM drive is 4.7GB, could this be the problem?

**Comment by Jules-WinnfieldX** [comment]
I'd need to see the downloader.log, but the program checks free space for the set download directories parent folder. 

https://github.com/Jules-WinnfieldX/CyberDropDownloader/blob/9a16a4f92fccfab96a18b84039ff645dd908ccbd/cyberdrop_dl/managers/download_manager.py#L68

It's likely your target drive you are talking about, isn't actually set as such in CDL. Or it's just funky linux things happening.

**Comment by trikki69** [comment]
Log file attached
[downloader.log](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/14975781/downloader.log)

**Comment by Jules-WinnfieldX** [comment]
I'd recommend trying to download to a subfolder of `/home/*********/scrape-store`

CDL will look at the free space of `/home/*********`

Which likely isn't mapped, and hence is seen as not sufficient space. But I'm just spit balling

**Comment by trikki69** [comment]
Yes, that worked - looks like CDL is looking at my home directory for free space available, as soon as I added another directory within the configured download directory it worked with the "required free space" setting at the default of 5GB.

Thanks for your input.
