### ISSUE TITLE
[BUG] DDoS-guard cookie selection is no longer available

### ISSUE THREAD

**Issue by baccccccc** [Jules-WinnfieldX/CyberDropDownloader#885]
I recently started getting 403 errors during scrape and download on what looks like perfectly good jpg4.su links. (Example: `https://jpg4.su/a/69nqE`, mildly NSFW.) The link works in browser, but CDL repeatedly receives a 403.

I suspect DDoS guard, like it's been for other sites in the past. I recall that previously there was an option to add/extract DDoS-guard cookies from the browser, somewhere in the Authentication menu. I can no longer find this option.

Is it gone or is my memory faulting me?

**Comment by baccccccc** [comment]
ok, maybe it's jpg-fish having issues, or it's some new type of highly sophisticated ddos-guard. I just checked again, and now I'm getting a 403 even in the browser.

nevertheless, original question stands. Is cookie extraction gone?

**Comment by Jules-WinnfieldX** [comment]
It isn't DDOS-Guard related.

**Comment by Jules-WinnfieldX** [comment]
But yes, it was removed in favor of flaresolverr.
