### ISSUE TITLE
[FEATURE] improve handling for unexpected download errors

### ISSUE THREAD

**Issue by baccccccc** [Jules-WinnfieldX/CyberDropDownloader#889]
This is a follow up to #791. I just rerun download on the same forum thread and noticed the following.

1. Overall, download *does* complete successfully. (So, #791 is indeed _fixed_ as confirmed previously.)
2. The "Download Failures" section in the final result message includes `Download Failures (Unknown): 3` (among other things which are expected).
3. There is **nothing** corresponding to those "unknown failures" in `Download_Error_URLs.csv`. (Other failures, such as 404's, get reported correctly.)
4. Examining `downloader.log` reveals the same three URLs from #791 with the same old error `UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte`.

So, perhaps, they should be recorded in `Download_Error_URLs.csv` after all?

In general, I would expect that every time there's a failure, the URL gets recorded to either `Download_Error_URLs.csv` or `Scrape_Error_URLs.csv`, even if we cannot handle it gracefully and hence merely list it as generic failure _("see log for details")._

**Comment by Jules-WinnfieldX** [comment]
5.2.44 should handle this, as well as Invalid Content Type and DDOS-Guard failures
