### ISSUE TITLE
[FEATURE] Limit on the number of files

### ISSUE THREAD

**Issue by kaynshae** [Jules-WinnfieldX/CyberDropDownloader#891]
Hello, I'm downloading data from simpcity. But I miss the file limit wildly, that is, if, for example, more than 50 photos and 30 videos are uploaded to folder n, then it no longer uploads anything to this folder.

I send 100-200 links from posts to URLs, and %name% (SimpCity) folders are created, so add a file limit to this folder. And not in general to the Downloads folder.

It's just that there is already a limit on file size, on file type, but not on number. Thank you

**Comment by Jules-WinnfieldX** [comment]
CDL has never had a file limit. 

Not sure what you mean by "then it no longer uploads anything to this folder"

**Comment by kaynshae** [comment]
"CDL has never had a file limit." that's what I said. I apologize for possible errors, I use google translate.

I will explain with an example what a limit on the number of files means in my understanding.
I wrote a parser of new posts with simpcity. I have 100-200 links uploaded in the format "https://simpcity.su/threads /**/post-**". I have a file size limit and scrape_single_forum_post: true, and CDL also downloads only photos and videos.

But there are times when in some post you will come across an 80+ GB bunker archive with 800 photos and 200 videos, although I do not need it. I would like to see a function to limit the number of files, that is, I set, for example, a limit of 50 photos and 10 videos, CDL starts downloading, for example, it uploaded 50/800 photos and 7/200 videos, it stops downloading photos (i.e. all photo files start to skip) and downloads only videos, when it downloads 10, then it reached the set limits and discards this link, then goes to the next one.

**Comment by Jules-WinnfieldX** [comment]
I don't particularly understand the need for this.

**Comment by kaynshae** [comment]
Look, I need new material from different models with SimpCity, I upload links, and he uploaded 104 GB(5000 photos and 500 videos), while one folder took over 45 GB (116 videos) of this, another folder 1900 photos. That is, 2 folders out of 241 take up half the space and almost half the photos. At the same time, the main goal is new material, different, and not a bunch of the same thing
