### ISSUE TITLE
[FEATURE] UI Indicator For Which Site A File Is Downloading From/An Indicator For Which Site Is Rate Limited

### ISSUE THREAD

**Issue by thorman123** [Jules-WinnfieldX/CyberDropDownloader#893]
**Is your feature request related to a problem? Please describe.**
When I'm downloading a large URL list, sometimes I get files that are downloading in single digit KB/s. It would be nice to see which site I am downloading that file from to see which site is rate limiting me, or just find out which site is rate limited 

**Describe the solution you'd like**
A way in the UI for me to see either one of 2 things, which site is rate limiting me, or which site I am currently downloading from.

**Comment by Jules-WinnfieldX** [comment]
It'll likely always be Coomer, and 5.2.52 will add this.
