### ISSUE TITLE
[FEATURE][Bug] When the Tools get started -> Directly start downloading 

### ISSUE THREAD

**Issue by timgahmen** [Jules-WinnfieldX/CyberDropDownloader#894]
(First off all thanks for this absolutly amazing tool! I use it very often and it is really a good help and very good codet !  👍
⭐️⭐️⭐️⭐️⭐️

But ..... maybe I have not seen the option:

**Is your feature request related to a problem? Please describe.**
It would be absolutlygreat if the Tool would (like before) directly start do download the files when the exe was started.

It is good that there could be nor more options set, BUT sadly I forgot the in like 60 % counting of my useage of the tool,
"start in tool again the second time" = the tool NOT started downloading 
the toll is still in the "start position" and waiting for another start command ..... and this to see after hours to come back ? 😉

**Describe the solution you'd like**
A clear and concise description of what you want to happen:
An option that the tool starts directly after opening the tool 

**Additional context**
thanks again fpr this great tool and your time

**Comment by Jules-WinnfieldX** [comment]
https://jules-winnfieldx.gitbook.io/cyberdrop-dl/reference/cli-arguments

--download
