### ISSUE TITLE
[FEATURE] Fetch favorite links from the coomer API and append them to URLs.txt

### ISSUE THREAD

**Issue by perpetuallyhorni** [Jules-WinnfieldX/CyberDropDownloader#895]
**Is your feature request related to a problem? Please describe.**
Not really, it improves UX but I wouldn't call it a problem.

**Describe the solution you'd like**
When using the coomer API to fetch favorites, the API returns a json object without URLs in it. 
I've made [this](https://github.com/perpetuallyhorni/coomer-favlink-generator) small pip package to parse the json and output a txt with the formatted links, ready to copy and paste to the URLs.txt file. 
I'd like to collaborate to CDL by expanding and integrating this functionality into CDL itself as follows:
Provide option in CDL to fetch user's favorites from the coomer API, process the json to extract links and append the links to the URLs.txt file (I'm not sure if CDL does duplicate detection but it would be probably needed).

**Additional context**
I can code the missing functionality and integrate the whole thing into CDL but my availability at the moment it's not the best, so it would likely take a few weeks at the very least for me to do it. 
I would like to know if Jules considers this worthy of adding or not, after all, the package I made already does this, integrating it into CDL really just streamlines the user experience.

**Comment by Jules-WinnfieldX** [comment]
This unfortunately seems out of scope in the project currently
