### ISSUE TITLE
[FEATURE] Option to only download videos or only download photos

### ISSUE THREAD

**Issue by CodexScript** [Jules-WinnfieldX/CyberDropDownloader#896]
**Is your feature request related to a problem? Please describe.**
For many pages on forums such as SimpCity, there are photo dumps which I am not interested in downloading, but CyberDropDownloader will download all linked files in the topic. I often download everything, use the sort functionality of CDD, and then delete all of the pictures leaving me with only videos.

**Describe the solution you'd like**
A config option such as: `downloads_type` that can be one of `photo`, `video`, or `all`.

**Additional context**
You can determine the media type of a file before downloading it by issuing a HEAD request to the download server. Based on the mimetype returned in the `Content-Type` response header, you can determine the media type of the download.

**Comment by Jules-WinnfieldX** [comment]
https://jules-winnfieldx.gitbook.io/cyberdrop-dl/reference/configuration-options/settings#ignore-options

This exists already
