### ISSUE TITLE
[BUG] Cli arguments for log files are not working.

### ISSUE THREAD

**Issue by the444xg** [Jules-WinnfieldX/CyberDropDownloader#897]
All arguments that sets custom log filenames are not working.
I tried combinations with and without --config Name and --config-file. Also tried removing the lines from the default settings file. No matter what it always use the default filename values.

Unless the wiki is wrong about "Anything input as a CLI argument will take priority over config values."  this looks like a bug.

These are the ones that i tested:
--main-log-filename
--last-forum-post-filename
--unsupported-urls-filename
--download-error-urls-filename
--scrape-error-urls-filename

**Setup Information**
 - OS: Linux
 - Cyberdrop Downloader Version  5.2.53

**Comment by Jules-WinnfieldX** [comment]
Fixed in 5.2.54
