### ISSUE TITLE
I can't figure out how to set up my downloads

### ISSUE THREAD

**Issue by googleitffs** [Jules-WinnfieldX/CyberDropDownloader#898]
Hi. Every time I download something, it creates a separate "Downloads" folder in my "Downloads" folder with 2 additional subfolders inside it. And additional "AppData" and "Old Files" folders. I just want to download files into my "Downloads" folder without any additional folders. How do I do that? I tried editing the config in "C:\Users\BigBrother\AppData\Local\Programs\Python\Python312\Scripts\AppData\Configs" but with no success. I'm running on Windows.

**Comment by Jules-WinnfieldX** [comment]
You are doing things incorrectly. All those files/folders are necessary. They need to exist somewhere, they'll be created wherever you run the program. So find a place you want them and stick with it. You can change the downloads folder after that in the settings.

**Comment by googleitffs** [comment]
> You are doing things incorrectly. All those files/folders are necessary. They need to exist somewhere, they'll be created wherever you run the program. So find a place you want them and stick with it. You can change the downloads folder after that in the settings.

It gets created anew for each folder I run the program in. And I can't figure out how to change the paths in the settings as it apparently only supports relative paths?

**Comment by Jules-WinnfieldX** [comment]
As I said, you need to have a central folder for CDL, and no, it isn't only relative.
