### ISSUE TITLE
Need some clarification on how to run the file on Mac?

### ISSUE THREAD

**Issue by johnbollock** [Jules-WinnfieldX/CyberDropDownloader#9]
Sorry, I've never really used something like this before. I've put the links in URLs.txt but nothing seems to happen when I then double click Start.sh. I've tried doing the chmod +x but I think I'm doing something wrong as the file just seems to open as a text file. 

Thanks

**Comment by Jules-WinnfieldX** [comment]
https://apple.stackexchange.com/a/322693

Try these steps and let me know if you get it working.

**Comment by johnbollock** [comment]
That did it! Thanks so much :)
