### ISSUE TITLE
Error 443 [BUG]

### ISSUE THREAD

**Issue by Gwilwilethal** [Jules-WinnfieldX/CyberDropDownloader#90]
Hi,

I am getting this error running cyberdrop downloader:

Seems like an error 443.

Is this on my end?

![1](https://user-images.githubusercontent.com/102547195/160458242-a0c44ed0-ec59-4100-9b07-5f4d249ebc3f.PNG)

**Comment by Jules-WinnfieldX** [comment]
Make sure your computer is up to date, But this is either on your end or on Cyberdrops

**Comment by Gwilwilethal** [comment]
I will try that!! Thank you!

**Comment by Gwilwilethal** [comment]
This is resolved!

It was trying to use python 39 instead of 310!
