### ISSUE TITLE
Scrape content from Kemono/Discord [FEATURE]

### ISSUE THREAD

**Issue by Kafajesty** [Jules-WinnfieldX/CyberDropDownloader#900]
Is it possible to make the tool scrape the contents of Kemono [Discord]?

**Comment by Jules-WinnfieldX** [comment]
It does already

https://jules-winnfieldx.gitbook.io/cyberdrop-dl/reference/supported-websites

**Comment by Kafajesty** [comment]
> It does already

The tool does not scrape discord service, for example https://kemono.su/discord/server/965498627483131915

**Comment by Jules-WinnfieldX** [comment]
It does, if you'd actually read the page, you'd realize you have to give it a specific channel..
https://kemono.su/discord/server/965498627483131915#966335860742193182
