### ISSUE TITLE
[FEATURE] Sort errors alphabetically

### ISSUE THREAD

**Issue by baccccccc** [Jules-WinnfieldX/CyberDropDownloader#901]
This obviously has as low a priority as it can be, but it would be neat if we could sort both the current error list and the summary alphabetically. I.e., 403 goes before 404, and any textual messages such as "failed login" go after that.

![image](https://github.com/Jules-WinnfieldX/CyberDropDownloader/assets/107458411/ce5d3841-ed92-42f8-9280-870b2873b972)

![image](https://github.com/Jules-WinnfieldX/CyberDropDownloader/assets/107458411/a8a85417-a1ef-4fc1-b026-792d9f566806)

Rationale: it would be easier to glance if they are always in a consistent order.

**Comment by Jules-WinnfieldX** [comment]
Honestly, fair. It probably would be easy

**Comment by Jules-WinnfieldX** [comment]
I believe this is added now, but haven't confirmed yet.

**Comment by baccccccc** [comment]
nope :(

![image](https://github.com/Jules-WinnfieldX/CyberDropDownloader/assets/107458411/059ce44e-0040-422f-af83-526b2da7e9f5)

(needless to say, it's the latest version upgraded today.)

**Comment by Jules-WinnfieldX** [comment]
Oh yea those I cannot do. I did the final outputs. But ordering task bars is something that isn't supported in rich. I've asked for it to be a feature added, but it doesn't seem like it's a high priority

**Comment by baccccccc** [comment]
> I did the final outputs.

ok, then I think you succeeded.

![image](https://github.com/Jules-WinnfieldX/CyberDropDownloader/assets/107458411/f3964e53-bd6e-43c3-b6c6-71cb0a628cdc)

but yeah, if/when the dependency gets the required features, please make use of it. Thanks!
