### ISSUE TITLE
[BUG] Haven't used this in a while, came back and nothing works

### ISSUE THREAD

**Issue by wdos3** [Jules-WinnfieldX/CyberDropDownloader#902]
**Describe the bug**
Unhandled exception; stopping loop: 'Task exception was never retrieved'
Traceback (most recent call last):
  File "C:\Users\Username\AppData\Roaming\Python\Python39\site-packages\cyberdrop_dl\scraper\scraper.py", line 323, in
map_urls
    scrape_item: ScrapeItem = await self.manager.queue_manager.url_objects_to_map.get()
  File "C:\Program Files\Python39\lib\asyncio\queues.py", line 166, in get
    await getter
RuntimeError: Task <Task pending name='Task-54' coro=<ScrapeMapper.map_urls() running at
C:\Users\Username\AppData\Roaming\Python\Python39\site-packages\cyberdrop_dl\scraper\scraper.py:323>> got Future <Future
pending> attached to a different loop

**To Reproduce**
Just run the file.
Currently, the URL file only has bunker links.

**Screenshots**

**Setup Information**
 - OS: Windows 11
 - Cyberdrop Downloader Version: Newest Ver

**Downloader.log file**
I didn't get one.

**Comment by Jules-WinnfieldX** [comment]
You aren't on the newest version.  You need python 3.11 or newer.
