### ISSUE TITLE
[BUG] `'NoneType' object has no attribute 'get'` on cyberfile

### ISSUE THREAD

**Issue by baccccccc** [Jules-WinnfieldX/CyberDropDownloader#903]
here are two URLs that show this errror
```
https://cyberfile.me/fsgW, See Log for Details
https://cyberfile.me/bg81, See Log for Details
```
both seem to be working in browser. (NSFW)

(Although thumbnails are a bit weird looking, not sure if it's normal for cyberfile.)

but CDL does not like them.
```
INFO     : 2024-05-18 09:16:23,327 : utilities.py:103 : Scrape Starting: https://cyberfile.me/fsgW
ERROR    : 2024-05-18 09:16:24,771 : utilities.py:103 : Scrape Failed: https://cyberfile.me/fsgW ('NoneType' object has no attribute 'get')
ERROR    : 2024-05-18 09:16:24,807 : utilities.py:103 : Traceback (most recent call last):
  File "C:\Users\<username>\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\cyberdrop_dl\utils\utilities.py", line 63, in wrapper
    return await func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\<username>\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\cyberdrop_dl\scraper\crawlers\cyberfile_crawler.py", line 159, in handle_content_id
    html_download_text = file_button.get("onclick")
                         ^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'

INFO     : 2024-05-18 09:16:24,810 : utilities.py:103 : Scrape Finished: https://cyberfile.me/fsgW

...

INFO     : 2024-05-18 09:16:24,810 : utilities.py:103 : Scrape Starting: https://cyberfile.me/bg81
ERROR    : 2024-05-18 09:16:26,194 : utilities.py:103 : Scrape Failed: https://cyberfile.me/bg81 ('NoneType' object has no attribute 'get')
ERROR    : 2024-05-18 09:16:26,206 : utilities.py:103 : Traceback (most recent call last):
  File "C:\Users\<username>\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\cyberdrop_dl\utils\utilities.py", line 63, in wrapper
    return await func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\<username>\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\cyberdrop_dl\scraper\crawlers\cyberfile_crawler.py", line 159, in handle_content_id
    html_download_text = file_button.get("onclick")
                         ^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'

INFO     : 2024-05-18 09:16:26,207 : utilities.py:103 : Scrape Finished: https://cyberfile.me/bg81
```

**Comment by baccccccc** [comment]
some browser extensions, such as Ant video downloader, somehow manage to extract the download link. Although I'm not sure about how exactly they do this.

for the reference, here are the links extracted by the extension:

```
https://p1.cyberfile.me/fsgW/plug_intro.mp4?download_token=dfbfa0e484126c163c18eff6b1879564c831649d58ebef639374a0d2475c35b0
https://p1.cyberfile.me/bg81/ripped_latexpants.mp4?download_token=0feb48f4c31cbe17b3997693b646f71802d70bc391ba3fe96f47fbef21644e38
```
(the token is likely unique to my machine or IP, so might not work for you, but you get the idea.)

that said, it took me 3-4 retries to get a working link with the extension. For some reason, it sometimes produced a link to html file (which won't even download) and sometimes a working mp4 link. So maybe it's just cybefile having hard times. They have a honest warning at the top of the page after all.

anyway, if you don't feel like fixing it, I don't have a big problem with it. It's not the first time I have seen this problem, so I wanted to report it. But it does not seem to happen very often, so I'm fine with downloading a file or two using browser extension.

but maybe think of how you could improve error reporting if this becomes a recurring theme.

thanks for your work as always!

**Comment by Jules-WinnfieldX** [comment]
So those extensions are dragging the link out of the video player itself, which is loaded via Javascript. CDL can't load that portion of the page. 

The only reason I've been able to scrape the site at all is for some reason the script to create the download button on the page contains all the necessary information CDL needs to extract. Loading the page without JS enabled (try it if you haven't, would recommend a disable javascript browser extension) essentially loads a completely blank page. 

In cases like this, the download link doesn't appear because whoever uploaded said files restricted the permissions on it to view only, no downloads, hence no download button.

**Comment by baccccccc** [comment]
> In cases like this, the download link doesn't appear because whoever uploaded said files restricted the permissions on it to view only, no downloads, hence no download button.

ok, so if that's standard (expected) behavior for this website, maybe all we need is a more explicit error message. Not “see log for details” but something like “download disabled by uploader”.

**Comment by Jules-WinnfieldX** [comment]
5.3.27 will make this throw a 422 HTTP code.
