### ISSUE TITLE
[FEATURE] Scrape for content breakdown.

### ISSUE THREAD

**Issue by jamr1167** [Jules-WinnfieldX/CyberDropDownloader#906]
Would it be possible to add a feature or command line option that would scrape a site and return the breakdown of what content is available such as how many videos, images, or other content by type.  A bonus would be if it could be sorted into previously downloaded and not-downloaded.

**Comment by Jules-WinnfieldX** [comment]
This seems like a lot of traffic use, for very minimal upside. I won't be writing this personally, but someone else can and I'll look over the pull request.
