### ISSUE TITLE
[FEATURE] Expand the "Retry Failed Downloads"  or "Download" to process downloads with completed set to 0

### ISSUE THREAD

**Issue by bewbylover** [Jules-WinnfieldX/CyberDropDownloader#907]
**Is your feature request related to a problem? Please describe.**
I had a few files as partials (*.part) in the download folder.  Some were old and the links were purged with reasonings in the response, but some were still valid.  I looked at the DB and the completed field on a number of them is set to 0, but they don't resume if the application is restarted and "Retry Failed Downloads" or "Download" options are chosen.  Yet if I load the referer field I can access the files and manually download them.  In my examples it was an imgur and pixeldrain link that were still valid but not resumed.  If there is something doing this let me know I can share my DB or whatever would help.

**Describe the solution you'd like**
As part of either action have the application loop through the incomplete downloads and attempt to resume them.

**Additional context**
N/A

**Comment by Jules-WinnfieldX** [comment]
I'd need to see the cyberdrop.db file and an example link where this is the case

**Comment by bewbylover** [comment]
DB: https://drive.google.com/file/d/155ivJNMaFwxrrhN7x1_dyQtxNYMftal5/view?usp=drive_link

https://pixeldrain.com/api/file/HZWn9E4Z?download

I get the following error, but changing the link to https://pixeldrain.com/u/HZWn9E4Z lets me download it:
{"success":false,"value":"file_rate_limited_captcha_required","message":"We have detected the use of hotlinking for this file. Hotlinking is only supported when either the uploader or the downloader has a paid subscription"}

I couldn't find the image, but here is a different one on pixhost:
https://pixhost.to/show/718/396885897_playmate_9.jpg

There are 1538 other examples, though some of them have been removed and are no longer valid.

Let me know what else would be helpful.

**Comment by Jules-WinnfieldX** [comment]
Both of those fail as expected. 

Pixeldrain even tells you why it failed. 

For the other, pixhost.to isn't a supported domain, but CDL will try to download anything with a file extension, but that link doesn't lead to a photo, it leads to a webpage.
