### ISSUE TITLE
[FEATURE]  Is there a way to download bunkr files without an extension?

### ISSUE THREAD

**Issue by SharingSpoon** [Jules-WinnfieldX/CyberDropDownloader#908]
I'm getting 
Scrape Failures:
Scrape Failures (No File Extension): 

for a bunch of files. This is correct, there is no file extension but how do I get it download anyway? I have a look through the config files and can't see anything about disallowing downloads of files with no extensions/allowing

**Comment by Jules-WinnfieldX** [comment]
Can I see the full log file?

**Comment by SharingSpoon** [comment]
INFO     : 2024-05-31 20:29:11,809 : utilities.py:103 : Starting Async Processes...
DEBUG    : 2024-05-31 20:29:11,812 : utilities.py:103 : Starting Cyberdrop-DL Process for Imported V4 Config
DEBUG    : 2024-05-31 20:29:11,812 : utilities.py:103 : Running version 5.3.24
DEBUG    : 2024-05-31 20:29:11,812 : utilities.py:103 : Using Config: Imported V4
DEBUG    : 2024-05-31 20:29:11,812 : utilities.py:103 : Using Config File: AppData\Configs\Imported V4\settings.yaml
DEBUG    : 2024-05-31 20:29:11,812 : utilities.py:103 : Using Input File: URLs.txt
DEBUG    : 2024-05-31 20:29:11,812 : utilities.py:103 : Using Download Folder: Downloads
DEBUG    : 2024-05-31 20:29:11,813 : utilities.py:103 : Using History File: AppData\Cache\cyberdrop.db
DEBUG    : 2024-05-31 20:29:11,813 : utilities.py:103 : Using Authentication: 
{
    "Forums Credentials": {
        "celebforum Credentials Provided": false,
        "f95zone Credentials Provided": false,
        "leakedmodels Credentials Provided": false,
        "nudostar Credentials Provided": false,
        "simpcity Credentials Provided": true,
        "socialmediagirls Credentials Provided": false,
        "xbunker Credentials Provided": false
    },
    "Forums XF Cookies": {
        "celebforum XF Cookie Provided": false,
        "f95zone XF Cookie Provided": false,
        "leakedmodels XF Cookie Provided": false,
        "nudostar XF Cookie Provided": false,
        "simpcity XF Cookie Provided": false,
        "socialmediagirls XF Cookie Provided": false,
        "xbunker XF Cookie Provided": false
    },
    "GoFile Provided": false,
    "Imgur Provided": false,
    "JDownloader Provided": false,
    "PixelDrain Provided": false,
    "Reddit Provided": true
}
DEBUG    : 2024-05-31 20:29:11,813 : utilities.py:103 : Using Settings: 
{
    "Download_Options": {
        "block_download_sub_folders": false,
        "disable_download_attempt_limit": false,
        "disable_file_timestamps": false,
        "include_album_id_in_folder_name": false,
        "include_thread_id_in_folder_name": false,
        "remove_domains_from_folder_names": false,
        "remove_generated_id_from_filenames": false,
        "scrape_single_forum_post": false,
        "separate_posts": false,
        "skip_download_mark_completed": false
    },
    "File_Size_Limits": {
        "maximum_image_size": 0,
        "maximum_other_size": 0,
        "maximum_video_size": 0,
        "minimum_image_size": 0,
        "minimum_other_size": 0,
        "minimum_video_size": 0
    },
    "Files": {
        "download_folder": "Downloads",
        "input_file": "URLs.txt"
    },
    "Ignore_Options": {
        "exclude_audio": false,
        "exclude_images": false,
        "exclude_other": false,
        "exclude_videos": false,
        "ignore_coomer_ads": false,
        "only_hosts": [],
        "skip_hosts": []
    },
    "Logs": {
        "download_error_urls_filename": "Download_Error_URLs.csv",
        "last_forum_post_filename": "Last_Scraped_Forum_Posts.txt",
        "log_folder": "AppData\\Configs\\Imported V4\\Logs",
        "main_log_filename": "downloader.log",
        "scrape_error_urls_filename": "Scrape_Error_URLs.csv",
        "unsupported_urls_filename": "Unsupported_URLs.txt"
    },
    "Runtime_Options": {
        "delete_partial_files": false,
        "ignore_history": false,
        "log_level": 10,
        "send_unsupported_to_jdownloader": false,
        "skip_check_for_empty_folders": false,
        "skip_check_for_partial_files": false,
        "update_last_forum_post": false
    },
    "Sorting": {
        "sort_downloads": false,
        "sort_folder": "Downloads\\Cyberdrop-DL Sorted Downloads",
        "sort_incremementer_format": " ({i})",
        "sorted_audio": "{sort_dir}/{base_dir}/Audio/{filename}{ext}",
        "sorted_image": "{sort_dir}/{base_dir}/Images/{filename}{ext}",
        "sorted_other": "{sort_dir}/{base_dir}/Other/{filename}{ext}",
        "sorted_video": "{sort_dir}/{base_dir}/Videos/{filename}{ext}"
    }
}
DEBUG    : 2024-05-31 20:29:11,813 : utilities.py:103 : Using Global Settings: 
{
    "General": {
        "allow_insecure_connections": false,
        "flaresolverr": "",
        "max_file_name_length": 95,
        "max_folder_name_length": 60,
        "proxy": "",
        "required_free_space": 5,
        "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/112.0"
    },
    "Rate_Limiting_Options": {
        "connection_timeout": 15,
        "download_attempts": 10,
        "download_delay": 0,
        "max_simultaneous_downloads": 15,
        "max_simultaneous_downloads_per_domain": 4,
        "rate_limit": 50,
        "read_timeout": 300
    },
    "UI_Options": {
        "downloading_item_limit": 5,
        "refresh_rate": 10,
        "scraping_item_limit": 5,
        "vi_mode": false
    }
}
INFO     : 2024-05-31 20:29:11,829 : utilities.py:103 : Starting UI...
INFO     : 2024-05-31 20:29:12,050 : utilities.py:103 : Scrape Starting: https://bunkr.ci/v/iB8NaSD2KI4IX
ERROR    : 2024-05-31 20:29:13,014 : utilities.py:103 : Scrape Failed: https://bunkr.ci/v/iB8NaSD2KI4IX (No File Extension)
INFO     : 2024-05-31 20:29:13,014 : utilities.py:103 : Scrape Finished: https://bunkr.sk/v/iB8NaSD2KI4IX
INFO     : 2024-05-31 20:29:13,165 : utilities.py:116 : Running Post-Download Processes For Config: Imported V4...
INFO     : 2024-05-31 20:29:13,165 : utilities.py:116 : Checking for partial downloads...
INFO     : 2024-05-31 20:29:13,311 : utilities.py:116 : There are partial downloads in the downloads folder
INFO     : 2024-05-31 20:29:13,315 : utilities.py:116 : Checking for empty folders...
INFO     : 2024-05-31 20:29:13,471 : utilities.py:103 : Printing Stats...
INFO     : 2024-05-31 20:29:13,471 : utilities.py:116 : 
Download Stats:
INFO     : 2024-05-31 20:29:13,471 : utilities.py:116 : Downloaded 0 files
INFO     : 2024-05-31 20:29:13,471 : utilities.py:116 : Previously Downloaded 0 files
INFO     : 2024-05-31 20:29:13,471 : utilities.py:116 : Skipped By Config 0 files
INFO     : 2024-05-31 20:29:13,471 : utilities.py:116 : Failed 0 files
INFO     : 2024-05-31 20:29:13,485 : utilities.py:116 : 
Scrape Failures:
INFO     : 2024-05-31 20:29:13,485 : utilities.py:116 : Scrape Failures (No File Extension): 1
INFO     : 2024-05-31 20:29:13,485 : utilities.py:116 : 
Download Failures:
INFO     : 2024-05-31 20:29:13,485 : utilities.py:103 : Checking for Program End...
INFO     : 2024-05-31 20:29:13,485 : utilities.py:103 : Checking for Updates...
INFO     : 2024-05-31 20:29:13,738 : utilities.py:103 : Closing Program...
INFO     : 2024-05-31 20:29:13,738 : utilities.py:116 : 
Finished downloading. Enjoy :)

**Comment by Jules-WinnfieldX** [comment]
The program is correct, it doesn't have a file extension. There is no forcing it past that error, if you want it, it'd be up to you to download manually.
