### ISSUE TITLE
[BUG] 'cyberdrop-dl' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by jtm666** [Jules-WinnfieldX/CyberDropDownloader#91]
For manual install I looked at another post and did a clean install of python 3.10.4 and still has the "...is not recognized as an internal.." error. 

Tried running "pip3 install --user cyberdrop-dl" with python and get the following error:

  File "<stdin>", line 1
    pip3 install --user cyberdrop-dl
         ^^^^^^^
SyntaxError: invalid syntax

I kept CyberDropDownloader-2.5.5 and it still works though.

Thanks for your contribution as always.

**Comment by Jules-WinnfieldX** [comment]
https://github.com/Jules-WinnfieldX/CyberDropDownloader/releases/download/Release/Cyberdrop_DL.V2.zip
Can you try this?

**Comment by jtm666** [comment]
> https://github.com/Jules-WinnfieldX/CyberDropDownloader/releases/download/Release/Cyberdrop_DL.V2.zip Can you try this?

It works! Takes some time to install the first time running the program but works like a charm so far, very nice! Gonna leave this thread open for now in case there's any update.

**Comment by ivantyr** [comment]
I have the same issue
however, all the requirements are already installed

This is using the V2
![image](https://user-images.githubusercontent.com/6587147/160678059-329e6874-3367-40a7-b186-48c0642902d8.png)

**Comment by jtm666** [comment]
Update: So I was testing V2 with a cyberdrop album (pics) and a bunkr album (vids), while scrapping from cyberdrop is going smoothly, scrapping from bunkr isn't working properly, it started and stopped immediately like this:

Starting scrape of https://bunkr.is/a/XXXXX
Finished scrape of https://bunkr.is/a/XXXXX

**Comment by Jules-WinnfieldX** [comment]
If you open a feature request I can look into it. For the bunkr scraping issue, I'd need to see the downloader.log after you try.

**Comment by jtm666** [comment]
> If you open a feature request I can look into it. For the bunkr scraping issue, I'd need to see the downloader.log after you try.
[downloader.log](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/8381290/downloader.log)

Here you go, all .jpg are from cyberdrop, no .mp4 from bunkr.

**Comment by jtm666** [comment]
> It hadn't finished, nor had it stopped it. It was going through a retry phase. Let it run for a while and just leave it, see if it downloads.

ok, I will keep an eye on that.

**Comment by Jules-WinnfieldX** [comment]
I'm going to reduce the time between retries in the next release. It's currently 4 seconds. Bunkr we add another 2-3s before trying to download as well.

**Comment by jtm666** [comment]
Update 2: The .mp4 are being downloaded now when the .jpg are 90% done, all is fine now I suppose :) 
Attached log for reference
[downloader.log](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/8389160/downloader.log)
