### ISSUE TITLE
[FEATURE] Scrape reddit subreddits by flare

### ISSUE THREAD

**Issue by yada-yoda** [Jules-WinnfieldX/CyberDropDownloader#911]
**Is your feature request related to a problem? Please describe.**
Trying to not have to download the full subreddit and for example if you want just the posts that are "flaired" with Memes, you'd download only the memes flair, etc. This I think would help with downloading files not needed and maybe even with the api calls?

**Describe the solution you'd like**
Download subreddits by flair - 

For example here is a url for context I tried recently that did not work (Names are just example variables):
https://www.reddit.com/r/Example2/?f=flair_name%3A%22ExampleFlairName%20%F0%9F%92%B5%22

**Additional context**
I noticed under supported websites it doesn't list anything about flairs, but didn't know if maybe this was something that could work or someone had gotten it to work.

**Comment by Jules-WinnfieldX** [comment]
I won't be adding support for this unfortunately.
