### ISSUE TITLE
[BUG] Not able to download from bunkrrr.org

### ISSUE THREAD

**Issue by Ubantos** [Jules-WinnfieldX/CyberDropDownloader#913]
I am trying to download from simpcity but it is throwing error to download on bunkrrr sites.
Eg..please check in log

I am using termux...python 3.11 and cyberdrop version 4.2.8(I cannot upgrade to latest version due to pillow wheel error so installed this version)

Attaching the downloader.log...please help...

**Comment by Ubantos** [comment]
[downloader.log](https://github.com/user-attachments/files/15644160/downloader.log)

**Comment by Jules-WinnfieldX** [comment]
I still haven't been able to get bunkrrr.org to load at all, it always redirects to a different endpoint. So not much chance I have at fixing it.

**Comment by Jules-WinnfieldX** [comment]
It isn't working because you are on 4.2.231 of CDL. You need to update. You need python 3.11 or newer

**Comment by Ubantos** [comment]
I have python 3.11 installed

**Comment by Ubantos** [comment]
![Screenshot_20240622-120921](https://github.com/Jules-WinnfieldX/CyberDropDownloader/assets/93125364/75e1e234-e9a6-45af-bc17-d307902e6401)
