### ISSUE TITLE
[FEATURE] nsfwalbum.com Support

### ISSUE THREAD

**Issue by GarethFreeman** [Jules-WinnfieldX/CyberDropDownloader#917]
**Is your feature request related to a problem?** No, just want to request for rip support.

**Describe the solution you'd like**
Ripper support for this website for their album collection.

**Additional context**
![Screenshot 2024-06-18 at 13-38-18 Erotic photos search engine](https://github.com/Jules-WinnfieldX/CyberDropDownloader/assets/86075581/a550b7a3-f884-45be-8721-114ef683744d)

**Comment by Jules-WinnfieldX** [comment]
I don't see myself adding this at the moment.
