### ISSUE TITLE
[BUG] error parsing the text 

### ISSUE THREAD

**Issue by Aliaksandr3by** [Jules-WinnfieldX/CyberDropDownloader#92]
[URL unfurl="true"]https://cyberdrop.me/a/w9jxg0Kg[/URL]

This does not understand the tag [/ URL] at the end of the line 

![image](https://user-images.githubusercontent.com/11432724/160693362-b32c92f4-3beb-4ee3-a6bd-a197a4238e36.png)

**Comment by Jules-WinnfieldX** [comment]
Try now.

**Comment by Aliaksandr3by** [comment]
I think, it is nice work.
thx
