### ISSUE TITLE
Update the User Guide to include how to get started [FEATURE]

### ISSUE THREAD

**Issue by Texster25** [Jules-WinnfieldX/CyberDropDownloader#920]
The instructions to get this program loaded and working on a Windows machine (and to get the correct version of Python up and running) were spot-on, but when it came to actually using the program to try and download something, the documentation was not complete. The reference docs have a very basic list of the options, but there are no examples of how/where to input the pages you want to download, and no explanation of how to setup the config when you want something other than the standard. 

In my case, I still have not figured out how to set it up to download the text of all posts from a user (on Kemono/Patreon) for an author I am a patron of. I limited the downloads to only Kemono, added the link to the author's page in the download aection, and initiated the download, but it only downloaded the pictures that were at the top of the posts, not the text within the posts themselves. 

**Describe the solution you'd like**
Specifically for my scenario, I'd like to know what I need to do to download the text within the posts of an author/user. 

More broadly, I would like to see the documentation include a section on how to format the program for specific searches/scrapes/etc., or an example file that includes more examples for the CLI (Similar to what the documentation for "Bulk Rename Utility" or BRU has (they include a whole section on the regular expressions you can use, and then there is a further manual created by some users that has some 500 pages of specific recipes - no reason to get that detailed, but more info would be nice)

**Comment by Jules-WinnfieldX** [comment]
> I'd like to know what I need to do to download the text within the posts of an author/user.

You can't.

> but there are no examples of how/where to input the pages you want to download, and no explanation of how to setup the config when you want something other than the standard.

Fair, and done. https://jules-winnfieldx.gitbook.io/cyberdrop-dl/quick-start#what-now
