### ISSUE TITLE
Socialmediagirls post download method

### ISSUE THREAD

**Issue by Quaso00** [Jules-WinnfieldX/CyberDropDownloader#921]
Hello, I'm using an application to download the contents of threads from the socialmediagirls site, but there's a point I don't understand. To explain based on the photo I left below, does the downloader only detect the existing links in the thread and download the contents within those links? Or does it also download the photos shared in the thread in addition to the contents within the links? Because, as seen in the photo below, some threads don't have links, only photos.

Secondly, I know this is not a suggestion post, but I had to post it here because I didn't know where to open this post. Please forgive me.

![Ekran görüntüsü 2024-06-23 220940](https://github.com/Jules-WinnfieldX/CyberDropDownloader/assets/51510166/dbf59ddd-6110-489b-b49d-1076c7d77713)

**Comment by Jules-WinnfieldX** [comment]
It should also download the photos.
