### ISSUE TITLE
[BUG] Unable to download after i've moved folders to a larger drive

### ISSUE THREAD

**Issue by KevinQMonkey** [Jules-WinnfieldX/CyberDropDownloader#922]
I've moved the folder from one drive to another due to space issues and after the move when I run the Start Windows.bat it goes to this screen and gives this error.

Cyberdrop Downloader (V5.0.14)
Current Config: Default
? What would you like to do? Download
Unhandled exception; stopping loop: 'Task exception was never retrieved'
Traceback (most recent call last):
  File "c:\users\ *******\appdata\local\programs\python\python39\lib\site-packages\cyberdrop_dl\scraper\scraper.py", line 323, in map_urls
    scrape_item: ScrapeItem = await self.manager.queue_manager.url_objects_to_map.get()
  File "c:\users\ *******\appdata\local\programs\python\python39\lib\asyncio\queues.py", line 166, in get
    await getter
RuntimeError: Task <Task pending name='Task-10' coro=<ScrapeMapper.map_urls() running at c:\users\ *******\appdata\local\programs\python\python39\lib\site-packages\cyberdrop_dl\scraper\scraper.py:323>> got Future <Future pending> attached to a different loop

****masking admin user.

here is a link to the downloader.log file
https://www.filemail.com/d/rhonvpqxefrjbps

**Comment by Jules-WinnfieldX** [comment]
You need to update CDL. Uninstall python 3.9, and install python 3.11 or newer. Python 3.11 or newer is required.

**Comment by KevinQMonkey** [comment]
Morning I've now uninstalled all the old versions of Python and left the 312 version but when i run the start.bat it looks like i'm still getting an error but different now.

Error: 
Installing / Updating Cyberdrop-DL
Requirement already satisfied: cyberdrop-dl in c:\python312\lib\site-packages (5.3.29)
Collecting cyberdrop-dl
  Using cached cyberdrop_dl-5.3.31-py3-none-any.whl.metadata (3.1 kB)
Requirement already satisfied: aiofiles==0.8.0 in c:\python312\lib\site-packages (from cyberdrop-dl) (0.8.0)
Requirement already satisfied: aiohttp<4.0.0,>=3.9.1 in c:\python312\lib\site-packages (from cyberdrop-dl) (3.9.5)
Requirement already satisfied: aiolimiter<2.0.0,>=1.1.0 in c:\python312\lib\site-packages (from cyberdrop-dl) (1.1.0)
Requirement already satisfied: aiosqlite==0.17.0 in c:\python312\lib\site-packages (from cyberdrop-dl) (0.17.0)
Requirement already satisfied: asyncpraw<8.0.0,>=7.7.1 in c:\python312\lib\site-packages (from cyberdrop-dl) (7.7.1)
Requirement already satisfied: beautifulsoup4<5.0.0,>=4.12.2 in c:\python312\lib\site-packages (from cyberdrop-dl) (4.12.3)
Requirement already satisfied: browser-cookie3<0.20.0,>=0.19.1 in c:\python312\lib\site-packages (from cyberdrop-dl) (0.19.1)
Requirement already satisfied: certifi<2025.0.0,>=2024.2.2 in c:\python312\lib\site-packages (from cyberdrop-dl) (2024.6.2)
Requirement already satisfied: filedate<4.0,>=3.0 in c:\python312\lib\site-packages (from cyberdrop-dl) (3.0)
Requirement already satisfied: get-video-properties<0.2.0,>=0.1.1 in c:\python312\lib\site-packages (from cyberdrop-dl) (0.1.1)
Requirement already satisfied: inquirerpy<0.4.0,>=0.3.4 in c:\python312\lib\site-packages (from cyberdrop-dl) (0.3.4)
Requirement already satisfied: mediafire<0.7.0,>=0.6.1 in c:\python312\lib\site-packages (from cyberdrop-dl) (0.6.1)
Requirement already satisfied: mutagen<2.0.0,>=1.47.0 in c:\python312\lib\site-packages (from cyberdrop-dl) (1.47.0)
Requirement already satisfied: myjdapi<2.0.0,>=1.1.7 in c:\python312\lib\site-packages (from cyberdrop-dl) (1.1.7)
Requirement already satisfied: pillow<11.0.0,>=10.2.0 in c:\python312\lib\site-packages (from cyberdrop-dl) (10.3.0)
Requirement already satisfied: platformdirs<5.0.0,>=4.2.2 in c:\python312\lib\site-packages (from cyberdrop-dl) (4.2.2)
Requirement already satisfied: pyyaml<7.0.0,>=6.0.1 in c:\python312\lib\site-packages (from cyberdrop-dl) (6.0.1)
Requirement already satisfied: rich<14.0.0,>=13.7.0 in c:\python312\lib\site-packages (from cyberdrop-dl) (13.7.1)
Requirement already satisfied: typing_extensions>=3.7.2 in c:\python312\lib\site-packages (from aiosqlite==0.17.0->cyberdrop-dl) (4.11.0)
Requirement already satisfied: aiosignal>=1.1.2 in c:\python312\lib\site-packages (from aiohttp<4.0.0,>=3.9.1->cyberdrop-dl) (1.3.1)
Requirement already satisfied: attrs>=17.3.0 in c:\python312\lib\site-packages (from aiohttp<4.0.0,>=3.9.1->cyberdrop-dl) (23.2.0)
Requirement already satisfied: frozenlist>=1.1.1 in c:\python312\lib\site-packages (from aiohttp<4.0.0,>=3.9.1->cyberdrop-dl) (1.4.1)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\python312\lib\site-packages (from aiohttp<4.0.0,>=3.9.1->cyberdrop-dl) (6.0.5)
Requirement already satisfied: yarl<2.0,>=1.0 in c:\python312\lib\site-packages (from aiohttp<4.0.0,>=3.9.1->cyberdrop-dl) (1.9.4)
Requirement already satisfied: asyncprawcore<3,>=2.1 in c:\python312\lib\site-packages (from asyncpraw<8.0.0,>=7.7.1->cyberdrop-dl) (2.4.0)
Requirement already satisfied: update-checker>=0.18 in c:\python312\lib\site-packages (from asyncpraw<8.0.0,>=7.7.1->cyberdrop-dl) (0.18.0)
Requirement already satisfied: soupsieve>1.2 in c:\python312\lib\site-packages (from beautifulsoup4<5.0.0,>=4.12.2->cyberdrop-dl) (2.5)
Requirement already satisfied: lz4 in c:\python312\lib\site-packages (from browser-cookie3<0.20.0,>=0.19.1->cyberdrop-dl) (4.3.3)
Requirement already satisfied: pycryptodomex in c:\python312\lib\site-packages (from browser-cookie3<0.20.0,>=0.19.1->cyberdrop-dl) (3.20.0)
Requirement already satisfied: python-dateutil in c:\python312\lib\site-packages (from filedate<4.0,>=3.0->cyberdrop-dl) (2.9.0.post0)
Requirement already satisfied: pfzy<0.4.0,>=0.3.1 in c:\python312\lib\site-packages (from inquirerpy<0.4.0,>=0.3.4->cyberdrop-dl) (0.3.4)
Requirement already satisfied: prompt-toolkit<4.0.0,>=3.0.1 in c:\python312\lib\site-packages (from inquirerpy<0.4.0,>=0.3.4->cyberdrop-dl) (3.0.47)
Requirement already satisfied: requests in c:\python312\lib\site-packages (from mediafire<0.7.0,>=0.6.1->cyberdrop-dl) (2.32.3)
Requirement already satisfied: requests-toolbelt in c:\python312\lib\site-packages (from mediafire<0.7.0,>=0.6.1->cyberdrop-dl) (1.0.0)
Requirement already satisfied: six in c:\python312\lib\site-packages (from mediafire<0.7.0,>=0.6.1->cyberdrop-dl) (1.16.0)
Requirement already satisfied: pycryptodome in c:\python312\lib\site-packages (from myjdapi<2.0.0,>=1.1.7->cyberdrop-dl) (3.20.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\python312\lib\site-packages (from rich<14.0.0,>=13.7.0->cyberdrop-dl) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\python312\lib\site-packages (from rich<14.0.0,>=13.7.0->cyberdrop-dl) (2.18.0)
Requirement already satisfied: mdurl~=0.1 in c:\python312\lib\site-packages (from markdown-it-py>=2.2.0->rich<14.0.0,>=13.7.0->cyberdrop-dl) (0.1.2)
Requirement already satisfied: wcwidth in c:\python312\lib\site-packages (from prompt-toolkit<4.0.0,>=3.0.1->inquirerpy<0.4.0,>=0.3.4->cyberdrop-dl) (0.2.13)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\python312\lib\site-packages (from requests->mediafire<0.7.0,>=0.6.1->cyberdrop-dl) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\python312\lib\site-packages (from requests->mediafire<0.7.0,>=0.6.1->cyberdrop-dl) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\python312\lib\site-packages (from requests->mediafire<0.7.0,>=0.6.1->cyberdrop-dl) (2.2.1)
Using cached cyberdrop_dl-5.3.31-py3-none-any.whl (153 kB)
Installing collected packages: cyberdrop-dl
  Attempting uninstall: cyberdrop-dl
    Found existing installation: cyberdrop-dl 5.3.29
    Uninstalling cyberdrop-dl-5.3.29:
      Successfully uninstalled cyberdrop-dl-5.3.29
  WARNING: Failed to write executable - trying to use .deleteme logic
  Rolling back uninstall of cyberdrop-dl
  Moving to c:\python312\lib\site-packages\cyberdrop_dl-5.3.29.dist-info\
   from C:\Python312\Lib\site-packages\~yberdrop_dl-5.3.29.dist-info
  Moving to c:\python312\lib\site-packages\cyberdrop_dl\
   from C:\Python312\Lib\site-packages\~yberdrop_dl
ERROR: Could not install packages due to an OSError: [WinError 2] The system cannot find the file specified: 'C:\\Python312\\Scripts\\cyberdrop-dl.exe' -> 'C:\\Python312\\Scripts\\cyberdrop-dl.exe.deleteme'


'cyberdrop-dl' is not recognized as an internal or external command,
operable program or batch file.
Press any key to continue . . .

i can see that the cyberdrop-dl.exe is in the venv
![image](https://github.com/Jules-WinnfieldX/CyberDropDownloader/assets/168743366/3124ad0b-cd76-41d3-ada7-6578720f8ab7)

but not in my Python Folder on C://, can i copy it over?
![image](https://github.com/Jules-WinnfieldX/CyberDropDownloader/assets/168743366/50620de4-f820-4307-a9fc-dbc03f1f7aaf)

**Comment by Jules-WinnfieldX** [comment]
My only recommendation to you, is uninstall py 3.12, delete c:\python312\ if it still exists after uninstalling, delete the venv. Then reinstall python and try again.
