### ISSUE TITLE
[BUG] Rule34 not working

### ISSUE THREAD

**Issue by Pizzy23** [Jules-WinnfieldX/CyberDropDownloader#923]
**Describe the bug**
Download rule34 make this thing

Checking for partial downloads...
Checking for empty folders...

Download Stats:
Downloaded 0 files
Previously Downloaded 0 files
Skipped By Config 0 files
Failed 0 files

Scrape Failures:

Download Failures:

New version of cyberdrop-dl available: 5.3.31

New versions of this program will require python 3.11 specifically to run.
If you are seeing this message, that means you need to update python to continue getting Cyberdrop-DL updates.
You can see how to do that here: https://jules-winnfieldx.gitbook.io/cyberdrop-dl/quick-start

**To Help Reproduce**
Any rule34 url

**Screenshots**
![image](https://github.com/Jules-WinnfieldX/CyberDropDownloader/assets/79873070/4e1ee04f-9895-4dfa-a0cb-8a0f6695117e)
![image](https://github.com/Jules-WinnfieldX/CyberDropDownloader/assets/79873070/3e02dde8-3607-49f9-bee6-4f0f5ca44084)
![image](https://github.com/Jules-WinnfieldX/CyberDropDownloader/assets/79873070/6c800d51-9ad2-4317-aef4-276565bcc280)

**Setup Information**
 - OS: [Windows 11,]
 - Cyberdrop Downloader Version V5.0.124#

**Downloader.log file**
[downloader.log](https://github.com/user-attachments/files/16038929/downloader.log)

**Comment by Jules-WinnfieldX** [comment]
You have multiple versions of python installed probably. Uninstall them all, and install only 3.11
