### ISSUE TITLE
[BUG] Can not use SOCKS5 proxy with login and password

### ISSUE THREAD

**Issue by PtitBiscuitRaci** [Jules-WinnfieldX/CyberDropDownloader#924]
Hello,

I can not use SOCKS5 proxy with login and password.
I have read all the FAQ and Issues about proxy and can not find a solution.

Here is the "global_setting" file content :

> General:
  allow_insecure_connections: false
  flaresolverr: ''
  max_file_name_length: 95
  max_folder_name_length: 60
  proxy: socks5://MyLogin:MyPassword@IPAdress:1080
  required_free_space: 5
  user_agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:120.0) Gecko/20100101 Firefox/120.0
Rate_Limiting_Options:
  connection_timeout: 15
  download_attempts: 30
  download_delay: 0
  max_simultaneous_downloads: 15
  max_simultaneous_downloads_per_domain: 2
  rate_limit: 50
  read_timeout: 300
UI_Options:
  downloading_item_limit: 5
  refresh_rate: 10
  scraping_item_limit: 5
  vi_mode: false

Here is the "downloader.log" file content :

> INFO     : 2024-06-29 11:36:38,494 : utilities.py:103 : Starting Async Processes...
DEBUG    : 2024-06-29 11:36:38,495 : utilities.py:103 : Starting Cyberdrop-DL Process for Default Config
DEBUG    : 2024-06-29 11:36:38,495 : utilities.py:103 : Running version 5.3.31
DEBUG    : 2024-06-29 11:36:38,495 : utilities.py:103 : Using Config: Default
DEBUG    : 2024-06-29 11:36:38,495 : utilities.py:103 : Using Config File: AppData/Configs/Default/settings.yaml
DEBUG    : 2024-06-29 11:36:38,495 : utilities.py:103 : Using Input File: XXX/Cyberdrop/URL.txt
DEBUG    : 2024-06-29 11:36:38,495 : utilities.py:103 : Using Download Folder:XXX/Cyberdrop/Dowloads
DEBUG    : 2024-06-29 11:36:38,495 : utilities.py:103 : Using History File: AppData/Cache/cyberdrop.db
DEBUG    : 2024-06-29 11:36:38,495 : utilities.py:103 : Using Authentication: 
{
    "Forums Credentials": {
        "celebforum Credentials Provided": false,
        "f95zone Credentials Provided": false,
        "leakedmodels Credentials Provided": false,
        "nudostar Credentials Provided": false,
        "simpcity Credentials Provided": false,
        "socialmediagirls Credentials Provided": false,
        "xbunker Credentials Provided": false
    },
    "Forums XF Cookies": {
        "celebforum XF Cookie Provided": false,
        "f95zone XF Cookie Provided": false,
        "leakedmodels XF Cookie Provided": false,
        "nudostar XF Cookie Provided": false,
        "simpcity XF Cookie Provided": false,
        "socialmediagirls XF Cookie Provided": false,
        "xbunker XF Cookie Provided": false
    },
    "GoFile Provided": false,
    "Imgur Provided": false,
    "JDownloader Provided": false,
    "PixelDrain Provided": false,
    "Reddit Provided": false
}
DEBUG    : 2024-06-29 11:36:38,496 : utilities.py:103 : Using Settings: 
{
    "Download_Options": {
        "block_download_sub_folders": false,
        "disable_download_attempt_limit": true,
        "disable_file_timestamps": false,
        "include_album_id_in_folder_name": false,
        "include_thread_id_in_folder_name": false,
        "remove_domains_from_folder_names": false,
        "remove_generated_id_from_filenames": false,
        "scrape_single_forum_post": false,
        "separate_posts": false,
        "skip_download_mark_completed": false
    },
    "File_Size_Limits": {
        "maximum_image_size": 0,
        "maximum_other_size": 0,
        "maximum_video_size": 0,
        "minimum_image_size": 0,
        "minimum_other_size": 0,
        "minimum_video_size": 0
    },
    "Files": {
        "download_folder": "XXX/Cyberdrop/Dowloads",
        "input_file": "XXX/Cyberdrop/URL.txt"
    },
    "Ignore_Options": {
        "exclude_audio": false,
        "exclude_images": false,
        "exclude_other": false,
        "exclude_videos": false,
        "ignore_coomer_ads": false,
        "only_hosts": [],
        "skip_hosts": []
    },
    "Logs": {
        "download_error_urls_filename": "Download_Error_URLs.csv",
        "last_forum_post_filename": "Last_Scraped_Forum_Posts.txt",
        "log_folder": "AppData/Configs/Default/Logs",
        "main_log_filename": "downloader.log",
        "scrape_error_urls_filename": "Scrape_Error_URLs.csv",
        "unsupported_urls_filename": "Unsupported_URLs.txt"
    },
    "Runtime_Options": {
        "delete_partial_files": false,
        "ignore_history": false,
        "log_level": 10,
        "send_unsupported_to_jdownloader": false,
        "skip_check_for_empty_folders": false,
        "skip_check_for_partial_files": false,
        "update_last_forum_post": false
    },
    "Sorting": {
        "sort_downloads": false,
        "sort_folder": "Downloads/Cyberdrop-DL Sorted Downloads",
        "sort_incremementer_format": " ({i})",
        "sorted_audio": "{sort_dir}/{base_dir}/Audio/{filename}{ext}",
        "sorted_image": "{sort_dir}/{base_dir}/Images/{filename}{ext}",
        "sorted_other": "{sort_dir}/{base_dir}/Other/{filename}{ext}",
        "sorted_video": "{sort_dir}/{base_dir}/Videos/{filename}{ext}"
    }
}
DEBUG    : 2024-06-29 11:36:38,496 : utilities.py:103 : Using Global Settings: 
{
    "General": {
        "allow_insecure_connections": false,
        "flaresolverr": "",
        "max_file_name_length": 95,
        "max_folder_name_length": 60,
        "proxy": "socks5://MyLogin:MyPassword@IPAdress:1080",
        "required_free_space": 5,
        "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:120.0) Gecko/20100101 Firefox/120.0"
    },
    "Rate_Limiting_Options": {
        "connection_timeout": 15,
        "download_attempts": 30,
        "download_delay": 0,
        "max_simultaneous_downloads": 15,
        "max_simultaneous_downloads_per_domain": 2,
        "rate_limit": 50,
        "read_timeout": 300
    },
    "UI_Options": {
        "downloading_item_limit": 5,
        "refresh_rate": 10,
        "scraping_item_limit": 5,
        "vi_mode": false
    }
}
INFO     : 2024-06-29 11:36:38,549 : utilities.py:103 : Starting UI...
INFO     : 2024-06-29 11:36:38,630 : utilities.py:103 : Scrape Starting: https://bunkr.si/a/ngG9lCgf
ERROR    : 2024-06-29 11:36:38,734 : utilities.py:103 : Scrape Failed: https://bunkr.si/a/ngG9lCgf (Server disconnected)
ERROR    : 2024-06-29 11:36:38,736 : utilities.py:103 : Traceback (most recent call last):
  File "/home/XXX/.local/lib/python3.11/site-packages/cyberdrop_dl/utils/utilities.py", line 63, in wrapper
    return await func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/XXX/.local/lib/python3.11/site-packages/cyberdrop_dl/scraper/crawlers/bunkrr_crawler.py", line 56, in album
    soup = await self.client.get_BS4(self.domain, scrape_item.url)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/XXX/.local/lib/python3.11/site-packages/cyberdrop_dl/clients/scraper_client.py", line 35, in wrapper
    return await func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/XXX/.local/lib/python3.11/site-packages/cyberdrop_dl/clients/scraper_client.py", line 83, in get_BS4
    async with client_session.get(url, headers=self._headers, ssl=self.client_manager.ssl_context,
  File "/home/XXX/.local/lib/python3.11/site-packages/aiohttp/client.py", line 1197, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "/home/XXX/.local/lib/python3.11/site-packages/aiohttp/client.py", line 581, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/XXX/.local/lib/python3.11/site-packages/aiohttp/connector.py", line 544, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/XXX/.local/lib/python3.11/site-packages/aiohttp/connector.py", line 942, in _create_connection
    _, proto = await self._create_proxy_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/XXX/.local/lib/python3.11/site-packages/aiohttp/connector.py", line 1329, in _create_proxy_connection
    resp = await proxy_resp.start(conn)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/XXX/.local/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 976, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/XXX/.local/lib/python3.11/site-packages/aiohttp/streams.py", line 640, in read
    await self._waiter
aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected
INFO     : 2024-06-29 11:36:38,737 : utilities.py:103 : Scrape Finished: https://bunkr.sk/a/ngG9lCgf
INFO     : 2024-06-29 11:36:38,746 : utilities.py:116 : Running Post-Download Processes For Config: Default...
INFO     : 2024-06-29 11:36:38,747 : utilities.py:116 : Checking for partial downloads...
INFO     : 2024-06-29 11:36:38,747 : utilities.py:116 : There are partial downloads in the downloads folder
INFO     : 2024-06-29 11:36:38,748 : utilities.py:116 : Checking for empty folders...
INFO     : 2024-06-29 11:36:38,749 : utilities.py:103 : Printing Stats...
INFO     : 2024-06-29 11:36:38,749 : utilities.py:116 : 
Download Stats:
INFO     : 2024-06-29 11:36:38,749 : utilities.py:116 : Downloaded 0 files
INFO     : 2024-06-29 11:36:38,750 : utilities.py:116 : Previously Downloaded 0 files
INFO     : 2024-06-29 11:36:38,750 : utilities.py:116 : Skipped By Config 0 files
INFO     : 2024-06-29 11:36:38,750 : utilities.py:116 : Failed 0 files
INFO     : 2024-06-29 11:36:38,751 : utilities.py:116 : 
Scrape Failures:
INFO     : 2024-06-29 11:36:38,751 : utilities.py:116 : Scrape Failures (Unknown): 1
INFO     : 2024-06-29 11:36:38,752 : utilities.py:116 : 
Download Failures:
INFO     : 2024-06-29 11:36:38,752 : utilities.py:103 : Checking for Program End...
INFO     : 2024-06-29 11:36:38,752 : utilities.py:103 : Checking for Updates...
INFO     : 2024-06-29 11:36:38,860 : utilities.py:103 : Closing Program...
INFO     : 2024-06-29 11:36:38,861 : utilities.py:116 : 
Finished downloading. Enjoy :)

I would appreciate some help :-)

**Comment by Jules-WinnfieldX** [comment]
http proxy only.
