### ISSUE TITLE
Help with Scrolller gif/webm

### ISSUE THREAD

**Issue by RandomGuy5598** [Jules-WinnfieldX/CyberDropDownloader#925]
All of the (originally) gif files, which are on Scrolller's site as webm, always downlod as webp.

Is there a way to get the webm files? I upgraded from v4 to v5. Maybe there's something I need to change in a setting/config file from the transition? I haven't seen anything about this in settings/config nor mentioned here.

Thanks for any insight into this.

Cheers! :D

**Comment by Jules-WinnfieldX** [comment]
5.3.32 fixes this
