### ISSUE TITLE
CLI argument to exclude file types

### ISSUE THREAD

**Issue by c0d3m0nky** [Jules-WinnfieldX/CyberDropDownloader#95]
I see that around utils/downloaders.py line 101 you're checking if the file extension is in groups of Images/Videos/Audio/Other

Is it possible to add a CLI argument to exclude by those groups (i.e. --exclude-videos)

**Comment by Jules-WinnfieldX** [comment]
Added this functionality in 2.10.4

**Comment by c0d3m0nky** [comment]
Awesome thanks!
