### ISSUE TITLE
[BUG] "TypeError: argument of type 'URL' is not iterable"

### ISSUE THREAD

**Issue by TheConMan3** [Jules-WinnfieldX/CyberDropDownloader#97]
Running Cyberdrop Downloader version 2.10.5 gets me the error "TypeError: argument of type 'URL' is not iterable" each time.

I've tried redownloading Cyberdrop Downloader, installing latest version of Python (version 3.10.4), and using different URLs. Any URLs I try produce this same error code even ones I've been able to download in the past with this downloader. This is on Windows 10 and there are no OS updates available.

I've attached screenshots of the cmd window and the downloader log.

I'm sure this is just something super obvious that I'm just not seeing.
![downloader log](https://user-images.githubusercontent.com/102829877/161359794-9f92e38d-1cce-46c8-aef2-474df5da14eb.png)
![URL not iterable](https://user-images.githubusercontent.com/102829877/161359795-1ba32864-541e-4ad5-a125-de7886dce326.png)

**Comment by MitchPetersen** [comment]
Nah, this was a bug left in by me after recent changes. Try now.

**Comment by Jules-WinnfieldX** [comment]
Try now

**Comment by TheConMan3** [comment]
It's working now! Thank you!
