### ISSUE TITLE
'cyberdrop-dl' is not recognized I have added the path. Still getting the error

### ISSUE THREAD

**Issue by sunny9t1** [Jules-WinnfieldX/CyberDropDownloader#98]
**Describe the bug**
PS G:\Cyberdrop-JPGChurch Downloader> cyberdrop-dl
cyberdrop-dl : The term 'cyberdrop-dl' is not recognized as the name of a cmdlet, function, script file, or operable
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ cyberdrop-dl
+ ~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (cyberdrop-dl:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by Jules-WinnfieldX** [comment]
This isn't a bug. This is caused by not having python installed properly. You can google how to add the python folders to path, or you can uninstall and reinstall and make sure you click the add to path checkbox during installation.
